### PR TITLE
ethdb/pebble: fix range compaction

### LINKED ISSUE #26762: Offline prune failed  -dbengine "pebble"
```
INFO [02-23|07:22:26.969] Pruned state data                        nodes=424,362,282 size=100.60GiB elapsed=4h55m25.741s
INFO [02-23|07:22:27.513] Compacting database                      range=0x00-0x10 elapsed="462.331µs"
INFO [02-23|07:23:00.007] Compacting database                      range=0x10-0x20 elapsed=32.494s
INFO [02-23|07:23:40.184] Compacting database                      range=0x20-0x30 elapsed=1m12.671s
INFO [02-23|07:24:14.136] Compacting database                      range=0x30-0x40 elapsed=1m46.623s
INFO [02-23|07:24:51.761] Compacting database                      range=0x40-0x50 elapsed=2m24.247s
INFO [02-23|07:25:47.672] Compacting database                      range=0x50-0x60 elapsed=3m20.159s
INFO [02-23|07:26:20.408] Compacting database                      range=0x60-0x70 elapsed=3m52.895s
INFO [02-23|07:30:59.957] Compacting database                      range=0x70-0x80 elapsed=8m32.443s
INFO [02-23|07:31:33.846] Compacting database                      range=0x80-0x90 elapsed=9m6.332s
INFO [02-23|07:32:08.155] Compacting database                      range=0x90-0xa0 elapsed=9m40.641s
INFO [02-23|07:32:44.734] Compacting database                      range=0xa0-0xb0 elapsed=10m17.221s
INFO [02-23|07:33:19.279] Compacting database                      range=0xb0-0xc0 elapsed=10m51.766s
INFO [02-23|07:33:56.079] Compacting database                      range=0xc0-0xd0 elapsed=11m28.566s
INFO [02-23|07:34:35.443] Compacting database                      range=0xd0-0xe0 elapsed=12m7.930s
INFO [02-23|07:35:16.061] Compacting database                      range=0xe0-0xf0 elapsed=12m48.548s
INFO [02-23|07:36:16.822] Compacting database                      range=0xf0-     elapsed=13m49.309s
ERROR[02-23|07:36:16.832] Database compaction failed               error="Compact start \\xf0 is not less than end "
ERROR[02-23|07:36:16.844] Failed to prune state                    err="Compact start \\xf0 is not less than end "
Compact start \xf0 is not less than end
```
I resynced a full node on goerli with pebble and when I pruned it , it failed to compact.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #26762

### CODE REVIEW

File: ethdb/pebble/pebble.go [hunk 1]
```diff
@@ -361,6 +362,13 @@ func (d *Database) Stat(property string) (string, error) {
 // is treated as a key after all keys in the data store. If both is nil then it
 // will compact entire data store.
 func (d *Database) Compact(start []byte, limit []byte) error {
+	// There is no special flag to represent the end of key range
+	// in pebble(nil in leveldb). Use an ugly hack to construct a
+	// large key to represent it.
```
Comment (karalabe) [inline ethdb/pebble/pebble.go:367]: Perhaps add a note that any prefixed database entry will be smaller than this due to the prefix; as for trie nodes we need the 32 byte 0xff because there might be a shared prefix starting with a number of 0xff-s, so 32 ensures than only a hash collision could touch it.
