### PR TITLE
common: fix #1818, secondary datadir paths to fall back to

### LINKED ISSUE #1818: panic: runtime error: invalid memory address or nil pointer dereference
#### OS :
Fedora 20 || Linux mount-kailash 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

#### Go version :
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

#### Error description :
I followed go-ethereum installation instruction and did the following things -
> git clone go-ethereum.git
> make
> build/bin/geth

Then I am getting this error.
###### Error log : http://fpaste.org/269002/59583314/raw/

### PR DESCRIPTION
**Pull request by karalabe**
This PR fixes an issue in Fedora and Android where the current user cannot be retrieved on certain platforms (Actually, the fix is more generic). If the user cannot be accessed, the default data dir uses a workspace in the current working folder. If that also cannot be retrieved, it defaults to an empty folder, leaving it to the user to sort it out manually via CLI flags (still better than crashing).

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Sep 29 14:23:54 UTC 2015_

**Comment by karalabe** [comment]
Hey @0mkara, if you have the time, could you check if this fix solves the homedir issue for you on Fedora? Thanks!

File: common/path.go [hunk 1]
```diff
@@ -100,14 +100,28 @@ func DefaultAssetPath() string {
...
+			return filepath.Join(usr.HomeDir, ".ethereum")
+		}
+	}
+	// If the user cannot be retrieved (Android, Fedora/Go bug), use the current folder
+	if dir, err := os.Getwd(); err == nil {
+		if runtime.GOOS == "darwin" {
+			return filepath.Join(dir, "Ethereum")
+		} else if runtime.GOOS == "windows" {
+			return filepath.Join(dir, "Ethereum")
+		} else {
```
Comment (bas-vk) [inline common/path.go]: I'm not sure about this. On android this will probably be fine. On Fedora it is a bug and when it gets fixed the datadir might change. And each time the user starts geth in a different working dir the datadir is different. This can get really confusing. Maybe its best on Fedora to exit the program and print a message informing the user that he needs to specify the datadir manually.

Comment (karalabe) [inline common/path.go]: Well, anoth eroption would be to drop the second block (the pwd one), and check in geth main that an empty data dir should return an error. I'm fine with that approach too. This is actually why I never implemented this, because I couldn't decide what the best course of action is.

**Comment by 0mkara** [comment]
Yes @karalabe this worked on fedora for me.

File: common/path.go (hunk 1 above)
Comment (fjl) [inline common/path.go]: You could try using `os.Getenv("HOME")` as a fallback. 
That should also work on Fedora in most cases.

**Comment by Gustav-Simonsson** [comment]
:+1:

**Comment by 0mkara** [comment]
:thumbsup:
