### PR TITLE
core: fix #1921, decode all receipt field, not just consensus

### LINKED ISSUE #1921: eth.getTransactionReceipt is broken in develop
```
> tx = "0xb0e0e491330d034b9e3abff82ae2e2e73a6666bb0a6b424a8245101cd1fe7be3"
"0xb0e0e491330d034b9e3abff82ae2e2e73a6666bb0a6b424a8245101cd1fe7be3"
> eth.getTransactionReceipt(tx)
{
  blockHash: "0xfdd8e4bf0de6967e2ba31083c182458a96d452fdb3e0d9b52f2654e2413770e0",
  blockNumber: 421169,
  contractAddress: null,
  cumulativeGasUsed: 0,
  gasUsed: 0,
  logs: [],
  transactionHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  transactionIndex: 0
}
```

http://etherscan.io/tx/0xb0e0e491330d034b9e3abff82ae2e2e73a6666bb0a6b424a8245101cd1fe7be3

This seems to be happening for regular and contract creating transactions.

### PR DESCRIPTION
**Pull request by karalabe**
This PR fixes a small regression caused by the fast sync core refactors. Receipts were reworked a bit to use different semantics for working with consensus receipts and storage receipts. This method (`GetReceipt`) for retrieving a single individual receipt somehow was forgotten to be changed to the storage version and apparently no test covered it. This fix should hopefully be enough to get it back on track, but maybe we should consider writing a full API test suite to catch bugs like this in the future.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Oct 22 10:13:02 UTC 2015_

File: core/database_util.go [hunk 1]
```diff
@@ -234,6 +238,67 @@ func GetBlock(db ethdb.Database, hash common.Hash) *types.Block {
 	return types.NewBlockWithHeader(header).WithBody(body.Transactions, body.Uncles)
 }
 
+// GetBlockReceipts retrieves the receipts generated by the transactions included
+// in a block given by its hash.
+func GetBlockReceipts(db ethdb.Database, hash common.Hash) types.Receipts {
+	data, _ := db.Get(append(blockReceiptsPrefix, hash[:]...))
```
Comment (Gustav-Simonsson) [inline core/database_util.go]: Everything is data. All variables contain data. Would recommend a more descriptive name, something like `receiptsRLP`

File: core/database_util.go [hunk 2]
```diff
@@ -234,6 +238,67 @@ func GetBlock(db ethdb.Database, hash common.Hash) *types.Block {
...
+		receipts[i] = (*types.Receipt)(receipt)
+	}
+	return receipts
+}
+
+// GetTransaction retrieves a specific transaction from the database, along with
+// its added positional metadata.
+func GetTransaction(db ethdb.Database, hash common.Hash) (*types.Transaction, common.Hash, uint64, uint64) {
+	// Retrieve the transaction itself from the database
+	data, _ := db.Get(hash.Bytes())
```
Comment (Gustav-Simonsson) [inline core/database_util.go]: Same here, `txRLP` would be more descriptive.

File: core/database_util.go (hunk 1 above)
Comment (karalabe) [inline core/database_util.go]: Hmm, by `data` I really meant `binary blob`, just didn't want to write that all out. A better option would be plain `rlp`, but that would conflict with the package. Hence why I left it with just `data`, didn't want to write a lot of different variable names that just mean `binary blob`.

**Comment by Gustav-Simonsson** [comment]
:+1:

File: core/database_util.go (hunk 1 above)
Comment (Gustav-Simonsson) [inline core/database_util.go]: Not a blocker :) I just try to always make a case to avoid "data" as a variable because it's worst variable name there is :D 2nd worst is "data2". Followed by "value".

Even though all of these can be seen as binary blobs, they do contain different things. `receiptsRLP`, `txRLP` etc would be good name, informing the reader that the variable contains RLP of a certain Ethereum thing.

**Comment by obscuren** [comment]
:-1: cleanup. Remove that, it interferes way too much with other PRs

**Comment by karalabe** [comment]
Which one does it conflict with? Imho it should allow clean rebasing.

**Comment by obscuren** [comment]
Renaming of the functions. I'm in the middle of this terrible merge

**Comment by obscuren** [comment]
What I'm saying is, please don't cause me extra headaches :)

**Comment by karalabe** [comment]
@obscuren PTAL, cleanup split out into https://github.com/ethereum/go-ethereum/pull/1923

**Comment by obscuren** [comment]
:+1:
