### PR TITLE
core/vm: fixed jit error & added inline docs

### LINKED ISSUE #1633: core/vm: consensus issues using JIT
There's a known consensus failure when using the JIT VM (`--jitvm`)

### PR DESCRIPTION
**Pull request by obscuren**
`opNumber` did not create a new big int which could lead to the block's
number being modified.

Closes #1633

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 10 22:18:23 UTC 2015_

File: core/vm/instructions.go [hunk 1]
```diff
@@ -415,15 +415,12 @@ func opSstore(instr instruction, env Environment, context *Context, memory *Memo
...
 
-func opJump(instr instruction, env Environment, context *Context, memory *Memory, stack *stack) {
-}
-func opJumpi(instr instruction, env Environment, context *Context, memory *Memory, stack *stack) {
-}
-func opJumpdest(instr instruction, env Environment, context *Context, memory *Memory, stack *stack) {
-}
+func opJump(instr instruction, env Environment, context *Context, memory *Memory, stack *stack)     {}
+func opJumpi(instr instruction, env Environment, context *Context, memory *Memory, stack *stack)    {}
+func opJumpdest(instr instruction, env Environment, context *Context, memory *Memory, stack *stack) {}
```
Comment (fjl) [inline core/vm/instructions.go]: Why do these functions exist?

Comment (obscuren) [inline core/vm/instructions.go]: Because of https://github.com/obscuren/go-ethereum/blob/jit-fixes/core/vm/jit.go#L349 I like the explicitness of the name over a generic one (that could accidentally be changed during an update) such as `noOp` and leave that empty.

File: core/block_processor.go [hunk 2]
```diff
@@ -354,18 +354,8 @@ func (sm *BlockProcessor) GetLogs(block *types.Block) (logs state.Logs, err erro
...
-	// TODO: remove backward compatibility
-	var (
-		parent = sm.bc.GetBlock(block.ParentHash())
-		state  = state.New(parent.Root(), sm.chainDb)
-	)
-
-	sm.TransitionState(state, parent, block, true)
-
-	return state.Logs(), nil
+	return
```
Comment (fjl) [inline core/block_processor.go]: Would prefer `return logs, nil`.

File: core/vm/instructions.go (hunk 1 above)
Comment (fjl) [inline core/vm/instructions.go]: But aren't invalid opcodes detected during compilation?

Comment (obscuren) [inline core/vm/instructions.go]: Invalid opcode do not make the program invalid. You still have to run it fully (resulting in OOG) and since paths are variable we **need** to run it unless we can statically determine a certain path is invalid given certain input. Static analysis is still way off

**Comment by fjl** [comment]
:+1:

File: core/vm/settings.go [hunk 3]
```diff
@@ -17,9 +17,9 @@
 package vm
 
 var (
-	DisableJit  bool = true // Disable the JIT VM
-	ForceJit    bool        // Force the JIT, skip byte VM
-	MaxProgSize int         // Max cache size for JIT Programs
+	EnableJit   bool // Enables the JIT VM
```
Comment (obscuren) [inline core/vm/settings.go]: Per @tgerring suggestion

**Comment by Gustav-Simonsson** [comment]
:+1:
