### PR TITLE
console: fix admin.sleepBlocks() call

### LINKED ISSUE #21621: admin.sleepBlocks(1) returns immediately
#### System information

 Geth/v1.9.21-stable-0287d548/windows-amd64/go1.15

#### Expected behaviour

I open geth console and run the following command 

```
> eth.blockNumber
329
> admin.sleepBlocks(1)
true
> eth.blockNumber
```

Since I run this on a private chain, I expect admin.sleepBlocks to block the console until I have mined 1 block. Further,  I expect eth.blockNumber to be 330 because admin.sleepBlocks waits 1 block then return.

#### Actual behaviour
admin.sleepBlocks(1) returns immediately on my private chain without any miner working. 

Further, eth.blockNumber is still 329.

### PR DESCRIPTION
**Pull request by de1acr0ix**
The first time `lastNumber` is assigned with an actual block number should not count.

Fixes #21621

### CODE REVIEW

File: console/bridge.go [hunk 1]
```diff
@@ -353,19 +353,18 @@ func (b *bridge) SleepBlocks(call jsre.Call) (goja.Value, error) {
...
 		var number hexutil.Uint64
-		err := b.client.Call(&number, "eth_blockNumber")
-		if err != nil {
+		if err := b.client.Call(&number, "eth_blockNumber"); err != nil {
 			return nil, err
 		}
 		if number != lastNumber {
 			lastNumber = number
-			blocks--
 		}
```
Comment (holiman) [inline console/bridge.go:368]: You removed the `blocks--`. I don't see how this can work...?

Comment (de1acr0ix) [reply console/bridge.go]: Apparently I was careless - I just fixed it and please have a re-review. Thanks!

**Review by fjl — APPROVED** [review]
