### PR TITLE
core, triedb/pathdb: calculate the size for batch pre-allocation

### LINKED ISSUE #29061: The memory preallocated for WriteBatch is always smaller than the actual size in nodebuffer
#### System information

Geth version:  1.13
CL client & version: none
OS & Version: Windows/Linux/OSX
Commit hash : master

#### Expected behaviour

https://github.com/ethereum/go-ethereum/blob/b87b9b45331f87fb1da379c5f17a81ebc3738c6e/triedb/pathdb/nodebuffer.go#L209-L236

Pre-allocated memory to avoid re-allocated.

#### Actual behaviour

The calculated size in Nodebuffer is actually slightly smaller than the actual size, which can result in large memory re-allocate(256M+) during the batch.Put process, affecting performance.

#### Steps to reproduce the behaviour

add detailed log to reproduce

```
log.Debug("Persisted pathdb nodes", "nodes", len(b.nodes), "pre-bytes", common.StorageSize(b.size), "bytes", common.StorageSize(size), "elapsed", common.PrettyDuration(time.Since(start)))
```

#### Backtrace

none.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #29061

### CODE REVIEW

File: triedb/pathdb/nodebuffer.go [hunk 1]
```diff
@@ -204,6 +204,19 @@ func (b *nodebuffer) setSize(size int, db ethdb.KeyValueStore, clean *fastcache.
 	return b.flush(db, clean, id, false)
 }
 
+// allocBatch returns a database batch with pre-allocated buffer.
+func (b *nodebuffer) allocBatch(db ethdb.KeyValueStore) ethdb.Batch {
+	var metasize int
```
Comment (Fynnss) [inline triedb/pathdb/nodebuffer.go:209]: Why don't you calculate it during the `commit`?

https://github.com/ethereum/go-ethereum/blob/8efb094e3541e44e05b04b0bc9f44590080d2b78/triedb/pathdb/nodebuffer.go#L105-L112

File: triedb/pathdb/nodebuffer.go [hunk 2]
```diff
@@ -204,6 +204,19 @@ func (b *nodebuffer) setSize(size int, db ethdb.KeyValueStore, clean *fastcache.
...
+	for owner, nodes := range b.nodes {
+		if owner == (common.Hash{}) {
+			metasize += len(nodes) * len(rawdb.TrieNodeAccountPrefix) // database key prefix
+		} else {
+			metasize += len(nodes) * (len(rawdb.TrieNodeStoragePrefix) + common.HashLength) // database key prefix + owner
+		}
+	}
+	return db.NewBatchWithSize(int(float64(uint64(metasize)+b.size) * 1.1)) // extra 10% for potential pebble internal stuff
```
Comment (karalabe) [inline triedb/pathdb/nodebuffer.go:217]: Possibly doing a `(metasize + int(b.size)) * 11 / 10` is a bit cleaner than all the casts?

File: triedb/pathdb/nodebuffer.go (hunk 1 above)
Comment (karalabe) [reply triedb/pathdb/nodebuffer.go:209]: IMO it's cleaner to do it as late as possible instead of risking the counters going out of sync with the code. Also less code/fields to keep in mind.
