### PR TITLE
eth/downloader: fix #910, thread safe peers & polishes

### LINKED ISSUE #910: Node crashed while importing blocks
Error log
```js
I0511 10:07:54.307413   48528 xeth.go:327] EOF
I0511 10:07:58.407441   48528 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 10.531398739s. #294576 [89595ef9 / 2f09b8a3]
I0511 10:08:06.572569   48528 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 8.165045218s. #294832 [0fa2cec7 / 1851dea1]
I0511 10:08:23.842992   48528 chain_manager.go:628] imported 256 block(s) (0 queued 0 ignored) in 17.27033827s. #295088 [8ea64453 / bd45f4c1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x446b93e]

goroutine 475 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*peer).promote(0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/eth/downloader/peer.go:104 +0x8e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).startFetchingBlocks(0xc20b6c4070, 0xc20d1e4e00, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:368 +0x765
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).getFromPeer(0xc20b6c4070, 0xc20d1e4e00, 0x80c33f5e0a335d50, 0x85c9ef3270fb3ca5, 0x8a2e0ed26a5c441e, 0xec244660b350ea2e, 0x403c900, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:191 +0x2d9
...
```

[-> Full error log](https://gist.github.com/frozeman/8b9e5514ccde1849a668)

### PR DESCRIPTION
**Pull request by karalabe**
This PR reworks the internal peer set of the downloader to be thread safe instead of the direct map accesses of the previous implementation.

Some additional fixes:

 - Drop the `ignoreInitial` hash, as it was always downloaded anyway in the code.
 - Check for duplicate hashes to prevent a bad peer from injecting the same hash multiple times and corrupting our internal state (there might still be interesting "opportunities for that though").
 - ~~If a bad peer is detected, it's dropped from the active list, not just demoted.~~

### CODE REVIEW

File: eth/downloader/downloader.go [hunk 1]
```diff
@@ -381,13 +358,12 @@ out:
...
-				if peer := d.peers[pid]; peer != nil {
-					peer.demote()
-					peer.reset()
+				if peer := d.peers.Peer(pid); peer != nil {
+					peer.Demote()
 				}
 			}
 			// After removing bad peers make sure we actually have sufficient peer left to keep downloading
-			if len(d.peers) == 0 {
+			if d.peers.Peers() == 0 {
```
Comment (obscuren) [inline eth/downloader/downloader.go]: Change to `Len`
