### PR TITLE
core/state: Set log index. Closes #1226

### LINKED ISSUE #1226: [RPC] incorrect logIndex in logs received from eth_getfilterchanges
> `logIndex`: QUANTITY - integer of the log index position in the block. `null` when its pending log.

Currently it's always 0.

Steps to reproduce:
- create multiple transactions. Make each one create an event.
- mine them in the same block
- event when `transactionIndex` is > 0, `logIndex` is `0`

```json
{
  "address": "0xfe69e6f32a2a02b3169b072a7631ff33bf472ed0",
  "blockNumber": 115,
  "logIndex": 0,
  "blockHash": "0x7dcaec77bdc5bd3dc1c96cdc3504ed23dc6132ea756ab3cb56a2ddaccae432d5",
  "transactionHash": "0x09abbb095230e93b725929a8671a6c7e8ba51d7b8f3e4ae54db1ca7135ede61d",
  "transactionIndex": 4,
  "event": "Incremented",
  "args": {
    "odd": true,
    "x": "91"
  }
}
```

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

File: core/state/statedb.go [hunk 1]
```diff
@@ -66,6 +66,7 @@ func (self *StateDB) AddLog(log *Log) {
 	log.TxHash = self.thash
 	log.BlockHash = self.bhash
 	log.TxIndex = uint(self.txIndex)
+	log.Index = uint(len(self.logs))
```
Comment (tgerring) [inline core/state/statedb.go]: Should index be 1-based or 0-based?

Comment (obscuren) [inline core/state/statedb.go]: Shit. Even that is wrong. I meant to do `len(self.logs[self.thash])` (it's the len of  that because it's set prior to adding the log)

Comment (obscuren) [inline core/state/statedb.go]: No, it's actually wrong all together.

**Comment by tgerring** [comment]
Untested locally, but the changes seem reasonable. Do you have some sample output? If so, :+1:

**Comment by obscuren** [comment]
@tgerring sample output can be found in https://github.com/ethereum/go-ethereum/issues/1226

**Comment by bas-vk** [comment]
:+1:

**Comment by fjl** [comment]
:+1:
