### PR TITLE
CLI and JS admin changes

### LINKED ISSUE #721: bunch of CLI/JS admin related issues to check/fix
- [x]  geth show "primary" account #732 
- [x] improve README Broken link for detailed go build instructions #661 fixed in #761
- [x]  Correct subdirectory used for keys and use os.Remove instead of RemoveAll #443 fixed in #796
- [x] ~~anything for filters and watch support~~ @frozeman @zsfelfoldi 
- [x] remove minGasPrice #754 fixed in #763
- [x] ~~RPC access control #745~~
- [x] implement stopRPC #729
- [x] rpccorsheader arg to startRPC
- [x]  admin.miner.start() hangs until the dag is generated
- [x] stop with fatal error if RPC or mining cannot start (many reported issues about hidden msgs)
- [x] ~~admin.unlock timeout issue #665~~
- [x]  ~~eth_defaultBlock #306 #310~~
- [x] confirm if there is string conversion issues, #710 
- [x]  ~~console "admin" feature to view pending transactions #675~~ 
- [x]  ubuntu address after new account #508 
- [x] reenable -shh option on command line #755
- [x] pprof via CLI + pprof port #755
- [x] update wiki with new functionality

### LINKED ISSUE #732: geth show "primary" account
2 quick suggestions.  When running ``geth account list`` modify the output like this:
Welcome to the FRONTIER
Address: {29d33c02a200937995e632c4597b4dca8e503978}
**Primary** Address: {57b723e224954a3026c1fb44c5f07b4b5fc096a8}

Or add an option to ``geth account``.
``geth account`` has:

COMMANDS:
   list		print account addresses
   new		create a new account
   import	import a private key into a new account
   help		Shows a list of commands or help for one command

### PR DESCRIPTION
**Pull request by zelig**
*  js console: rename debug.block to debug.processBlock
*  js console: move backtrace under debug
* js console: add cors domain optional argument to startRpc
* cli: clean up flag descriptions, usage docs, account list uses primary - fixes #732
* cli: fatal error if rpc could not be started 
* backend: start miner in its go routine (no wait to generate DAG) 
* cli: fatal error if no etherbase for mining

Note major change of behaviour:

```
geth -datadir /tmp/zelig  -port 30300 -rpc -rpcaddr 'foo'
Welcome to the FRONTIER
Fatal: Error starting RPC: listen tcp 127.0.53.53:8545: bind: can't assign requested address
```

``` 
geth -datadir /tmp/zelig  -port 30300 -mine
Welcome to the FRONTIER
Fatal: Cannot start mining without etherbase address: no accounts found
```
closes #721

### CODE REVIEW

File: cmd/geth/admin.go [hunk 1]
```diff
@@ -210,10 +210,19 @@ func (js *jsre) startRPC(call otto.FunctionCall) otto.Value {
...
+		if err != nil {
+			fmt.Println(err)
+			return otto.FalseValue()
+		}
+	}
+
 	config := rpc.RpcConfig{
 		ListenAddress: addr,
 		ListenPort:    uint(port),
-		// CorsDomain:    ctx.GlobalString(RPCCORSDomainFlag.Name),
```
Comment (obscuren) [inline cmd/geth/admin.go]: This should still be honoured in case the `corsDomain` was left blank.

Comment (zelig) [inline cmd/geth/admin.go]: thx i think this is a mistake

**Comment by zelig** [comment]
fixed and rebased
