### PR TITLE
cmd/geth, jsre: restore command line editing on windows

### LINKED ISSUE #1608: Windows: Wordwrap on Geth client breaks command line
The Windows Geth client has some major issues:

1) Word wrap at the right edge of the window breaks the command line
2) Cursor keys and insert/delete do not function at all

Geth for windows is essentially unusable for initiating transactions.

### LINKED ISSUE #1612: eth.getTransactionReceipt: contractAddress: Error: Cannot access member 'constructor' of null
with `geth 1.0.1` in the JS console (via `geth attach`):

```
> eth.getTransactionReceipt('0x9d3f3e5b651c3b4472eca4cd57db6549d474a23af182c768d418bd9e278195b5')
{
  blockHash: '0x35803048a469e86a0e9df1641ddf84a237aad0b4c0702ee9b99e1035afc992f0',
  blockNumber: 47527,
  contractAddress: Error: Cannot access member 'constructor' of null,
  cumulativeGasUsed: 21000,
  gasUsed: 21000,
  logs: [ ],
  transactionHash: '0x9d3f3e5b651c3b4472eca4cd57db6549d474a23af182c768d418bd9e278195b5',
  transactionIndex: 0
}
```

I don't expect to see the error message `contractAddress: Error: Cannot access member 'constructor' of null,`, but probably `null`, `0x` or something similar if no `contractAddress` is involved.

### PR DESCRIPTION
**Pull request by fjl**
PR #856 broke command line editing by wrapping stdout with a filter that
interprets ANSI escape sequences to fix colored printing on windows.
Implement the printer in Go instead so it can do its own
platform-dependent coloring.

As a nice side effect, the JS console is now noticeably more responsive
when printing results.

Fixes #1608
Fixes #1612

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Aug 11 16:24:21 UTC 2015_

**Comment by fjl** [comment]
One problem I saw while working on this is that attached consoles get disconnected after 60s
of inactivity. The ipc client doesn't seem to reconnect when geth closes the pipe.

File: jsre/pretty.go [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+		numberColor.Printf("NaN")
+	case v.IsNumber():
+		s, _ := v.ToString()
+		numberColor.Printf("%s", s)
+	default:
+		fmt.Printf("%s<unprintable>", indent)
+	}
+}
+
+func (ctx ppctx) printObject(obj *otto.Object, indent string) {
```
Comment (obscuren) [inline jsre/pretty.go]: Is there a reason why you're using this type of "type casting" over `obj.Value()` and use [`value.Export`](https://github.com/robertkrimen/otto#func-value-export)?

**Comment by bas-vk** [comment]
:+1:

File: jsre/pretty.go (hunk 1 above)
Comment (fjl) [inline jsre/pretty.go]: Export converts both `undefined` and `null` to Go `nil`. It also has other issues, e.g.
`new String('foo')` exports as `map[string]interface{}{"0": "f", "1": "o", "2": "o"}`.
`Export` is recursive and crashes for circular structures. The new printer does, too, but
we can fix it whereas `Export` is part of otto.

**Comment by fjl** [comment]
I'll add circular structure handling so the following doesn't crash the printer:

```js
> a = {'b': 1}
> a.a = a
> a
```

**Comment by fjl** [comment]
@bas-vk PTAL. I've added a depth limit so the above case prints as

```js
> a = {b:1}
{
  b: 1
}
> a.a = a
{
  a: {
    a: {
      a: {
        a: {...},
        b: 1
      },
      b: 1
    },
    b: 1
  },
  b: 1
}
```

File: jsre/pretty.go [hunk 2]
```diff
@@ -0,0 +1,220 @@
...
+	}
+	sort.Strings(vals)
+	sort.Strings(methods)
+	return append(vals, methods...)
+}
+
+func (ctx ppctx) doOwnProperties(v otto.Value, f func(string)) {
+	Object, _ := ctx.vm.Object("Object")
+	rv, _ := Object.Call("getOwnPropertyNames", v)
+	gv, _ := rv.Export()
```
Comment (Gustav-Simonsson) [inline jsre/pretty.go]: What does rv and gv mean? Is the second returned value here errors? If so why are they not checked?

Comment (fjl) [inline jsre/pretty.go]: `rv` is short for return value, `gv` for go value. None of the errors are checked because
`Object.getOwnPropertyNames` exists as a method and should not error for JS objects.
Try breaking it.

Comment (fjl) [inline jsre/pretty.go]: The easiest way to break this is to evaluate `Object.getOwnPropertyNames = null` at the console.
Printing any object after that crashes the console. I don't think this is worth fixing though. The best
thing we could do in such a situation would be to print something like "can't print because you broke Object".

**Comment by bas-vk** [comment]
Maybe we should print such a message and inform the user that its probably best to restart geth or the console in case of an attach. Now it crashes which might cause issues.

The depth limit change is ok.

**Comment by obscuren** [comment]
:+1:
