### PR TITLE
p2p/dnsdisc: fix hot-spin when all trees are empty

### LINKED ISSUE #22306: DNS discovery spinloop
When running geth with a dns discovery setting where there set of nodes in the crawled public set is empty, the dns client goes into a spinloop, consuming 100% of a CPU core. 

Testcase to repro this, where the last `it.Next()` spins : 
```diff
diff --git a/p2p/dnsdisc/client_test.go b/p2p/dnsdisc/client_test.go
index 6a6705abf2..7be13176db 100644
--- a/p2p/dnsdisc/client_test.go
+++ b/p2p/dnsdisc/client_test.go
@@ -115,6 +115,21 @@ func TestIterator(t *testing.T) {
 	checkIterator(t, it, nodes)
 }
 
+// This test checks that randomIterator finds all entries.
+func TestEmptyIterator(t *testing.T) {
+	tree, url := makeTestTree("n", testNodes(nodesSeed1, 00), nil)
+	c := NewClient(Config{
+		Resolver:  mapResolver(tree.ToTXT("n")),
+		Logger:    testlog.Logger(t, log.LvlTrace),
+		RateLimit: 500,
+	})
+	it, err := c.NewIterator(url)
+	if err != nil {
+		t.Fatal(err)
+	}
+	it.Next()
+}
+
 // This test checks if closing randomIterator races.
 func TestIteratorClose(t *testing.T) {
 	nodes := testNodes(nodesSeed1, 500)
```
Can also be tested live using e.g. `geth --goerli --syncmode=snap`.

### PR DESCRIPTION
**Pull request by fjl**
In the random sync algorithm used by the DNS node iterator, we first pick a random
tree and then perform one sync action on that tree. This happens in a loop until any
node is found. If no trees contain any nodes, the iterator will enter a hot loop spinning
at 100% CPU.

The fix is complicated. The iterator now checks if a meaningful sync action can
be performed on any tree. If there is nothing to do, it waits for the next root record
recheck time to arrive and then tries again.

Fixes #22306

### CODE REVIEW

File: p2p/dnsdisc/client.go [hunk 1]
```diff
@@ -294,14 +295,56 @@ func (it *randomIterator) nextTree() *clientTree {
...
+		// The only meaningful thing to do now is waiting for any root record to get
+		// updated.
+		if !it.waitForRootUpdates(disabled) {
+			return nil // Iterator was closed.
+		}
+	}
+}
+
+// syncableTrees finds trees on which any meaningful sync action can be performed.
+func (it *randomIterator) syncableTrees() (syncable, disabled []*clientTree) {
```
Comment (fjl) [inline p2p/dnsdisc/client.go:316]: I still want optimize this to reuse the same slices over and over, but let's review the basic idea first.

**Comment by fjl** [comment]
```
~/d/e/s/g/e/go-ethereum >> ./geth --ropsten --vmodule p2p/dnsdisc=5 --snapshot --syncmode=snap
INFO [02-11|14:40:24.430] Starting Geth on Ropsten testnet... 
TRACE[02-11|14:40:24.861] Updating DNS discovery root              tree=all.ropsten.ethdisco.net err=nil
TRACE[02-11|14:40:24.886] Updating DNS discovery root              tree=snap.ropsten.ethdisco.net err=nil
TRACE[02-11|14:40:24.925] DNS discovery lookup                     name=FDXN3SN67NA5DKA4J2GOK7BVQI.all.ropsten.ethdisco.net err=nil
TRACE[02-11|14:40:24.951] DNS discovery lookup                     name=FDXN3SN67NA5DKA4J2GOK7BVQI.snap.ropsten.ethdisco.net err=nil
DEBUG[02-11|14:40:24.951] DNS iterator waiting for root updates    sleep=29m59.878292709s
```

**Comment by fjl** [comment]
Adjusted the log message a bit:

```
~/d/e/s/g/e/go-ethereum >> ./geth --ropsten --vmodule p2p/dnsdisc=5 --snapshot --syncmode=snap
INFO [02-11|14:48:45.458] Starting Geth on Ropsten testnet... 
TRACE[02-11|14:48:45.761] Updating DNS discovery root              tree=snap.ropsten.ethdisco.net err=nil
TRACE[02-11|14:48:45.761] Updating DNS discovery root              tree=all.ropsten.ethdisco.net  err=nil
TRACE[02-11|14:48:45.792] DNS discovery lookup                     name=FDXN3SN67NA5DKA4J2GOK7BVQI.snap.ropsten.ethdisco.net err=nil
DEBUG[02-11|14:48:45.792] DNS iterator waiting for root updates    sleep=29m59.937671166s tree=enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@snap.ropsten.ethdisco.net

**Comment by holiman** [comment]
It doesn't spin when I run it on goerli, however, my simple testcase in the bug-entry does cause a spin. `go test . -run TestEmptyIterator --cpuprofile cpu.out -timeout 10s`
profile001

**Comment by holiman** [comment]
Sorry, I ran the wrong code!

**Review by holiman — APPROVED** [review]
This seems to solve the issue :+1:

File: p2p/dnsdisc/client.go [hunk 2]
```diff
@@ -282,26 +285,79 @@ func (it *randomIterator) nextNode() *enode.Node {
...
+		} else {
+			it.disabledList = append(it.disabledList, ct)
 		}
-		limit--
 	}
-	return nil
+	if len(it.syncableList) > 0 {
+		return true, it.syncableList
+	}
+	return false, it.disabledList
```
Comment (holiman) [inline p2p/dnsdisc/client.go:336]: Maybe this totally doesn't matter (depends on how large the trees are?), but you could resize the unused one to zero here before returning

**Review by holiman — APPROVED** [review]
Still LGTM, one question only

File: p2p/dnsdisc/client.go (hunk 2 above)
Comment (fjl) [reply p2p/dnsdisc/client.go:336]: At the moment, we only use one tree per client and I'm not worried about the memory usage. But will think about a way to avoid holding on to the trees in the future.
