### PR TITLE
common/compiler: new solc API

### LINKED ISSUE #1770: eth.compile with solidity 0.1.2
Name: "Geth/v1.1.2-58766921/linux/go1.4.2"

cannot compile the simple sample (from Frontier guide) using solc 0.1.2

```
> eth.getCompilers()
["Solidity"]

> source
"contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"

> eth.compile.solidity(source)
solc error: missing code output
    at InvalidResponse (<anonymous>:-81076:-29)
    at send (<anonymous>:-154580:-29)
    at solidity (<anonymous>:-131712:-29)
    at <anonymous>:1:1
```

### PR DESCRIPTION
**Pull request by zelig**
* adapt to new compiler versioning
* use compiler version as language version
* implement new solc API for versions >= 0.1.[2-9][0-9]* fixes #1770
* add optimize=1 to options
* backward compatibility (for now) for <= 0.1.1, and old versions (0.[2-9][0-9]*.[0-9]+)
* introduce compilerOptions to ContractInfo
* clean up flair, include full version string to version line and ContractInfo

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Sep 10 12:15:22 UTC 2015_

File: common/compiler/solidity.go [hunk 1]
```diff
@@ -122,11 +134,21 @@ func (sol *Solidity) Compile(source string) (map[string]*Contract, error) {
 	if err != nil {
 		return nil, fmt.Errorf("solc: failed to create temporary build folder: %v", err)
 	}
-	defer os.RemoveAll(wd)
+	// defer os.RemoveAll(wd)
```
Comment (Gustav-Simonsson) [inline common/compiler/solidity.go]: Can be removed? Also what does os.ModePerm do when the return is not used?

Comment (zelig) [inline common/compiler/solidity.go]: thx @Gustav-Simonsson  thank good we got review!

File: common/compiler/solidity_test.go [hunk 2]
```diff
@@ -26,7 +26,7 @@ import (
 	"github.com/ethereum/go-ethereum/common"
 )
 
-const solcVersion = "0.9.23"
+const solcVersion = "0.1.1"
```
Comment (obscuren) [inline common/compiler/solidity_test.go]: Huh, `solc` went backward in version numbering?

**Comment by obscuren** [comment]
:+1: LGTM

File: common/compiler/solidity_test.go (hunk 2 above)
Comment (zelig) [inline common/compiler/solidity_test.go]: yep. funny right?

File: common/compiler/solidity.go [hunk 3]
```diff
@@ -54,6 +49,15 @@ var (
 		"--add-std",
 		"1",
 	}
+	paramsNew = []string{
+		"--bin",        // Request to output the contract in binary (hexadecimal).
+		"--abi",        // Request to output the contract's JSON ABI interface.
+		"--userdoc",    // Request to output the contract's Natspec user documentation.
+		"--devdoc",     // Request to output the contract's Natspec developer documentation.
+		"--add-std",    // include standard lib contracts
+		"--optimize=1", // code optimizer switched on
```
Comment (chriseth) [inline common/compiler/solidity.go]: Does this work? I think it should be simply `--optimize`.

File: common/compiler/solidity.go [hunk 4]
```diff
@@ -34,15 +34,10 @@ import (
...
-	// flair           = "Christian <c@ethdev.com> and Lefteris <lefteris@ethdev.com> (c) 2014-2015"
-	flair           = ""
-	languageVersion = "0"
-)
-
 var (
-	versionRegExp = regexp.MustCompile("[0-9]+.[0-9]+.[0-9]+")
-	params        = []string{
+	versionRegExp = regexp.MustCompile("[0-9]+\\.[0-9]+\\.[0-9]+")
+	newAPIRegexp  = regexp.MustCompile("0\\.1\\.[2-9][0-9]*")
```
Comment (chriseth) [inline common/compiler/solidity.go]: `0.1.10` and `0.2.0` probably still have the new interface

File: common/compiler/solidity_test.go (hunk 2 above)
Comment (chriseth) [inline common/compiler/solidity_test.go]: `0.9.23` was the version of cpp-ethereum. At the point solc was actually released, it started with `0.1.0`.

File: common/compiler/solidity.go (hunk 4 above)
Comment (zelig) [inline common/compiler/solidity.go]: @chriseth ok so what version matching should I use to catch legacy? I wanna be backward compatible on cpp versions but yeah it is also inconvenient to have to change the api when solc 0.2 is out. 
As an alternative you could include an API version in the output of --version so I can match on it from now on. Then I only have to match 0.1.2 additionally and the rest is legacy?

Comment (chriseth) [inline common/compiler/solidity.go]: I guess "0\\.(9\\..*|1\\.[01])" should work fine to detect legacy.

File: common/compiler/solidity_test.go (hunk 2 above)
Comment (obscuren) [inline common/compiler/solidity_test.go]: Ah cool :+1:

File: common/compiler/solidity.go (hunk 3 above)
Comment (tgerring) [inline common/compiler/solidity.go]: Solidity can accept two different "optimize" parameters, both of which accept an integer value, hence the desire to pass it through from Geth.

```
--optimize arg (=0)                   Optimize bytecode
--optimize-runs arg (=200)            Estimated number of contract runs for optimizer.
```

Comment (chriseth) [inline common/compiler/solidity.go]: For me the help screen looks like this:
```
  --optimize           Enable bytecode optimizer.
  --optimize-runs n (=200)
                       Estimated number of contract runs for optimizer tuning.
```

**Comment by fjl** [comment]
:+1:

File: common/compiler/solidity.go (hunk 3 above)
Comment (ethers) [inline common/compiler/solidity.go]: I just rebuit geth develop branch with this fix and I think @chriseth is correct that this does NOT work...
```
"solc: exit status 1
option '--optimize' does not take any arguments"
```
