### PR TITLE
core/state: ensure deterministic hook emission order in Finalise

### LINKED ISSUE #33630: Flaky test
--- FAIL: TestHooks_OnCodeChangeV2 (0.00s)
    statedb_hooked_test.go:171: error event 2
        have: 0xbb00000000000000000000000000000000000000.code: 0x1326 (0x3c54516221d604e623f358bc95996ca3242aaa109bddabcebda13db9b3f90dcb) -> (0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470) SelfDestruct
        want: 0xaa00000000000000000000000000000000000000.code: 0x1325 (0xa12ae05590de0c93a00bc7ac773c2fdb621e44f814985e72194f921c0050f728) -> (0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470) SelfDestruct
FAIL
FAIL	github.com/ethereum/go-ethereum/core/state	14.796s

see: https://github.com/ethereum/go-ethereum/pull/33628

### PR DESCRIPTION
**Pull request by forkfury**
Fixes #33630

Sort self-destructed addresses before emitting hooks in Finalise() to ensure deterministic ordering and fix flaky test TestHooks_OnCodeChangeV2.

### CODE REVIEW

**Review by jwasinger — APPROVED** [review]

File: core/state/statedb_hooked.go [hunk 1]
```diff
@@ -234,13 +236,25 @@ func (s *hookedStateDB) Finalise(deleteEmptyObjects bool) {
...
+	var selfDestructedAddrs []common.Address
 	for addr := range s.inner.journal.dirties {
 		obj := s.inner.stateObjects[addr]
 		if obj == nil || !obj.selfDestructed {
 			// Not self-destructed, keep searching.
 			continue
 		}
+		selfDestructedAddrs = append(selfDestructedAddrs, addr)
+	}
+	// Sort addresses to ensure deterministic hook emission order.
```
Comment (jwasinger) [inline core/state/statedb_hooked.go]:
```suggestion
```

File: core/state/statedb_hooked.go [hunk 2]
```diff
@@ -234,13 +236,25 @@ func (s *hookedStateDB) Finalise(deleteEmptyObjects bool) {
...
+	sort.Slice(selfDestructedAddrs, func(i, j int) bool {
+		return bytes.Compare(selfDestructedAddrs[i][:], selfDestructedAddrs[j][:]) < 0
+	})
+
+	// Iterate over sorted addresses and record self-destructs.
```
Comment (jwasinger) [inline core/state/statedb_hooked.go]:
```suggestion
```

**Review by jwasinger — CHANGES_REQUESTED** [review]
LGTM but I would remove a few of the comments, because they don't improve the readability.

File: core/state/statedb_hooked.go [hunk 3]
```diff
@@ -234,13 +236,23 @@ func (s *hookedStateDB) Finalise(deleteEmptyObjects bool) {
 		return
 	}
 
-	// Iterate all dirty addresses and record self-destructs.
+	// Collect all self-destructed addresses first, then sort them to ensure
+	// deterministic ordering when emitting hooks.
```
Comment (jwasinger) [inline core/state/statedb_hooked.go]:
```suggestion
	// that state change hooks will be invoked in deterministic
	// order when the accounts are deleted below
```
