### PR TITLE
eth/filter: check nil pointer when unsubscribe

### LINKED ISSUE #16606: Segmentation Fault(SIGSEGV) when starting Geth
Geth version: 1.8.6-stable
OS & Version: Ubuntu 16.04.2

#### Expected behaviour
Geth should start syncing the blockchain.

#### Actual behaviour
Geth crashes with segmentation violation

#### Steps to reproduce the behaviour
No specific steps. Simply starting Geth.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6faab]

goroutine 83 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc420662940)
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:434 +0x2eb
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/build/ethereum-LEwR9U/ethereum-1.8.6+build13246+xenial/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:113 +0x104
````

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #16606 and #16675 
The reason for the system crash is: When we try to bind an non-exist address to a tcp listener, it will return an error and exit the system.
While we do something in parallel, for example **subscribe events in filter system**. So sometime, we do subscribe before we stop the `blockchain`, sometime we do subscribe after we stop the `blockchain`.  For the latter case, our subscription returned is nil, so when unsubscribe is invoked, crash happen.

### CODE REVIEW

**Comment by rjl493456442** [comment]
@karalabe Updated. I'm not sure whether it can be accepted.
I return a nil when we create service instance failed due to subscribing failed. When we register RPC service with this empty instance, it will be detected and exit the system. But it is quite implicit.
We can also filter the invalid service instances when we register the RPC services. Which way is better?

**Comment by karalabe** [comment]
Hmm, it is indeed less than desirable.

Could we then instead not return an error, but still do the subscriptions inside New? That should ensure that we don't terminate before booting up in the first place. Would that be enough to fix this issue?

**Comment by rjl493456442** [comment]
@karalabe Updated.

File: eth/filters/filter_system.go [hunk 1]
```diff
@@ -108,10 +121,36 @@ func NewEventSystem(mux *event.TypeMux, backend Backend, lightMode bool) *EventS
...
+	}
+	m.chainSub = m.backend.SubscribeChainEvent(m.chainCh)
+	if m.chainSub == nil {
+		return nil
+	}
+	// TODO(rjl493456442): use feed to subscribe pending log event
+	m.pendingLogSub = m.mux.Subscribe(core.PendingLogsEvent{})
+	if m.pendingLogSub.Closed() {
+		return nil
+	}
```
Comment (karalabe) [inline eth/filters/filter_system.go]: The `return nil`-s here are problematic, because they promote bad use. It says to the caller that they should check whether the return is `nil`, and handle it as an error. If we want to handle error cases, we need to return an `error`. If we don't want to handle error cases, we need to abort.

Returning `nil` is furthermore problematic because it doesn't clean up previous successful subscriptions.

In theory these code paths cannot get called, at least if the code initialization code is correct. As such we should either not care about them becoming `nil` (and panic if they do and find the culprit further up the stack), or if we want to handle things a bit more gracefully, we could do a `log.Crit` to abort.

**Comment by rjl493456442** [comment]
@karalabe Please take a look again.

File: eth/filters/filter_system.go [hunk 2]
```diff
@@ -411,50 +442,36 @@ func (es *EventSystem) lightFilterLogs(header *types.Header, addresses []common.
...
+	var index = make(filterIndex)
+
+	defer func() {
+		// Unsubscribe all events
+		es.pendingLogSub.Unsubscribe()
+		es.txSub.Unsubscribe()
+		es.logsSub.Unsubscribe()
+		es.rmLogsSub.Unsubscribe()
+		es.chainSub.Unsubscribe()
+	}()
```
Comment (karalabe) [inline eth/filters/filter_system.go]: Minor suggestions:

  * Put the `// Unsubscribe all events` commen outside of the defer, on the line before it
  * Instead of `var index = make(filterIndex)`, use `index := make(filterIndex)`
  * Move the `index` creation down below the defers, to keep things clean and everywhere where they are used.

```go
func (es *EventSystem) eventLoop() {
	// Ensure all subscriptions get cleaned up
	defer func() {
		es.pendingLogSub.Unsubscribe()
		es.txSub.Unsubscribe()
		es.logsSub.Unsubscribe()
		es.rmLogsSub.Unsubscribe()
		es.chainSub.Unsubscribe()
	}()

	index := make(filterIndex)
	for i := UnknownSubscription; i < LastIndexSubscription; i++ {
		index[i] = make(map[rpc.ID]*subscription)
	}
```

File: eth/filters/filter_system.go [hunk 3]
```diff
@@ -108,10 +122,27 @@ func NewEventSystem(mux *event.TypeMux, backend Backend, lightMode bool) *EventS
...
-	go m.eventLoop()
+	// Subscribe events
+	m.txSub = m.backend.SubscribeTxPreEvent(m.txCh)
+	m.logsSub = m.backend.SubscribeLogsEvent(m.logsCh)
+	m.rmLogsSub = m.backend.SubscribeRemovedLogsEvent(m.rmLogsCh)
+	m.chainSub = m.backend.SubscribeChainEvent(m.chainCh)
+	// TODO(rjl493456442): use feed to subscribe pending log event
+	m.pendingLogSub = m.mux.Subscribe(core.PendingLogsEvent{})
+
+	// Make sure all the subscriptions are not empty
```
Comment (karalabe) [inline eth/filters/filter_system.go]: Formulation nitpick, `all the subscriptions are not empty` is not really correct grammatically, please fix to `none of the subscriptions are empty`.

File: event/event.go [hunk 4]
```diff
@@ -180,6 +180,10 @@ func (s *TypeMuxSubscription) Unsubscribe() {
 	s.closewait()
 }
 
+func (s *TypeMuxSubscription) Closed() bool {
+	return s.closed
```
Comment (karalabe) [inline event/event.go]: This is racey. You need to add a read lock for `s.closeMu`.
