### PR TITLE
graphql, node, rpc: improve HTTP write timeout handling

### LINKED ISSUE #21430: Calls for block/transaction information sometimes don't return
This is intended to be a migration of [this issue](https://github.com/ethereum/web3.js/issues/3656) originally filed on web3.  However, I dove all the way in to the W3CWebSocket used by web3 and found that the requests are being sent but the responses were not being received at all from geth, so I don't think it's a web3 issue.

Additionally, I have an odd observation from Geth which might help in debugging.

#### System information
Geth version: 1.9.18
OS & Version: Windows/Linux/OSX: Windows 10

#### Steps to reproduce the behaviour
Follow the setup [here](https://github.com/ethereum/web3.js/issues/3656#issuecomment-668108119). Use a WebSocket URL when connecting to geth (in truffle-config) and in `migrations/3_increment_counter.js` you can set `batchSize` to 100 without an issue.  This should produce a blockchain with >100K transactions in just over 1000 blocks, with most blocks containing 100 transactions (sometimes that's split across a couple). 

The expected and actual behavior are as listed there.  If the responses are not going to be responded to, some error is expected; if no error at least some logging and documentation about how to configure the threshold would be better than status quo silent failure. 

Now here's the twist.  If I make all three of the following changes (from the code as of the 1.9.18 release tag), I get the expected results.  The changes are all Geth console logging and *shouldn't* affect correctness of operation, but in combination, these three log statements do. The changes are:
  - In internal/ethapi/api.go, the getBlockByNumber function, add at the start of the function `log.Info("In api.go GetBlockByNumber", "number", number);`
  - In core/blockchain.go, the getBlock function, add at the start of the function `log.Info("In getBlock for number", "number", number);`
  - In core/blockchain.go, the getBlock function, add at the start of the if block for checking the cache `log.Info("Returning from getBlock (cached) for number", "number", number);`

The third one gets lots of use because of how the transaction generation and querying process works; if yours isn't doing that you could add a similar log statement (without "cached") just before the return statement.

Comment out any of those three and Geth only returns data for roughly 325 blocks and 0 transactions out of an expected 100K of each. Include all three, and you get the expected 100K block and 100K transactions returned.

I suspect that there may be some buffer or limit that is being overwhelmed, causing some glitch that leads Geth to stop sending responses to queries for at least a little while, and that these log statements slow down processing just enough that the issue threshold is never exceeded.  However, I'm not yet quite sure where that threshold is set.

### PR DESCRIPTION
**Pull request by s1na**
A work-around for https://github.com/golang/go/issues/47229. Trigger timeout a bit before stdlib closes the connection so users see a proper error message. Note I still kept the WriteTimeout of the http.Server.

I'm not sure what happens if the method handler and the timeout statement both write at the same time

Fixes #21430

### CODE REVIEW

**Comment by s1na** [comment]
I implemented a different approach we roughly discussed with @fjl:

the rpc handler will run the method in a goroutine now. It waits for that to finish OR the context deadline to expire, in which case returns an error. The method will be running in background until it stops (possible leak). Therefore it's important that long-running methods respect context deadline. I made sure this happens in `getLogs` which received most of the tickets of this issue.

The timeout is being set in the outer layer (`node/rpcstack`). Alternatively we can pass it through to handler for it to set the timeout.

Note: The error type I added feels awkward between official json-rpc errors.

File: node/rpcstack.go [hunk 1]
```diff
@@ -198,6 +198,9 @@ func (h *httpServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	// if http-rpc is enabled, try to serve request
 	rpc := h.httpHandler.Load().(*rpcHandler)
 	if rpc != nil {
+		ctx, cancel := context.WithTimeout(r.Context(), h.timeouts.ReadTimeout-(50*time.Millisecond))
```
Comment (s1na) [inline node/rpcstack.go:201]: Also this here. 50 ms is totally a magic number. I think lower numbers like 20ms should also be fine.

File: rpc/handler.go [hunk 2]
```diff
@@ -334,8 +334,20 @@ func (h *handler) handleCall(cp *callProc, msg *jsonrpcMessage) *jsonrpcMessage
 		return msg.errorResponse(&invalidParamsError{err.Error()})
 	}
 	start := time.Now()
-	answer := h.runMethod(cp.ctx, msg, callb, args)
+	answerCh := make(chan *jsonrpcMessage)
+	go func() {
+		answer := h.runMethod(cp.ctx, msg, callb, args)
+		answerCh <- answer
```
Comment (holiman) [inline rpc/handler.go:340]:
```suggestion
		answerCh <- h.runMethod(cp.ctx, msg, callb, args)
```

**Comment by holiman** [comment]
This seems to work well. With the test-method like this: 
```diff
diff --git a/internal/ethapi/api.go b/internal/ethapi/api.go
index 90322033b9..b90ac5048d 100644
--- a/internal/ethapi/api.go
+++ b/internal/ethapi/api.go
@@ -2035,3 +2035,10 @@ func toHexSlice(b [][]byte) []string {
 	}
 	return r
 }
+
+func (api *DebugAPI) TimeMeOut(ctx context.Context, seconds uint64) (string, error) {
+	log.Info("TimeMeOut sleeping...", "seconds", seconds)
+	time.Sleep(time.Second * time.Duration(seconds))
+	log.Info("TimeMeOut waking up!")
+	return "Oll korrekt!", nil
+}

```
The `25s` works fine, but `35s` times out
```
[user@work go-ethereum]$ curl --data '{"method":"debug_timeMeOut","params":[25],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","id":1,"result":"Oll korrekt!"}
[user@work go-ethereum]$ curl --data '{"method":"debug_timeMeOut","params":[35],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":408,"message":"request timed out"}}
```
And the timeout triggers after `30s`:
```
INFO [08-30|18:47:55.105] TimeMeOut sleeping...                    seconds=35
WARN [08-30|18:48:25.056] Served debug_timeMeOut                   conn=127.0.0.1:44346 reqid=1 duration=29.950591423s err="request timed out"
INFO [08-30|18:48:30.106] TimeMeOut waking up! 
```

**Review by holiman — APPROVED** [review]

File: rpc/handler.go [hunk 3]
```diff
@@ -334,8 +334,19 @@ func (h *handler) handleCall(cp *callProc, msg *jsonrpcMessage) *jsonrpcMessage
 		return msg.errorResponse(&invalidParamsError{err.Error()})
 	}
 	start := time.Now()
-	answer := h.runMethod(cp.ctx, msg, callb, args)
+	answerCh := make(chan *jsonrpcMessage)
```
Comment (fjl) [inline rpc/handler.go:337]: This channel needs to be buffered, otherwise the handler goroutine will leak when there is a timeout.

**Review by fjl — CHANGES_REQUESTED** [review]
What I don't like about this PR, is that the RPC handler will keep running in case of timeout, because it executes the RPC call on a background goroutine now.

It would be nicer to keep this out and rely on the individual RPC handlers to exit promptly when the context is canceled.

**Comment by holiman** [comment]
Triage discussion: worth doing this or is it dead in the water, due to the inherent limitations of this apprach?

**Comment by fjl** [comment]
Alternative approach:

When handling RPC call, launch a timer using `time.AfterFunc(timeout, callback)` where the callback will deliver the error response **if the response was not sent yet**. This can be done using a 1-buffered channel for example.

```go
responseSlot := make(chan struct{}, 1)
responseSlot <- struct{}{}

responded := make(struct{})

timeoutResponseTimer := time.AfterFunc(timeout, func() {
    select {
    case <-responseSlot:
         // The timeout occurred and the method has not responded yet.
         // send the timeout error response
         close(responded)
    case <-responded:
         // The method responded.
    }
})

response := runMethod()
timeoutResponseTimer.Stop()
select {
   case <-responseSlot:
       // send the response
       close(responded)
   case <-responded:
       // timeout error response was already sent
}
```

**Comment by fjl** [comment]
Actually, it can also be done with less channels using `sync.Once`

```go
var respondOnce sync.Once
timeoutResponseTimer := time.AfterFunc(timeout, func() {
    respondOnce.Do(func () {
        // send timeout error
    })
})

response := runMethod()
timeoutResponseTimer.Stop()
respondOnce.Do(func () {
    // send response
})
```

**Comment by s1na** [comment]
We tried this approach with Felix. Some notes:

- Now an error is always returned when timeout hits, without launching unnecessary routines 👍 
- Also timeouts are now handled to batch requests too which we had missed before
- There's a small issue we have to investigate. When timeout happens curl gives a warning `curl: (18) transfer closed with outstanding read data remaining`
- Also batch timeout handling got out of hand with mutex, probably try channels

**Comment by holiman** [comment]
This PR closes #26127 (probably)

File: rpc/errors.go [hunk 4]
```diff
@@ -117,3 +117,10 @@ type internalServerError struct {
 func (e *internalServerError) ErrorCode() int { return e.code }
 
 func (e *internalServerError) Error() string { return e.message }
+
+// timeout reached
+type timeoutError struct{}
+
+func (e *timeoutError) ErrorCode() int { return 408 }
+
+func (e *timeoutError) Error() string { return "request timed out" }
```
Comment (fjl) [inline rpc/errors.go:126]: The error code needs to be in the `-32xxx` range (it's an "implementation-defined server error").

File: rpc/http.go [hunk 5]
```diff
@@ -254,7 +254,17 @@ type httpServerConn struct {
 func newHTTPServerConn(r *http.Request, w http.ResponseWriter) ServerCodec {
 	body := io.LimitReader(r.Body, maxRequestContentLength)
 	conn := &httpServerConn{Reader: body, Writer: w, r: r}
-	return NewCodec(conn)
+	enc := json.NewEncoder(conn)
+	dec := json.NewDecoder(conn)
+	dec.UseNumber()
+	encoder := func(v any) error {
+		err := enc.Encode(v)
+		if f, ok := w.(http.Flusher); ok {
```
Comment (fjl) [inline rpc/http.go:262]: Need to add a comment here, something like

```
// In case of a timeout error, the response must be written before the HTTP server's write
// timeout occurs. So we need to flush the response here.
```

File: rpc/handler.go [hunk 6]
```diff
@@ -91,6 +91,77 @@ func newHandler(connCtx context.Context, conn jsonWriter, idgen func() ID, reg *
...
+	for _, msg := range b.calls {
+		if !msg.isNotification() {
+			b.answers = append(b.answers, msg.errorResponse(&internalServerError{errcodeTimeout, errMsgTimeout}))
+		}
+	}
+
+	b.write(ctx, conn)
+}
+
+func (b *batchCallBuffer) popCall() *jsonrpcMessage {
```
Comment (holiman) [inline rpc/handler.go:116]: Since this method doesn't _actually_ `pop`, perhaps `peekCall` would a more apt name?

File: rpc/handler.go [hunk 7]
```diff
@@ -113,16 +184,35 @@ func (h *handler) handleBatch(msgs []*jsonrpcMessage) {
...
+			// No need to handle rest of calls if timed out.
+			if ctx.Err() != nil {
+				break
+			}
+			msg := callBuffer.popCall()
+			if msg == nil {
+				break
 			}
+			answer := h.handleCallMsg(cp, msg)
+			callBuffer.pushAnswer(answer)
```
Comment (holiman) [inline rpc/handler.go:209]: For the timeouts, you take care and ensure that you don't push a response to a notification, but here you unconditionally push the anwer.  The previous code only did something with the answer after checking `answer != nil`, and I see you have moved that check into `handleCall`. 
I suspect that this works fine, but perhaps a more robust way to do it would be to 

```golang
if !msg.IsNotification() { 
    callBuffer.pushAnswer(answer)
}
```

**Comment by s1na** [comment]
For some reason Go's http client doesn't play nice with how we're handling timeouts. When using `ethclient` to invoke a method that times out, I get `Post "http://127.0.0.1:8545": EOF` instead of the timeout response. cURL and JS clients work fine.

**Comment by s1na** [comment]
Aha I found out why one is working and the other not. If request has `Accept-Encoding: gzip` (default for go client) then it stalls and connection is cut. Going to look into the reason.

**Comment by s1na** [comment]
`Content-Length` was wrong for gzip compressed responses. But after fixing that still the problem is not gone. Requests with `Accept-Encoding: gzip` that time out still hang.

**Comment by fjl** [comment]
There is still one unresolved issue with this PR, and it's that the server outputs incomplete chunked-transfer encoding in case of timeout when gzip is enabled. Apparently, the Go htto client doesn't care. curl warns about it:

```
curl: (18) transfer closed with outstanding read data remaining
```

In linked issue #26127, the Python http client raised an exception about it. The problem with implementing it correctly, is that we'd need to compress the entire response to get the correct Content-Length.

Another way of handling this could be to disable compression for error responses somehow.

File: rpc/http.go [hunk 8]
```diff
@@ -273,6 +273,14 @@ func newHTTPServerConn(r *http.Request, w http.ResponseWriter) ServerCodec {
 			return err
 		}
 		w.Header().Set("content-length", strconv.Itoa(len(encdata)))
+
+		// If this request is wrapped in a handler that might remove Content-Length (such
+		// as the automatic gzip we do in package node), we need to ensure the HTTP server
+		// doesn't perform chunked encoding. When timeout case, the chunked encoding might
+		// not be finished correctly, and some clients will refuse to process the response
+		// when the final chunk is missing.
+		w.Header().Set("transfer-encoding", "identity")
```
Comment (holiman) [inline rpc/http.go:282]: Will this still use content-encoding gzip, but transfer-encoding identity?

Comment (s1na) [reply rpc/http.go]: Yes content-encoding will be gzip. This solution fixes it for some clients, most notably the go http client (and python).

Curl and ethers.js fail with EoF. I initially thought it fixes ethers but seems gzip compression is disabled by default. After enabling it, it fails too.

```console
❯ curl -X POST -H "Content-Type: application/json" -H "Accept-Encoding: gzip" --data '{"method":"eth_blockNumber","id":1,"jsonrpc":"2.0"}' --output - -s http://127.0.0.1:8545 | gunzip -
gunzip: (stdin): unexpected end of file
```

```js
const { ethers } = require('ethers')
async function main() {
    const provider = new ethers.providers.JsonRpcProvider({ url: 'http://127.0.0.1:8545', allowGzip: true })
    const num = await provider.getBlockNumber()
    console.log(num)
}
main().then().catch((err) => console.log(err))
```
Result:
```console
❯ node test.js
node:zlib:465
      throw self[kError];
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at processChunkSync (node:zlib:455:12)
    at zlibBufferSync (node:zlib:178:12)
    at syncBufferWrapper (node:zlib:790:14)
    at IncomingMessage.<anonymous> (/Users/sina/dev/geth-scripts/node_modules/ethers/node_modules/@ethersproject/web/lib/geturl.js:78:81)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

Comment (s1na) [reply rpc/http.go]: That said, I think this PR is strictly much better than status quo:
- If gzip compression is disabled it returns an error message on timeout across the board, both for messages and batch requests.
- Timing wise error is returned as soon as timeout hits and connection is terminated, instead of waiting until the method handler returns. This is also strictly an improvement because connection was only cut after the method handler returned before.
- When gzip is enabled the Go client will get the error message. Curl and ethers.js don't. But even there connection is cut sooner and there wasn't a response before anyway.

**Comment by holiman** [comment]
Usign the tests from https://github.com/ethereum/go-ethereum/issues/21430#issuecomment-853695381:

```
[user@work go-ethereum]$ curl --data '{"method":"debug_timeMeOut","params":[25],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","id":1,"result":"Oll korrekt!"}
[user@work go-ethereum]$ curl --data '{"method":"debug_timeMeOut","params":[30],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":408,"message":"request timed out"}}

```
LGTM!

**Review by holiman — APPROVED** [review]

**Comment by s1na** [comment]
I'm going to revert #26116 in this PR since the HTTP timeout cuts connection on graphql anyway. Unfortunately there's no error message in this case either:

```console
❯ curl -X POST -H "Content-Type: application/json" --data '{"query":"query{block() { number }}"}' --output - http://127.0.0.1:8545/graphql
curl: (52) Empty reply from server
```

**Comment by s1na** [comment]
Graphql also returns an error now. Note it's a plain error with status internal server error. Similar to how we did it for json marshalling error:

```console
❯ curl -X POST -H "Content-Type: application/json" --data '{"query":"query{block() { number }}"}' -v http://127.0.0.1:8545/graphql
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8545...
* Connected to 127.0.0.1 (127.0.0.1) port 8545 (#0)
> POST /graphql HTTP/1.1
> Host: 127.0.0.1:8545
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 37
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 17
< Date: Tue, 29 Nov 2022 14:08:54 GMT
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host 127.0.0.1 left intact
request timed out
```

**Comment by fjl** [comment]
Can't we return a GraphQL error response?

File: rpc/http.go (hunk 8 above)
Comment (fjl) [reply rpc/http.go]: Been thinking about it more, we could check for the special value `transfer-encoding` value `identity` in the gzip handler and skip compression. That would fix the JS problem.

Comment (s1na) [reply rpc/http.go]: It works! both for JS and curl. Will push it now

Comment (s1na) [reply rpc/http.go]: I'm not sure if there's still a benefit in keeping the length-tracking in gzipWriter. I think we can remove it?

**Comment by fjl** [comment]
I have decided to remove changes in eth/filters and eth/tracers from the PR. We can submit them in a separate change.

**Comment by fjl** [comment]
RPC method handler changes resubmitted in https://github.com/ethereum/go-ethereum/pull/26320
