### PR TITLE
p2p/discover: fix race involving the seed node iterator

### LINKED ISSUE #1660: segfault on Windows
Version: `   /v1.0.1/windows/go1.4.2`
What I did: nothing, just let it run in the background for around 2 days, computer was sleeping a few times in between. Also ran a VirtualBox VM but I don't think I ran out of memory.

Started using:
`.\geth.exe --rpc --rpcaddr="localhost" --rpcport="8545" --rpccorsdomain="http://localhost:3000" --verbosity=3 --datadir "..\geth_data" --genesis "..\genesis.json" console`

Output / stacktrace:
http://hastebin.com/pupozejoro.avrasm

### PR DESCRIPTION
**Pull request by fjl**
nodeDB.querySeeds was not safe for concurrent use but could be called
concurrenty on multiple goroutines in the following case:

- the table was empty
- a timed refresh started
- a lookup was started and initiated refresh

These conditions are unlikely to coincide during normal use, but are
much more likely to occur all at once when the user's machine just woke
from sleep. The root cause of the issue is that querySeeds reused the
same leveldb iterator until it was exhausted.

This commit moves the refresh scheduling logic into its own goroutine
(so only one refresh is ever active) and changes querySeeds to not use
a persistent iterator. The seed node selection is now more random and
ignores nodes that have not been contacted in the last 5 days.

Fixes #1660. 

@karalabe wrote the previous implementation of the refresh logic and might be the
best person to judge these changes.

------------------------

Note: The last commit removes the strict version matching on discovery packets
because it makes protocol upgrades much harder. I'm trying to sneak this in before
1.2.0.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Sep 30 03:26:06 UTC 2015_

File: p2p/discover/database_test.go [hunk 1]
```diff
@@ -224,63 +241,6 @@ func TestNodeDBSeedQuery(t *testing.T) {
...
-		t.Errorf("seed count mismatch: have %v, want %v", len(seeds), len(nodeDBSeedQueryNodes)-1)
-	}
-	have := make(map[NodeID]struct{})
-	for _, seed := range seeds {
-		have[seed.ID] = struct{}{}
-	}
-	if _, ok := have[self]; ok {
-		t.Errorf("self not evacuated")
-	}
 }
```
Comment (karalabe) [inline p2p/discover/database_test.go]: Do we want to delete the self query test? At a certain point we had issues with geth trying to connect to itself because `self id` ended up in the seed database. Wouldn't it be worth to keep this test (and the self test check in the lookup mechanism) still in?

File: p2p/discover/table.go [hunk 2]
```diff
@@ -257,56 +266,91 @@ func (tab *Table) Lookup(targetID NodeID) []*Node {
...
+func (tab *Table) doRefresh(done chan struct{}) {
+	defer close(done)
+
+	// Start the background expiration goroutine when the first
+	// refresh is done. Subsequent calls have no effect if it is
+	// already running.
+	// We do this here instead of somewhere else so that the very
+	// first DB iteration to find seed nodes also considers older
+	// nodes that would otherwise be removed by the expiration.
+	defer tab.db.ensureExpirer()
```
Comment (karalabe) [inline p2p/discover/table.go]: I'm not sure this is correct here. The previous semantics was that nodes should only be evacuated if we managed to contact at least one external node in the network (then we have a potentially working peer to bootstrap from). But with the expirer moved here, it will start dumping the node db immediately after a seed cycle, even if all the seed nodes were unreachable (e.g. you are offline).

File: p2p/discover/table.go [hunk 3]
```diff
@@ -44,6 +44,10 @@ const (
 
 	maxBondingPingPongs = 16
 	maxFindnodeFailures = 5
+
+	autoRefreshInterval = 1 * time.Hour
+	seedCount           = 30
+	seedMaxAge          = 5 * 24 * time.Hour
```
Comment (karalabe) [inline p2p/discover/table.go]: Do we need this max age thing? Nodes older than 24h should be automatically evacuated if the node has a healthy connection, so given that you were recently connected, everything should be fresh. On the other hand if you weren't connected for a long time, then at least give a fighting chance with the seeds and not simply disable them altogether. I'd rely on the expiration mechanism for cleanup and not limit the max are during seed retrieval.

File: p2p/discover/udp.go [hunk 4]
```diff
@@ -529,9 +521,6 @@ func (req *ping) handle(t *udp, from *net.UDPAddr, fromID NodeID, mac []byte) er
 	if expired(req.Expiration) {
 		return errExpired
 	}
-	if req.Version != Version {
-		return errBadVersion
-	}
```
Comment (karalabe) [inline p2p/discover/udp.go]: How does this help during protocol updates? By the newer nodes potentially trying to parse the older nodes' packets? Wouldn't there be problems the other way around when only a few older nodes are left and they can't discover an more (although it's debatable, that such a scenario would appear anyway during any update).

Comment (fjl) [inline p2p/discover/udp.go]: A new version doesn't necessarily mean that the packet format changes.
This change can help in the following case:

We want to make a breaking change to rlpx. Nodes that have the new code need to know
the version of the node they're connecting in order to decide whether to use the old or the new
logic.

File: p2p/discover/table.go (hunk 3 above)
Comment (fjl) [inline p2p/discover/table.go]: I added this because I noticed that most of the seed nodes found in my database had a last pong time of more than a week ago. This can happen because the first expiration happens 1h after startup. Nodes that haven't been contacted for that long are unlikely to be still alive.

File: p2p/discover/database_test.go (hunk 1 above)
Comment (fjl) [inline p2p/discover/database_test.go]: In hindsight, I think that removing the self entries is misguided. We should rather make sure that
self never ends up in the database.

File: p2p/discover/table.go (hunk 2 above)
Comment (fjl) [inline p2p/discover/table.go]: fixed

File: p2p/discover/database_test.go (hunk 1 above)
Comment (fjl) [inline p2p/discover/database_test.go]: I added a check to not include self in the seed result slice.

**Comment by alexvandesande** [comment]
👏🏻 Have no meaningful comment but would like to say that I enjoyed looking at the code and thanks for finding the bug.

**Comment by karalabe** [comment]
LGTM :+1:

File: p2p/discover/database.go [hunk 5]
```diff
@@ -302,52 +300,70 @@ func (db *nodeDB) updateFindFails(id NodeID, fails int) error {
...
+func (db *nodeDB) querySeeds(n int, maxAge time.Duration) []*Node {
+	var (
+		now   = time.Now()
+		nodes = make([]*Node, 0, n)
+		it    = db.lvl.NewIterator(nil, nil)
+		id    NodeID
+	)
+	defer it.Release()
+
+seek:
```
Comment (Gustav-Simonsson) [inline p2p/discover/database.go]: Just out of curiosity, what is the advantage of this label?

**Comment by obscuren** [comment]
:+1: squash commits please

File: p2p/discover/database.go (hunk 5 above)
Comment (fjl) [inline p2p/discover/database.go]: The loop is structured like this:

```
for {
     node = load random node
     check
     check
     check
     add as result
}
```

If any if the checks fail, the node is not added to the result. `continue seek` is supposed to make that cleat.
