### PR TITLE
console, cli, api fixes

### LINKED ISSUE #1457: admin registrar commands always returning true
related to #1435 

if the registrar is not set up, shouldn't some of these commands be returning some kind of error or false?

```
> contenthash = admin.saveInfo(abiObj, '/tmp/btcrelayWithBulkStoreContractInfo.json')
'0xc8601bd85c4bb2cf9bde1d2e47fd6e20e733ffe2cd051a4eec0d2fd86c29477d'

> admin.register(primaryAccount, address, contenthash)
true

> url='https://cdn.rawgit.com/ethereum/btcrelay/master/examples/btcrelayWithBulkStoreContractInfo.json'
'https://cdn.rawgit.com/ethereum/btcrelay/master/examples/btcrelayWithBulkStoreContractInfo.json'

> admin.registerUrl(primaryAccount, contenthash, url)
true
```

### LINKED ISSUE #1564: improve error message when starting a second instance of geth
"Fatal: extra db err: resource temporarily unavailable" indicates another geth instance running. 
should say that.

### LINKED ISSUE #1580: Same derived address with any password when importing presale wallet?
Hi. Having issues importing my presale wallet.

On OSX. No matter what password I put in (via interactive or through a file), it always generates the same derived address: 9cce34f7ab185c7aba1b7c8140d620b4bda941d6.

Is this normal?

### LINKED ISSUE #1697: leading whitespace should not save to geth console history
Expanding on #1562 usual BASH behavior is to not store commands that have a leading whitespace.
eg http://stackoverflow.com/questions/6475524/how-to-prevent-commands-to-show-up-in-bash-history

Can geth do the same?

### LINKED ISSUE #1785: accounts: unlock multiple accounts fails
When trying to use ``--unlock="0 1"`` geth fails with the message: `Fatal: Unlock account failed 'Decryption failed: MAC mismatch'`. The first account is unlocked and the message `Account '0' unlocked` is printed. 

It's important to note that `unlock="0"` AND `unlock="1"` both works! Also, if you invert the order ("1 0" instead of "0 1"), it prints `Account '1' unlocked` and then fails to unlock second account with same message. So, the problem is clearly related to unlock multiple accounts and problem always happens on second account.

### PR DESCRIPTION
**Pull request by zelig**
This PR addresses several minor bugs, regressions, inconsistencies relating to geth UI including console, cli, rpc api
* [x] console: bash history behaviour: lines with leading space are ommitted from history. fixes #1697
* [x] console: exit processed even with whitespace around
* [x] console: all whitespace lines (not only empty ones) are ignored
* [x] registrar: methods now return proper error if reg addresses are not set + tests. fixes #1457
* [x] registrar: fix major regression: deploy registrars, register HashsReg and UrlHint in GlobalRegistrar. set all 3 contract addresses in code
* [x] rpc/console: fix major [unreported] regression. Now all comms accept interactive password for personal.newAccount() 
* [x] rpc/console: fix regression with docRoot / admin API (natspec example on wiki)
* [x] cli/accounts: unlock multiple accounts (with inline passwdfile). fixes #1785 
* [x] crypto (CLI): catch AES decryption error on presale wallet import + fix error msg format. fixes #1580
* [x]  CLI: improve error message when starting a second instance of geth. fixes #1564 
* [x] common/natspec: fix end to end test 
* [x] common/docserver: catch http errors from response

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Sep 22 18:48:54 UTC 2015_

**Comment by bas-vk** [comment]
Review progress:
* [ ] console: bash history behaviour: lines with leading space are ommitted from history. fixes #1697
* [ ] console: exit processed even with whitespace around
* [ ] console: all whitespace lines (not only empty ones) are ignored
* [ ] registrar: methods now return proper error if reg addresses are not set + tests. fixes #1457
* [ ] registrar: fix major regression: deploy registrars, register HashsReg and UrlHint in GlobalRegistrar. set all 3 contract addresses in code
* [ ] rpc/console: fix major [unreported] regression. Now all comms accept interactive password for personal.newAccount() 
* [ ] rpc/console: fix regression with docRoot / admin API (natspec example on wiki)
* [ ] cli/accounts: unlock multiple accounts (with inline passwdfile). fixes #1785 
* [ ] crypto (CLI): catch AES decryption error on presale wallet import + fix error msg format. fixes #1580
* [ ]  CLI: improve error message when starting a second instance of geth. fixes #1564 
* [ ] common/natspec: fix end to end test 
* [ ] common/docserver: catch http errors from response

File: cmd/geth/js.go [hunk 1]
```diff
@@ -425,12 +437,13 @@ func (self *jsre) interactive() {
 	}
 }
 
-func hidepassword(input string) string {
-	if passwordRegexp.MatchString(input) {
-		return passwordRepl
-	} else {
-		return input
+func postprocess(input string) (string, bool) {
```
Comment (bas-vk) [inline cmd/geth/js.go]: This function doesn't do any real post processing and the returned string is not actually necessary. Consider changing it to something like `func mustLogInHistory(input string) bool`.

File: common/registrar/registrar.go [hunk 2]
```diff
@@ -55,10 +55,10 @@ So the caller needs to make sure the relevant environment initialised the desire
 contracts
```
Comment (bas-vk) [inline common/registrar/registrar.go]: Now the addresses of the 3 contracts are hard coded and the contracts are deployed these docs can be updated?

File: rpc/api/personal.go [hunk 3]
```diff
@@ -98,9 +98,22 @@ func (self *personalApi) NewAccount(req *shared.Request) (interface{}, error) {
...
+	var passwd string
+	if args.Passphrase == nil {
+		fe := self.xeth.Frontend()
+		if fe == nil {
+			return false, fmt.Errorf("No password provided")
+		}
+		var ok bool
+		passwd, ok = fe.AskPassword()
+		if !ok {
+			return false, nil
```
Comment (bas-vk) [inline rpc/api/personal.go]: Return an error with the reason that the account could not be created because the password could not be asked.

File: crypto/crypto.go [hunk 4]
```diff
@@ -269,7 +272,7 @@ func decryptPreSaleKey(fileContent []byte, password string) (key *Key, err error
 	derivedAddr := hex.EncodeToString(key.Address.Bytes()) // needed because .Hex() gives leading "0x"
 	expectedAddr := preSaleKeyStruct.EthAddr
 	if derivedAddr != expectedAddr {
-		err = errors.New(fmt.Sprintf("decrypted addr not equal to expected addr ", derivedAddr, expectedAddr))
+		err = errors.New(fmt.Sprintf("decrypted addr '%s' not equal to expected addr '%s'", derivedAddr, expectedAddr))
```
Comment (bas-vk) [inline crypto/crypto.go]: You can use `fmt.Errorf`.

File: cmd/geth/main.go [hunk 5]
```diff
@@ -400,6 +401,9 @@ func run(ctx *cli.Context) {
 
 	ethereum, err := eth.New(cfg)
 	if err != nil {
+		if datadirInUseErrRE.MatchString(err.Error()) {
+			err = fmt.Errorf("%v (another instance of geth is already running with the same data directory '%v')", err, ctx.GlobalString(utils.DataDirFlag.Name))
+		}
```
Comment (bas-vk) [inline cmd/geth/main.go]: This doesn't work. The returned error from `eth.New` is the original error message with the database which could not be opened prefix. You can change the regex but a better solution would be to catch the error in `ethdb.NewLDBDatabase` and convert it to an error with a more user friendly message. That would save a string comparison. You can test if the returned error in `leveldb.OpenFile` is `syscall.Errno` (11).

The last argument in `Errorf` is a string, use the `%s` formatter.

File: common/docserver/docserver.go [hunk 6]
```diff
@@ -95,14 +95,20 @@ func (self *DocServer) Get(uri, path string) (content []byte, err error) {
...
 	if err != nil {
 		return
 	}
+
 	content, err = ioutil.ReadAll(resp.Body)
 	if err != nil {
 		return
 	}
 
+	if resp.StatusCode >= 400 {
```
Comment (bas-vk) [inline common/docserver/docserver.go]: I'm not sure if this is valid. There are some other error codes which are < 400 (e.g. 304) which can be returned and don't contain the actual requested data. But maybe these are never returned in this case?

File: cmd/geth/main.go (hunk 5 above)
Comment (zelig) [inline cmd/geth/main.go]: can this be a platform thing? On Mac I get:

     Fatal: blockchain db err: resource temporarily unavailable (another instance of geth is already running with the same data directory 'tmp/try2')

File: common/docserver/docserver.go (hunk 6 above)
Comment (zelig) [inline common/docserver/docserver.go]: Yes they could be returned. Is there an other canonical way to match errors. I could certainly add 304 but wonder if that is the only one.

File: common/registrar/registrar.go (hunk 2 above)
Comment (zelig) [inline common/registrar/registrar.go]: oops indeed

File: cmd/geth/js.go (hunk 1 above)
Comment (zelig) [inline cmd/geth/js.go]: how about forgetting this automation entirely, pass interactivity as a parameter to modules and simply enforce interactive use on the console(s).

File: cmd/geth/main.go (hunk 5 above)
Comment (bas-vk) [inline cmd/geth/main.go]: The problem is actually that this check is only added to the `run` subcommand. When you run it with another subcommand the program will still print the old message. Try to run `geth console` twice, that should reproduce the issue.

I tested it on Windows 10 to see what happens there:
```
C:\Go\GoPath\src\github.com\ethereum\go-ethereum\cmd\geth>geth.exe
I1001 09:55:40.596052    4992 database.go:71] Alloted 16MB cache to C:\Users\bas\AppData\Roaming\Ethereum\chaindata
Fatal: blockchain db err: The process cannot access the file because it is being used by another process. 
```

The returned error differs a bit from the other supported platforms. The leveldb returns an `syscall.Errno` instance with errno 11 on linux/osx and errno 32 on Windows when the database is already opened. I would suggest checking on those error numbers instead of a string match.

File: cmd/geth/js.go (hunk 1 above)
Comment (bas-vk) [inline cmd/geth/js.go]: I think @ethers (https://github.com/ethereum/go-ethereum/issues/1697) asked for this feature not to hide passwords but to prevent dangerous commands not to end up in the history from which they can accidentally be executed again when the users browses through history. That means that besides password interaction also transaction confirmation from the console should be enabled since transactions will have irreversible consequences.

File: common/docserver/docserver.go (hunk 6 above)
Comment (bas-vk) [inline common/docserver/docserver.go]: You can reverse the check and test if you got a valid response (status code 200) instead of testing for an error. `http.Client.Get` handles most redirects so you should in almost all normal cases get a valid response.

File: cmd/geth/main.go (hunk 5 above)
Comment (zelig) [inline cmd/geth/main.go]: I shall do thx

**Comment by zelig** [comment]
@bas-vk I agree with all points, thanks for the thorough review

File: cmd/geth/main.go (hunk 5 above)
Comment (bas-vk) [inline cmd/geth/main.go]: This still doesn't work. 

`ethdb.NewLDBDatabase` will return a `syscall.Errno` error for which you can check. In backend.go these errors are converted to an `*errors.errorString` instance. 

```
chainDb, err := newdb(filepath.Join(config.DataDir, "chaindata"))
if err != nil {
	return nil, fmt.Errorf("blockchain db err: %v", err)
}
```
The check in main.go for an errno wil then obviously fail.

Second problem is that the check if only added to the run subcommand. Users who will start the `console` (or any other subcommand) will still get the old error message when another instance already claimed the database datadir.

File: cmd/geth/main.go [hunk 7]
```diff
@@ -399,6 +400,16 @@ func run(ctx *cli.Context) {
 
 	ethereum, err := eth.New(cfg)
 	if err != nil {
+		var ok bool
+		for _, no := range datadirInUseErrNos {
+			if uint(err.(syscall.Errno)) == no {
```
Comment (bas-vk) [inline cmd/geth/main.go]: This still doesn't work. 

`ethdb.NewLDBDatabase` will return a `syscall.Errno` error for which you can check. In backend.go these errors are converted to an `*errors.errorString` instance. 

```
chainDb, err := newdb(filepath.Join(config.DataDir, "chaindata"))
if err != nil {
	return nil, fmt.Errorf("blockchain db err: %v", err)
}
```
The check in main.go for an errno wil then obviously fail.

Second problem is that the check if only added to the run subcommand. Users who will start the `console` (or any other subcommand) will still get the old error message when another instance already claimed the database datadir.

File: rpc/api/personal.go [hunk 8]
```diff
@@ -98,9 +98,22 @@ func (self *personalApi) NewAccount(req *shared.Request) (interface{}, error) {
...
+	var passwd string
+	if args.Passphrase == nil {
+		fe := self.xeth.Frontend()
+		if fe == nil {
+			return false, fmt.Errorf("unable to create account: password cannot be input interactively")
+		}
+		var ok bool
+		passwd, ok = fe.AskPassword()
+		if !ok {
+			return false, fmt.Errorf("unable to create account: password cannot be input interactively")
```
Comment (bas-vk) [inline rpc/api/personal.go]: The error messages on line 105 and 110 can be improved I think.
Something in the lines of:

L105: Unable to interact with user
L110: User didn't give password

**Comment by bas-vk** [comment]
What did you end up doing for #1697?

File: eth/backend.go [hunk 9]
```diff
@@ -281,6 +286,18 @@ func New(config *Config) (*Ethereum, error) {
 	// Open the chain database and perform any upgrades needed
 	chainDb, err := newdb(filepath.Join(config.DataDir, "chaindata"))
 	if err != nil {
+		var ok bool
+		errno := uint(err.(syscall.Errno))
+		fmt.Printf("encountered error %d: %v\n", errno, err)
```
Comment (bas-vk) [inline eth/backend.go]: This is probably a debug line and can be removed?

**Comment by bas-vk** [comment]
Apart from the minor issue I'm ok :+1:
