### PR TITLE
eth, les: fix tracer

### LINKED ISSUE #22469: Tracing in 1.10 no longer returns results immediately
#### System information

Geth versions: `1.10.1-stable` and `1.9.25-stable`
OS & Version: Ubuntu 20.04.2 LTS (5.4.0-54-generic) and macOS Big Sur 11.2.2

#### Expected behaviour
When chain tracing via the Json RPC under 1.9.25-stable, the results of the processed transaction are returned immediately and I can instantly process them further. This does not happen under 1.10.*

#### Actual behaviour
Under 1.10.*, the results are no longer immediately returned. It seems geth is regenerating the state snapshots first (?) before returning any result. This is kind of undesired when tracing large chain segments, as it may take hours before returning any result.
Also, using htop I can observe geth's RAM usage growing while the historical state is regenerated. When the tracing range is large enough (e.g. block 0x0 to block 0xfffff) geth starts taking up my computer's entire memory before having finished state regeneration, and thus my system is becoming unresponsive before any result is returned.

This does not happen under version 1.9.25-stable. I can still observe a slight raise in memory usage, but nowhere as fast as in 1.10.1-stable. Results are returned to e.g. netcat immediately and i assume the regenerated states aren't kept in memory(?)

#### Steps to reproduce the behaviour
* Start geth using e.g.: `./build/bin/geth --rinkeby --maxpeers=0`
* Connect via netcat to UDS socket: `nc -U geth.ipc`
* Issue command e.g. `{"id": 1, "method": "debug_subscribe", "params": ["traceChain", "0x0", "0xfffff", {"tracer": "4byteTracer"}]}` (when using a too small block range you might not notice the difference)

Doing these steps in both versions will result in the different behaviors described above.

I am unsure whether or not this is a bug. If this is intended behavior I would be very glad for some help on how to do chaintracing with custom JS tracers for the entire chain in the newest version. Also there seems to be another problem with JS tracers timing out instantly on most transactions, but I think that belongs into another issue...

### PR DESCRIPTION
**Pull request by rjl493456442**
fixes #22469

### CODE REVIEW

File: eth/tracers/api.go [hunk 1]
```diff
@@ -226,33 +226,22 @@ func (api *API) traceChain(ctx context.Context, start, end *types.Block, config
...
 		threads = blocks
 	}
 	var (
-		pend    = new(sync.WaitGroup)
-		tasks   = make(chan *blockTraceTask, threads)
-		results = make(chan *blockTraceTask, threads)
+		pend     = new(sync.WaitGroup)
+		tasks    = make(chan *blockTraceTask, threads)
+		results  = make(chan *blockTraceTask, threads)
+		localctx = context.Background()
```
Comment (karalabe) [inline eth/tracers/api.go:244]: Why do we need this local context?

File: eth/state_accessor.go [hunk 2]
```diff
@@ -33,37 +33,47 @@ import (
...
+		database state.Database
+		report   = true
+	)
+	if base != nil {
+		statedb, database, report = base, base.Database(), false
+		current = eth.blockchain.GetBlock(block.ParentHash(), block.NumberU64()-1)
+	} else {
+		// Otherwise try to reexec blocks until we find a state or reach our limit
+		current = block
+		database = state.NewDatabaseWithConfig(eth.chainDb, &trie.Config{Cache: 16, Preimages: true})
```
Comment (karalabe) [inline eth/state_accessor.go:54]: Do we need the preimages? I'd guess no

File: eth/tracers/api.go (hunk 1 above)
Comment (rjl493456442) [reply eth/tracers/api.go:244]: Because we are using the ctx passed by the API, but the entire tracing procedure is async and the function is returned. So the ctx is always closed.

It's the reason for `execution timeout`

File: eth/state_accessor.go (hunk 2 above)
Comment (rjl493456442) [reply eth/state_accessor.go]: fixed

File: eth/tracers/api.go [hunk 3]
```diff
@@ -355,6 +368,10 @@ func (api *API) traceChain(ctx context.Context, start, end *types.Block, config
 			}
 			done[uint64(result.Block)] = result
 
+			// Dereference any paret tries held in memory by this task
```
Comment (karalabe) [inline eth/tracers/api.go:371]: paret -> parent?

File: eth/tracers/api.go [hunk 4]
```diff
@@ -324,15 +315,37 @@ func (api *API) traceChain(ctx context.Context, start, end *types.Block, config
 				log.Info("Tracing chain segment", "start", start.NumberU64(), "end", end.NumberU64(), "current", number, "transactions", traced, "elapsed", time.Since(begin))
 			}
 			// Retrieve the next block to trace
```
Comment (karalabe) [inline eth/tracers/api.go:317]: // Retrieve the next block to trace -> // Retrieve the parent state to trance on top

File: eth/state_accessor.go [hunk 5]
```diff
@@ -72,138 +82,59 @@ func (eth *Ethereum) stateAtBlock(block *types.Block, reexec uint64) (statedb *s
...
-			log.Info("Regenerating historical state", "block", block.NumberU64()+1, "target", origin, "remaining", origin-block.NumberU64()-1, "elapsed", time.Since(start))
+		if time.Since(logged) > 8*time.Second && report {
+			log.Info("Regenerating historical state", "block", current.NumberU64()+1, "target", origin, "remaining", origin-current.NumberU64()-1, "elapsed", time.Since(start))
 			logged = time.Now()
 		}
 		// Retrieve the next block to regenerate and process it
-		if block = eth.blockchain.GetBlockByNumber(block.NumberU64() + 1); block == nil {
-			return nil, nil, fmt.Errorf("block #%d not found", block.NumberU64()+1)
+		if current = eth.blockchain.GetBlockByNumber(current.NumberU64() + 1); current == nil {
+			return nil, fmt.Errorf("block #%d not found", current.NumberU64()+1)
```
Comment (holiman) [inline eth/state_accessor.go:93]: You're assigning to `current` here, and if `current` is `nil`, you try to access `current.NumberU64`. This was erroneous previously too, see https://github.com/ethereum/go-ethereum/issues/22485#issuecomment-796981882

File: eth/state_accessor.go [hunk 6]
```diff
@@ -72,138 +82,59 @@ func (eth *Ethereum) stateAtBlock(block *types.Block, reexec uint64) (statedb *s
...
 		}
```
Comment (holiman) [inline eth/state_accessor.go:94]:
```suggestion
		if next := eth.blockchain.GetBlockByNumber(current.NumberU64() + 1); next == nil {
			return nil, fmt.Errorf("block #%d not found", current.NumberU64()+1)
		}else{
			current = next
		}
```

File: eth/state_accessor.go (hunk 5 above)
Comment (rjl493456442) [reply eth/state_accessor.go]: fixed

File: eth/tracers/api.go [hunk 7]
```diff
@@ -487,7 +488,7 @@ func (api *API) traceBlock(ctx context.Context, block *types.Block, config *Trac
 	if config != nil && config.Reexec != nil {
 		reexec = *config.Reexec
 	}
-	statedb, err := api.backend.StateAtBlock(ctx, parent, reexec, nil)
+	statedb, err := api.backend.StateAtBlock(ctx, parent, reexec, nil, false)
```
Comment (karalabe) [inline eth/tracers/api.go:491]: You want this and the others true :) Only traceChain should be false, shouldn't it?

**Review by karalabe — APPROVED** [review]
Here's to hopping all issues are fixed :D
