### PR TITLE
rpc: add SetHeader method to Client

### LINKED ISSUE #20163: rpc: add support for setting HTTP headers on Client
"ethclient.Client" doesn't support setting http header.
While i use infura jsonapi with "ethclient.Client", for security considerations, i gonna set "User-Agent", "Origin" by HTTP Headers.
But i can't find a way to do so.
Do i miss something ?

#### System information

Geth version: `v1.9.5`
OS & Version: ubuntu 18.04.01 

#### Backtrace

````
[backtrace]
````

### PR DESCRIPTION
**Pull request by renaynay**
Resolves #20163

### CODE REVIEW

File: rpc/http.go [hunk 1]
```diff
@@ -39,7 +39,10 @@ const (
 var acceptedContentTypes = []string{contentType, "application/json-rpc", "application/jsonrequest"}
 
 type httpConn struct {
+	sync.Mutex
+
 	client    *http.Client
+	headers   map[string]string
```
Comment (fjl) [inline rpc/http.go:45]: Might be better to use the `http.Header` type for this. It keeps the keys lowercase.

File: rpc/http.go [hunk 2]
```diff
@@ -39,7 +39,10 @@ const (
 var acceptedContentTypes = []string{contentType, "application/json-rpc", "application/jsonrequest"}
 
 type httpConn struct {
+	sync.Mutex
```
Comment (fjl) [inline rpc/http.go:42]: Please name this field.

File: rpc/client_test.go [hunk 3]
```diff
@@ -429,6 +430,41 @@ func TestClientNotificationStorm(t *testing.T) {
 	doTest(23000, true)
 }
 
+// TestClientSetHeader tests whether an http header has been properly set
+// to the given key and value on a client's http request.
+func TestClientSetHeader(t *testing.T) {
```
Comment (fjl) [inline rpc/client_test.go:435]: This test is a bit useless because it just checks if the map is updated. If you want to make a real test,
use package httptest to launch a server and verify that the request sent by client contains the custom headers.

File: rpc/http.go [hunk 4]
```diff
@@ -166,10 +177,23 @@ func (hc *httpConn) doRequest(ctx context.Context, msg interface{}) (io.ReadClos
...
+	req, err := http.NewRequestWithContext(ctx, "POST", hc.url, ioutil.NopCloser(bytes.NewReader(body)))
+	if err != nil {
+		return nil, err
+	}
 	req.ContentLength = int64(len(body))
 
+	// set headers
+	hc.mu.Lock()
+	for key, vals := range hc.headers {
+		req.Header.Del(key)
```
Comment (renaynay) [inline rpc/http.go:189]: Why do you have to delete the key before setting the key & Vals even though the request is a fresh new request?

Comment (fjl) [reply rpc/http.go:189]: Yeah, you're right, I got confused.
