### PR TITLE
rlp: fixes for two corner cases and documentation

### LINKED ISSUE #19367: rlp: annotation need to update for the support of booleans
I am reading the rlp package source code, the annotations for `Decode` and `Encode` tell me the booleans are not supported, but the codes tells me the booleans are already supported.

https://github.com/ethereum/go-ethereum/blob/master/rlp/decode.go#L124
```
// Non-empty interface types are not supported, nor are booleans,
// signed integers, floating point numbers, maps, channels and
// functions.
```

https://github.com/ethereum/go-ethereum/blob/master/rlp/encode.go#L78
```
// Boolean values are not supported, nor are signed integers, floating
// point numbers, maps, channels and functions.
```

### PR DESCRIPTION
**Pull request by fjl**
These changes fix two corner cases related to internal handling of types
in package rlp:

- The "tail" struct tag can only be applied to the last field. The check for this
  was wrong and didn't allow for private fields after the field with the tag.
- Unsupported types (e.g. structs containing int) which implement either
  the Encoder or Decoder interface but not both couldn't be encoded/decoded.

Also fixes #19367

### CODE REVIEW

File: rlp/encode_test.go [hunk 1]
```diff
@@ -239,6 +246,8 @@ var encTests = []encTest{
 	{val: (*testEncoder)(nil), output: "00000000"},
 	{val: &testEncoder{}, output: "00010001000100010001"},
 	{val: &testEncoder{errors.New("test error")}, error: "test error"},
+	// verify that the Encoder interface works for otherwise unencodable values.
```
Comment (karalabe) [inline rlp/encode_test.go]: "unencodable values" -> "undencodable values" (missing a d?)
