### PR TITLE
les: handle conn/disc/reg logic in the eventloop

### LINKED ISSUE #16610: Data race in LES
Tagged Geth v1.8.6, built with Go 1.10.1 on macOS 10.13.4 with race detector enabled.

```
$ geth --syncmode=light

[…]

==================
WARNING: DATA RACE
Write at 0x00c4200d08a0 by goroutine 75:
  github.com/ethereum/go-ethereum/les.(*wrsNode).insert()
      /XXX/src/github.com/ethereum/go-ethereum/les/randselect.go:116 +0x222
  github.com/ethereum/go-ethereum/les.(*weightedRandomSelect).setWeight()
      /XXX/src/github.com/ethereum/go-ethereum/les/randselect.go:70 +0x1cf
  github.com/ethereum/go-ethereum/les.(*weightedRandomSelect).update()
      /XXX/src/github.com/ethereum/go-ethereum/les/randselect.go:45 +0x6a
  github.com/ethereum/go-ethereum/les.(*serverPool).updateCheckDial()
      /XXX/src/github.com/ethereum/go-ethereum/les/serverpool.go:450 +0x6e
  github.com/ethereum/go-ethereum/les.(*serverPool).eventLoop()
      /XXX/src/github.com/ethereum/go-ethereum/les/serverpool.go:313 +0x6a7

Previous read at 0x00c4200d08a0 by main goroutine:
  [failed to restore the stack]

Goroutine 75 (running) created at:
  github.com/ethereum/go-ethereum/les.(*serverPool).start()
      /XXX/src/github.com/ethereum/go-ethereum/les/serverpool.go:151 +0x2ad
  github.com/ethereum/go-ethereum/les.(*LightEthereum).Start()
      /XXX/src/github.com/ethereum/go-ethereum/les/backend.go:229 +0x28a
  github.com/ethereum/go-ethereum/node.(*Node).Start()
      /XXX/src/github.com/ethereum/go-ethereum/node/node.go:203 +0xf6f
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  fmt.(*ss).doScanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:1193 +0x345
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  fmt.(*ss).doScanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:1193 +0x345
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_util.go:52 +0x2e6
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:129 +0xa4c
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  fmt.(*ss).doScanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:1193 +0x345
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  fmt.(*ss).doScanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:1193 +0x345
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:585 +0x239
  fmt.(*ss).doScanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:1193 +0x345
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2b0
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:475 +0xd9
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:124 +0xa28
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.Open()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:196 +0x186
  fmt.Fscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/Cellar/go/1.10.1/libexec/src/fmt/scan.go:114 +0xbb
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x16c
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseNamePtr()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:594 +0x46
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:312 +0xdd3
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*session).recover()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/session.go:119 +0xd6
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.Open()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:182 +0xc8
  github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.OpenFile()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:218 +0x9f
  github.com/ethereum/go-ethereum/ethdb.NewLDBDatabase()
      /XXX/src/github.com/ethereum/go-ethereum/ethdb/database.go:76 +0x4c5
  github.com/ethereum/go-ethereum/node.(*ServiceContext).OpenDatabase()
      /XXX/src/github.com/ethereum/go-ethereum/node/service.go:46 +0x1a7
  github.com/ethereum/go-ethereum/eth.CreateDB()
      /XXX/src/github.com/ethereum/go-ethereum/eth/backend.go:203 +0x9a
  github.com/ethereum/go-ethereum/les.New()
      /XXX/src/github.com/ethereum/go-ethereum/les/backend.go:83 +0x75
  github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func1()
      /XXX/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1128 +0x4f
  github.com/ethereum/go-ethereum/node.(*Node).Start()
      /XXX/src/github.com/ethereum/go-ethereum/node/node.go:182 +0x706
  github.com/ethereum/go-ethereum/cmd/utils.StartNode()
      /XXX/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:66 +0x3c
  main.startNode()
      /XXX/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:227 +0x53
  main.geth()
      /XXX/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:217 +0x50
  github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xfd
  github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run()
      /XXX/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x92a
  main.main()
      /XXX/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:206 +0x82
==================
```

### PR DESCRIPTION
**Pull request by rjl493456442**
This pr fix #16610 .

Now almost all operations are done in the eventloop, so we can ensure the concurrency safety. But some operations exposed by serverpool (e.g. connect, disconnect, register) are handled in different way, it can introduce concurrency problems.

E.g, like described in the issue, a node is discovered, eventloop will try to update the `newSelect` to schedule a new dial. But in the mean time a peer's registration operation can happen and `knownQueue` is oversize, which can leads to the least recently entry be deleted. So `newSelect` is suffered a concurrency problem.

### CODE REVIEW

**Comment by ligi** [comment]
> Work in progress now.

Ideally mention this in the title like with a [WIP] prefix

**Comment by zsfelfoldi** [comment]
Running connect/registered/disconnect in the event loop might be a cleaner solution so I'm not against it but I'd like to understand the issue first and I don't see how the described scenario could cause a data race. Both serverPool.registered (which calls setLatest) and the event pool handler of newly discovered peers are protected by the same pool.lock mutex. Probably I'm missing something because the data race detector did catch something but I don't see it yet.

**Comment by rjl493456442** [comment]
@zsfelfoldi Sorry for my negligence, i missed the lock there. So i guess the data race might caused by the `checkDial` function during the start stage.

Besides, i clean up some unused codes. PTAL

File: les/serverpool.go [hunk 1]
```diff
@@ -158,83 +183,63 @@ func (pool *serverPool) start(server *p2p.Server, topic discv5.Topic) {
...
-		if connAdjust > 1 {
-			connAdjust = 1
+	stopped := false
+	select {
+	case <-pool.quit:
+		stopped = true
+	default:
+	}
+
+	if stopped {
```
Comment (zsfelfoldi) [inline les/serverpool.go]: Duplicating this logic here is weird and also unsafe. When pool.quit has been closed there is no guarantee that the event loop has actually stopped and no one will concurrently access the entry. What I'd do is
- put this logic into a function with stopped as a parameter
- disconnect should always create discReqs and send them to discCh (do not care about pool.quit here, always send it)
- add a for .. range loop in the main event loop's case <-pool.quit handler that reads from discCh until it is closed and calls the disconnect logic with stopped=true
- run pool.connWg.Wait() in a goroutine before that event loop and close discCh after Wait has returned

**Comment by rjl493456442** [comment]
@zsfelfoldi Thanks for your comments! For the `stopped` judgement, i add some extra logic. When a disconnection requested is sent, it will check whether the `quit` is closed.
So that under this situation: `quit` is actually closed, but the request is catched by the `disconnCh` handler instead of `quit` handler. With these extra logic, we can ensure that the `stopped` is always correct.

File: les/serverpool.go [hunk 2]
```diff
@@ -158,83 +184,45 @@ func (pool *serverPool) start(server *p2p.Server, topic discv5.Topic) {
...
+	req := &registerReq{entry: entry, done: make(chan struct{})}
+	select {
+	case pool.registerCh <- req:
+	case <-pool.quit:
+		return
 	}
-	pool.knownQueue.setLatest(entry)
-	entry.shortRetry = shortRetryCnt
+	<-req.done
+	return
```
Comment (zsfelfoldi) [inline les/serverpool.go]: Linter complains about this, please remove.

File: les/serverpool.go [hunk 3]
```diff
@@ -277,25 +265,57 @@ func (pool *serverPool) eventLoop() {
...
+			pool.knownSelected--
+		} else {
+			pool.newSelected--
+		}
+		pool.setRetryDial(entry)
+		pool.connWg.Done()
+		close(req.done)
+	}
+
+	go func() {
```
Comment (zsfelfoldi) [inline les/serverpool.go]: This is not right, connWg is only Add-ed by connect so this Wait will pass instantly, closing disconnCh immediately. This also causes case req := <-pool.disconnCh to receive a nil req and panic. Put this goroutine in the case <-pool.quit handler instead, before running the final disconnect loop. This ensures that the normal disconn req handler will never receive nil and also that connWg will not be Add-ed after Wait.

File: les/serverpool.go [hunk 4]
```diff
@@ -327,15 +337,66 @@ func (pool *serverPool) eventLoop() {
...
 		case <-pool.quit:
 			if pool.discSetPeriod != nil {
 				close(pool.discSetPeriod)
 			}
-			pool.connWg.Wait()
+
+			// Spawn a goroutine to close the disconnCh until all connections are disconnected.
+			go func() {
+				pool.connWg.Wait()
+				close(pool.disconnCh)
```
Comment (karalabe) [inline les/serverpool.go]: Why do you close this channel? In general closing channels that you are a reader of is very very dangerous and can almost always backfire. The general rule is that only the single-sender should ever close a channel. Otherwise it's very easy to end up in a panic.

File: les/serverpool.go [hunk 5]
```diff
@@ -158,83 +184,44 @@ func (pool *serverPool) start(server *p2p.Server, topic discv5.Topic) {
...
-	if entry.knownSelected {
-		pool.knownSelected--
-	} else {
-		pool.newSelected--
-	}
-	pool.setRetryDial(entry)
-	pool.connWg.Done()
+	// Block until disconnection request be served.
+	pool.disconnCh <- req
+	<-req.done
```
Comment (karalabe) [inline les/serverpool.go]: This seems to be  racy construct to me:

 * Check whether stopped, not yet, continue to disconnect
 * In the mean time scheduler runs a different goroutine that stops the server pool
 * Schedule this `pool.disconnCh <- req`, which will either crash (if closed) or hang (it open).

Comment (karalabe) [reply les/serverpool.go]: Actually, even if pool.quit is closed, this branch will trigger, causing a panic.

File: les/serverpool.go [hunk 6]
```diff
@@ -327,15 +337,66 @@ func (pool *serverPool) eventLoop() {
...
 			}
-			pool.connWg.Wait()
+
+			// Spawn a goroutine to close the disconnCh until all connections are disconnected.
+			go func() {
+				pool.connWg.Wait()
+				close(pool.disconnCh)
+			}()
+
+			// Handle all remain disconnection requests before exit.
```
Comment (karalabe) [inline les/serverpool.go]: `remain` -> `remaining`

File: les/serverpool.go [hunk 7]
```diff
@@ -327,15 +337,66 @@ func (pool *serverPool) eventLoop() {
...
+			// Handle peer disconnection requests.
+			disconnect(req, req.stopped)
+
 		case <-pool.quit:
 			if pool.discSetPeriod != nil {
 				close(pool.discSetPeriod)
 			}
-			pool.connWg.Wait()
+
+			// Spawn a goroutine to close the disconnCh until all connections are disconnected.
```
Comment (karalabe) [inline les/serverpool.go]: `until` -> `after`

File: les/serverpool.go [hunk 8]
```diff
@@ -158,83 +184,44 @@ func (pool *serverPool) start(server *p2p.Server, topic discv5.Topic) {
...
 
-	entry.state = psNotConnected
-	if entry.knownSelected {
-		pool.knownSelected--
-	} else {
-		pool.newSelected--
-	}
-	pool.setRetryDial(entry)
-	pool.connWg.Done()
+	// Block until disconnection request be served.
```
Comment (karalabe) [inline les/serverpool.go]: `be` -> `is`

**Comment by rjl493456442** [comment]
@karalabe Updated
