### PR TITLE
swarm/pot: each() functions refactored

### LINKED ISSUE #1104: Synchronisation failed: block downloading cancelled
I0526 14:39:40.435886    7272 server.go:349] Listening on [::]:30303
I0526 14:39:40.436886    7272 nat.go:95] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-PPP1
> I0526 14:39:50.437458    7272 downloader.go:159] Block synchronisation started
I0526 14:39:55.463745    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:39:55.463745    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:39:55.463745    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:39:55.463745    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:06.491376    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:06.491376    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:06.491376    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:06.491376    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:12.957746    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:12.962746    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:12.962746    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:12.970746    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:29.082668    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:29.083668    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:29.084668    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:29.086668    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)
I0526 14:40:41.465376    7272 chain_manager.go:743] INVALID block #446189 (38f5bbbffd74804820ffa4bab0cd540e9de229725afb98c1a7e57936f4a714bc)
I0526 14:40:41.466376    7272 chain_manager.go:744] gas used error (44532 / 160116)
I0526 14:40:41.498378    7272 sync.go:73] Block insertion failed: gas used error (44532 / 160116)
I0526 14:40:41.517379    7272 sync.go:122] Synchronisation failed: block downloading cancelled (requested)

### PR DESCRIPTION
**Pull request by gluk256**
Second parameter (int) was removed from each() and eachFrom(), since it does not contain any meaningful value. 
Related functions refactored accordingly.

This PR is clone of https://github.com/ethersphere/go-ethereum/pull/1120

fixes https://github.com/ethersphere/go-ethereum/issues/1104

### CODE REVIEW

File: swarm/pot/pot_test.go [hunk 1]
```diff
@@ -102,23 +101,18 @@ func TestPotRemoveSameBin(t *testing.T) {
...
 		t.Fatalf("incorrect number of elements in Pot. Expected %v, got %v", expi, goti)
 	}
-	inds, po = indexes(n)
+	inds = indexes(n)
 	got := fmt.Sprintf("%v", inds)
 	exp := "[5 3 2 1 0]"
 	if got != exp {
 		t.Fatalf("incorrect indexes in iteration over Pot. Expected %v, got %v", exp, got)
 	}
-	got = fmt.Sprintf("%v", po)
```
Comment (nonsense) [inline swarm/pot/pot_test.go]: @gluk256 why is this test removed?

Comment (gluk256) [reply swarm/pot/pot_test.go]: because i have removed the corresponding variable / return value

Comment (gluk256) [reply swarm/pot/pot_test.go]: internal representation of PO does not have any meaning

Comment (justelad) [reply swarm/pot/pot_test.go]: the return value is no longer there
