### PR TITLE
eth/tracers: return proper error from debug_TraceTransaction when tx not found

### LINKED ISSUE #22846: Unexpected response from debug_traceTransaction
#### System information

Geth version: `v1.10.2`
OS & Version: Linux

#### Expected behaviour
When `debug_traceTransaction` with `{"tracer": "callTracer"}` option, I expected to get general response like actions.

#### Actual behaviour
It usually responses fine, but intermittently gives `{code=-32000, message=genesis is not traceable}` error Or `{code=-32000, message=transaction 0b3251312a4091994164b1de4fc10900527b656cc08ef3dd90a82d7921afff1c not found}` error

#### Steps to reproduce the behaviour
I am running a scheduler which `eth_getBlockByNumber`  first and `debug_traceTransaction` using the transaction hashes from the getBlock response.

### PR DESCRIPTION
**Pull request by mdehoog**
Currently calling `debug_TraceTransaction` with a transacation hash that doesn't exist returns a confusing error: `{code=-32000, message=genesis is not traceable}`. This is because the `GetTransaction` returns `blockNumber=0` when the transaction doesn't exist.

This PR checks if the tx is `nil` and returns `nil` if so. This will match the behavior of `eth_getTransactionByHash` and `eth_getTransactionReceipt` for transactions that don't exist or aren't yet included in a block.

Fixes #22846.

Example RPC response:
```
> curl -d '{"id":0,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x0000000000000000000000000000000000000000000000000000000000000000"]}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":0,"result":null}
```

### CODE REVIEW

File: eth/tracers/api_test.go [hunk 1]
```diff
@@ -117,9 +116,6 @@ func (b *testBackend) BlockByNumber(ctx context.Context, number rpc.BlockNumber)
 
 func (b *testBackend) GetTransaction(ctx context.Context, txHash common.Hash) (*types.Transaction, common.Hash, uint64, uint64, error) {
 	tx, hash, blockNumber, index := rawdb.ReadTransaction(b.chaindb, txHash)
-	if tx == nil {
-		return nil, common.Hash{}, 0, 0, errTransactionNotFound
-	}
```
Comment (mdehoog) [inline eth/tracers/api_test.go:122]: this was removed because the `testBackend` implementation of `GetTransaction` does not match the real backend: https://github.com/ethereum/go-ethereum/blob/c2e0abce2eedc1ba2a1b32c46fd07ef18a25354a/eth/api_backend.go#L267-L270

File: eth/tracers/api.go [hunk 2]
```diff
@@ -801,10 +801,13 @@ func containsTx(block *types.Block, hash common.Hash) bool {
 // TraceTransaction returns the structured logs created during the execution of EVM
 // and returns them as a JSON object.
 func (api *API) TraceTransaction(ctx context.Context, hash common.Hash, config *TraceConfig) (interface{}, error) {
-	_, blockHash, blockNumber, index, err := api.backend.GetTransaction(ctx, hash)
+	tx, blockHash, blockNumber, index, err := api.backend.GetTransaction(ctx, hash)
 	if err != nil {
 		return nil, err
 	}
+	if tx == nil {
+		return nil, nil
```
Comment (holiman) [inline eth/tracers/api.go:809]: Why not return the error `errTransactionNotFound` here instead of `nil`?

Comment (holiman) [reply eth/tracers/api.go:809]: Changing this to 

```suggestion
		return nil, errors.New("transaction not found")
```
We get 
```
> debug.traceTransaction("0x0000000000000000000000000000000000000000000000000000000000000000")
WARN [11-18|10:38:20.230] Served debug_traceTransaction            reqid=9 duration="127.204µs" err="transaction not found"
Error: transaction not found
	at web3.js:6365:9(45)
	at send (web3.js:5099:62(34))
	at <eval>:1:23(4)

```

Comment (holiman) [reply eth/tracers/api.go:809]: It can be written _slightly_ more compact using a switch 
```golang
	switch {
	case err != nil:
		return nil, err
	case tx == nil:
		return nil, errors.New("transaction not found")
	case blockNumber == 0:
		return nil, errors.New("genesis is not traceable")
	}
```

Comment (s1na) [reply eth/tracers/api.go:809]: > Why not return the error errTransactionNotFound here instead of nil?

I came here to say the same

Comment (fjl) [reply eth/tracers/api.go:809]: We have an existing convention in other RPC APIs returning `null` when the requested item is not found.

Comment (mdehoog) [reply eth/tracers/api.go:809]: That sounds fine to me too; I was trying to match the behavior of `eth_getTransactionByHash` and `eth_getTransactionReceipt` which both return `nil` for a not-found transaction. But happy to take that suggestion if you think it's better.

Comment (mdehoog) [reply eth/tracers/api.go:809]: If we want to return `errTransactionNotFound`, we could also do this in the `GetTransaction` method: https://github.com/ethereum/go-ethereum/blob/c2e0abce2eedc1ba2a1b32c46fd07ef18a25354a/eth/api_backend.go#L267-L270

Comment (holiman) [reply eth/tracers/api.go:809]: > We have an existing convention in other RPC APIs returning null when the requested item is not found.

@fjl so you think the pr as is (return `nil` rather than error) is preferrable? 

I don't really understand the motivation behind that, personally.

Comment (fjl) [reply eth/tracers/api.go:809]: The motivation for the behavior of `getTransactionByHash` and `getTransactionReceipt` is that 'not found' is not an error. You could imagine that, with an RPC client that throws an exception for any error response, the case where the requested item is not found should not raise an exception.

Another reason might be that the people who designed these APIs didn't know that JSON-RPC has error codes. Returning `null` provides a way to recognize this specific condition. 

Returning `errors.New("transaction not found")` here is not great because it will not return any specific error code, and callers will not be able to know whether the error is related to a database/disk fault or simply means the item is not there.

**Comment by holiman** [comment]
I can somewhat agree that for getTransaction, it might not be an error for it to be missing. There are two expected outcomes, it's there or it's not there. For traceTransaction, however, I think it's an error if the tx is not present. The call implies that the tx exists. It not existing is an error.

File: eth/tracers/api.go (hunk 2 above)
Comment (mdehoog) [reply eth/tracers/api.go:809]: FWIW it's already returning an error: `genesis is not traceable`. So returning `transaction not found` would retain the existing behavior, with an error message that makes more sense.

**Review by holiman — APPROVED** [review]

**Review by s1na — APPROVED** [review]
LGTM

File: eth/tracers/api_test.go [hunk 3]
```diff
@@ -365,6 +361,15 @@ func TestTraceTransaction(t *testing.T) {
...
 	}
+
+	// Test non-existent transaction
+	result, err = api.TraceTransaction(context.Background(), common.Hash{42}, nil)
+	if err == nil {
+		t.Fatal("Tracing a non-existent transaction should return an error")
+	}
+	if err.Error() != errTxNotFound {
+		t.Fatalf("exptected error %s, got %s", errTxNotFound, err.Error())
+	}
```
Comment (holiman) [inline eth/tracers/api_test.go:372]:
```suggestion
	if !errors.Is(err, errTxNotFound) {
		t.Fatal("want %w, have %w", errTxNotFound, err)
	}
```

**Review by holiman — CHANGES_REQUESTED** [review]

File: eth/tracers/api_test.go [hunk 4]
```diff
@@ -365,6 +361,12 @@ func TestTraceTransaction(t *testing.T) {
 	}) {
 		t.Error("Transaction tracing result is different")
 	}
+
+	// Test non-existent transaction
+	result, err = api.TraceTransaction(context.Background(), common.Hash{42}, nil)
```
Comment (holiman) [inline eth/tracers/api_test.go:366]:
```suggestion
	_, err = api.TraceTransaction(context.Background(), common.Hash{42}, nil)
```

**Review by holiman — APPROVED** [review]
