### PR TITLE
core: fix missing receipt

### LINKED ISSUE #20239: Freezer is failed to freeze data
Sometimes we can have such error log shown `Block receipts missing, can't freeze`.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #20239

It fixes this scenario which may lead to `losing receipts`.

* Running Geth for clique chain(rinkeby, ropsten)
* Crash(without commit the latest state)
* Restart, rewind the `CurrentBlock` to a lower point which has the available relevant state
* Start to sync, import a batch of blocks via `insertSideChain`
* This batch blocks contain some "unknown" blocks, we commit them without "receipts"
* The "sidechain" longer than the "canonical" one, re-insert them for state generation
* But if there is an "empty" block, the first block will also complete this empty one since the state root is same.
* Skip reinsert the "empty" block, we lose the receipt entry

So the issue happens only when we run a clique chain and the block is empty. So the fix can always insert an empty receipt slice whenever we meet this scenario.

### CODE REVIEW

File: core/blockchain.go [hunk 1]
```diff
@@ -1672,6 +1672,15 @@ func (bc *BlockChain) insertChain(chain types.Blocks, verifySeals bool) (int, er
...
 
+			// Special case. Commit the empty receipt slice if we meet the known
+			// block in the middle. It can only happen in the clique chain. Whenever
+			// we insert blocks via `insertSideChain`, we only commit `td`, `header`
+			// and `body` if it's non-existent. Since we don't have receipts without
+			// reexecution, so nothing to commit. But if the sidechain will be adpoted
+			// as the canonical chain eventually, it needs to be reexecuted for missing
+			// state, but if it's this special case here(skip reexecution) we will lose
+			// the empty receipt entry.
+			rawdb.WriteReceipts(bc.db, block.Hash(), block.NumberU64(), nil)
```
Comment (holiman) [inline core/blockchain.go:1683]: Does not this presume that the block is empty? I don't think there's any guarantee about that..? 
Consider: 
```
block A: state X
block B1 (1tx): -> state Y  , block B2 (0 tx) -> state Z
block C1( 0tx):-> state O  , block C2 (1tx) -> state O
```

Comment (rjl493456442) [reply core/blockchain.go:1683]: Yes, let me think..

Comment (rjl493456442) [reply core/blockchain.go:1683]: Actually I think it's impossible. We are importing a batch of `known` blocks in `InsertChain`. The only use case is for regenerating the missing state for "side chain".

For the "side chain", they are checked that the relevant state is missing by `insertSideChain` function.

While in the special case: "so importing an older block might complete the state of the subsequent one", it's only possible in clique chain and the second block is empty.

Comment (rjl493456442) [reply core/blockchain.go:1683]: But I agree it's dangerous to commit the nil here. I will add a check, if the transaction list is empty, then commit the nil, otherwise print an error log. Do you think it makes sense?

Comment (holiman) [reply core/blockchain.go]: That makes sense. It's a bit difficult to reason about this, and make sure we cover all possibilities, so for me it sounds good to print out the error, so we can at least notice if our assumptions hold.
