### PR TITLE
accounts/external: fetch external accounts

### LINKED ISSUE #20995: Clef: "unknown account" error unless eth_accounts is called first
#### System information
```
$ geth version
Geth
Version: 1.9.14-unstable
Git Commit: 5c3993444d725aba00c7c8c976c5cc9f4bf6a317
Git Commit Date: 20200427
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.7
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go
```

#### Expected behaviour
After correctly starting `clef` and `geth --signer /path/to/clef.ipc`, a call to `eth_sign` (or any other signing API) with a valid account should succeed.

#### Actual behaviour
The call fails with error `unknown account`.   
If `eth_accounts` or `personal_listWallets` is called before the signing API, the call succeeds.

#### Steps to reproduce the behaviour
1. Start clef
1. Start geth with `--signer /path/to/clef.ipc`
1. Call `eth_sign` with an account known to be available to clef - the sign will fail
1. Call `eth_accounts`
1. Call `eth_sign` with the same account - the sign will now succeed

#### Cause
The `ExternalSigner` implementation of `accounts.Wallet` uses `cache []accounts.Account` to look up accounts that are available for signing.  This cache is populated by calls to `eth_accounts` (and a few other methods).

### PR DESCRIPTION
**Pull request by holiman**
This PR fills the account-cache from an externals signer, if that hasn't already been done. Fixes #20995
Bug repro below (but I only include the results for this PR): 

gethsign.json:
```json
 cat gethsign.json
{
  "jsonrpc": "2.0",
  "method": "eth_sign",
  "params": [ "0xD38018ac06AE8394C2a0Ed55BfDc3EE76e0Aa55C", ""],
  "id": 67
}
```

Start `clef` with: `build/bin/clef --keystore ~/tmp/fookeys`
Start `geth` with `build/bin/geth --nodiscover --maxpeers 0 --signer /home/user/.clef/clef.ipc`

Then send a request (without having touched the console) : `cat gethsign.json | nc -U /home/user/.ethereum/geth.ipc`

Clef output:
```
-------- List Account request--------------
A request has been made to list all accounts.
You can select which accounts the caller can see
  [x] 0xD38018ac06AE8394C2a0Ed55BfDc3EE76e0Aa55C
    URL: keystore:///home/user/tmp/fookeys/UTC--2020-04-28T11-50-33.375837463Z--d38018ac06ae8394c2a0ed55bfdc3ee76e0aa55c
-------------------------------------------
Request context:
	NA -> NA -> NA

Additional HTTP header data, provided by the external caller:
	User-Agent: ""
	Origin: ""
Approve? [y/N]:
> y

... followed by sign text ...
```
Eventually, the response:
```
[user@work clef]$ cat gethsign.json | nc -U /home/user/.ethereum/geth.ipc
{"jsonrpc":"2.0","id":67,"result":"0x324b5f7e6be13118848225da6b0c18fd80d2759952ba3d55d15de01bb36d5a0808141daa1b50ea216e99d1cb855446c86462244b63baa610f8d8d77740c09a3c37"}

```

### CODE REVIEW

File: accounts/external/backend.go [hunk 1]
```diff
@@ -131,6 +131,12 @@ func (api *ExternalSigner) Accounts() []accounts.Account {
 func (api *ExternalSigner) Contains(account accounts.Account) bool {
 	api.cacheMu.RLock()
 	defer api.cacheMu.RUnlock()
+	if api.cache == nil {
```
Comment (gballet) [inline accounts/external/backend.go:134]: Why not call `api.Accounts()` at the start of the function, before the lock is taken in the first place?

**Comment by holiman** [comment]
Because that would be racy on cache...?
