### PR TITLE
trie: remove inconsistent trie nodes during sync in path mode

### LINKED ISSUE #28587: `Unexpected trie node` error occurs after initial snap sync
#### System information

Geth version: `geth version`: `1.13.5`

#### Issue description

Ref: original ticket https://github.com/ethereum/go-ethereum/issues/27983#issuecomment-1818965551

```
Nov 22 12:33:19 ip-10-0-0-11.ec2.internal geth[30414]: INFO [11-22|12:33:19.850] Initialized transaction indexer          limit=2,350,000
Nov 22 12:33:19 ip-10-0-0-11.ec2.internal geth[30414]: INFO [11-22|12:33:19.850] Loaded local transaction journal         transactions=0 dropped=0
Nov 22 12:33:19 ip-10-0-0-11.ec2.internal geth[30414]: INFO [11-22|12:33:19.851] Regenerated local transaction journal    transactions=0 accounts=0
Nov 22 12:33:20 ip-10-0-0-11.ec2.internal geth[30414]: WARN [11-22|12:33:20.370] Switch sync mode from snap sync to full sync reason="snap sync complete"
Nov 22 12:33:20 ip-10-0-0-11.ec2.internal geth[30414]: INFO [11-22|12:33:20.370] Chain post-merge, sync via beacon client
Nov 22 12:33:20 ip-10-0-0-11.ec2.internal geth[30414]: INFO [11-22|12:33:20.370] Gasprice oracle is ignoring threshold set threshold=2
Nov 22 12:33:20 ip-10-0-0-11.ec2.internal geth[30414]: ERROR[11-22|12:33:20.389] Unexpected trie node in disk             owner=5cc0a4..667982 path="[12 5 9 3 7]" expect=8b09b1..e87152 got=99f9a0..b9f78f
Nov 22 12:33:20 ip-10-0-0-11.ec2.internal geth[30414]: ERROR[11-22|12:33:20.389] State snapshotter failed to iterate trie err="missing trie node 8b09b17b3a4e17de5274c52cc6387cf42c1fb25fd97effda757bb9a2cde87152 (owner 5cc0a47442e6bc69eb1ec9e2ff1fe0c9657c26dfa5836f560fd7141038667982) (path 0c05090307) unexpected node, loc: disk, node: (5cc0a47442e6bc69eb1ec9e2ff1fe0c9657c26dfa5836f560fd7141038667982 [12 5 9 3 7]), 8b09b17b3a4e17de5274c52cc6387cf42c1fb25fd97effda757bb9a2cde87152!=99f9a0c9f954cd0d8cf5bb7df9c2b5e529a1652fcc97824ee446ba9300b9f78f, blob: 0xf87180a0df5465feffb831b1f31a6184b1efdf75f10f13b2b4900956c22f41a6108c45c9808080808080a0b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae808080a02ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e780808080"
```

The node is reported as invalid, with 
- owner: `5cc0a47442e6bc69eb1ec9e2ff1fe0c9657c26dfa5836f560fd7141038667982`, 
- address: `0x32400084C286CF3E17e7B677ea9583e60a000324`
- path:`[12 5 9 3 7]`
- content: `0xf87180a0df5465feffb831b1f31a6184b1efdf75f10f13b2b4900956c22f41a6108c45c9808080808080a0b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae808080a02ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e780808080`
- exphash: `8b09b17b3a4e17de5274c52cc6387cf42c1fb25fd97effda757bb9a2cde87152`
- gothash `99f9a0c9f954cd0d8cf5bb7df9c2b5e529a1652fcc97824ee446ba9300b9f78f`

After retrieving the correct node from our benchmark machine, I rlpdump them

**correct node**

```
(base) ➜  ~ rlpdump -hex 0xf8518080808080808080a0b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae808080a02ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e780808080
[
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae,
  "",
  "",
  "",
  2ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e7,
  "",
  "",
  "",
  "",
]
```

**corrupted node**

```
(base) ➜  ~ rlpdump -hex 0xf87180a0df5465feffb831b1f31a6184b1efdf75f10f13b2b4900956c22f41a6108c45c9808080808080a0b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae808080a02ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e780808080
[
  "",
  df5465feffb831b1f31a6184b1efdf75f10f13b2b4900956c22f41a6108c45c9,
  "",
  "",
  "",
  "",
  "",
  "",
  b1902b4fca66415f63634e3ddeae1bfa7b877a1db5ed4c029730e166ba2031ae,
  "",
  "",
  "",
  2ded9e78076e79e96fcd5562c7951f678d22a167429cc75c17d30a08705bb6e7,
  "",
  "",
  "",
  "",
]
```

The corrupted node has one more child at the index 1.

---

Also, I dumped out the parent nodes of this one, they are all full nodes with no shortNode in the middle of path, so it's not relevant with the shortNode trick at all.

This storage is quite huge, with 1.8m slots inside.

--- 

I analyzed the contract, there are two functions can mutate the states: 

- `finalizeEthWithdrawal (0x6c0960f9)`: example from [etherscan](https://etherscan.io/tx/0x48c7d8df67c9f69ca1d92cfdcb779728683cd1a7ac4c54a8308f922212a94c20#statechange)
- `requestL2Transaction (0xeb672419)`: example from [etherscan](https://etherscan.io/tx/0x58a8e1c66852219e509fd34b13b1973e1d5bb1a42f83a0b102b9a1b6a67d2dc3#statechange) 

Both of them only create new storage slot, but never delete storage slot. 

--- 

There are a few possibilities here for this situation:
- The state sync target is forked, the transaction which creates the trie node at index 1 is reorged out and never get accepted
   I don't think it's the case here. Geth uses `head-64` as the sync target, which is very very hard to be reorged in the proof-of-stake network.

- programatic problems??

--- 

The log is attached. 

> Here it is -- I had a few mis-starts in the log but each time I purged the DB

[sync-log.zip](https://github.com/ethereum/go-ethereum/files/13446792/sync-log.zip)

### PR DESCRIPTION
**Pull request by rjl493456442**
This pull request fixes #28587 

--- 

**State sync recap**

In Geth state sync mechanism, there are two steps: (1) snap sync (2) state healing. In the first stage, Geth will request a batch of states(accounts and storage slots), verify the correctness via range proof and construct the internal merkle tree nodes locally. 

However due to the fact that the retrieved states may be incomplete, lacking either the head or the tail, the locally constructed merkle trie nodes may be inconsistent with the correct one. In order to avoid committing inconsistent trie nodes, the boundary trie nodes are filtered out and this logic is implemented in https://github.com/ethereum/go-ethereum/pull/28327.

After retrieving the states of the entire keyspace, the persistent states, along with their Merkle tree nodes, can still be inconsistent with each other due to differences in sync targets between different sync cycles. To fix this inconsistency, state healing is necessary.

State healing essentially traverses the entire Merkle trie from root to bottom, retrieving any inconsistent nodes and continuously expanding the trie until the entire trie aligns with the provided root node.

---

**What's the issue this pull request trying to fix?**

Originally, in the state healing stage, the inconsistent trie nodes would be left in the database, awaiting overwriting. However, one corner case is not handled: What if the children of this inconsistent node are committed, and the sync cycle is aborted without overwriting this inconsistent one? The persistent state ends up in a weird situation where nodes on the same path are inconsistent with each other.

And, even worse, what if the target of the next sync cycle switches to one that matches the leftover inconsistent node? The entire subtrie won't be expanded because the state healer believes the subtrie must exist and be consistent with the sub-root node.

截屏2023-11-27 下午2 54 48

Here is an example to demonstrate the situation.

- The original state root is 1
- The current state root is 1'
- State healer detects the inconsistency and expands the node path from 1 to 6
- State healer commits the 6' into database
- Healing is aborted
- The next state root is switched to 1 again
- The original root node 1 is present in database, healing finished

However, the `6'` is left in database, causing the state as corrupted.

Although this corner case is pretty hard to occur, but it's totally possible and #28587 is the example.

---

**How to fix the state healer to address this it?**

This fix is specifically for path mode and not relevant with hash based at all. 

In path mode, whenever the inconsistent nodes are met by state healer, these nodes must be marked as deleted, **from top to bottom**, consistent with the order of traverse.

- If a few nodes are bypassed by a shortNode, should these node be marked as deleted?

Yes. in the picture above, node 3 is bypassed by node 2'. In this case, the node 3 should also be deleted otherwise the leftover 3 will be inconsistent with bottom nodes.

- If a fullNode is replaced by a shortNode and do we need to delete the other branches?

No. These branches are not linked with the trie anymore, and also they are complete. It's totally safe to leave them in disk and they can be re-linked if state switches.

- It might be possible that a node is deleted because of inconsistency and re-written. The delete and write can happen in the same database batch, does leveldb and pebble support it?

Yes, both database engine support mixing delete and write in same batch and there is a test case to prove that in codebase.

### CODE REVIEW

File: trie/sync.go [hunk 1]
```diff
@@ -221,6 +223,16 @@ func (s *Sync) AddSubTrie(root common.Hash, path []byte, parent common.Hash, par
...
 	}
+	// If the node does not exist in the database or its content does not
+	// match the requested content, schedule it for retrieval.
+	//
+	// Notably, the existent node should be wiped first if path scheme is
+	// used, otherwise state will end up with a weird situation that parent
+	// node is inconsistent with children while they are all present in
+	// database.
+	if s.scheme == rawdb.PathScheme {
+		rawdb.DeleteTrieNode(s.database, owner, inner, common.Hash{} /* unused */, s.scheme)
```
Comment (holiman) [inline trie/sync.go:234]: When we wind up here, we're being a bit wasteful. 
The `rawdb.HasTrieNode` already invoked `HasStorageTrieNode(db, owner, path, hash)`, and looked up the path. It found a node, however, the check `h.hash(data) == hash` failed, so it returned `false`. 
At this point, we do `DeleteTrieNode` -> `DeleteStorageTrieNode`, which adds a deletion to the batch -- regardless of whether there is anything there or not. ( deletion puts a tombstone in the database, so even if there's nothing there to begin with, a deletion is _not_ a no-op).


A more lenient use of resources would be something like, 
```golang
	ok, mismatch := rawdb.HasTrieNode(s.database, owner, path, root, s.scheme)
	if ok{
		return
	}
	// node is not present, however, mismatch == true means that _something_ is 
	// occupying that path (but does not match the hash). This can only occur in path-scheme
	if mismatch{
		rawdb.DeleteTrieNodeByPath(s.database, owner, path)
	}
```

File: trie/sync.go [hunk 2]
```diff
@@ -385,7 +398,13 @@ func (s *Sync) Commit(dbw ethdb.Batch) error {
 		} else {
 			storage += 1
 		}
-		rawdb.WriteTrieNode(dbw, owner, inner, s.membatch.hashes[path], value, s.scheme)
+		valid := true
+		if s.onPersist != nil {
+			valid = s.onPersist(owner, inner)
+		}
```
Comment (holiman) [inline trie/sync.go:404]:
```suggestion
		valid := (s.onPersist == nil) || s.onPersist(owner, inner)
```
perhaps?

**Review by holiman — COMMENTED** [review]
Generally lgtm, bugfix-wise, although I think it could be improved upon. 

Also, I know that we have pretty good sync-tests, but the sync-tests are notoriously not very good at simulating a trie that actually progresses, so it's a bit hard to write those kinds of tests.

File: trie/sync.go (hunk 1 above)
Comment (holiman) [reply trie/sync.go:234]: I guess my suggestion is moot, in the long run, since we're getting rid of the hash-check

Comment (holiman) [reply trie/sync.go:234]: But: how will we implement this fix after getting rid of hash-checks?

**Review by holiman — APPROVED** [review]
LGTM as far as I can tell

File: trie/sync.go [hunk 3]
```diff
@@ -639,6 +667,40 @@ func (s *Sync) commitCodeRequest(req *codeRequest) error {
...
+		return false
+	}
+	blob, hash := rawdb.ReadStorageTrieNode(s.database, owner, path)
+	if hash == root {
+		return true
+	}
+	// Remove the inconsistent node before expanding the path.
+	if len(blob) != 0 {
+		s.membatch.delNode(owner, path)
+	}
```
[the remark this answers is not in the document]
Comment (fjl) [reply trie/sync.go:700]: One thing I don't like, is that deletions will be added to the membatch from within methods that used to be free of side effects. With the changes in this PR, `hasNode` now *must be called* to clean up the database, and it is no longer simply a check whether the node exists. It is usually better to structure things such that side effects are performed explicitly based on the outcome of idempotent checks. I need to look into the PR more to understand how that could be done here.

[the remark this answers is not in the document]
Comment (fjl) [reply trie/sync.go:700]: Adding a mutation of the membatch here could also introduce a race because we run `hasNode` in a new goroutine.

**Review by fjl — APPROVED** [review]
