### PR TITLE
Fix for xeth OOM issue

### LINKED ISSUE #1930: geth 1.2.2, possible memory leak
I can create by doing this:
```
geth & # watch this process memory
while :
do
geth --exec admin.peers attach
done
```
After a while the main geth process running in the background will run out of memory.

### PR DESCRIPTION
**Pull request by fjl**
This PR fixes an issue where every IPC connection would leak goroutines and memory when the connection was closed.
Fixes #1930. I ran the shell loop there for a few minutes and didn't see any changes in the memory profile.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Oct 29 12:32:23 UTC 2015_

File: eth/filters/filter_system.go [hunk 1]
```diff
@@ -31,30 +31,32 @@ import (
...
 func NewFilterSystem(mux *event.TypeMux) *FilterSystem {
 	fs := &FilterSystem{
-		eventMux: mux,
-		filters:  make(map[int]*Filter),
-		created:  make(map[int]time.Time),
+		filters: make(map[int]*Filter),
+		created: make(map[int]time.Time),
 	}
+	fs.sub = mux.Subscribe(
+		//core.PendingBlockEvent{},
```
Comment (Gustav-Simonsson) [inline eth/filters/filter_system.go]: Please add a comment describing why this is out commented.

File: eth/filters/filter_system.go [hunk 2]
```diff
@@ -89,57 +91,37 @@ func (fs *FilterSystem) Get(id int) *Filter {
...
-			case core.ChainEvent:
-				fs.filterMu.RLock()
-				for id, filter := range fs.filters {
-					if filter.BlockCallback != nil && fs.created[id].Before(event.Time) {
-						filter.BlockCallback(ev.Block, ev.Logs)
-					}
+	for event := range fs.sub.Chan() {
+		switch ev := event.Data.(type) {
+		case core.ChainEvent:
+			fs.filterMu.RLock()
```
Comment (Gustav-Simonsson) [inline eth/filters/filter_system.go]: Since `fs.filterMu.RLock()` and `fs.filterMu.RUnlock()` are called regardless of event type, they can be moved outside of the `switch`.

File: eth/filters/filter_system.go [hunk 3]
```diff
@@ -89,57 +91,37 @@ func (fs *FilterSystem) Get(id int) *Filter {
...
+			for id, filter := range fs.filters {
```
Comment (Gustav-Simonsson) [inline eth/filters/filter_system.go]: `for id, filter := range fs.filters {` is common pattern for all event types - this could be made into an anonymous function, in which case it could also do the locking and unlocking of `fs.filterMu`

File: eth/filters/filter_system.go (hunk 1 above)
Comment (fjl) [inline eth/filters/filter_system.go]: I didn't comment it out. No idea why it is not enabled.

File: eth/filters/filter_system.go (hunk 2 above)
Comment (fjl) [inline eth/filters/filter_system.go]: The purpose of this PR is to fix a specific issue, not improving the filter code.

File: miner/worker.go [hunk 4]
```diff
@@ -92,7 +92,7 @@ type Result struct {
 type worker struct {
 	mu sync.Mutex
 
-	agents []Agent
+	agents map[Agent]struct{}
```
Comment (Gustav-Simonsson) [inline miner/worker.go]: What's the benefit of using a map with dummy elements compared to a slice of elements?

File: rpc/comms/ipc_windows.go [hunk 5]
```diff
@@ -698,27 +698,27 @@ func startIpc(cfg IpcConfig, codec codec.Codec, initializer func(conn net.Conn)
 	os.Chmod(cfg.Endpoint, 0600)
 
 	go func() {
+		defer os.Remove(cfg.Endpoint)
```
Comment (obscuren) [inline rpc/comms/ipc_windows.go]: The amount of return values of this function needs to change as well (not on this line, L691)

File: miner/worker.go (hunk 4 above)
Comment (fjl) [inline miner/worker.go]: `delete`

File: eth/filters/filter_system.go (hunk 1 above)
Comment (Gustav-Simonsson) [inline eth/filters/filter_system.go]: OK, in that case please remove it.

File: miner/worker.go (hunk 4 above)
Comment (Gustav-Simonsson) [inline miner/worker.go]: Please elaborate what the benefit is. The current code also deletes the agent from the slice of agents.

Comment (fjl) [inline miner/worker.go]: The benefit is being able to call `delete`.

File: eth/filters/filter_system.go (hunk 1 above)
Comment (fjl) [inline eth/filters/filter_system.go]: I think you misunderstand this PR. The purpose of this PR is calling `XEth.Stop` when IPC connections end.
All the other changes are just there to make `Stop` work. I will not fix random stuff everywhere in this PR.

File: miner/worker.go (hunk 4 above)
Comment (Gustav-Simonsson) [inline miner/worker.go]: Please elaborate what the benefit of being able to call `delete` is, compared to the current code which already has a working implementation of deleting an element from a slice.

Comment (fjl) [inline miner/worker.go]: The benefit is being able to call `delete` instead of having to use a for loop and slice operations.

Comment (fjl) [inline miner/worker.go]: I can do this all day btw.

**Comment by fjl** [comment]
I tested on windows and it still seems to be working.

File: eth/filters/filter_system.go (hunk 1 above)
Comment (Gustav-Simonsson) [inline eth/filters/filter_system.go]: If so, then please revert the changes done to `agents` field in `miner/worker.go` since they are not needed for the purpose of this PR.

File: miner/worker.go (hunk 4 above)
Comment (Gustav-Simonsson) [inline miner/worker.go]: OK, this change does not affect performance, maintainability or readability in any significant way. Would therefore recommend to skip it. Also, this change is inconsistent with your statement that the purpose of this PR is to calling XEth.Stop when IPC connections end.

You cannot simultaneously claim that is the purpose of the PR and thus the motivation for not doing other, suggested, code improvement but then do such an unrelated (potential) improvement here.

**Comment by bas-vk** [comment]
Code looks okay but I agree with Gustav that some of the changes are not required to solve the issue. Since we haven them I would not revert them just to keep the PR as clean as possible.

**Comment by fjl** [comment]
@bas-vk Is this about the slice vs. map?

File: miner/worker.go (hunk 4 above)
Comment (fjl) [inline miner/worker.go]: If this is not a map, deletion looks like this:

```go
func deleteAgent(a Agent, s []Agent) []Agent {
	for i := range s {
		if s[i] == a {
			return append(s[:i], s[i+1:]...)
		}
	}
	return s
}
```

I don't want to include that. `delete` is just easier.

**Comment by bas-vk** [comment]
Not just, the modification to the log line in worker.go, or code format such as such as removing the index in the range loop.

**Comment by fjl** [comment]
@bas-vk I removed the change to the log message. The for loop indexes need to change because of the map.

File: miner/worker.go (hunk 4 above)
Comment (Gustav-Simonsson) [inline miner/worker.go]: Aside from the fact that changing this data type resulted in a discussion which now caused you to write the very function you wanted to avoid writing by making this change, you don't have to write this function to delete an agent.

Rather, you can make use of `agent.index` to know which element in the slice to delete. Each agent has it's index set on creation: https://github.com/ethereum/go-ethereum/blob/master/miner/miner.go#L115

This will shorten the delete operation to `a = append(a[:i], a[i+1:]...)`

**Comment by fjl** [comment]
@obscuren squashed
