### PR TITLE
cmd/geth: change to non-fatal error message when legacy receipt storage is not implemented

### LINKED ISSUE #24602: Geth crashes in dev mode with `Failed to check for legacy receipts`
#### System information

Geth version: `geth version`
`1.10.17-unstable-0fffd3ac`
OS & Version: `ethereum/client-go:latest
DIGEST:sha256:40e8b7cf5c7cd597c9a9f019f249f5dc1ffc34e6fbf4db37d8ddd06cb7915186`

#### Expected behaviour

Runs in developer mode.

#### Actual behaviour

Crashes with `Fatal: Failed to check db for legacy receipts: this operation is not supported`

#### Steps to reproduce the behaviour

Just run it in a container,
` podman run -it  --network=host ethereum/client-go --mine --dev --dev.period 1` or `docker run -it  --network=host ethereum/client-go --mine --dev --dev.period 1`.

#### Backtrace

````
INFO [03-28|23:15:00.891] Starting Geth in ephemeral dev mode... 
INFO [03-28|23:15:00.892] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-28|23:15:00.892] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [03-28|23:15:00.893] Set global gas cap                       cap=50,000,000
INFO [03-28|23:15:01.062] Using developer account                  address=0x42b19ac33157C646B7fe39e35705772409B842fA
INFO [03-28|23:15:01.062] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [03-28|23:15:01.063] Writing custom genesis block 
INFO [03-28|23:15:01.063] Persisted trie from memory database      nodes=13 size=1.90KiB time="43.517µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [03-28|23:15:01.063] Initialised chain configuration          config="{ChainID: 1337 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 0, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: clique}"
INFO [03-28|23:15:01.064] Initialising Ethereum protocol           network=1337 dbversion=<nil>
INFO [03-28|23:15:01.064] Loaded most recent local header          number=0 hash=6a6cac..e380a5 td=1 age=52y11mo4w
INFO [03-28|23:15:01.064] Loaded most recent local full block      number=0 hash=6a6cac..e380a5 td=1 age=52y11mo4w
INFO [03-28|23:15:01.064] Loaded most recent local fast block      number=0 hash=6a6cac..e380a5 td=1 age=52y11mo4w
WARN [03-28|23:15:01.064] Failed to load snapshot, regenerating    err="missing or corrupted snapshot"
INFO [03-28|23:15:01.064] Rebuilding state snapshot 
INFO [03-28|23:15:01.064] Resuming state snapshot generation       root=32ce24..f8f48b accounts=0 slots=0 storage=0.00B elapsed="275.489µs"
INFO [03-28|23:15:01.065] Generated state snapshot                 accounts=10 slots=0 storage=412.00B elapsed="553.995µs"
INFO [03-28|23:15:01.065] Stored checkpoint snapshot to disk       number=0 hash=6a6cac..e380a5
INFO [03-28|23:15:01.065] Gasprice oracle is ignoring threshold set threshold=2
WARN [03-28|23:15:01.065] Error reading unclean shutdown markers   error="not found"
Fatal: Failed to check db for legacy receipts: this operation is not supported

````

### PR DESCRIPTION
**Pull request by jwasinger**
fixes #24602

### CODE REVIEW

File: cmd/geth/config.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func makeFullNode(ctx *cli.Context) (*node.Node, ethapi.Backend) {
 	}
 	backend, eth := utils.RegisterEthService(stack, &cfg.Eth)
 	// Warn users to migrate if they have a legacy freezer format.
-	if eth != nil {
+	if eth != nil && !ctx.GlobalIsSet(utils.DeveloperFlag.Name) {
```
Comment (rjl493456442) [inline cmd/geth/config.go:167]: In Line 177, we forcibly stop the Geth if any error is occurred. Can we degrade the log level to `Error`? It's just an additional check and it's OK to fail.

Just in case we still have a few mistakes.

**Comment by karalabe** [comment]
I'm not entirely sure what the purpose of this PR is? Dev mode is just like all the other modes, it should not have db checks disabled. If someone has an old db, it should be treated just like an old db of mainnet, it needs to be upgraded somehow. Otherwise it won't be accessible any more.

Wasn't there a db command to update the legacy format to new?

**Comment by rjl493456442** [comment]
> ev mode is just like all the other modes, it should not have db checks disabled. If someone has an old db, it should be treated just like an old db of mainnet, it needs to be upgraded somehow. Otherwise it won't be accessible any more.

The reason is: for legacy receipt format checking, it will invoke some ancient store API, but memorydb doesn't implement it(dev mode), so an error is occurred.
I think we can drop the dev checking, but just degrade the log level to Error Level instead of Crit

**Review by holiman — APPROVED** [review]
LGTM

**Review by holiman — APPROVED** [review]
Still lgtm

**Review by Newman1515 — COMMENTED** [review]
🔥🔥🔥🔥🔥
