### PR TITLE
core: fix race condition in WriteMipmapBloom

### LINKED ISSUE #3502: Subscribing to a log/filter in geth returns less results than Parity
#### System information
Geth version: 1.5.5
OS & Version: Windows

#### Expected behaviour
Subscribing to the ENS SimplifiedHashRegistry ("0xc68de5b43c3d980b0c110a77a5f78d3c4c4d63b4").AuctionStarted() event log in geth returns 3 fewer AuctionStarted events than Parity.  At the time of lodging this issue its 420 for Geth and 423 for Parity.

#### Actual behaviour
Geth not returning some event logs, particularly the first one.

#### Steps to reproduce the behaviour
Subscribe to event listing above.  Using ABI defined in https://github.com/ethereum/ens/blob/master/ensutils.js

### PR DESCRIPTION
**Pull request by bas-vk**
`core#WriteMipmapBloom` first retrieves the existing bloom filter on a level, updates it with the new set of logs and adds it to a batch that is written when the bloom filters on all levels are updated. When called in parallel (`core.BlockChain#InsertReceiptChain`) this can cause a race condition because one of the batches can overwrite the other.

Fixes #3502 and #2370

### CODE REVIEW

File: core/database_util.go [hunk 1]
```diff
@@ -63,6 +64,8 @@ var (
 	oldBlockHashPrefix     = []byte("block-hash-") // [deprecated by the header/block split, remove eventually]
 
 	ChainConfigNotFoundErr = errors.New("ChainConfig not found") // general config not found error
+
+	mipmapBloomMu = sync.Mutex{} // protect against race condition when updating mipmap blooms
```
Comment (karalabe) [inline core/database_util.go]: This line could simply be `mipmapBloomMu sync.Mutex`, imho a lot cleaner :)

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: cc04bcff4eb287a47afbd3e7723c22898297863b
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com
