### PR TITLE
RPC Hexify

### LINKED ISSUE #607: RPC: "eth_getTransactionByBlockNumberAndIndex" refused connection
When i send:

```
{"jsonrpc":"2.0","method":"eth_getTransactionByBlockNumberAndIndex","params":["0x2e7","0x0"],"id":4539}
```

I get no response back the connection simply fails.

### LINKED ISSUE #608: RPC: "eth_getTransactionByHash" returns a transaction with empty blockHash and blockNumber
sending:

```
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x99ab199e1f1ab9d5a08373c4e693d5a71a3ac65d52da5430581ed8b74d5b940a"],"id":4540}
```

Returns me the transaction but with the following `blockHash`, `blockNumber` and `transactionIndex` (?):

```js
{
	"id": 4540,
	"jsonrpc": "2.0",
	"result": {
		"hash": "0x99ab199e1f1ab9d5a08373c4e693d5a71a3ac65d52da5430581ed8b74d5b940a",
		"nonce": "0x0",
		"blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"blockNumber": "0x0",
		"transactionIndex": "0x0",
		"from": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"to": "0x8b09e3535d27ad599d984fd63b1578b6f068f01b",
		"value": "0x2710",
		"gas": "0x0186a0",
		"gasPrice": "0x015f90",
		"input": "0x0"
	}
}
```

The transactions are correctly returned using `eth_getTransactionByBlockHashAndIndex ` and when inside a block with `eth_getBlock` and second parameter `true`.

### PR DESCRIPTION
**Pull request by tgerring**
* [x] Define new hexnum and hexdata types to convey formatting information (updated spec)
* [x] Compact constructor and marshal steps (reduces codes)
* [x] Fix #607
* [x] Fix #608
* [x] Updated eth_call arguments
* [x] Fix or remove response tests (low priority)

### CODE REVIEW

File: rpc/messages.go [hunk 1]
```diff
@@ -19,8 +19,91 @@ package rpc
...
+
+func (d *hexdata) UnmarshalJSON(b []byte) (err error) {
+	d.data = common.FromHex(string(b))
+	return nil
+}
+
+func newHexData(input interface{}) *hexdata {
+	d := new(hexdata)
+
+	switch input.(type) {
```
Comment (obscuren) [inline rpc/messages.go]: Change this to 

```go
switch input := input.(type) {
case common.Hash:
    d.data = input.Bytes()
}
```

No need to do the extra type assertions

File: xeth/xeth.go [hunk 2]
```diff
@@ -185,12 +185,29 @@ func (self *XEth) EthBlockByHash(strHash string) *types.Block {
...
+func (self *XEth) EthTransactionByHash(hash string) (tx *types.Transaction, blhash common.Hash, blnum *big.Int, txi uint64) {
 	data, _ := self.backend.ExtraDb().Get(common.FromHex(hash))
 	if len(data) != 0 {
-		return types.NewTransactionFromBytes(data)
+		tx = types.NewTransactionFromBytes(data)
 	}
-	return nil
+
+	// blockhash
+	data, _ = self.backend.ExtraDb().Get(append(common.FromHex(hash), 0x0001))
```
Comment (obscuren) [inline xeth/xeth.go]: See comment above

File: core/block_processor.go [hunk 3]
```diff
@@ -358,11 +359,32 @@ func (sm *BlockProcessor) GetLogs(block *types.Block) (logs state.Logs, err erro
...
 
-func putTx(db common.Database, tx *types.Transaction) {
+func putTx(db common.Database, tx *types.Transaction, block *types.Block, i int) {
 	rlpEnc, err := rlp.EncodeToBytes(tx)
 	if err != nil {
 		statelogger.Infoln("Failed encoding tx", err)
 		return
 	}
 	db.Put(tx.Hash().Bytes(), rlpEnc)
+
```
Comment (obscuren) [inline core/block_processor.go]: Change this to something like:

```go
var txExtra struct {
    Tx *types.Transaction
    Index uint
    BlockHash common.Hash
}

encoded, err := rlp.EncodeToBytes(txExtra{tx, i, block.Hash()})
```

It's unnecessarily complex now.
