### PR TITLE
eth/catalyst: ensure period zero mode leaves no pending txs in pool

### LINKED ISSUE #29475: Transactions stuck in pending in dev-mode
#### System information

* Geth version
    ```
    Geth
    Version: 1.13.14-stable
    Git Commit: 2bd6bd01d2e8561dd7fc21b631f4a34ac16627a1
    Git Commit Date: 20240227
    Architecture: arm64
    Go Version: go1.21.0
    Operating System: darwin
    GOPATH=
    GOROOT=/Users/gashkov/.asdf/installs/golang/1.22.0/go
    ```
* CL client & version: none (dev-mode)
* OS & Version: macOS Sonoma 14.4.1 (23E224)
* Commit hash: not applicable

#### Steps to reproduce the behaviour

1. Run `go-ethereum` in a dev-mode with block generation on demand
2. Send a batch of transactions concurrently

<details>
<summary>Stress-testing script I used for reproducing this behavior.</summary>

```go
package main

import (
	"fmt"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/rpc"
	"log"
	"sync"
	"time"
)

func getCoinbase(c *rpc.Client) common.Address {
	var coinbase common.Address

	if err := c.Call(&coinbase, "eth_coinbase"); err != nil {
		log.Fatalln("error obtaining coinbase", err)
	} else {
		log.Printf("coinbase=%v", coinbase)
	}

	return coinbase
}

func getTransactionCount(c *rpc.Client, address common.Address) hexutil.Uint {
	var nonce hexutil.Uint

	if err := c.Call(&nonce, "eth_getTransactionCount", address, "latest"); err != nil {
		log.Fatalln("error obtaining coinbase's initial nonce", err)
	} else {
		log.Printf("nonce=%v", nonce)
	}

	return nonce
}

func sendTransactionToSelf(c *rpc.Client, address common.Address, nonce hexutil.Uint) (common.Hash, error) {
	txObject := map[string]any{"from": address, "to": address, "nonce": nonce}

	var txHash common.Hash
	if err := c.Call(&txHash, "eth_sendTransaction", txObject); err != nil {
		return common.Hash{}, err
	}

	return txHash, nil
}

func waitTransactionReceipt(c *rpc.Client, txHash common.Hash) (*types.Receipt, error) {
	for i := 0; i < 10; i++ {
		var txReceipt *types.Receipt
		if err := c.Call(&txReceipt, "eth_getTransactionReceipt", txHash); err != nil {
			if fmt.Sprint(err) == "transaction indexing is in progress" {
				// `transaction indexing is in progress` is returned when
				// `eth_getTransactionCount` is called with no previously mined
				// blocks.
				time.Sleep(1 * time.Second)
			} else {
				return nil, err
			}
		}

		if txReceipt != nil {
			return txReceipt, nil
		}

		time.Sleep(100 * time.Millisecond)
	}

	return nil, fmt.Errorf("timeout waiting tx hash=%v to be mined", txHash)
}

func main() {
	c, err := rpc.Dial("http://localhost:8545")

	if err != nil {
		log.Fatal("error dialing server", "url", "http://localhost:8545")
	}

	coinbase := getCoinbase(c)
	startingNonce := getTransactionCount(c, coinbase)

	var (
		wg  sync.WaitGroup
		sem = make(chan struct{}, 5)
	)

	for nonce := startingNonce; nonce <= startingNonce+15; nonce++ {
		nonce := nonce
		sem <- struct{}{}
		wg.Add(1)

		go func() {
			defer func() { <-sem }()
			defer wg.Done()

			if txHash, err := sendTransactionToSelf(c, coinbase, nonce); err != nil {
				log.Printf("error sending tx nonce=%v err=%v", uint64(nonce), err)
			} else if receipt, err := waitTransactionReceipt(c, txHash); err != nil {
				log.Printf("error waiting tx nonce=%v err=%v", uint64(nonce), err)
			} else {
				log.Printf("sent tx hash=%v nonce=%v blockNumber=%v", receipt.TxHash, uint64(nonce), receipt.BlockNumber)
			}
		}()
	}

	wg.Wait()
}
```
</details>
</details>
<details>
<summary>Stress-testing output</summary>

```
% go run main.go
2024/04/06 20:13:14 coinbase=0xfb8c69691E914275e19Eb9d42735844A120067aD
2024/04/06 20:13:14 nonce=0x0
2024/04/06 20:13:15 sent tx hash=0xad155b491b06bffa28d2e0ebd4cf4f85a8e5bec108428cb2492b0048395fc3b7 nonce=2 blockNumber=1
2024/04/06 20:13:15 sent tx hash=0x7c7d61049a6118838cb0babd50aa05d5f8feece647637313d2e432dc2448e6e4 nonce=1 blockNumber=1
2024/04/06 20:13:15 sent tx hash=0xa53f94890c86c1d20f6c6398c8cd07d8c91bad816c91b7119c525f597ae7237a nonce=0 blockNumber=1
2024/04/06 20:13:15 sent tx hash=0x06bbb3c89850442f73ac53fff35b42a529dac62dde0167480455dda21e4b54e4 nonce=4 blockNumber=1
2024/04/06 20:13:15 sent tx hash=0xb55986ad438a261b8225e6384eba83a3dd710f196a5105526f149d0c8f85c0a8 nonce=3 blockNumber=1
2024/04/06 20:13:15 sent tx hash=0xc2f5aa3063d679fd39d9f2495577cb204519e9b8ecd68065155083f9c13a9aae nonce=7 blockNumber=2
2024/04/06 20:13:15 sent tx hash=0xedb2c69e889019102540da5800c4717aa3e9178fa9f8a8e4ac260235827b122d nonce=5 blockNumber=2
2024/04/06 20:13:15 sent tx hash=0xcc36386a360e4c35ccf7da2cd6d87ec4509f619f6f1620a3a9e3c43d0a050f71 nonce=6 blockNumber=2
2024/04/06 20:13:15 sent tx hash=0xf7f8a37a85beb5d366c989295cd46961a9e2bb59fac54b58fcb69fd93c7caa25 nonce=8 blockNumber=2
2024/04/06 20:13:16 error waiting tx nonce=9 err=timeout waiting tx hash=0x9b54d66bb30c77334f95e2931ca4ab6f11f61b139af1a6fc517b3fb4fe8b5e93 to be mined
2024/04/06 20:13:16 error waiting tx nonce=11 err=timeout waiting tx hash=0x6bd2490d9e4539f37ef2493389cd1066a25b32b4b2f50076e2824437335ead8f to be mined
2024/04/06 20:13:16 error waiting tx nonce=13 err=timeout waiting tx hash=0x2298fea2beeae800aa07c9e1751de1a4995d3fc506e0af3fc9039d77e89309e9 to be mined
2024/04/06 20:13:16 error waiting tx nonce=10 err=timeout waiting tx hash=0x034b4941ac6c1de3fd8e32b5c9d9976fb5896c6dbd6f37e9bb019db9e136d825 to be mined
2024/04/06 20:13:16 error waiting tx nonce=12 err=timeout waiting tx hash=0x24ca4ec05d745c4271e7b4a70d7a74d403daa38306ef7a6f6ae01a8394db7964 to be mined
2024/04/06 20:13:17 error waiting tx nonce=14 err=timeout waiting tx hash=0x2120f1d967a28ba0c467fd6c638db89959d64a92872569e7e0869ba0f3abad43 to be mined
2024/04/06 20:13:17 error waiting tx nonce=15 err=timeout waiting tx hash=0xb0e0165e29eb44545cd852da79937ad50c5933bead69cf54fbc122b5b50163e6 to be mined
```

</details>

#### Expected behaviour

`geth --dev` accepts and executes transactions concurrently.

#### Actual behaviour

Transactions are accepted but stuck in the pool:

```
% curl \
  -s \
  -X POST http://localhost:8545/ \
  -H 'content-type: application/json' \
  -H 'accept: application/json, */*;q=0.5' \
  -d '{"jsonrpc":"2.0","id":"1","method":"txpool_inspect","params":[]}' | jq

{
  "jsonrpc": "2.0",
  "id": "1",
  "result": {
    "pending": {
      "0xfb8c69691E914275e19Eb9d42735844A120067aD": {
        "9": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1750000001 wei"
      }
    },
    "queued": {
      "0xfb8c69691E914275e19Eb9d42735844A120067aD": {
        "10": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei",
        "11": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei",
        "12": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei",
        "13": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei",
        "14": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei",
        "15": "0xfb8c69691E914275e19Eb9d42735844A120067aD: 0 wei + 21000 gas × 1535240671 wei"
      }
    }
  }
}
```

Looks like the root cause is the deadlock between `SimulatedBeacon` and
`TxPool` waiting each other. Overall, the following happens:

```
SimulatedBeacon.loop():
  case <-newTxs:
    SimulatedBeacon.SealBlock()
      TxPool.Sync()  // Runs pool reorg and waits until done
        LegacyPool.runReorg()
```

and at the same time

```
SubmitTransaction(newTx)
  EthAPIBackend.SendTx(newTx)
    LegacyPool.add(newTx)
      LegacyPool.runReorg()
        txFeed.send(newTx)
          newTxs <- newTx // Waits until SimulatedBeacon.loop will be ready
```

So, when new TXs are sent concurrently, `LegacyPool` waits `SimulatedBeacon`
to react to the new TX but the `SimulatedBeacon` itself waits `LegacyPool` to
sync itself.

#### Backtrace

Nothing too suspicious in logs, but stacktraces contain two goroutines
indirectly waiting each other though:

```
goroutine 4279 [chan receive, 1 minutes]:
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).Sync(0xc000513e60)
        /Users/gashkov/dev/go-ethereum/core/txpool/txpool.go:478 +0x148
github.com/ethereum/go-ethereum/eth/catalyst.(*ConsensusAPI).forkchoiceUpdated(0xc000178be0, {{0xc9, 0x10, 0x26, 0x77, 0xa1, 0x3, 0x24, 0x7, 0xab, ...}, ...}, ...)
        /Users/gashkov/dev/go-ethereum/eth/catalyst/api.go:397 +0x28d0
github.com/ethereum/go-ethereum/eth/catalyst.(*SimulatedBeacon).sealBlock(0xc0006626e0, {0x108c0da00, 0x0, 0x0}, 0x661190bc)
        /Users/gashkov/dev/go-ethereum/eth/catalyst/simulated_beacon.go:159 +0x4f4
github.com/ethereum/go-ethereum/eth/catalyst.(*SimulatedBeacon).Commit(0xc0006626e0)
        /Users/gashkov/dev/go-ethereum/eth/catalyst/simulated_beacon.go:249 +0xc4
github.com/ethereum/go-ethereum/eth/catalyst.(*api).loop(0xc0001b6980)
        /Users/gashkov/dev/go-ethereum/eth/catalyst/simulated_beacon_api.go:50 +0x2d8
created by github.com/ethereum/go-ethereum/eth/catalyst.RegisterSimulatedBeaconAPIs in goroutine 1
        /Users/gashkov/dev/go-ethereum/eth/catalyst/simulated_beacon.go:294 +0x14c
```
```
goroutine 4369 [select, 1 minutes]:
reflect.rselect({0xc00001d148, 0x2, 0x99?})
        /Users/gashkov/.asdf/installs/golang/1.21.0/go/src/runtime/select.go:589 +0x2d0
reflect.Select({0xc000000b40, 0x2, 0x5})
        /Users/gashkov/.asdf/installs/golang/1.21.0/go/src/reflect/value.go:3104 +0xa00
github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc0003b9c90, {0x106d49200, 0xc000b78078})
        /Users/gashkov/dev/go-ethereum/event/feed.go:160 +0x758
github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).runReorg(0xc0003b9c00, 0xc0005e8fc0, 0xc000488ed0, 0xc000458ce0, 0xc00089d290)
        /Users/gashkov/dev/go-ethereum/core/txpool/legacypool/legacypool.go:1336 +0xbf0
created by github.com/ethereum/go-ethereum/core/txpool/legacypool.(*LegacyPool).scheduleReorgLoop in goroutine 46
        /Users/gashkov/dev/go-ethereum/core/txpool/legacypool/legacypool.go:1205 +0x37c
```

* [All logs](https://raw.githubusercontent.com/nikitagashkov/go-ethereum-1-13-4-dev-mode-deadlock-report/70ef96998d9d3a1b37dd6f1065b20b539a84a122/logs.txt)
* [All stacktraces](https://raw.githubusercontent.com/nikitagashkov/go-ethereum-1-13-4-dev-mode-deadlock-report/70ef96998d9d3a1b37dd6f1065b20b539a84a122/stacktrace.txt)

Thank you for reviewing this report!

### PR DESCRIPTION
**Pull request by lightclient**
closes #29475, replaces #29657, #30104 

The original problem noted in #29475 was a deadlock where `runReorg` was trying to write to `newTxs` subscription, but the reader was already waiting for `runReorg` to finish in a call to `txpool.Sync()`. This PR solves that issue by creating a worker thread in the simulated beacon API which allows the API's main event handler to never block. Instead, when a new tx or withdrawal event is received it notifies the worker thread to begin constructing a block. It uses a buffered channel to ensure that while the worker is building a block, additional requests to construct a block are not dropped nor blocked on.

Although this was also solved by spawning a new goroutine on each `newTxs` event #29657, an additional issue around handling txs [was noticed](https://github.com/ethereum/go-ethereum/pull/29657#issuecomment-2196832615). It's possible for a `newTxs` event to have more txs than can be included in a single block. Because we only called `Commit` once, these txs would be left dangling in the pool. This PR also fixes this issue by calling `txpool.Sync()` to ensure the reorg has happened to account for the recently produced block, followed by `txpool.Stats()` to check if there are any remaining executable txs.

There is a concern here is that the relationship between the miner determining if the pending txs can be included and the result of `txpool.Stats()` is sort of weak. It's possible that if those get out-of-whack the simulated beacon api could go into an infinite loop of block production. Since the miner only checks if txs can 1) pay the appropriate miner tip, 2) afford the base fee, and 3) fit within the gas limit. Currently I can't see how this would happen unless maybe a local tx submits a base below the theoretical floor (7 wei). Open to suggestions on improving that.

The PR #30104 did not have this issue, because it would build blocks until it got an empty block. Originally I felt this was rather crude and polluted the separation of `sealBlock` with the concept of `allowEmpty`. It still feels hacky to me, but given the complexity of the subsystems (miner, txpool, sim), it may actually be the cleanest way to ensure we get the desired outcome. One scenario the current PR can handle that #30104 cannot though is if there are pending txs which cannot pay the base fee due to a previous iteration pushing the base fee too high. Th

--

I also tacked on a commit to move the call for `txpool.Sync()` out of `forkchoiceUpdated` and into the simulated beacon. @karalabe originally added it into fcu, would be curious to know if there was a reason for adding there versus in the simulator. By adding it to the simulator we can simplify the parameters for `forkchoiceUpdated` slightly.

If it seems better to go down the path set by #30104 I can adjust this PR to just check the resulting block's tx count and stop the loop once it receives an empty block. I still think there are some worth while renamings / improvements in this PR.

### CODE REVIEW

File: eth/catalyst/simulated_beacon.go [hunk 1]
```diff
@@ -41,36 +43,47 @@ const devEpochLength = 32
...
+
 // add queues a withdrawal for future inclusion.
-func (w *withdrawalQueue) add(withdrawal *types.Withdrawal) error {
-	select {
-	case w.pending <- withdrawal:
-		break
-	default:
-		return errors.New("withdrawal queue full")
-	}
+func (w *withdrawalQueue) Add(withdrawal *types.Withdrawal) error {
```
Comment (rjl493456442) [inline eth/catalyst/simulated_beacon.go:55]: the `withdrawalalQueue` is only used inside of the package, please convert the function to private one.

File: eth/catalyst/simulated_beacon.go [hunk 2]
```diff
@@ -41,36 +43,47 @@ const devEpochLength = 32
...
-			withdrawals = append(withdrawals, withdrawal)
-			if len(withdrawals) == maxCount {
-				return withdrawals
-			}
-		default:
-			return withdrawals
-		}
-	}
+// pop dequeues the specified number of withdrawals from the queue.
+func (w *withdrawalQueue) Pop(count int) types.Withdrawals {
```
Comment (rjl493456442) [inline eth/catalyst/simulated_beacon.go:66]: the withdrawalalQueue is only used inside of the package, please convert the function to private one.

File: eth/catalyst/simulated_beacon.go [hunk 3]
```diff
@@ -41,36 +43,47 @@ const devEpochLength = 32
...
+	count = min(count, len(w.pending))
+	popped := w.pending[0:count]
+	w.pending = w.pending[count:]
+
+	return popped
+}
+
+// subscribe allows a listener to be updated when new withdrawals are added to
+// the queue.
+func (w *withdrawalQueue) Subscribe(ch chan<- newWithdrawalsEvent) event.Subscription {
```
Comment (rjl493456442) [inline eth/catalyst/simulated_beacon.go:79]: the withdrawalalQueue is only used inside of the package, please convert the function to private one.

File: eth/catalyst/simulated_beacon_api.go [hunk 4]
```diff
@@ -18,44 +18,77 @@ package catalyst
...
+	for {
+		select {
+		case <-a.sim.shutdownCh:
+			return
+		case <-a.doCommit:
 			a.sim.Commit()
+			a.sim.eth.TxPool().Sync()
+			executable, _ := a.sim.eth.TxPool().Stats()
+			if executable != 0 {
+				a.commit()
```
Comment (rjl493456442) [inline eth/catalyst/simulated_beacon_api.go:80]: This commit operation will always be ignored, as the channel receiver is still occupied.

You can convert the `doCommit` channel to 1-size channel

Comment (rjl493456442) [reply eth/catalyst/simulated_beacon_api.go:80]: EDIT: Ah, you did allocate a 1-size channel, nitpick, can we relocate the `simulatedBeaconAPI` constructor in this file? It's a bit easier to review/read

File: eth/catalyst/simulated_beacon.go [hunk 5]
```diff
@@ -301,12 +319,14 @@ func (c *SimulatedBeacon) AdjustTime(adjustment time.Duration) error {
...
-	withdrawals := c.withdrawals.gatherPending(10)
+	withdrawals := c.withdrawals.Pop(10)
 	return c.sealBlock(withdrawals, parent.Time+uint64(adjustment/time.Second))
 }
 
+// RegisterSimulatedBeaconAPIs registers the simulated beacon's API with the
+// stack.
 func RegisterSimulatedBeaconAPIs(stack *node.Node, sim *SimulatedBeacon) {
-	api := &api{sim}
+	api := &simulatedBeaconAPI{sim: sim, doCommit: make(chan struct{}, 1)}
```
Comment (rjl493456442) [inline eth/catalyst/simulated_beacon.go:329]: Please relocate the simulated beacon api constructor to its own file

e.g.

```diff
func RegisterSimulatedBeaconAPIs(stack *node.Node, sim *SimulatedBeacon) {
-       api := &simulatedBeaconAPI{sim: sim, doCommit: make(chan struct{}, 1)}
-       if sim.period == 0 {
-               // mine on demand if period is set to 0
-               go api.loop()
-       }
        stack.RegisterAPIs([]rpc.API{
                {
                        Namespace: "dev",
-                       Service:   api,
+                       Service:   newSimulatedBeaconAPI(sim),
                        Version:   "1.0",
                },
        })
diff --git a/eth/catalyst/simulated_beacon_api.go b/eth/catalyst/simulated_beacon_api.go
index b26316f858..e98c14afca 100644
--- a/eth/catalyst/simulated_beacon_api.go
+++ b/eth/catalyst/simulated_beacon_api.go
@@ -30,6 +30,19 @@ type simulatedBeaconAPI struct {
        doCommit chan struct{}
 }
 
+// newSimulatedBeaconAPI initializes the simulated beacon api.
+func newSimulatedBeaconAPI(sim *SimulatedBeacon) *simulatedBeaconAPI {
+       api := &simulatedBeaconAPI{
+               sim:      sim,
+               doCommit: make(chan struct{}, 1),
+       }
+       if sim.period == 0 {
+               // mine on demand if period is set to 0
+               go api.loop()
+       }
+       return api

```

**Review by rjl493456442 — APPROVED** [review]
nitpicks, otherwise sgtm!

File: eth/catalyst/simulated_beacon.go [hunk 6]
```diff
@@ -156,6 +164,16 @@ func (c *SimulatedBeacon) sealBlock(withdrawals []*types.Withdrawal, timestamp u
 		c.setCurrentState(header.Hash(), *finalizedHash)
 	}
 
+	// Because transaction insertion, block insertion and block production will
+	// happen without any timing delay between them in simulator mode and the
+	// transaction pool will be running its internal reset operation on a
+	// background thread, flaky executions can happen. To avoid the racey
+	// behavior, the pool will be explicitly blocked on its reset before
+	// continuing to the block production below.
+	if err := c.eth.APIBackend.TxPool().Sync(); err != nil {
```
Comment (jwasinger) [inline eth/catalyst/simulated_beacon.go:173]: I don't think we need a manual call to `Sync()` here.   When we are running in non-zero period dev mode, any includeable transactions that weren't picked up will be caught when sealing a subsequent block.

Comment (jwasinger) [reply eth/catalyst/simulated_beacon.go:173]: Oh right.  This is for tests.

File: eth/catalyst/simulated_beacon.go (hunk 1 above)
Comment (lightclient) [reply eth/catalyst/simulated_beacon.go:55]: good point, updated

File: eth/catalyst/simulated_beacon.go (hunk 5 above)
Comment (lightclient) [reply eth/catalyst/simulated_beacon.go:329]: done

**Comment by lightclient** [comment]
PR feedback addressed, PTAL @rjl493456442.

**Review by rjl493456442 — APPROVED** [review]
sgtm

File: eth/catalyst/simulated_beacon.go [hunk 7]
```diff
@@ -41,36 +43,47 @@ const devEpochLength = 32
...
-	case w.pending <- withdrawal:
-		break
-	default:
-		return errors.New("withdrawal queue full")
-	}
+	w.mu.Lock()
+	defer w.mu.Unlock()
+
+	w.pending = append(w.pending, withdrawal)
+	w.feed.Send(newWithdrawalsEvent{types.Withdrawals{withdrawal}})
```
Comment (holiman) [inline eth/catalyst/simulated_beacon.go:60]: Is it a requirement that the `Send` happens inside the mutex? Otherwise that would typically be good to not have inside the mutex-area

File: eth/catalyst/simulated_beacon_api.go [hunk 8]
```diff
@@ -18,44 +18,89 @@ package catalyst
...
+func (a *simulatedBeaconAPI) commit() {
+	select {
+	case a.doCommit <- struct{}{}:
+	default:
+	}
+}
+
+// worker runs in the background and signals to the simulator when to commit
+// based on messages over doCommit.
+func (a *simulatedBeaconAPI) worker() {
```
Comment (holiman) [inline eth/catalyst/simulated_beacon_api.go:82]: I have a feeling that both `commit()` and `worker()` doesn't make a lot of sense, other than in the context of `loop()`. And that _maybe_, they should just be closures inside `loop()`? OTOH maybe that just makes things convoluted. 
I'll let you decide

**Review by holiman — APPROVED** [review]
LGTM

File: eth/catalyst/simulated_beacon_api.go (hunk 8 above)
Comment (holiman) [reply eth/catalyst/simulated_beacon_api.go]: I pushed this change. IMO it makes more sense to keep it together, also makes it possible to range over the `doCommit`, since we "own it" inside the `loop`, and are at liberty to close it on exit

File: eth/catalyst/simulated_beacon_api.go [hunk 9]
```diff
@@ -18,44 +18,82 @@ package catalyst
...
+	// based on messages over doCommit.
+	go func() {
+		for _ = range doCommit {
+			a.sim.Commit()
+			a.sim.eth.TxPool().Sync()
+			executable, _ := a.sim.eth.TxPool().Stats()
+			if executable != 0 {
+				commit()
+			}
+		}
```
Comment (holiman) [inline eth/catalyst/simulated_beacon_api.go:75]: I don't love this loop. It is un-untuitively recursive, passing a struct over the chan that we're iterating on. It works due to chan buffering and non-blocking send, but can't we just do something more obvious, like for example: 

```golang
		for _ = range doCommit {
			a.sim.Commit()
			a.sim.eth.TxPool().Sync()
			for {
				a.sim.Commit()
				if executable, _ := a.sim.eth.TxPool().Stats(); executable == 0 {
					break
				}
			}
		}
```
This is _nearly_ the same, but not quite: it avoids sending on the channel we're iterating on, but OTOH we won'd notice if the channel becomes closed. 

In both cases, if for some reason we have an executable transaction which is never included in a block, this PR will spinloop here. 

And yeah, the code I pushed here is a bit unsafe: I close the `doCommit` in the outer loop, on exit, but the current code sends on it. So possibly send-on-closed crash here (my bad!).

Comment (holiman) [reply eth/catalyst/simulated_beacon_api.go]: Ok, removed the recursion and the spin-looping, and the "send on closed". Now it does max one extra Commit on each loop, but not indefinite.

File: eth/catalyst/simulated_beacon.go (hunk 7 above)
Comment (lightclient) [reply eth/catalyst/simulated_beacon.go:60]: Ah you're right, no need for that to be in mutex.

File: eth/catalyst/simulated_beacon_api.go (hunk 9 above)
Comment (lightclient) [reply eth/catalyst/simulated_beacon_api.go]: Hmm the problem is that doing one extra commit per loop doesn't really fix the issue when the pending txs cannot be included over two blocks? It's an improvement over 1, but it can still leave txs in the pool.

Comment (holiman) [reply eth/catalyst/simulated_beacon_api.go]: Yeah you were right, I had to change that

Comment (lightclient) [reply eth/catalyst/simulated_beacon_api.go]: The inner loop does make things much clearer though.

File: eth/catalyst/simulated_beacon_api.go (hunk 8 above)
Comment (lightclient) [reply eth/catalyst/simulated_beacon_api.go]: it looks good inside the loop 👍

**Comment by lightclient** [comment]
Added a comment about potential spin loop. LGTM though.

**Review by gballet — APPROVED** [review]
