### PR TITLE
tests/fuzzers: supply gnark multiexp config, fixes #26669

### LINKED ISSUE #26669: fuzzing build faliure
https://oss-fuzz-build-logs.storage.googleapis.com/log-2b2be386-7e9d-4a34-a839-7ec37794b7f9.txt

```
Step #3 - "compile-libfuzzer-address-x86_64": Building fuzz_g1_add
Step #3 - "compile-libfuzzer-address-x86_64": + [[ address = *coverage* ]]
Step #3 - "compile-libfuzzer-address-x86_64": + cd /root/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/bls12381
Step #3 - "compile-libfuzzer-address-x86_64": + go-fuzz -func FuzzG1Add -o /work/fuzz_g1_add.a .
Step #3 - "compile-libfuzzer-address-x86_64": # github.com/ethereum/go-ethereum/tests/fuzzers/bls12381
Step #3 - "compile-libfuzzer-address-x86_64": ./bls12381_fuzz.go:201:42: gnarkScalar.SetBigInt(s).FromMont undefined (type *fr.Element has no field or method FromMont)
Step #3 - "compile-libfuzzer-address-x86_64": ./bls12381_fuzz.go:220:27: not enough arguments in call to cp.MultiExp
Step #3 - "compile-libfuzzer-address-x86_64": 	have ([]"github.com/consensys/gnark-crypto/ecc/bls12-381".G1Affine, []fr.Element)
Step #3 - "compile-libfuzzer-address-x86_64": 	want ([]"github.com/consensys/gnark-crypto/ecc/bls12-381".G1Affine, []fr.Element, ecc.MultiExpConfig)
Step #3 - "compile-libfuzzer-address-x86_64": 2023/02/11 06:11:04 failed to build packages:exit status 2
Step #3 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Step #
```
Most likely fallout from https://github.com/ethereum/go-ethereum/pull/26545

### PR DESCRIPTION
**Pull request by holiman**
I _think_ this fixes https://github.com/ethereum/go-ethereum/issues/26669 . There may be other issues too, related to `blst`, but we can tackle that later in that case.

### CODE REVIEW

**Comment by holiman** [comment]
Needs some more work 
```
[user@work bls12381]$ go-fuzz-build . 
/home/user/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/bls12381/bls12381_fuzz.go:202:42: gnarkScalar.SetBigInt(s).FromMont undefined (type *fr.Element has no field or method FromMont)
typechecking of . failed

```
Due to https://github.com/ConsenSys/gnark-crypto/pull/288 , discussion https://github.com/ConsenSys/gnark-crypto/issues/276

**Comment by alokeutpal** [comment]
Thanks

**Comment by holiman** [comment]
@alokeutpal please stop spamming

**Comment by holiman** [comment]
Ok, according to Kev the `FromMont` can probably just be removed. Trying that now.

**Comment by kevaundray** [comment]
For reference; the new gnark external API does not reveal the fact that internally we are using montgomery form, so one no longer needs to call `.FromMont` or `.ToMont`.

This change makes the API easier to use because when you create a field, you use "Normal Form" and when you return a Big.Int from a field, you can only get back "Normal form"

File: tests/fuzzers/bls12381/bls12381_fuzz.go [hunk 1]
```diff
@@ -217,7 +218,7 @@ func FuzzCrossG1MultiExp(data []byte) int {
 
 	// gnark multi exp
 	cp := new(gnark.G1Affine)
-	cp.MultiExp(gnarkPoints, gnarkScalars)
+	cp.MultiExp(gnarkPoints, gnarkScalars, ecc.MultiExpConfig{NbTasks: 1})
```
Comment (kevaundray) [inline tests/fuzzers/bls12381/bls12381_fuzz.go:221]: Not important as this is for fuzzing, though note that if this is set to 0, then it will use all of the available CPUs: https://github.com/ConsenSys/gnark-crypto/blob/1a7a29904a7c29ba3e1c644d9752765b6ae9775e/ecc/bls12-381/multiexp.go#L78

Comment (holiman) [reply tests/fuzzers/bls12381/bls12381_fuzz.go:221]: Yeah, I know. I set it to `0` since I suspect that the fuzz-framework already uses as many cores as are available.

Comment (holiman) [reply tests/fuzzers/bls12381/bls12381_fuzz.go:221]: hm, actually, you're right. let's leave it at default
```suggestion
	cp.MultiExp(gnarkPoints, gnarkScalars, ecc.MultiExpConfig{})
```
