### PR TITLE
eth: better active protocol handler tracking

### LINKED ISSUE #27509: Close Geth but got panic: sync: WaitGroup is reused before previous Wait has returned
I am running a full node. Today I just restart my geth and got this problem and my state snapshot is broken. I did not forcibly close the geth process, just use `kill geth's pid`  I post the log below

#### System information

Geth version: `1.11.6`
CL client & version: prysm@v4.0.6
OS & Version: Linux
Commit hash : (if `develop`) release version

#### Expected behaviour
Close without panic or at least the data should not broken.

#### Actual behaviour
got panic 'panic: sync: WaitGroup is reused before previous Wait has returned' 

#### Logs:

'INFO [06-19|09:59:48.583] Imported new potential chain segment     number=17,510,679 hash=6e295c..ed8098 blocks=1  txs=93   mgas=7.559   elapsed=63.471ms    mgasps=119.091 dirty=228.54MiB'
'INFO [06-19|09:59:48.626] Chain head was updated                   number=17,510,679 hash=6e295c..ed8098 root=b2514d..c946ad elapsed=1.51769ms'
'INFO [06-19|10:00:00.371] Imported new potential chain segment     number=17,510,680 hash=64359b..3b02ba blocks=1  txs=99   mgas=7.256   elapsed=106.217ms   mgasps=68.311  dirty=228.37MiB'
'INFO [06-19|10:00:00.413] Chain head was updated                   number=17,510,680 hash=64359b..3b02ba root=67e807..962bd7 elapsed=1.546763ms'
'INFO [06-19|10:00:01.371] Got interrupt, shutting down... '
'INFO [06-19|10:00:01.375] HTTP server stopped                      endpoint=192.168.0.142:8545'
'INFO [06-19|10:00:01.375] HTTP server stopped                      endpoint=192.168.0.142:8546'
'INFO [06-19|10:00:02.964] HTTP server stopped                      endpoint=127.0.0.1:8551'
'INFO [06-19|10:00:02.964] IPC endpoint closed                      url=/workdir/execution/geth.ipc'
panic: sync: WaitGroup is reused before previous Wait has returned'
''
'goroutine 415923 [running]:'
'sync.(*WaitGroup).Wait(0xc000618bc0?)'
'        sync/waitgroup.go:118 +0x7f'
'github.com/ethereum/go-ethereum/eth.(*handler).Stop(0xc00fadc000)'
'        github.com/ethereum/go-ethereum/eth/handler.go:575 +0x8b'
'github.com/ethereum/go-ethereum/eth.(*Ethereum).Stop(0xc000620400)'
'        github.com/ethereum/go-ethereum/eth/backend.go:527 +0x50'
'github.com/ethereum/go-ethereum/node.(*Node).stopServices(0xc0001f4b60, {0xc000093a80, 0x1, 0x0?})'
'        github.com/ethereum/go-ethereum/node/node.go:298 +0xbd'
'github.com/ethereum/go-ethereum/node.(*Node).Close(0xc0001f4b60)'
'        github.com/ethereum/go-ethereum/node/node.go:218 +0x18e'
'created by github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1.1'
'        github.com/ethereum/go-ethereum/cmd/utils/cmd.go:92 +0x96'

### PR DESCRIPTION
**Pull request by lightclient**
fixes #27509

Wasn't able to reproduce the original race condition, but this does remove the `WaitGroup`, so it should suffice.

The idea here is to use two unbuffered channels to track active protocol handlers. `handlerStartCh` is called when a new protocol handler is started up, as long as we aren't actively quitting. When the handler closes, it writes to `handlerDoneCh`.

A separate goroutine watches theses channels and converts the writes into an integer tracking the total number of active routines. When quit is initiated, it waits until the active count goes down to zero before exiting, thus releasing the overarching `handler.wg`.

### CODE REVIEW

**Comment by fjl** [comment]
Might be easier to do this with a buffered channel.

**Comment by lightclient** [comment]
As mentioned offline, I looked into using a buffered channel, but wasn't sure how to correctly size it. The `maxPeers` value isn't known until after `handler` is started, plus it is not a true upper bound. Trusted peers can cause peer count to go over `maxPeers`. For this reason, I attempted to use unbuffered channels.

I also considered creating a map of channels where each entry corresponded to an active handler. I wasn't sure what to use as the key though, because right now the protocol handlers themselves check later on if they are already connected. So at the time that the handler is registered as "active" it's possible that there would already be a peer there. So changing where we check for already registered peers would be a bigger refactor.

File: eth/handler.go [hunk 1]
```diff
@@ -288,22 +292,69 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+// quitting.
+func (h *handler) incHandlers() bool {
+	select {
+	case <-h.quitSync:
+		return false
+	default:
+		h.handlerStartCh <- struct{}{}
+		return true
+	}
+}
```
Comment (holiman) [inline eth/handler.go:336]: The logics here are a bit devious. So this first checks if quitsync is happening. If not, it waits, blockingly, to send something on `handlerStartCh`. 
I'm suspecting that there's a potential deadlock here...? But I'm not sure, I don't have the full picture of the statemachine internalized

Comment (holiman) [reply eth/handler.go:336]: A more 'typical' switch wold be something like this
```
select { 
  case <- h.quitSync: 
       return false
   case h.handlerStartCh <- struct{}{}:
       return true
  } 
```

Comment (lightclient) [reply eth/handler.go:336]: Basically it is verifying that we aren't actively quitting. This is the logic in [handlePeerEvent`](https://github.com/ethereum/go-ethereum/blob/c2db667c8f824ec0d025cbde95e6aaad67fc10ba/eth/sync.go#L92-L99) which was previously at the beginning of the `runXXXXPeer`.

I guess the situation I'm not super sure about is say we get to line 333 here and then somehow the runtime decides to pause the thread long enough so that `protoTracker` is torn down completely, then it resumes at 333 and there is nothing listening to the channel anymore and it blocks forever.

Comment (lightclient) [reply eth/handler.go:336]: Ah okay I see, that makes more sense without the default.

Comment (holiman) [reply eth/handler.go]: > I guess the situation ...

Yeah it was exactly that which I meant

File: eth/handler.go [hunk 2]
```diff
@@ -288,22 +292,68 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+	var (
+		active int
+		done   = make(chan struct{})
+	)
+	// Start goroutine to track active protocol handlers.
+	go func() {
+		for {
+			select {
+			case <-h.handlerStartCh:
+				active--
```
Comment (holiman) [inline eth/handler.go:307]: This probably works fine, but it's a bit funny, you are counting on the negative side of the x-axis :)

File: eth/handler.go [hunk 3]
```diff
@@ -288,22 +292,68 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+		}
+	}()
+	<-h.quitSync
+
+	// After quit is initiated, poll until all handlers are closed.
+	for range time.Tick(time.Millisecond * 50) {
+		if active == 0 {
+			break
+		}
+	}
```
Comment (holiman) [inline eth/handler.go:322]: This is one way to do it, sure. Another way is to use a `sync.Cond`, this snippet would just `Wait()` on the cond, and the loop above would Signal or Broadcast on it.

File: eth/handler.go (hunk 2 above)
Comment (lightclient) [reply eth/handler.go]: Heh oops - fixed now

Comment (holiman) [reply eth/handler.go]: Oh, another thing though, this is "probably fine" but strictly speaking, this is racy. You are accessing `active` from two different go-routines simultaneously, which is a no-no. So either use an atomic int, or use an int, but make it scoped inside this goroutine, and let the outer checker wait on a Cond instead.

File: eth/handler.go (hunk 3 above)
Comment (lightclient) [reply eth/handler.go]: I tried a bit with `sync.Cond` but it seemed like a lot of overhead and `sync.WaitGroup` seems more straightforward. I have never actually successfully pulled off a `sync.Cond` though so it's possibly simpler still than what I came up with.

File: eth/handler.go [hunk 4]
```diff
@@ -288,22 +292,74 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+	wg.Add(1)
+	go func() {
+		for {
+			select {
+			case <-h.handlerStartCh:
+				active++
+			case <-h.handlerDoneCh:
+				active--
+			case <-done:
+				quitting = true
```
Comment (holiman) [inline eth/handler.go:314]: I don't see why you are using a `done` chan, instead of just using `h.quitSync` here?

File: eth/handler.go [hunk 5]
```diff
@@ -288,22 +292,74 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+			}
+			// Only check if active is 0 after quitSync has been
+			// closed. This ensures that in case active drops to 0
+			// naturally, this tracker routine stays operational.
+			if quitting && active == 0 {
+				wg.Done()
+				return
+			}
```
Comment (holiman) [inline eth/handler.go:322]: One thing which I think is a problem is that even after quitting has been signalled, you still permit new handlers to be added. IMO you should do something like this
```golang
			select {
			case <-h.handlerStartCh:
				active++
			case <-h.handlerDoneCh:
				active--
			case <-h.quitSync:
				quitting = true
			}
			if quitting { 
				for active > 0 {
					<- handlerDoneCh
					active--
				}
				wg.Done()
				return
		        }
```
(maybe inline the quitting-thing and skip the `quitting` bool)

File: eth/handler.go [hunk 6]
```diff
@@ -288,22 +292,74 @@ func newHandler(config *handlerConfig) (*handler, error) {
...
+
+// incHandlers signals to increment the number of active handlers if not
+// quitting.
+func (h *handler) incHandlers() bool {
+	select {
+	case h.handlerStartCh <- struct{}{}:
+		return true
+	case <-h.quitSync:
+		return false
+	}
```
Comment (holiman) [inline eth/handler.go:340]: See my comment above. I am not sure that it's guaranteed that it uses the quitSync branch just because it's available. We want to make it so that as soon as quitSync is closed, it must only use the `return false` branch

File: eth/handler.go (hunk 5 above)
Comment (holiman) [reply eth/handler.go:322]: Oh, and if you do this, you can skip a layer of `go func`. So no need to spin off a new goroutine, if you use `quitSync` instead of the dance with the `done`. But maybe I'm missing something there (?)

File: eth/handler.go (hunk 4 above)
Comment (lightclient) [reply eth/handler.go:314]: It seemed less racy to use `done` here. The scenario I was imagining is say `h.quitSync` is closed while another routine is in the process of writing to `h.handlerStartCh`. Since there is nothing reading that channel anymore, it will sit there blocking and never close.

I wrote it in the way it is so that the select is always able to unblock any channel neccessary. Between closing `h.quitSync` and calling `peerset.close()`, the handlers _should_ be in the process of closing, even if some last minute handlers end up being registered as active.

File: eth/handler.go (hunk 6 above)
Comment (lightclient) [reply eth/handler.go:340]: I was following this pattern: https://github.com/ethereum/go-ethereum/blob/c2db667c8f824ec0d025cbde95e6aaad67fc10ba/eth/sync.go#L92-L99

If we want to ensure false is _always_ returned, would something like this work?

```suggestion
        select {
        case <-h.quitSync:
                return false
        default:
        }
	select {
	case h.handlerStartCh <- struct{}{}:
		return true
	case <-h.quitSync:
		return false
	}
```

File: eth/handler.go (hunk 4 above)
Comment (lightclient) [reply eth/handler.go:314]: actually maybe that scenario isn't possible - once select chooses a branch is it guaranteed to complete uninterrupted?

**Comment by holiman** [comment]
The select either succeeds or not. It doesn't half-suceed and get stuck, no.

**Comment by lightclient** [comment]
This should be ready for review again. PTAL!

**Review by holiman — APPROVED** [review]
LGTM
