### PR TITLE
core: added future proc mutex lock

### LINKED ISSUE #2305: Geth crash during synchronization
Geth crash during synchronization.
Geth/v1.3.5/linux/go1.5.1
The whole error report here http://pastebin.com/YyUExG81

### PR DESCRIPTION
**Pull request by obscuren**
Added a future lock which prevents the anything being added or removed
from or to the set when looping over the set of blocks. This fixes a nil
pointer in the range loop when trying to retrieve a block from the set
which was previously available but removed due to regular chain
processing.

Fixes #2305

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Mar 8 15:00:01 UTC 2016_

**Comment by zsfelfoldi** [comment]
:+1:

File: core/blockchain.go [hunk 1]
```diff
@@ -99,15 +99,16 @@ type BlockChain struct {
...
 	// procInterrupt must be atomically called
-	procInterrupt int32 // interrupt signaler for block processing
-	wg            sync.WaitGroup
+	procInterrupt int32          // interrupt signaler for block processing
+	wg            sync.WaitGroup // chain processing wait group for shutting down
 
 	pow       pow.PoW
-	processor Processor
-	validator Validator
+	rand      *mrand.Rand
```
Comment (karalabe) [inline core/blockchain.go]: I think this is a merge anomaly since @zsfelfoldi moved the rand into the header chain.

File: core/blockchain.go [hunk 2]
```diff
@@ -857,6 +867,9 @@ func (self *BlockChain) InsertChain(chain types.Blocks) (int, error) {
 				continue
 			}
 
+			self.futureMu.Lock()
+			defer self.futureMu.Unlock()
```
Comment (karalabe) [inline core/blockchain.go]: This is inside a for loop. It can go very wrong if you get two errors as it will deadlock the entire system.

File: core/blockchain.go (hunk 1 above)
Comment (obscuren) [inline core/blockchain.go]: Must be. I didn't add it. Thanks

File: core/blockchain.go (hunk 2 above)
Comment (karalabe) [inline core/blockchain.go]: http://play.golang.org/p/r9WZP80uty :)

Comment (obscuren) [inline core/blockchain.go]: Ouch. Nothing inherently wrong locking within the loop though. It's the unlocking which is problematic.

**Comment by obscuren** [comment]
@karalabe the fact that the cache is thread safe for read / write doesn't matter. The problem is that `range Keys()` returns an array of keys. During that time there's a possibility of a key being deleted in the meantime resulting in a `Get` returning `nil`.

**Comment by obscuren** [comment]
I understand that the issue can be solved without a mutex (and perhaps is the better solution) BTW.

**Comment by karalabe** [comment]
LGTM apart from `rand` :P 

The reason I suggested this approach is because it's much less invasive on the code in general and we don't need to keep in mind yet another sync construct in core :)

**Comment by obscuren** [comment]
@karalabe I fully agree.

**Comment by obscuren** [comment]
`rand` removed

**Comment by karalabe** [comment]
LGTM :+1:
