### PR TITLE
[website] fix: colorMode flashing

### LINKED ISSUE #26422: [website] Flick to light mode when open a search'ed page
When I do a search in dark mode and click on a search result the UI goes to light mode really quickly and back to dark mode again.

this causes the sense of a Flickr screen

https://user-images.githubusercontent.com/1120748/208495135-168983ce-7854-46cb-b553-5f524e3c22d9.mov

### PR DESCRIPTION
**Pull request by nhsz**
This PR fixes #26422

### CODE REVIEW

File: src/pages/_app.tsx [hunk 1]
```diff
@@ -20,7 +20,9 @@ export default function App({ Component, pageProps }: AppProps) {
   }, []);
 
   return (
-    <ChakraProvider theme={theme}>
+    // `colorModeManager` added to fix flashing issue
+    // See: https://chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr
+    <ChakraProvider theme={theme} colorModeManager={localStorageManager}>
```
Comment (wackerow) [inline src/pages/_app.tsx:25]: Ah, right! Thanks for fixing this, sorry I missed it during dark mode implementation.

**Review by wackerow — APPROVED** [review]
Looks great! Thanks @nhsz!
