### PR TITLE
internal, accounts: fix funding check when estimate gas

### LINKED ISSUE #21311: eth_estimateGas command with gasPrice param always returns "gas required exceeds allowance (0)"
#### System information

Geth/v1.9.15-stable-0f77f34b/linux-amd64/go1.14.4

#### Expected behaviour

`eth_estimateGas` on an ERC-20 `transfer` call should accepts the parameter `gasPrice` as the actual call does 

#### Actual behaviour

Every time `eth_estimateGas` is called with `gasPrice`, `{"code":-32000,"message":"gas required exceeds allowance (0)"}` is answered

#### Steps to reproduce the behaviour

1. Trying on `geth`:
- with `gasPrice`:
```
$ curl -X POST -H "Content-Type: application/json"  --data "{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0xfa43b7400\",\"from\":\"0xc9f51aaf29433a2a916aa5fa704ef192db0d0d2d\",\"to\":\"0x38c87aa89b2b8cd9b95b736e1fa7b612ea972169\",\"data\":\"0xa9059cbb0000000000000000000000001bff412b4dcacc0bf61b9f18f8cfd45607a5a89300000000000000000000000000000000000000000000000000001b48eb57e000\"}],\"id\":45,\"jsonrpc\":\"2.0\"}" http://GETH_SERVER
{"jsonrpc":"2.0","id":45,"error":{"code":-32000,"message":"gas required exceeds allowance (0)"}}
```
- without `gasPrice`:
```
$ curl -X POST -H "Content-Type: application/json"  --data "{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0xc9f51aaf29433a2a916aa5fa704ef192db0d0d2d\",\"to\":\"0x38c87aa89b2b8cd9b95b736e1fa7b612ea972169\",\"data\":\"0xa9059cbb0000000000000000000000001bff412b4dcacc0bf61b9f18f8cfd45607a5a89300000000000000000000000000000000000000000000000000001b48eb57e000\"}],\"id\":45,\"jsonrpc\":\"2.0\"}" http://GETH_SERVER
{"jsonrpc":"2.0","id":45,"result":"0xa78c"}
```

2. Trying on `parity`:
- works with `gasPrice`:
```
curl -X POST -H "Content-Type: application/json"  --data "{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0xfa43b7400\",\"from\":\"0xc9f51aaf29433a2a916aa5fa704ef192db0d0d2d\",\"to\":\"0x38c87aa89b2b8cd9b95b736e1fa7b612ea972169\",\"data\":\"0xa9059cbb0000000000000000000000001bff412b4dcacc0bf61b9f18f8cfd45607a5a89300000000000000000000000000000000000000000000000000001b48eb57e000\"}],\"id\":45,\"jsonrpc\":\"2.0\"}" http://PARITY_SERVER
{"jsonrpc":"2.0","result":"0x5a58","id":45}
```

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #21311

### CODE REVIEW

File: accounts/abi/bind/backends/simulated.go [hunk 1]
```diff
@@ -448,7 +448,7 @@ func (b *SimulatedBackend) EstimateGas(ctx context.Context, call ethereum.CallMs
 		hi = b.pendingBlock.GasLimit()
 	}
 	// Recap the highest gas allowance with account's balance.
-	if call.GasPrice != nil && call.GasPrice.Uint64() != 0 {
+	if call.GasPrice != nil && call.GasPrice.Cmp(big.NewInt(0)) != 0 {
```
Comment (karalabe) [inline accounts/abi/bind/backends/simulated.go:451]: Shouldn't we use `BitLen() > 0`?

Comment (MariusVanDerWijden) [reply accounts/abi/bind/backends/simulated.go]: Yep, its ~30% faster
```
BenchmarkBigCmp2-16    	20199627	        58.5 ns/op	       7 B/op	       0 allocs/op
BenchmarkBigCmp-16    	49185616	        36.2 ns/op	       7 B/op	       0 allocs/op
```

```go
func BenchmarkBigCmp(b *testing.B) {
	t := 0
	for i := 0; i < b.N; i++ {
		a := big.NewInt(int64(i % 1000))
		if a.BitLen() == 0 {
			t++
		}
	}
}

func BenchmarkBigCmp2(b *testing.B) {
	t := 0
	for i := 0; i < b.N; i++ {
		a := big.NewInt(int64(i % 1000))
		if a.Cmp(big.NewInt(0)) == 0 {
			t++
		}
	}
}
```
