### PR TITLE
eth/tracers: apply block header overrides correctly

### LINKED ISSUE #32175: tracing via debug_traceCall with blockOverrides causes a previous block hash of 0
#### System information

Geth version: v1.16.1
CL client & version: n/a
OS & Version: osx

#### Expected behaviour

the solidity `blockhash(block.number - 1)` will read the latest block hash. i.e. the block overrides are applied to the block context when it's created: `vmctx := core.NewEVMBlockContext(block.Header(), api.chainContext(ctx), nil)`.

#### Actual behaviour

`blockhash(block.number - 1)` returns a blockhash of 0.

#### Steps to reproduce the behaviour

attempt to trace a contract call that uses  `blockhash(block.number - 1)` via `debug_traceCall` when the block number is overridden to pending (latest + 1). `blockhash(block.number - 1)` will always return 0.

this behavior allows malicious contract code to detect that it's running in a simulation.

### PR DESCRIPTION
**Pull request by shazam8253**
Fixes #32175.

This fixes the scenario where the blockhash opcode would return 0x0 during RPC simulations when using BlockOverrides with a future block number. The root cause was that BlockOverrides.Apply() only modified the vm.BlockContext, but GetHashFn() depends on the actual types.Header.Number to resolve valid historical block hashes. This caused a mismatch and resulted in incorrect behavior during trace and call simulations.

**Changes:**
Added a new ApplyHeader method to BlockOverrides, which mutates the *types.Header with overridden fields. Updated the RPC simulation/tracing paths to apply header overrides directly to the Header object before creating the EVM block context. This makes sure that there is consistency between BlockContext.BlockNumber and Header.Number to allow GetHashFn() to function correctly in simulations.

**Tests**
I reproduced the error in a dev chain on geth and ran the updated code against the issue to ensure correctness. 
test
test2
test3

### CODE REVIEW

File: internal/ethapi/override/override.go [hunk 1]
```diff
@@ -171,6 +171,29 @@ func (o *BlockOverrides) Apply(blockCtx *vm.BlockContext) error {
 	return nil
 }
 
+func (o *BlockOverrides) ApplyHeader(h *types.Header) error {
```
Comment (lightclient) [inline internal/ethapi/override/override.go]: this is pretty similar to `MakeHeader`? I think you can reuse that then `Apply` to the new vmcontext based on that header to get the other overrides like `BlobBaseFee`

File: eth/tracers/api.go [hunk 2]
```diff
@@ -953,7 +953,14 @@ func (api *API) TraceCall(ctx context.Context, args ethapi.TransactionArgs, bloc
 	}
 	defer release()
 
-	vmctx := core.NewEVMBlockContext(block.Header(), api.chainContext(ctx), nil)
+	hdr := *block.Header()
```
Comment (lightclient) [inline eth/tracers/api.go]:
```suggestion
	h := *block.Header()
```
the only common abbreviation we use for header is `h`, would avoid non-standard ones like these

**Review by rjl493456442 — APPROVED** [review]
please address the comment from matt, otherwise lgtm

**Comment by shazam8253** [comment]
made the changes matt suggested!

**Comment by rjl493456442** [comment]
@shazam8253 forgot to push the new commit?

**Comment by shazam8253** [comment]
I noticed that the parent hash was not being set. The way we do getHash relies on the parentHash to be cached correctly, so setting the parentHash after doing makeHeader fixes the issue. I have also added a seperate test as well.

File: eth/tracers/api.go [hunk 3]
```diff
@@ -953,7 +953,18 @@ func (api *API) TraceCall(ctx context.Context, args ethapi.TransactionArgs, bloc
 	}
 	defer release()
 
-	vmctx := core.NewEVMBlockContext(block.Header(), api.chainContext(ctx), nil)
+	h := *block.Header()
```
Comment (lightclient) [inline eth/tracers/api.go]: Why does this need to be dereferenced?

File: eth/tracers/api.go [hunk 4]
```diff
@@ -953,7 +953,18 @@ func (api *API) TraceCall(ctx context.Context, args ethapi.TransactionArgs, bloc
...
+
+	if config != nil && config.BlockOverrides != nil {
+		h = *config.BlockOverrides.MakeHeader(block.Header())
+		if h.Number.Uint64() == block.NumberU64()+1 {
+			h.ParentHash = block.Hash()
+		} else if h.Number.Uint64() > block.NumberU64()+1 {
+			h.ParentHash = common.Hash{}
+		}
```
Comment (lightclient) [inline eth/tracers/api.go]: Should this be in `MakeHeader`?

File: eth/tracers/api_test.go [hunk 5]
```diff
@@ -689,6 +689,10 @@ func TestTracingWithOverrides(t *testing.T) {
 		Failed      bool
 		ReturnValue string
 	}
+	overrideBlockNumber := genBlocks + 1
+	parentHash := backend.chain.GetHeaderByNumber(uint64(genBlocks)).Hash().Hex()[2:]
+	expectParent := fmt.Sprintf("0x%064s", parentHash)
```
Comment (lightclient) [inline eth/tracers/api_test.go]: Please remove this and write the test inline -- if every test wrote helpers above the test definitions it would be very cluttered!

File: eth/tracers/api.go (hunk 3 above)
Comment (Krzysztofmaki) [reply eth/tracers/api.go:956]: https://drive.google.com/file/d/1KQg9ZAlUpLdRRA0UDXbtoHis14H8e-Ro/view?usp=drivesdk

File: eth/tracers/api.go (hunk 4 above)
Comment (Krzysztofmaki) [reply eth/tracers/api.go:964]: 0x78346B52a517b496b5Be03a5AD17E57fefE8FB36

**Review by lightclient — APPROVED** [review]
