### PR TITLE
cmd/utils: fix #16006 by not lowering OS ulimit

### LINKED ISSUE #16006: Geth sets limit for open files too low after startup, results in "too many open files"
I guess that might be related to how the file limit is set by this function:
https://github.com/ethereum/go-ethereum/blob/fdb34b7a7c87142cde48a2ec092f77a56d66f773/common/fdlimit/fdlimit_unix.go#L25

Observed behaviour:
=================
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

```
./geth --rpc --rpcport 8102 --rpcaddr 192.168.0.1 --cache=2048 --maxpeers=10
INFO [02-01|09:29:56] Starting peer-to-peer node               instance=Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2
INFO [02-01|09:29:56] Allocated cache and file handles         database=/home/miner/.ethereum/geth/chaindata cache=2048 handles=1024
INFO [02-01|09:29:59] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675
000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
INFO [02-01|09:29:59] Disk storage enabled for ethash caches   dir=/home/miner/.ethereum/geth/ethash count=3
INFO [02-01|09:29:59] Disk storage enabled for ethash DAGs     dir=/home/miner/.ethash               count=2
INFO [02-01|09:29:59] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [02-01|09:29:59] Loaded most recent local header          number=5006992 hash=c37de0…ddc325 td=2303374863991927018140
INFO [02-01|09:29:59] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
INFO [02-01|09:29:59] Loaded most recent local fast block      number=5006744 hash=749e77…bfba64 td=2302708533829412214126
INFO [02-01|09:29:59] Upgrading chain index                    type=bloombits percentage=1
WARN [02-01|09:29:59] Failed to load transaction journal       err="open /home/miner/.ethereum/geth/transactions.rlp: too many open files"
WARN [02-01|09:29:59] Failed to rotate transaction journal     err="open /home/miner/.ethereum/geth/transactions.rlp.new: too many open files"
ERROR[02-01|09:29:59] Section processing failed                type=bloombits error="canonical block #77824 unknown"
INFO [02-01|09:29:59] Starting P2P networking
Fatal: Error starting protocol stack: listen udp :30303: socket: too many open files
```

On a second console I'm polling the ulimits for the geth process with
```cat /proc/$(pidof geth)/limits | grep files```

Directly after the start this reports:
```Max open files            150000               150000               files```

(which is what I configured for my system)

But shortly after that the limits seem to get reduced by the geth process itself to
```Max open files            2048               150000               files```

which then results in the "too many open files" problem.

Workaround:
==========
Running this command continously in a seperate shell during geth startup raises the ulimits back to the intended value fast enough for geth to properly start up and begin syncing
```prlimit -n150000 -p $(pidof geth)```

So far this seems to fix it.

Expected behaviour:
==========
Do not crash with "too many open files" ;)

Proposed fix:
==========
Set the correct max open files from within geth or don't do it at all and let the OS manage it.

Hope that helps someone, that is also struggeling with this problem.
And maybe this is an easy fix for the devs.
Thanks for your time.

### PR DESCRIPTION
**Pull request by holiman**
This PR fixes  #16006 by not lowering `ulimit` in case the OS is already configured with a higher max allowed files than we require. 

I'm _believe_ this is the actual intention of the earlier implementation, based on the documentation of `Raise`:
```
// Raise tries to maximize the file descriptor allowance of this process
// to the maximum hard-limit allowed by the OS.
```

### CODE REVIEW

**Comment by holiman** [comment]
@fjl any comments ?

**Comment by karalabe** [comment]
@fjl So, we're pinging you because the original code did max out the ulimit, and you've told me to lower it back, though I don't remember why :D Do you by any chance?

File: cmd/utils/flags.go [hunk 1]
```diff
@@ -714,13 +714,15 @@ func setIPC(ctx *cli.Context, cfg *node.Config) {
...
 		Fatalf("Failed to retrieve file descriptor allowance: %v", err)
 	}
+	if limit < 2048 {
+		if err := fdlimit.Raise(2048); err != nil {
+			Fatalf("Failed to raise file descriptor allowance: %v", err)
+		}
+	}
 	if limit > 2048 { // cap database file descriptors even if more is available
 		limit = 2048
 	}
```
Comment (karalabe) [inline cmd/utils/flags.go]: We still limit the amount allowed to the database though. Is this still correct?

Comment (holiman) [reply cmd/utils/flags.go]: Yes, this will limit the database to 1024 file handles, regardless of what the OS max is. i figured from the comment that that was the desired behaviour.
