### PR TITLE
eth/filters: fix pending for getLogs

### LINKED ISSUE #24237: eth_getLogs does not work with pending
#### System information

Geth version: `v1.10.15`
OS & Version: Linux

This is kind of a duplicate of [#5359](https://github.com/ethereum/go-ethereum/issues/15359) however, that was automatically closed and was never addressed.

#### Expected behaviour
`eth_getLogs` should work with `"pending"` blocks - according to all available documentation `"pending"` is a valid string for both `fromBlock` and `toBlock`

Both Nethermind and OpenEthereum support "pending" here in accordance with the docs.

#### Actual behaviour
`"pending"` to `"pending"`:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed to get block number from hash"}}
```

That ☝️ is just broken completely

`"latest"` to `"pending"`:
```
{"jsonrpc":"2.0","id":1,"result":[]}
```

That ☝️ always returns an empty array, despite the fact there should be logs (test an OpenEthereum node, it'll return lots of stuff)

#### Steps to reproduce the behaviour
Take the the following `eth_getLogs` command and just modify the `fromBlock` and/or `toBlock`

```
curl -H "Content-Type: application/json" -d '{"method":"eth_getLogs","params":[{"fromBlock":"pending","toBlock":"pending","topics":[["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef","0xc3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62"],["0x0000000000000000000000000000000000000000000000000000000000000000"]]}],"id":1,"jsonrpc":"2.0"}' localhost:8545
```

### PR DESCRIPTION
**Pull request by s1na**
Fixes #24237

### CODE REVIEW

File: eth/filters/filter.go [hunk 1]
```diff
@@ -134,12 +135,12 @@ func (f *Filter) Logs(ctx context.Context) ([]*types.Log, error) {
...
 	head := header.Number.Uint64()
-
-	if f.begin == -1 {
+	pending := f.end == rpc.PendingBlockNumber.Int64()
+	if f.begin == rpc.LatestBlockNumber.Int64() || f.begin == rpc.PendingBlockNumber.Int64() {
 		f.begin = int64(head)
 	}
 	end := uint64(f.end)
-	if f.end == -1 {
+	if f.end == rpc.LatestBlockNumber.Int64() || f.end == rpc.PendingBlockNumber.Int64() {
```
Comment (karalabe) [inline eth/filters/filter.go:143]: These need to be fixed, if I request filtering only the pending block, these clauses will force the latest non-pending block to be also included in the dump.

**Review by holiman — APPROVED** [review]
LGTM
