### PR TITLE
core: fix write concurrency in txpool

### LINKED ISSUE #19834: geth1.9.0 Program interrupt and quit
geth1.9.0 Program interrupt and quit

#### System information

Geth version: `geth 1.9.0`
OS & Version: Linux

Here is the log of the error
````
INFO [07-13|16:17:03.059] Deep froze chain segment                 blocks=5    elapsed=265.285ms number=8051568 hash=a7e330…4987ef
INFO [07-13|16:17:18.231] Imported new chain segment               blocks=1    txs=154  mgas=7.989   elapsed=155.491ms mgasps=51.377  number=8141570 hash=46c5e9…d13fb7 dirty=730.39MiB
INFO [07-13|16:17:35.372] Imported new chain segment               blocks=1    txs=115  mgas=4.992   elapsed=120.554ms mgasps=41.405  number=8141571 hash=da3771…fc50f9 dirty=730.41MiB
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 1604853 [running]:
runtime.throw(0x113251f, 0x15)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc0b1aef600 sp=0xc0b1aef5d0 pc=0x443532
runtime.mapassign(0xfa7e00, 0xc071a583c0, 0xc0b1aef73c, 0x8e66655d)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/map.go:682 +0x5c8 fp=0xc0b1aef688 sp=0xc0b1aef600 pc=0x423dc8
github.com/ethereum/go-ethereum/core/state.(*StateDB).setStateObject(...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:474
github.com/ethereum/go-ethereum/core/state.(*StateDB).getStateObject(0xc0f7791560, 0x7686fef92abcde16, 0x75d1020434344f32, 0x8e66655d, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:469 +0x4f5 fp=0xc0b1aef810 sp=0xc0b1aef688 pc=0x712335
github.com/ethereum/go-ethereum/core/state.(*StateDB).GetNonce(...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/state/statedb.go:232
github.com/ethereum/go-ethereum/core.(*txNoncer).get(0xc0c712d710, 0x7686fef92abcde16, 0x75d1020434344f32, 0x8e66655d, 0xc000020000)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_noncer.go:44 +0x108 fp=0xc0b1aef878 sp=0xc0b1aef810 pc=0x953a08
github.com/ethereum/go-ethereum/core.(*TxPool).Nonce(0xc00000c5a0, 0x7686fef92abcde16, 0x75d1020434344f32, 0x8e66655d, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/tx_pool.go:426 +0x94 fp=0xc0b1aef8b0 sp=0xc0b1aef878 pc=0x9561e4
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).GetPoolNonce(0xc05cd423a0, 0x13c4720, 0xc0dd3477c0, 0x7686fef92abcde16, 0x75d1020434344f32, 0x8e66655d, 0xffc4a0, 0x103ab00, 0xc0dd3477c0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/api_backend.go:188 +0x47 fp=0xc0b1aef8e8 sp=0xc0b1aef8b0 pc=0xc1cdb7
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).GetTransactionCount(0xc05da304e0, 0x13c4720, 0xc0dd3477c0, 0x7686fef92abcde16, 0x75d1020434344f32, 0x8e66655d, 0xfffffffffffffffe, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1151 +0x9d fp=0xc0b1aef970 sp=0xc0b1aef8e8 pc=0xb09ead
runtime.call128(0xc05de1a4b0, 0xc05db44690, 0xc09149d540, 0x3800000050)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/asm_amd64.s:521 +0x52 fp=0xc0b1aefa00 sp=0xc0b1aef970 pc=0x471012
reflect.Value.call(0xc05db02080, 0xc05db44690, 0x13, 0x111f85a, 0x4, 0xc109cf0ba0, 0x4, 0x4, 0xc000071c98, 0x18, ...)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/reflect/value.go:447 +0x461 fp=0xc0b1aefc20 sp=0xc0b1aefa00 pc=0x4a32d1
reflect.Value.Call(0xc05db02080, 0xc05db44690, 0x13, 0xc109cf0ba0, 0x4, 0x4, 0x2, 0x2, 0x0)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/reflect/value.go:308 +0xa4 fp=0xc0b1aefc88 sp=0xc0b1aefc20 pc=0x4a2d54
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc05db7f0e0, 0x13c4720, 0xc0dd3477c0, 0xc01d660480, 0x17, 0xc0bd450660, 0x2, 0x2, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/service.go:209 +0x2a3 fp=0xc0b1aefd68 sp=0xc0b1aefc88 pc=0x8635f3
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc068eb2a20, 0x13c4720, 0xc0dd3477c0, 0xc0c5886150, 0xc05db7f0e0, 0xc0bd450660, 0x2, 0x2, 0x2)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:369 +0x8a fp=0xc0b1aefdd8 sp=0xc0b1aefd68 pc=0x85c74a
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc068eb2a20, 0xc0bd450570, 0xc0c5886150, 0x20302f)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:331 +0x231 fp=0xc0b1aefe58 sp=0xc0b1aefdd8 pc=0x85bc61
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc068eb2a20, 0xc0bd450570, 0xc0c5886150, 0x13b4401)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/rpc/handler.go:298 +0x22d fp=0xc0b1aeff10 sp=0xc0b1aefe58 pc=0x85b32d
````

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #19834

### CODE REVIEW

File: core/tx_pool.go [hunk 1]
```diff
@@ -420,9 +420,6 @@ func (pool *TxPool) SetGasPrice(price *big.Int) {
 // Nonce returns the next nonce of an account, with all transactions executable
 // by the pool already applied on top.
 func (pool *TxPool) Nonce(addr common.Address) uint64 {
-	pool.mu.RLock()
-	defer pool.mu.RUnlock()
-
```
Comment (fjl) [inline core/tx_pool.go]: `pool.pendingNonces` is set in `pool.reset(...)`.

**Comment by rjl493456442** [comment]
@fjl done

File: core/tx_noncer.go [hunk 2]
```diff
@@ -49,5 +57,23 @@ func (txn *txNoncer) get(addr common.Address) uint64 {
...
 func (txn *txNoncer) set(addr common.Address, nonce uint64) {
+	txn.lock.Lock()
+	defer txn.lock.Unlock()
+
+	txn.nonces[addr] = nonce
+}
+
+// compareAndSet inserts or updates a new virtual nonce into the virtual state
+// database if the compare callback is true.
+func (txn *txNoncer) compareAndSet(addr common.Address, nonce uint64, compare func(uint64, uint64) bool) {
```
Comment (karalabe) [inline core/tx_noncer.go]: Passing a `compare` method in here seems really convoluted, especially since all instances use the same logic anyway. Let's just rename `compareAndSet` to `setLower`, get rid of `compare` altogether and do the comparison internally.

**Comment by rjl493456442** [comment]
@karalabe Fixed, please take another look.
