### PR TITLE
eth: improve shutdown synchronization

### LINKED ISSUE #18495: Failed to store fast sync trie progress on shutdown
#### System information

Geth version: Geth/v1.8.22-unstable-a0b0db63/darwin-amd64/go1.11.4
OS & Version: OSX
Commit hash : a0b0db630

#### Expected behaviour

Geth exits cleanly

#### Actual behaviour

Message is logged:

`CRIT [01-22|13:22:32.217] Failed to store fast sync trie progress  err="leveldb: closed"`

### PR DESCRIPTION
**Pull request by fjl**
Most goroutines started by eth.Ethereum didn't have any shutdown sync at
all, which lead to weird error messages when quitting the client.

This change improves the clean shutdown path by stopping all internal
components in dependency order and waiting for them to actually be
stopped before shutdown is considered done. In particular, we now stop
everything related to peers before stopping 'resident' parts such as
core.BlockChain.

Fixes #18495

### CODE REVIEW

File: eth/sync.go [hunk 1]
```diff
@@ -149,35 +152,41 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
 	defer pm.blockFetcher.Stop()
 	defer pm.txFetcher.Stop()
 	defer pm.downloader.Terminate()
 
-	// Wait for different events to fire synchronisation operations
-	forceSync := time.NewTicker(forceSyncCycle)
-	defer forceSync.Stop()
+	for pm.syncTriggerWait() {
+		pm.synchronise(pm.peers.BestPeer())
+	}
```
Comment (karalabe) [inline eth/sync.go]: This will spin once you are in sync and have enough peers.

File: eth/sync.go [hunk 2]
```diff
@@ -149,35 +152,41 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
-		case <-pm.newPeerCh:
-			// Make sure we have peers to select from, then sync
-			if pm.peers.Len() < minDesiredPeerCount {
-				break
+		case <-pm.quitSync:
+			return false
+		default:
+			if pm.peers.Len() >= minDesiredPeerCount {
+				return true
+			}
```
Comment (karalabe) [inline eth/sync.go]: The old check restrained spinning, this new one is actually enforces it.

**Comment by fjl** [comment]
@karalabe PTAL

**Comment by fjl** [comment]
I have now rewritten the chain sync controller as a proper state machine. The new behavior is as follows: 

Whenever a new peer connects or a new head is announced by a connected peer, the chainSyncer is notified and rechecks the preconditions for starting sync. If a sync is already running, we don't do anything. Otherwise we check if there are at least 5 peers or the 10 second 'force timeout' has passed. The sync is launched if any peer has a better TD than our local TD.

**Comment by fjl** [comment]
Force timeout handling could be improved. One issue with the new system is that it's too correct. The old code used a ticker, so retry times were about 5s on average. The new code starts the timer when sync stops. If there are too few peers (i.e. less than 5 with maxpeers >= 5), this means we'll now always wait 10s before retrying.

File: eth/backend.go [hunk 3]
```diff
@@ -84,8 +81,9 @@ type Ethereum struct {
 	engine         consensus.Engine
 	accountManager *accounts.Manager
 
-	bloomRequests chan chan *bloombits.Retrieval // Channel receiving bloom data retrieval requests
-	bloomIndexer  *core.ChainIndexer             // Bloom indexer operating during block imports
+	bloomRequests     chan chan *bloombits.Retrieval // Channel receiving bloom data retrieval requests
+	bloomIndexer      *core.ChainIndexer             // Bloom indexer operating during block imports
+	closeBloomHandler chan bool
```
Comment (karalabe) [inline eth/backend.go]: Can this be `chan struct{}`?

File: eth/sync.go [hunk 4]
```diff
@@ -149,73 +153,146 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
+// chainSyncer coordinates blockchain sync components.
+type chainSyncer struct {
+	pm          *ProtocolManager
+	force       *time.Timer
+	forced      bool // true when force timer fired
+	peerEventCh chan struct{}
+	doneCh      chan error // non-nil when sync is running
+}
+
+type chainSyncOp struct {
```
Comment (karalabe) [inline eth/sync.go]: Please add a doc

File: eth/sync.go [hunk 5]
```diff
@@ -149,73 +153,146 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
+	mode downloader.SyncMode
+	peer *peer
+	td   *big.Int
+	head common.Hash
+}
+
+func newChainSyncer(pm *ProtocolManager) *chainSyncer {
```
Comment (karalabe) [inline eth/sync.go]: Please add a doc

File: eth/sync.go [hunk 6]
```diff
@@ -149,73 +153,146 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
-	pm.txFetcher.Start()
-	defer pm.blockFetcher.Stop()
-	defer pm.txFetcher.Stop()
-	defer pm.downloader.Terminate()
+// chainSyncer coordinates blockchain sync components.
+type chainSyncer struct {
+	pm          *ProtocolManager
+	force       *time.Timer
+	forced      bool // true when force timer fired
+	peerEventCh chan struct{}
```
Comment (karalabe) [inline eth/sync.go]: This `peerEventCh` seems to just be a boring notification channel that something happened and we should recheck. There's no information content in it, and if there are 3 changes simultaneously, there's no need to handle each separately.

My suggestion would be to turn this into a buffered notification channel on 1 and whenever sending into it, if it's already notified, just return early. Wouldn't that make more sense?

File: eth/sync.go [hunk 7]
```diff
@@ -149,73 +153,146 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
+	mode downloader.SyncMode
+	peer *peer
+	td   *big.Int
+	head common.Hash
+}
+
+func newChainSyncer(pm *ProtocolManager) *chainSyncer {
+	return &chainSyncer{
+		pm:          pm,
+		peerEventCh: make(chan struct{}),
```
Comment (karalabe) [inline eth/sync.go]: If this is a notification channel, we should make it buffered with 1. There's no real reason for us to block on it, is there?

File: eth/sync.go [hunk 8]
```diff
@@ -149,73 +153,146 @@ func (pm *ProtocolManager) txsyncLoop64() {
...
+// handlePeerEvent notifies the syncer about a change in the peer set.
+// This is called for new peers and every time a peer announces a new
+// chain head.
+func (cs *chainSyncer) handlePeerEvent(p *peer) bool {
+	select {
+	case cs.peerEventCh <- struct{}{}:
+		return true
+	case <-cs.pm.quitSync:
+		return false
+	}
```
Comment (karalabe) [inline eth/sync.go]: I'd extend this select to handle peerEventCh as a notification:

```go
select {
case cs.peerEventCh <- struct{}{}:
	return true
default:
	select {
	case <-cs.pm.quitSync:
		return false
	default:
		return true
	}
}
```

Something like this?
