### PR TITLE
cmd/evm: evm input minor fixes

### LINKED ISSUE #18041: Opcode length checking
Hello,

- Go EVM version: evm version 1.8.18-unstable-68109336
- Aleth EVM version: aleth-vm 1.5.0-alpha.5-2+commit.ec558b26.dirty 
- Operating system: Ubuntu 18.04
- Fully synchronized: NA
- Network: NA
- Restarted: NA

Please see the stack trace of `evm` and `aleth-vm`:

````
➜  bin git:(master) ✗ ./evm --debug --code 33304f5a2f50E4eFC8B668c39197DDc1eA1Bf6D95AFFBCC6Af60CAfdeE359f1A6c11ce9E72CFBA0eAF072a9efA559DFf22e run
0x
 error: invalid opcode 0x4f
#### TRACE ####
CALLER          pc=00000000 gas=10000000000 cost=2

ADDRESS         pc=00000001 gas=9999999998 cost=2
Stack:
00000000  000000000000000000000000000000000000000000000000000073656e646572

Missing opcode 0x4fpc=00000002 gas=9999999996 cost=2 ERROR: invalid opcode 0x4f
Stack:
00000000  0000000000000000000000000000000000000000000000007265636569766572
00000001  000000000000000000000000000000000000000000000000000073656e646572

#### LOGS ####
````

````
➜  release git:(master) ./parity-evm --code 33304f5a2f50E4eFC8B668c39197DDc1eA1Bf6D95AFFBCC6Af60CAfdeE359f1A6c11ce9E72CFBA0eAF072a9efA559DFf22e --json
Invalid --code: Invalid input length
````

It seems that the opcode length is not validated first in `evm`. Not sure whether this is a real issue (since compiler may guarantee this), but still a potential way to waste gas.

### PR DESCRIPTION
**Pull request by holiman**
This PR fixes two minor things in the `evm` binary

- Validate length of hex input. 
- Accept `0x`-prefix on hex input

It also closes #18041 
## With this PR

Invalid length:
```
[user@work evm]$ ./evm --debug --code "585" run
Invalid input length for hex data (3)
```
Prefixed by `0x`:
```
[user@work evm]$ ./evm --debug --code "0x5858" run
Code is 0x5858
0x
#### TRACE ####
PC              pc=00000000 gas=10000000000 cost=0

PC              pc=00000001 gas=9999999998 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000000

STOP            pc=00000002 gas=9999999996 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000001
00000001  0000000000000000000000000000000000000000000000000000000000000000

#### LOGS ####
```
Not prefixed:
```
[user@work evm]$ ./evm --debug --code "5858" run
Code is 0x5858
0x
#### TRACE ####
PC              pc=00000000 gas=10000000000 cost=0

PC              pc=00000001 gas=9999999998 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000000

STOP            pc=00000002 gas=9999999996 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000001
00000001  0000000000000000000000000000000000000000000000000000000000000000

#### LOGS ####
```

## Before this PR

Invalid length:
```
[user@work evm]$ ./evm --debug --code "585" run
0x
#### TRACE ####
PC              pc=00000000 gas=10000000000 cost=0

STOP            pc=00000001 gas=9999999998 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000000

#### LOGS ####
```
Prefixed by `0x`:
```
[user@work evm]$ ./evm --debug --code "0x5858" run
0x
#### TRACE ####
#### LOGS ####
```
Not prefixed:
```
[user@work evm]$ ./evm --debug --code "5858" run
0x
#### TRACE ####
PC              pc=00000000 gas=10000000000 cost=0

PC              pc=00000001 gas=9999999998 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000000

STOP            pc=00000002 gas=9999999996 cost=0
Stack:
00000000  0000000000000000000000000000000000000000000000000000000000000001
00000001  0000000000000000000000000000000000000000000000000000000000000000

#### LOGS ####
```

### CODE REVIEW

File: cmd/evm/runner.go [hunk 1]
```diff
@@ -121,28 +120,37 @@ func runCmd(ctx *cli.Context) error {
...
+					os.Exit(1)
+				}
+			} else {
+				// Codefile with hex assembly
+				if hexcode, err = ioutil.ReadFile(codeFileFlag); err != nil {
+					fmt.Printf("Could not load code from file: %v\n", err)
+					os.Exit(1)
+				}
 			}
+
```
Comment (karalabe) [inline cmd/evm/runner.go]: Please remote this empty line, otherwise LGTM

Comment (holiman) [reply cmd/evm/runner.go]: fixed

**Comment by holiman** [comment]
done
