### PR TITLE
p2p/nat: limit UPNP request concurrency

### LINKED ISSUE #21370: UPnP does not work
#### System information

Version: 1.9.17-stable
Git Commit: 748f22c192d24082723f935afd0b0b63e7fd50f4
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-oJIima/.go

Router = ZTE F660

#### Expected behaviour

UPnP gets mapped into the router.

Even when using flag `--nat upnp` don't works.

#### Actual behaviour

Nothing happens.

#### Steps to reproduce the behaviour

Not sure.

### PR DESCRIPTION
**Pull request by fjl**
This adds a lock around requests because some routers can't handle
concurrent requests.

Fixes #21370

### CODE REVIEW

File: p2p/nat/natupnp.go [hunk 1]
```diff
@@ -90,36 +114,51 @@ func (n *upnp) internalAddress() (net.IP, error) {
...
 
+func (n *upnp) withRateLimit(fn func() error) error {
+	n.mu.Lock()
+	defer n.mu.Unlock()
+
+	lastreq := time.Since(n.lastReqTime)
+	if lastreq < rateLimit {
+		time.Sleep(rateLimit - lastreq)
+	}
+	err := fn()
```
Comment (zsfelfoldi) [inline p2p/nat/natupnp.go:134]: Why are you passing through an error result here? The input params and the rest of the results are passed through the caller's local context, it just feels illogical to pass an error result here when you are not doing anything else with it. It could be a simple `fn func()`.

Comment (zsfelfoldi) [reply p2p/nat/natupnp.go:134]: I see, sometimes the only result is an error. If you still prefer it this way then I am fine with it, it just gave me a wrong first impression that the error result might have a special meaning to the rate limiter function.
