### PR TITLE
pow: pure go ethash

### LINKED ISSUE #2328: Specify ethash folder in CLI
Data directory can be specified using the datadir flag but the Ethash folder cannot be specified by the user.
For people that have a  small SSD with HomeDir on it it can become quickly an issue since this folder is growing very fast.

I have used a turnaround : creating a Sym-link but it is a quick and dirty solution.

### LINKED ISSUE #2471: New node starts DAG generation before syncing
#### System information

Geth version: `Starting Geth/v1.3.6/linux/go1.5.1`
OS & Version: Linux/Ubuntu
#### Expected behaviour

syncs blockchain, then begins mining
#### Actual behaviour

starts building DAG from block zero, and will simultaneously build mutliple DAGs at the same time as the blockchain syncs.
#### Steps to reproduce the behaviour

start a fresh node with the mine flag `geth --mine`
#### Logs

syncing from start:

```
database.go:71] Alloted 16MB cache to /root/.ethereum/testnet/chaindata
database.go:71] Alloted 16MB cache to /root/.ethereum/testnet/dapp
backend.go:314] Protocol Versions: [63 62 61], Network Id: 2
backend.go:362] Blockchain DB Version: 3
blockchain.go:214] Last header: #0 [0cd786a2…] TD=131072
blockchain.go:215] Last block: #0 [0cd786a2…] TD=131072
blockchain.go:216] Fast block: #0 [0cd786a2…] TD=131072
cmd.go:115] Starting Geth/v1.3.6/linux/go1.5.1
server.go:311] Starting Server
udp.go:212] Listening, enode://ee44ebc754df8dd9eca31f24ed12434da155956241cc281fc0a24b712c73bcfa9a1167142a9f0a94211b304391545e7f8f6be45be21c3fd05649d7735201aed4@[::]:30303
backend.go:526] Server started
miner.go:119] Starting mining operation (CPU=1 TOT=2)
worker.go:569] commit new work on block 1 with 0 txs & 0 uncles. Took 408.173µs
ethash.go:220] Generating DAG for epoch 0 (size 1073739904) (0000000000000000000000000000000000000000000000000000000000000000)
backend.go:584] Automatic pregeneration of ethash DAG ON (ethash dir: /root/.ethash)
ipc.go:112] IPC service started (/root/.ethereum/geth.ipc)
backend.go:591] checking DAG (ethash dir: /root/.ethash)
server.go:552] Listening on [::]:30303
ethash.go:252] Generating DAG: 0%
ethash.go:252] Generating DAG: 1%
ethash.go:252] Generating DAG: 2%
ethash.go:252] Generating DAG: 3%
```

multiple DAGs at once

```
ethash.go:220] Generating DAG for epoch 14 (size 1191180416) (526ee6e688a9b3d466fe4a7355197a89898593509d75c570942cc73a5ca8299d)
ethash.go:252] Generating DAG: 40%
ethash.go:252] Generating DAG: 91%
ethash.go:252] Generating DAG: 0%
blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 635 txs in 7.631242763s. #420416 [b2a9f017 / 17a76e63]
worker.go:569] commit new work on block 420417 with 0 txs & 0 uncles. Took 878.832µs
blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 60 txs in 2.864135036s. #420672 [3bd31dfb / b4293d6f]
worker.go:569] commit new work on block 420673 with 0 txs & 0 uncles. Took 1.257414ms
blockchain.go:1251] imported 256 block(s) (0 queued 0 ignored) including 53 txs in 4.226514752s. #420928 [63b39c63 / dc07fc94]
worker.go:569] commit new work on block 420929 with 0 txs & 0 uncles. Took 997.89µs
ethash.go:252] Generating DAG: 54%
ethash.go:252] Generating DAG: 70%
ethash.go:252] Generating DAG: 41%
ethash.go:252] Generating DAG: 92%
```

### LINKED ISSUE #3465: no clear error when geth has run out of space to sync (at least in .ethash but maybe also in --datadir)
#### System information

Geth version: `geth version`
Geth
Version: 1.5.5-stable
Git Commit: ff07d54843ea7ed9997c420d216b4c007f9c80c3
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: linux

#### Expected behaviour
geth could check for available disk space before attempting to start activity.  Also, while it is running it could check for available disk space; in case there is an error, it could at least specifically check for lack of disk space and provide a clear error.

#### Actual behaviour
geth output a huge error (1379 lines long?) but no indication that it had run out of disk space where .ethash was.

#### Steps to reproduce the behaviour
Create a drive with only a little space.  Start syncing a geth node on it.

In case it is useful, this is what I went through:
* I had a Google Compute Engine server where i was doing some code
* For a talk/demo that I had to do, I was creating a new node.  So i attached a new disk.
* I set the --datadir to be on the new disk.  
* After the unclear errors in the logs, I did some trial and error to understand that even .ethash takes up quite some space.

[nohup.txt](https://github.com/ethereum/go-ethereum/files/660818/nohup.txt)

### LINKED ISSUE #3583: geth crashes with "fatal error: unexpected signal during runtime execution" - DAG
#### System information

Geth version: `1.5.5-unstable`
OS & Version: Ubuntu Linux 4.4.0-57-generic (Ethereum Virtual Machine running on AWS)
Commit hash : (`2dcf75a722f193ef5528f5af8fb4fd7c5824fded`)

#### Expected behavior
geth runs without crashing

#### Actual behaviour
geth crashes after running for a period of time, usually when the system as a whole is idle. In looking at the log, it appears that geth begins to generate a DAG for a particular epoch, and then before that generation is completed, it attempts to generate a DAG for that same epoch. Log entries with line numbers are below.

**Start of first DAG generation for epoch 45:**
`814625 I0117 13:08:04.067881 eth/backend.go:480] checking DAG (ethash dir: /home/ubuntu/.ethash)`
`814626 I0117 13:08:04.068012 eth/backend.go:489] removed DAG for epoch 43 (full-R23-67f3589ac683de3f)`
**`814627 I0117 13:08:04.068084 eth/backend.go:494] Pregenerating DAG for epoch 45 (full-R23-013d5197a3a03514)`**
`814628 I0117 13:08:04.068149 vendor/github.com/ethereum/ethash/ethash.go:259] Generating DAG for epoch 45 (size 1451229056) (013d5197a3a035144a79e3e09dfec250       5039ed176d81a0957e229886ddbee49b)`
`814629 I0117 13:08:04.714497 miner/worker.go:362] 🔨  Mined block (#1349894 / b4c70c6a). Wait 5 blocks for confirmation`
`814630 I0117 13:08:04.723304 miner/worker.go:563] commit new work on block 1349895 with 0 txs & 0 uncles. Took 8.757975ms`
`814631 I0117 13:08:04.723331 miner/worker.go:458] 🔨 🔗  Mined 5 blocks back: block #1349889`
`814632 I0117 13:08:05.286393 vendor/github.com/ethereum/ethash/ethash.go:291] Generating DAG: 0%`

**Later in that same log file, geth tries to generate a DAG for the same epoch 45, but the original DAG generation was still running (got to 47%):**

`814985 I0117 13:10:17.160545 vendor/github.com/ethereum/ethash/ethash.go:291] Generating DAG: 45%`
`814986 I0117 13:10:19.996926 vendor/github.com/ethereum/ethash/ethash.go:291] Generating DAG: 46%`
`814987 I0117 13:10:20.295196 miner/worker.go:362] 🔨  Mined block (#1349997 / a7d10f3f). Wait 5 blocks for confirmation`
`814988 I0117 13:10:20.304207 miner/worker.go:563] commit new work on block 1349998 with 0 txs & 0 uncles. Took 8.958392ms`
`814989 I0117 13:10:20.304236 miner/worker.go:458] 🔨 🔗  Mined 5 blocks back: block #1349992`
`814990 I0117 13:10:20.322157 miner/worker.go:362] 🔨  Mined block (#1349998 / 49c6e82c). Wait 5 blocks for confirmation`
`814991 I0117 13:10:20.331161 miner/worker.go:563] commit new work on block 1349999 with 0 txs & 0 uncles. Took 8.940344ms`
`814992 I0117 13:10:20.331191 miner/worker.go:458] 🔨 🔗  Mined 5 blocks back: block #1349993`
`814993 I0117 13:10:21.478291 miner/worker.go:362] 🔨  Mined block (#1349999 / 954f3765). Wait 5 blocks for confirmation`
`814994 I0117 13:10:21.487228 miner/worker.go:563] commit new work on block 1350000 with 0 txs & 0 uncles. Took 8.883875ms`
`814995 I0117 13:10:21.487258 miner/worker.go:458] 🔨 🔗  Mined 5 blocks back: block #1349994`
**`814996 I0117 13:10:21.487352 vendor/github.com/ethereum/ethash/ethash.go:259] Generating DAG for epoch 45 (size 1451229056) (013d5197a3a035144a79e3e09dfec250       5039ed176d81a0957e229886ddbee49b)`**
**`814997 I0117 13:10:22.648484 vendor/github.com/ethereum/ethash/ethash.go:291] Generating DAG: 47%`**
`814998 fatal error: unexpected signal during runtime execution`
`814999 [signal SIGBUS: bus error code=0x2 addr=0x7ff4985de000 pc=0xbbdc36]`

#### Steps to reproduce the behaviour
Still investigating

#### Backtrace

````
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0x7ff4985de000 pc=0xbbdc36]

runtime stack:
runtime.throw(0xdecabc, 0x2a)
	/usr/lib/go-1.7/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/go-1.7/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 102 [syscall, locked to thread]:
runtime.cgocall(0xbbb820, 0xc437fcdab8, 0xc400000000)
	/usr/lib/go-1.7/src/runtime/cgocall.go:131 +0x110 fp=0xc437fcda50 sp=0xc437fcda10
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash._Cfunc_ethash_full_new_internal(0x7ff8d0000a10, 0x1435a0a397513d01, 0x50c2fe9de0e3794a, 0x95a0816d17ed3950, 0x9be4bedd8698227e, 0x567fff80, 0x7ff8d00008c0, 0xbbed00, 0x0)
	??:0 +0x51 fp=0xc437fcdab8 sp=0xc437fcda50
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate.func1()
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:271 +0x492 fp=0xc437fcdc50 sp=0xc437fcdab8
sync.(*Once).Do(0xc42058f3a0, 0xc437fcdc98)
	/usr/lib/go-1.7/src/sync/once.go:44 +0xdb fp=0xc437fcdc88 sp=0xc437fcdc50
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate(0xc42058f380)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:277 +0x4c fp=0xc437fcdcb8 sp=0xc437fcdc88
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.MakeDAG(0x149970, 0x0, 0x0, 0xc45723de98, 0x2)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:303 +0x16c fp=0xc437fcdd28 sp=0xc437fcdcb8
github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG.func1(0xc4202aa540)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:495 +0x505 fp=0xc437fcdf98 sp=0xc437fcdd28
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc437fcdfa0 sp=0xc437fcdf98
created by github.com/ethereum/go-ethereum/eth.(*Ethereum).StartAutoDAG
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:510 +0x4b

goroutine 1 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(0xc42044a900)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:551 +0x8b
main.geth(0xc4202e8dc0, 0x0, 0x0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:191 +0x56
reflect.Value.call(0xc7caa0, 0xf8d418, 0x13, 0xd9ec41, 0x4, 0xc421acfd00, 0x1, 0x1, 0x4b6ed8, 0xd8ccc0, ...)
	/usr/lib/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc7caa0, 0xf8d418, 0x13, 0xc421acfd00, 0x1, 0x1, 0xc42044cf01, 0xc4202d3400, 0xc42004dcf0)
	/usr/lib/go-1.7/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xc7caa0, 0xf8d418, 0xc4202e8dc0, 0x0, 0x0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:482 +0x1e0
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4202ac300, 0xc42000c0a0, 0xa, 0xa, 0x0, 0x0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:240 +0x596
main.main()
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:179 +0x55

goroutine 17 [syscall, 4822 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x636
created by github.com/ethereum/go-ethereum/logger.init.1
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x35

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x165cc00)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:931 +0x7a
created by github.com/ethereum/go-ethereum/logger/glog.init.1
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:460 +0x83

goroutine 7 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc420064360, 0xc4200642a0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0x5a
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0x181

goroutine 8 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc420064360, 0xc420064300)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x94
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x1ad

goroutine 9 [syscall, 4822 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.7/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/lib/go-1.7/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/lib/go-1.7/src/os/signal/signal_unix.go:28 +0x41

goroutine 66 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/miner.(*Miner).update(0xc422918000)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:83 +0x1ae
created by github.com/ethereum/go-ethereum/miner.New
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:71 +0x141

goroutine 20 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/accounts.(*watcher).loop(0xc4202d3660)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/watch.go:91 +0x4c4
created by github.com/ethereum/go-ethereum/accounts.(*watcher).start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/watch.go:53 +0x5f

goroutine 22 [syscall, 4822 minutes]:
syscall.Syscall6(0xe8, 0x5, 0xc420025734, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x5, 0xc420025734, 0x1, 0x1, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/syscall/zsyscall_linux_amd64.go:365 +0x77
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).loop(0xc4200a0000, 0xc42008dc20)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:193 +0xa2
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:133 +0x145

goroutine 23 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc4200a0000, 0xc42008dc20)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:253 +0x66
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:136 +0x19c

goroutine 24 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).send(0xc4200a0000, 0xc42008dc20)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:253 +0x66
created by github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_inotify.go:136 +0x19c

goroutine 36 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).loop(0xc421a40410)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:316 +0x48fc
created by github.com/ethereum/go-ethereum/eth/fetcher.(*Fetcher).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/fetcher/fetcher.go:178 +0x3f

goroutine 13 [select, 483 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc420bb0480)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 12 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4202aa380)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 14 [select]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc420bb0480)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 15 [select, 483 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc420bb0480)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 16 [select, 707 minutes]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc420bb0480)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 50 [select]:
github.com/ethereum/go-ethereum/core.(*BlockChain).update(0xc4203a6240)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1205 +0x127
created by github.com/ethereum/go-ethereum/core.NewBlockChain
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:166 +0xb00

goroutine 51 [chan receive]:
github.com/ethereum/go-ethereum/core.(*TxPool).eventLoop(0xc4201882c0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:140 +0xe2
created by github.com/ethereum/go-ethereum/core.NewTxPool
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:128 +0x588

goroutine 52 [select]:
github.com/ethereum/go-ethereum/core.(*TxPool).expirationLoop(0xc4201882c0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:699 +0x3da
created by github.com/ethereum/go-ethereum/core.NewTxPool
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:129 +0x5aa

goroutine 53 [select]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).qosTuner(0xc420216380)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1475 +0x384
created by github.com/ethereum/go-ethereum/eth/downloader.New
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:204 +0xf5c

goroutine 54 [chan receive]:
github.com/ethereum/go-ethereum/miner.(*worker).update(0xc4203a6360)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:241 +0xa2
created by github.com/ethereum/go-ethereum/miner.newWorker
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:150 +0x48a

goroutine 55 [chan receive]:
github.com/ethereum/go-ethereum/miner.(*worker).wait(0xc4203a6360)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:281 +0xc0
created by github.com/ethereum/go-ethereum/miner.newWorker
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:152 +0x4ac

goroutine 67 [IO wait, 4822 minutes]:
net.runtime_pollWait(0x7ff93af676c8, 0x72, 0x0)
	/usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4225725a0, 0x72, 0xc420039db0, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4225725a0, 0x15af800, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc422572540, 0x0, 0x15ad580, 0xc420147960)
	/usr/lib/go-1.7/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4223efd90, 0xc420039e88, 0xc420039e88, 0x419305)
	/usr/lib/go-1.7/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc4223efd90, 0xc420c44120, 0x0, 0x2, 0xc42294e000)
	/usr/lib/go-1.7/src/net/tcpsock.go:222 +0x49
github.com/ethereum/go-ethereum/p2p.(*Server).listenLoop(0xc42140c000)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:633 +0x281
created by github.com/ethereum/go-ethereum/p2p.(*Server).startListening
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:423 +0x156

goroutine 68 [select, 8 minutes]:
github.com/ethereum/go-ethereum/p2p/nat.Map(0x15b6c40, 0xc42044e5c0, 0xc4229181e0, 0xd9e92c, 0x3, 0x765f, 0x765f, 0xdaad77, 0xc)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:114 +0x80b
github.com/ethereum/go-ethereum/p2p.(*Server).startListening.func1(0xc42140c000, 0xc4229152c0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:428 +0x8f
created by github.com/ethereum/go-ethereum/p2p.(*Server).startListening
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:430 +0x1fa

goroutine 69 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/p2p.(*Server).run(0xc42140c000, 0x15b6bc0, 0xc4225724d0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:492 +0x11bf
created by github.com/ethereum/go-ethereum/p2p.(*Server).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/server.go:408 +0x72e

goroutine 70 [chan receive, 630 minutes]:
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).txBroadcastLoop(0xc4202aa700)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:764 +0x80
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:217 +0xbe

goroutine 71 [chan receive]:
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).minedBroadcastLoop(0xc4202aa700)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:753 +0x77
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:220 +0x157

goroutine 72 [select]:
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer(0xc4202aa700)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:143 +0x285
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:223 +0x179

goroutine 73 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).txsyncLoop(0xc4202aa700)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:109 +0x5b3
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:224 +0x19b

goroutine 74 [select, 23 minutes]:
github.com/ethereum/go-ethereum/contracts/release.(*ReleaseService).checker(0xc4210edf40)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/contracts/release/release.go:119 +0xebb
created by github.com/ethereum/go-ethereum/contracts/release.(*ReleaseService).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/contracts/release/release.go:99 +0x3f

goroutine 75 [select, 4822 minutes]:
github.com/ethereum/go-ethereum/eth/downloader.(*PublicDownloaderAPI).eventLoop(0xc422916a40)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/api.go:63 +0x618
created by github.com/ethereum/go-ethereum/eth/downloader.NewPublicDownloaderAPI
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/api.go:49 +0xff

goroutine 76 [select]:
github.com/ethereum/go-ethereum/eth/filters.(*EventSystem).eventLoop(0xc422938050)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:441 +0x793
created by github.com/ethereum/go-ethereum/eth/filters.NewEventSystem
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter_system.go:132 +0x12b

goroutine 77 [chan receive, 3 minutes]:
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc4229380a0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/api.go:86 +0x6d
created by github.com/ethereum/go-ethereum/eth/filters.NewPublicFilterAPI
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/api.go:76 +0x1d0

goroutine 78 [IO wait, 876 minutes]:
net.runtime_pollWait(0x7ff93af673c8, 0x72, 0x0)
	/usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc422573870, 0x72, 0xc422ab1e10, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc422573870, 0x15af800, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc422573810, 0x0, 0x15ad580, 0xc45ff78360)
	/usr/lib/go-1.7/src/net/fd_unix.go:419 +0x238
net.(*UnixListener).accept(0xc422a76880, 0x44887e, 0xc422ab1ed0, 0x5821b9)
	/usr/lib/go-1.7/src/net/unixsock_posix.go:158 +0x32
net.(*UnixListener).Accept(0xc422a76880, 0xf8c680, 0xc422a46ea0, 0x15ba6a0, 0xc4213520f0)
	/usr/lib/go-1.7/src/net/unixsock.go:229 +0x49
github.com/ethereum/go-ethereum/node.(*Node).startIPC.func1(0xc42044a900, 0x15b5540, 0xc422a76880, 0xc422a46ea0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:344 +0xee
created by github.com/ethereum/go-ethereum/node.(*Node).startIPC
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:359 +0x2e5

goroutine 79 [IO wait, 631 minutes]:
net.runtime_pollWait(0x7ff93af67308, 0x72, 0x0)
	/usr/lib/go-1.7/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4225738e0, 0x72, 0xc42063dde8, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4225738e0, 0x15af800, 0xc420012078)
	/usr/lib/go-1.7/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc422573880, 0x0, 0x15ad580, 0xc45b30b120)
	/usr/lib/go-1.7/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc42296aeb8, 0x44887e, 0xc42063de98, 0x93f4cd)
	/usr/lib/go-1.7/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).Accept(0xc42296aeb8, 0xf8d6c0, 0xc422a48a00, 0x15b6800, 0xc422aa60c0)
	/usr/lib/go-1.7/src/net/tcpsock.go:222 +0x49
net/http.(*Server).Serve(0xc422a73780, 0x15b54c0, 0xc42296aeb8, 0x0, 0x0)
	/usr/lib/go-1.7/src/net/http/server.go:2273 +0x1ce
created by github.com/ethereum/go-ethereum/node.(*Node).startHTTP
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:410 +0x4c2

goroutine 80 [chan receive, 4822 minutes]:
github.com/ethereum/go-ethereum/cmd/utils.StartNode.func1(0xc42044a900)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:80 +0x105
created by github.com/ethereum/go-ethereum/cmd/utils.StartNode
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:91 +0x68

goroutine 81 [select, 4822 minutes, locked to thread]:
runtime.gopark(0xf8dd80, 0x0, 0xda1b6b, 0x6, 0x18, 0x2)
	/usr/lib/go-1.7/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc421dd4f30, 0x0, 0x18)
	/usr/lib/go-1.7/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc421dd4f30)
	/usr/lib/go-1.7/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/lib/go-1.7/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 104 [select]:
github.com/ethereum/go-ethereum/miner.(*RemoteAgent).maintainLoop(0xc422918720)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/remote_agent.go:156 +0x48d
created by github.com/ethereum/go-ethereum/miner.(*RemoteAgent).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/remote_agent.go:82 +0xd8

goroutine 105 [select]:
github.com/ethereum/go-ethereum/miner.(*CpuAgent).update(0xc420660d70)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:75 +0x297
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).Start
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:69 +0x6b

goroutine 1635 [chan receive]:
github.com/ethereum/go-ethereum/eth/gasprice.(*GasPriceOracle).listenLoop(0xc422572310)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/gasprice/gasprice.go:124 +0x20f
created by github.com/ethereum/go-ethereum/eth/gasprice.(*GasPriceOracle).init.func1
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/gasprice/gasprice.go:96 +0x51

goroutine 1399865 [runnable, locked to thread]:
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.ethashGoCallback(0xc400000000, 0xc42003e870)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:291 +0x73
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash._cgoexpwrap_564388193f1a_ethashGoCallback(0x3332522d00000000, 0x393135643331302d)
	??:0 +0x29
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash._Cfunc_ethash_full_new_internal(0x7ff930000a30, 0x1435a0a397513d01, 0x50c2fe9de0e3794a, 0x95a0816d17ed3950, 0x9be4bedd8698227e, 0x567fff80, 0x7ff930000a10, 0xbbed00, 0x0)
	??:0 +0x51
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate.func1()
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:271 +0x492
sync.(*Once).Do(0xc45643a120, 0xc42003ebf0)
	/usr/lib/go-1.7/src/sync/once.go:44 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*dag).generate(0xc45643a100)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:277 +0x4c
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*Full).getDAG(0xc4201be0c0, 0x149970, 0xc421dd9cf0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:333 +0xa0
github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash.(*Full).Search(0xc4201be0c0, 0x15b7e80, 0xc457244870, 0xc422919b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/ethereum/ethash/ethash.go:338 +0x74
github.com/ethereum/go-ethereum/miner.(*CpuAgent).mine(0xc420660d70, 0xc438c5b420, 0xc422919b00)
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:113 +0x136
created by github.com/ethereum/go-ethereum/miner.(*CpuAgent).update
	/home/bertrand/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:82 +0x153
````

### LINKED ISSUE #3640: delete old DAG files in .ethash
I am using geth Version: 1.5.5-unstable on Ubuntu 16.04. I am playing on a private testnet and mine on this machine. The `.ethash` folder is growing out of control (see example below). I would suggest auto-deleting old DAG files that are not required anymore.
```
root@VL-ZE:~/.ethash# ls -lah
total 28G
drwxr-xr-x  2 root root 4.0K Feb  3 03:13 .
drwx------ 12 root root 4.0K Feb  1 22:48 ..
-rw-r--r--  1 root root 1.0G Jan 10 13:17 full-R23-0000000000000000
-rw-r--r--  1 root root 1.3G Jan 29 08:05 full-R23-1842cb89c0dfad7e
-rw-r--r--  1 root root 1.1G Feb  2 05:47 full-R23-290decd9548b62a8
-rw-r--r--  1 root root 1.1G Jan 19 12:15 full-R23-356e5a2cc1eba076
-rw-r--r--  1 root root 1.4G Feb  1 20:31 full-R23-39238891c3ff3084
-rw-r--r--  1 root root 1.2G Jan 23 23:42 full-R23-3db89d407a531822
-rw-r--r--  1 root root 1.2G Jan 17 15:55 full-R23-4a5c69f25c2f9aa9
-rw-r--r--  1 root root 1.3G Jan 31 10:32 full-R23-4b77c50b31c33143
-rw-r--r--  1 root root 1.3G Feb  1 05:44 full-R23-5197b2a3898b31d4
-rw-r--r--  1 root root 1.2G Jan 15 12:46 full-R23-526ee6e688a9b3d4
-rw-r--r--  1 root root 1.1G Jan 12 16:00 full-R23-582b06447f087674
-rw-r--r--  1 root root 1.3G Jan 30 01:54 full-R23-5a46dd85298b0bef
-rw-r--r--  1 root root 1.2G Jan 27 10:29 full-R23-6a6513eeb3ff2d75
-rw-r--r--  1 root root 1.2G Jan 18 09:24 full-R23-77e29faaecdca731
-rw-r--r--  1 root root 1.3G Jan 29 17:14 full-R23-7e7d8bef9d86983a
-rw-r--r--  1 root root 1.2G Jan 27 05:02 full-R23-81c436d08902c24b
-rw-r--r--  1 root root 1.3G Jan 28 21:51 full-R23-920a075f9d5202e2
-rw-r--r--  1 root root 1.2G Jan 15 04:10 full-R23-9b1ca7a86d339a3f
-rw-r--r--  1 root root 1.1G Jan 22 01:18 full-R23-9b2baad7528ecec6
-rw-r--r--  1 root root 1.1G Jan 19 22:58 full-R23-b903bd7696740696
-rw-r--r--  1 root root 1.2G Jan 17 06:52 full-R23-c6320e3c1c345600
-rw-r--r--  1 root root 1.2G Jan 18 00:41 full-R23-cdf42a47e552f9b4
-rw-r--r--  1 root root 1.1G Jan 14 08:11 full-R23-d705bfceb1886284
-rw-r--r--  1 root root 1.1G Jan 21 15:08 full-R23-ec9d541d1c32bec7
-rw-r--r--  1 root root 1.1G Jan 12 05:49 full-R23-f2e59013a0a37983
```

### PR DESCRIPTION
**Pull request by karalabe**
**Acknowledgements**

 * Huge thanks to @3esmit for offering access to his MIPS64 router to debug big endian ethash issues on and optimize memory usage patterns! This PR would be much less useful without it!
 * Also the PR deserves a shout out to @fjl for various memory allocation optimizations.

---

This PR replaces the C++ ethash implementation from https://github.com/ethereum/ethash with a custom one fully written in Go. The reasons for doing this are numerous.

**Issues with C++ ethash**

 * We're not C++ developers. Every time a bug is reported against ethash we just blink and tell people how to work around it, but can't address it ourselves.
 * A pure Go implementation makes our code a lot more portable (e.g. GopherJS) by removing the last C++ dependency we have (USB still requires C, but that can be disabled).
 * C++ ethash doesn't support big endian systems currently. The included Keccak functions need to be replaced with ones that do (may be done from the Tor project), but even then the ethash implementation itself does not run on big endian systems. Further bugs need to be tracked down.
 * C++ ethash stores the verification caches and mining DAGs as flat byte arrays in little endian order (with words mapped on top as unions). This means every time a data item is accessed on big endian systems, the bytes need to be reversed, which is prohibitively expensive. The alternative is a full rewrite of C++ ethash to store in host byte order, but that's not something anyone is willing to undertake.
 * There are a lot of cryptic issue reports that stem from C++ crashing in wildly different ways when it goes OOM or OOD #3583, #3465, #3056, #2783, #2530, #1572. With a pure Go implementation we can at least emit meaningful error messages in these cases.

**Features enabled by Go**

 * Generating a single mining DAG can be parallelized  to use all available cores on the machine. In C++ this is semi impossible without adding boost threads as a dependency. With Go we can use simple goroutines and use all out capacity to generate the DAG.
 * By managing the DAGs ourselves, the PR finally adds capability to rotate old ones out instead of eeping them stored on disk forever. This should help users running private networks where they don't want to constantly babysit the size of the ethash folder.
 * By managing the caches ourselves, the PR adds the capability to store verification caches on disk (yes, in a rotating matter), and loading them up if available. This is essential for lower capability devices (phones, routers), as generating a cache usually takes considerably more time than loading from disk. It also permits devices to quickly become usable after a restart instead of waiting for caches to build again.
* Last but not least pure Go enables running on all platforms Go supports, even the exotic ones (e.g. mobiles, big endian) as well as all environments where Go transpilers exist (e.g GopherJS).

**Performance**

 * Generating the verification cache via C++ for epoch 0 on a Zenbook pro takes 650ms. The same thing using pure Go takes ~~850ms~~ 800ms. However with the disk cache extension loading it form there (which happens always apart from the very first startup) ~~takes 100ms~~ is instantaneous due to memory mapping.
   * On a MIPS router the generating the first cache takes 35s, loading from disk ~~4.6s~~ 0. The cache for block 2.6M takes 1m7s to generate but ~~only 12s to load~~ still memory maps instantly.
 * Generating the mining DAG via C++ for epoch 0 on a Zenbook pro takes a bit above 6 minutes. The same thing using pure Go + the threading it enables takes a bit above 1 minute.
 * Verifying a PoW for a random header using C++ took 2.7ms on the Zenbook whereas the pure Go version was benchmarked at ~~1.6ms~~ 1.4ms.  The comparison is not fully fair because I didn't write a full benchmark for C++.
 * Mining on 8 threads on the Zenbook was benchmarked via `ethminer` to have a hashrate of 200-250KH/s. Measuring the hashrate of the Go implementation (via gometrics) resulted in 240-250KH/s.
 * We can now memory map both mining datasets as well as verification caches, the latter reducing the hard memory requirement of geth on mainnet by about 120MB (3 recent caches + 1 future was stored until now).

**Fixes**

 * Fixes #3640 via the `ethash.dasondisk` flag.
 * Fixes #2328 via the `ethash.dagdir` flag.
 * Fixes #3583 via generate-rename-open.
 * Fixes #3465, #3056, #2783, #2530, #1572 via Go crash logs.
 * Fixes #2471 via sequential and properly locked DAG generation.

**Extras**

The PR introduces the following CLI flags (and eth.Config varialbes):

```
ETHASH OPTIONS:
  --ethash.cachedir            Directory to store the ethash verification caches (default = inside the datadir)
  --ethash.cachesinmem value   Number of recent ethash caches to keep in memory (16MB each) (default: 2)
  --ethash.cachesondisk value  Number of recent ethash caches to keep on disk (16MB each) (default: 3)
  --ethash.dagdir              Directory to store the ethash mining DAGs (default = inside home folder)
  --ethash.dagsinmem value     Number of recent ethash mining DAGs to keep in memory (1+GB each) (default: 1)
  --ethash.dagsondisk value    Number of recent ethash mining DAGs to keep on disk (1+GB each) (default: 2)
```

**Notes**

 * The PR drops support for all *autodag* flags and RPC endpoints. Automatic dag pre-generation is baked in and there's no way to disable it. There really isn't any meaningful scenario where this isn't needed, so it's just a lot less code and mess.
 * The PR currently hard codes `cachedir == "ethash"`, `cachesinmem == 2` and `cachesondisk == 3` on mobile. This should be a sane default. We can surface these as parameters later, but i'd not go there for now.

### CODE REVIEW

File: crypto/crypto.go [hunk 1]
```diff
@@ -54,6 +61,47 @@ func Keccak256Hash(data ...[]byte) (h common.Hash) {
...
+	hasher := sha3.NewKeccak512()
+
+	return func(data []byte) []byte {
+		hasher.Write(data)
+		result := hasher.Sum(nil)
+		hasher.Reset()
+		return result
+	}
+}
+
```
Comment (fjl) [inline crypto/crypto.go]: This function is easy to implement on top of `hash.Hash`, there is no need to add specialized variants to crypto/sha3. 

```go
import "hash"

func NewHasher(h hash.Hash) func ([]byte) []byte {
    return func (data []byte) []byte {
        h.Write(data)
        result := h.Sum(nil)
        h.Reset()
        return result
    }
}

File: pow/ethash.go [hunk 2]
```diff
@@ -0,0 +1,469 @@
...
+//
+// The go-ethereum library is distributed in the hope that it will be useful,
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU Lesser General Public License for more details.
+//
+// You should have received a copy of the GNU Lesser General Public License
+// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.
+
+package pow
```
Comment (fjl) [inline pow/ethash.go]: Please move ethash to pow/ethash. We can remove package pow if you want or keep it around for the interface (and FakePow). I'm suggesting this because having ethash here adds a ton of dependencies to the pow package, including "unsafe".

File: pow/ethash.go [hunk 3]
```diff
@@ -0,0 +1,469 @@
...
+		logger := log.New("seed", hexutil.Bytes(seed))
+
+		if dir != "" {
+			dump, err := os.Open(path)
+			if err == nil {
+				if !discard {
+					logger.Info("Loading ethash DAG from disk")
+					start := time.Now()
+					d.dataset = prepare(dsize, bufio.NewReader(dump))
+					logger.Info("Loaded ethash DAG from disk", "elapsed", common.PrettyDuration(time.Since(start)))
```
Comment (fjl) [inline pow/ethash.go]: It would be better to mmap DAGs and caches.

File: pow/ethash.go (hunk 2 above)
Comment (karalabe) [inline pow/ethash.go]: I already moved it in my PoA PR, all of it into a `consensus` package, and `ethash` and `rinkeby` into their own packages. If it's ok, let's leave it to that PR to avoid a merge nightmare for me :D

File: crypto/crypto.go (hunk 1 above)
Comment (fjl) [inline crypto/crypto.go]: or maybe even

```go
import "hash"

func NewHasher(h hash.Hash) func ([]byte) []byte {
    result := make([]byte, h.Size())
    return func (data []byte) []byte {
        h.Write(data)
        h.Sum(result[:0])
        h.Reset()
        return result
    }
}
```

**Comment by karalabe** [comment]
@fjl PTAL. Full mmap support done.

**Comment by karalabe** [comment]
PS: Please don't squash when merging. I'd like to retain the commits mostly as is.

File: pow/pow.go [hunk 4]
```diff
@@ -16,9 +16,43 @@
...
+	HashNoNonce() common.Hash
+	Nonce() uint64
+	MixDigest() common.Hash
+	NumberU64() uint64
+}
+
+type ChainManager interface {
+	GetBlockByNumber(uint64) *types.Block
+	CurrentBlock() *types.Block
+}
```
Comment (fjl) [inline pow/pow.go]: You can delete this interface.

File: pow/ethash.go [hunk 5]
```diff
@@ -0,0 +1,579 @@
...
+				logger.Error("Failed to allocate new ethash cache", "err", err)
+			} else {
+				// Dump allocates, map for writing and fill
+				dump.Close()
+
+				c.dump, c.mmap, c.cache, err = memoryMap(path, true)
+				if err != nil {
+					logger.Error("Failed to memory map ethash cache", "err", err)
+				}
+			}
```
Comment (fjl) [inline pow/ethash.go]: This is unsafe if multiple processes try to generate the same DAG. You can work around it by creating the file with a temporary name first (e.g. ".full-R23-hash.<pid>.tmp") then moving it into place after writing. AFAIK there is no need to remap the file after the move (not sure about Windows though).

Comment (fjl) [inline pow/ethash.go]: Same for caches.

Comment (fjl) [inline pow/ethash.go]: A follow-up question would be how those `.tmp` would get deleted after a process crash. Maybe leave a TODO comment about this.

Comment (fjl) [inline pow/ethash.go]: This test succeeds with nprocs=1 but fails with nprocs=3:

```go
func TestDiskCacheConcurrent(t *testing.T) {
	tmpdir, err := ioutil.TempDir("", "ethash-test")
	if err != nil {
		t.Fatal(err)
	}
	block := types.NewBlockWithHeader(&types.Header{
		Number:      big.NewInt(3311058), // Ethereum main net
		ParentHash:  common.HexToHash("0xd783efa4d392943503f28438ad5830b2d5964696ffc285f338585e9fe0a37a05"),
		UncleHash:   common.HexToHash("0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"),
		Coinbase:    common.HexToAddress("0xc0ea08a2d404d3172d2add29a45be56da40e2949"),
		Root:        common.HexToHash("0x77d14e10470b5850332524f8cd6f69ad21f070ce92dca33ab2858300242ef2f1"),
		TxHash:      common.HexToHash("0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"),
		ReceiptHash: common.HexToHash("0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"),
		Difficulty:  big.NewInt(167925187834220),
		GasLimit:    big.NewInt(4015682),
		GasUsed:     big.NewInt(0),
		Time:        big.NewInt(1488928920),
		Extra:       []byte("www.bw.com"),
		MixDigest:   common.HexToHash("0x3e140b0784516af5e5ec6730f2fb20cca22f32be399b9e4ad77d32541f798cd0"),
		Nonce:       types.EncodeNonce(0xf400cd0006070c49),
	})

	var wg sync.WaitGroup
	nprocs := 3
	wg.Add(nprocs)
	for i := 0; i < nprocs; i++ {
		go func() {
			defer wg.Done()
			ethash := NewFullEthash(tmpdir, 0, 1, "", 0, 0)
			if err := ethash.Verify(block); err != nil {
				t.Error(err)
			}
		}()
	}
	wg.Wait()
}
```

File: pow/pow.go (hunk 4 above)
Comment (karalabe) [inline pow/pow.go]: Already down in my PoA PR which cleans up the package as a whole (also dropping Blocks). Will rather postpone to that.

File: pow/ethash.go (hunk 5 above)
Comment (karalabe) [inline pow/ethash.go]: Thanks for the test. Albeit I figured caches won't conflict since they go into different folders and I don't expect people to mine with multi processes (especially with dag rotation). The problem nonetheless stands. Will try to fix.

A side effect is that if geth crashes (terminates) while generating a DAG/cache, currently that will corrupt it and we'll never know. So this is actually a better solution.

**Comment by karalabe** [comment]
@fjl PTAL

I've implemented the generate-rename-open mechanism. This passes your test that generate the same things concurrently, at it should also solve issues if a generation is aborted midway through (i.e. no junk will be left there in the main file to be loaded the next time).

I also modified the log levels a bit. They now report epochs instead of seeds. Dropped the "generating...", and modified the "generated" so that it's only displayed if it took more than 3 seconds. The rationale is that embedded devices which might take 1+ minutes to generate a mainned dag should not just hang with no output.

Btw, a more elegant solution to logging the epochs inside generateCache and generateDataset would be to pass in a logger instance that already has the epoch, instead of passing the epoch just to make a logger out of it. Unfortunately this screws up Go's optimizer/inliner/something, as the performance drops by 50%. Making the logger inside is fast.

File: pow/ethash.go [hunk 6]
```diff
@@ -0,0 +1,612 @@
...
+				}
+				generateDataset(dataset, d.epoch, cache)
+
+				// Generation succeeded, close and move in to final position
+				mem.Unmap()
+				dump.Close()
+
+				os.Rename(temp, path)
+
+				d.dump, d.mmap, d.dataset, err = memoryMap(path, false)
```
Comment (fjl) [inline pow/ethash.go]: Can the mapping stay established? It should work.

Comment (fjl) [inline pow/ethash.go]: Please move the memory mapping logic into its own function, e.g.

```go
generateMappedFile(dir, name, size, func (dataset []uint32) { generateDataset(dataset, d.epoch, cache) })
```

This way it can be reused for both cache and DAG.

**Comment by karalabe** [comment]
@fjl Done, PTAL

File: pow/ethash.go [hunk 7]
```diff
@@ -0,0 +1,581 @@
...
+	// Try to open the file and memory map it
+	var (
+		file *os.File
+		mem  mmap.MMap
+		err  error
+	)
+	if write {
+		file, err = os.OpenFile(path, os.O_RDWR, os.ModePerm)
+	} else {
+		file, err = os.OpenFile(path, os.O_RDONLY, os.ModePerm)
```
Comment (fjl) [inline pow/ethash.go]: `os.ModePerm` is supposed to be used as a *mask*. Its value is `0777`, all files will be created with read/write/execute permission for all users. It would be better to use a sane mode like `0644`.

File: pow/ethash.go [hunk 8]
```diff
@@ -0,0 +1,581 @@
...
+	}
+	if write {
+		mem, err = mmap.Map(file, mmap.RDWR, 0)
+	} else {
+		mem, err = mmap.Map(file, mmap.RDONLY, 0)
+	}
+	if err != nil {
+		file.Close()
+		return nil, nil, nil, err
+	}
```
Comment (fjl) [inline pow/ethash.go]: The logic is more complicated than it needs to be. You can just do:

```go
flag, mapflag := os.O_RDONLY, mmap.RDONLY
if write {
    flag, mapflag = os.O_RDWR, mmap.RDWR
}
file, err := os.OpenFile(path, flag, 0644)
if err != nil {
    return nil, nil, nil, err
}
mem, err := mmap.Map(file, mapflag, 0)
if err != nil {
    file.Close()
    return nil, nil, nil, err
}
```

File: pow/ethash.go [hunk 9]
```diff
@@ -0,0 +1,572 @@
...
+	dump.Close()
+
+	// Memory map the file for writing and fill it with the generator
+	dump, mem, buffer, err := memoryMap(temp, true)
+	if err != nil {
+		return nil, nil, nil, err
+	}
+	generator(buffer)
+
```
Comment (fjl) [inline pow/ethash.go]: Please add an error-checked call to `mem.Flush()` here.

File: pow/ethash.go [hunk 10]
```diff
@@ -0,0 +1,572 @@
...
+	temp := path + "." + strconv.Itoa(rand.Int())
+
+	dump, err := os.Create(temp)
+	if err != nil {
+		return nil, nil, nil, err
+	}
+	if err = dump.Truncate(int64(size)); err != nil {
+		return nil, nil, nil, err
+	}
+	dump.Close()
```
Comment (fjl) [inline pow/ethash.go]: Now that I look at this again, it looks weird that you're closing the file and reopen it just below. You can reuse the file that's already open.

File: pow/ethash.go [hunk 11]
```diff
@@ -0,0 +1,572 @@
...
+
+		// No previous dataset available, create a new cache file to fill
+		cache := make([]uint32, csize/4)
+		generateCache(cache, d.epoch, seed)
+
+		d.dump, d.mmap, d.dataset, err = memoryMapAndGenerate(path, dsize, func(buffer []uint32) { generateDataset(buffer, d.epoch, cache) })
+		if err != nil {
+			logger.Error("Failed generate mapped ethash dataset", "err", err)
+
+			d.dataset = make([]uint32, dsize/2)
```
Comment (fjl) [inline pow/ethash.go]: I'm not sure I like how errors are handled here. If memory mapping fails because of an out of memory condition, this allocation will crash the process. We could avoid that by always using mmap. If no file is needed (path is ""), the mmap call can use the ANON option to allocate a non-file-backed buffer. If that fails, Search/Verify simply can't do any work.

Comment (karalabe) [inline pow/ethash.go]: People will not use in memory DAGs anyway, this is only useful for testing. And for that we don't really care.

Comment (fjl) [inline pow/ethash.go]: The issue is that it will always try generate it in memory if mmap fails.

Comment (fjl) [inline pow/ethash.go]: What I'm trying to say: Go handles allocation failures by crashing. This is usually OK, but hurts if the program deals with large buffers like we do here. Using mmap means we can handle allocation errors gracefully.

File: pow/ethash.go (hunk 9 above)
Comment (karalabe) [inline pow/ethash.go]: Fixed. PTAL

File: pow/ethash.go (hunk 10 above)
Comment (karalabe) [inline pow/ethash.go]: Fixed. PTAL

File: pow/ethash.go (hunk 11 above)
Comment (karalabe) [inline pow/ethash.go]: This would require extra code to track that generation failed and handle that in Search/Verify. Given that there's no meaningful way to get out of this problem, we might as well crash :P

**Comment by fjl** [comment]
Will merge when CI is done.
