### PR TITLE
cmd/geth, cmd/devp2p: fix some cli parsing issues

### LINKED ISSUE #25209: geth account import flags no longer work
#### System information

Geth version: version 1.10.20 @ commit 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8
OS & Version: linux
Commit hash : 8f2416a89a3def6ec2c749d5afafbf2c9a18e3c8

#### Expected behaviour

It works

#### Actual behaviour

```
Fatal: keyfile must be given as the only argument
exit status 1
```

#### Steps to reproduce the behaviour

```
go run ./cmd/geth account import /tmp/key --datadir=/tmp/eth --keystore=/tmp/keystore --password=/tmp/pass
```

#### Backtrace

````
Fatal: keyfile must be given as the only argument
exit status 1

````

When submitting logs: please submit them as text and not screenshots.

### LINKED ISSUE #25224: `attach --exec` opens up the interactive console and does not log the result
#### System information

Geth version: ```
Geth
Version: 1.10.20-stable
Architecture: amd64
Go Version: go1.18.3
Operating System: linux
GOPATH=
GOROOT=go```
OS & Version: Ubuntu 20.04 LTS
Commit hash : -

Latest geth seems to have broken `attach` behavior - the `--exec` flag does nothing.

#### Expected behaviour
`--exec` prints out result and quits

#### Actual behaviour
`--exec` prints out nothing and opens up the interactive console.

#### Steps to reproduce the behaviour
Run any command with attach using `--exec` on v1.10.20

#### Backtrace

````
root@Ubuntu-2004-user ~/eth-node # ./geth_ethereum attach /root/eth-node/datadir/geth.ipc --exec "admin.nodeInfo"
Welcome to the Geth JavaScript console!

instance: Geth/v1.10.20-stable/linux-amd64/go1.18.3
at block: 15057827 (Fri Jul 01 2022 19:05:44 GMT+0200 (CEST))
datadir: /root/eth-node/datadir
modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d or type exit
>
````

image
Also seems to be reproduced by discord user schone#2266.

### PR DESCRIPTION
**Pull request by fjl**
This resolves a few regressions from the cli/v2 migration.

Closes #25224 
Closes #25209

### CODE REVIEW

File: cmd/geth/chaincmd.go [hunk 1]
```diff
@@ -166,10 +166,12 @@ This command dumps out the state for a given block (or latest, if none provided)
 // initGenesis will initialise the given JSON format genesis file and writes it as
 // the zero'd block (i.e. genesis) or will fail hard if it can't succeed.
 func initGenesis(ctx *cli.Context) error {
-	// Make sure we have a valid genesis JSON
+	if ctx.Args().Len() != 1 {
```
Comment (MariusVanDerWijden) [inline cmd/geth/chaincmd.go:169]: Can we not have more arguments? Later on we call `makeConfigNode` which probably expects more args as well

File: cmd/geth/chaincmd.go [hunk 2]
```diff
@@ -166,10 +166,12 @@ This command dumps out the state for a given block (or latest, if none provided)
...
+		utils.Fatalf("need genesis.json file as the only argument")
+	}
 	genesisPath := ctx.Args().First()
 	if len(genesisPath) == 0 {
-		utils.Fatalf("Must supply path to genesis JSON file")
+		utils.Fatalf("invalid path to genesis.json file")
```
Comment (gballet) [inline cmd/geth/chaincmd.go:174]: the file might not be called `genesis.json`, it has to be a JSON file containing the genesis

File: cmd/geth/chaincmd.go (hunk 1 above)
Comment (fjl) [reply cmd/geth/chaincmd.go:169]: Flags and args are different. `ctx.Args()` contains the non-flag arguments. In `geth init`, we only accept one argument, the genesis file.
