### PR TITLE
eth/catalyst: fix engine API

### LINKED ISSUE #28134: v1.13.0 Error:invalid withdrawals: fork inactive, unexpected attribute set
#### System information

Geth version: `geth 1.13.0`
CL client & version: `prysm Version v4.0.8`
OS & Version: Ubuntu 20.04.6 LTS

#### Actual behaviour

Updated geth to version 1.13.0, enabled pebble, removed LevelDB, synced from scratch (ancients included) with `--state.scheme=path` and then noticed missed proposal.

#### geth log

````
Sep 16 15:44:37 NLDW4-2-37-42 geth[326408]: WARN [09-16|15:44:37.395] Served engine_forkchoiceUpdatedV2        conn=127.0.0.1:56958 reqid=62839                     duration=3.354485ms err="Invalid parameters"            errdata="{Error:invalid withdrawals: fork inactive, unexpected attribute set}"
Sep 16 15:44:47 NLDW4-2-37-42 geth[326408]: WARN [09-16|15:44:47.077] Served engine_forkchoiceUpdatedV2        conn=127.0.0.1:56958 reqid=62841                     duration="221.26µs" err="Invalid parameters"            errdata="{Error:invalid withdrawals: fork inactive, unexpected attribute set}"
````

#### prysm beacon log

````
Sep 16 15:44:47 NLDW4-2-37-42 beacon-chain[262130]: time="2023-09-16 15:44:47" level=error msg="Could not pack deposits and attestations" error="rpc error: code = Internal desc = Could not get attestations to pack into block: could not filter attestations: context canceled" prefix="rpc/validator"
````
#### prysm validator log

````
Sep 16 15:44:47 NLDW4-2-37-42 validator[262177]: time="2023-09-16 15:44:47" level=error msg="Failed to request block from beacon node" blockSlot=[number] error="rpc error: code = Unknown desc = could not build block in parallel: rpc error: code = Internal desc = Could not get local payload: could not prepare payload: invalid method parameter(s)" prefix=validator
````

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #28134

### CODE REVIEW

File: eth/catalyst/api.go [hunk 1]
```diff
@@ -207,21 +207,21 @@ func (api *ConsensusAPI) verifyPayloadAttributes(attr *engine.PayloadAttributes)
...
-	if err := checkAttribute(c.IsCancun, attr.BeaconRoot != nil, attr.Timestamp); err != nil {
+	if err := checkAttribute(c.IsCancun, attr.BeaconRoot != nil, c.LondonBlock, attr.Timestamp); err != nil {
 		return fmt.Errorf("invalid parent beacon block root: %w", err)
 	}
 	return nil
 }
 
-func checkAttribute(active func(*big.Int, uint64) bool, exists bool, time uint64) error {
-	if active(common.Big0, time) && !exists {
+func checkAttribute(active func(*big.Int, uint64) bool, exists bool, block *big.Int, time uint64) error {
```
Comment (rjl493456442) [inline eth/catalyst/api.go:220]: The london block is used to align with line https://github.com/ethereum/go-ethereum/pull/28135/files#diff-96840e4882901b94cef9f51a992a44e64df659335ff13dd011be8c1ffa097135R179

Although I don't think london block is correct here. The block number to generate is the one to pass, IIUC.

Comment (karalabe) [reply eth/catalyst/api.go:220]: The original code passed the weird london block because in merge mode we *know* that we already passed london. So instead of complicating everything with passing a block number, it was a hacky way to hard code "always london".

**Review by karalabe — APPROVED** [review]
LGTM
