### PR TITLE
graphql: add storage slots to access list

### LINKED ISSUE #23640: Graphql service return empty accessList's storageKeys on goerli network data where it should not
I'm using geth's graphql to fetch block header and transactions of goerli net. At block 5000628 and tx no 71, one of the storageKeys is empty, but from JSON-RPC I got non-empty storageKeys. Same thing happened on block 5000647 tx no 42.

But the strange thing is both sender and tx hash returned by graphql query are correct. And using this sender and txhash I'm able to tell that the query result is wrong.

#### System information

Geth
Version: 1.10.8-stable
Git Commit: 26675454bf93bf904be7a43cce6b3f550115ff90
Git Commit Date: 20210824
Architecture: amd64
Go Version: go1.16.4
Operating System: windows

#### Expected behaviour

```json
...
 "accessList": [
    {
      "address": "0x57b96462b8d236cfec75dc9c0e0dcee20a22a7dd",
      "storageKeys": [
        "0x0000000000000000000000000000000000000000000000000000000000000006",
        "0x0000000000000000000000000000000000000000000000000000000000000007",
        "0x0000000000000000000000000000000000000000000000000000000000000008",
        "0x0000000000000000000000000000000000000000000000000000000000000009",
        "0x000000000000000000000000000000000000000000000000000000000000000a",
        "0x000000000000000000000000000000000000000000000000000000000000000c"
      ]
    },
    {
      "address": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
      "storageKeys": []
    },
    {
      "address": "0x4774be14b1e81eb9f78f5d58b061f796fb2c744f",
      "storageKeys": []
    }
]
...
```

#### Actual behaviour
```json
...
"accessList": [
    {
      "address": "0x57b96462b8d236cfec75dc9c0e0dcee20a22a7dd",
      "storageKeys": []
    },
    {
      "address": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
      "storageKeys": []
    },
    {
     "address": "0x4774be14b1e81eb9f78f5d58b061f796fb2c744f",
     "storageKeys": []
    }
]
...
```

#### Steps to reproduce the behaviour

using graphql client such as altair, connect to http://127.0.0.1:8545/graphql
or using geth's built-in client http://127.0.0.1:8545/graphql/ui
then send this query:

```graphql
query getAccessList($blockNumber: Long = 5000628) {  
  block(number: $blockNumber) {    
    transactionAt(index: 71) {
      accessList {
        address
        storageKeys
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by holiman**
I'm not really certain _why_ it didn't work previously, but for some reason, this fixes it. 

```
$ cat query.json 

{"query":"query getAccessList($blockNumber: Long = 5000628) { block(number: $blockNumber) {  transactionAt(index: 71) { accessList { address storageKeys } }  }}","variables":null,"operationName":"getAccessList"}

```

Without this PR: 
```
curl -X POST 'http://localhost:8545/graphql' -H 'Content-Type: application/json'  --data @query.json | jq . 
{
  "data": {
    "block": {
      "transactionAt": {
        "accessList": [
          {
            "address": "0x57b96462b8d236cfec75dc9c0e0dcee20a22a7dd",
            "storageKeys": []
          },
          {
            "address": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
            "storageKeys": []
          },
          {
            "address": "0x4774be14b1e81eb9f78f5d58b061f796fb2c744f",
            "storageKeys": []
          }
        ]
      }
    }
  }
}
```
With this PR: 
```
$ curl -X POST 'http://localhost:8545/graphql' -H 'Content-Type: application/json'  --data @query.json | jq . 
{
  "data": {
    "block": {
      "transactionAt": {
        "accessList": [
          {
            "address": "0x57b96462b8d236cfec75dc9c0e0dcee20a22a7dd",
            "storageKeys": [
              "0x0000000000000000000000000000000000000000000000000000000000000006",
              "0x0000000000000000000000000000000000000000000000000000000000000007",
              "0x0000000000000000000000000000000000000000000000000000000000000008",
              "0x0000000000000000000000000000000000000000000000000000000000000009",
              "0x000000000000000000000000000000000000000000000000000000000000000a",
              "0x000000000000000000000000000000000000000000000000000000000000000c"
            ]
          },
          {
            "address": "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6",
            "storageKeys": []
          },
          {
            "address": "0x4774be14b1e81eb9f78f5d58b061f796fb2c744f",
            "storageKeys": []
          }
        ]
      }
    }
  }
}

```

### CODE REVIEW

File: graphql/graphql.go [hunk 1]
```diff
@@ -440,9 +440,13 @@ func (t *Transaction) AccessList(ctx context.Context) (*[]*AccessTuple, error) {
 	accessList := tx.AccessList()
 	ret := make([]*AccessTuple, 0, len(accessList))
 	for _, al := range accessList {
+		var sKeys []common.Hash
```
Comment (karalabe) [inline graphql/graphql.go:443]: `al := al` would also fix it

Comment (fjl) [reply graphql/graphql.go:443]: Would be even better to change the type of `AccessTuple.storageKeys` to non-pointer.

Comment (holiman) [reply graphql/graphql.go]: fixed, PTAL
