### PR TITLE
utils: fix #16138 by checking if vhosts flag is set

### LINKED ISSUE #16138: HTTPVirtualHosts defined in config file get overridden by RPCVirtualHosts flag
This really threw me for a loop and took me a while to track down.

#### System information

Geth version: `v1.8.0` and `v1.8.1`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

You should be able to set `HTTPVirtualHosts` in your config file without setting the `--rpcvhosts` flag and it should use the virtual hosts defined in the config file.

#### Actual behaviour

Since `RPCVirtualHosts` is `localhost` by default ([as seen here](https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L400-L403)) any virtual hosts defined in the config file are always overridden by `localhost` [here](https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L699)

#### Steps to reproduce the behaviour

In your config file define `HTTPVirtualHosts = ["*"]` and run geth without the `--rpcvhosts` flag. You won't be able to hit your geth node over RPC from anywhere except localhost and you will see this in your logs:

```
INFO [02-20|02:29:38] HTTP endpoint opened                     url=http://0.0.0.0:8545 cors=* vhosts=localhost
INFO [02-20|02:29:38] IPC endpoint opened                      url=/home/ethereum/data/geth.ipc
```

### PR DESCRIPTION
**Pull request by holiman**
Snippet from TOML file
```
[Node]
DataDir = "/tmp/foo"
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPVirtualHosts = ["test.com"]
HTTPModules = ["net", "web3", "eth", "shh"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]

```

Before fix: 

```
#build/bin/geth --config testvhosts.config
[...]
INFO [02-20|13:27:43] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=localhost

```

After fix

```
#build/bin/geth --config testvhosts.config
[...]
INFO [02-20|13:28:57] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=test.com
```
After fix (override)

```
#build/bin/geth --config testvhosts.config --rpcvhosts "foobar"
[...]
INFO [02-20|13:29:11] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=foobar
```

### CODE REVIEW

**Comment by holiman** [comment]
This is borked. It'll never use the defaults...

**Comment by holiman** [comment]
Fixed, ptal. 

Snippet from TOML file
```
[Node]
DataDir = "/tmp/foo"
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPVirtualHosts = ["test.com"]
HTTPModules = ["net", "web3", "eth", "shh"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]

```

Before fix: 

```
#build/bin/geth --config testvhosts.config
[...]
INFO [02-20|13:27:43] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=localhost

```
After fix: 

Defaults: 
```
#build/bin/geth --nodiscover --maxpeers 0  --rpc
[...]
INFO [02-20|14:48:03] HTTP endpoint opened                     url=http://127.0.0.1:8545           cors= vhosts=localhost
``` 

Both toml and cmdline:
```
#build/bin/geth --config testvhosts.config --rpcvhosts "foobar"
[...]
INFO [02-20|14:48:10] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=foobar
```
Only toml: 

```
#build/bin/geth --config testvhosts.config 
[...]
INFO [02-20|14:48:21] HTTP endpoint opened                     url=http://127.0.0.1:8545 cors= vhosts=test.com
INFO [02-20|14:48:21] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv2-IP1"
```

**Comment by holiman** [comment]
> Please move the default value into node.DefaultConfig to make the else if branch unnecessary.

I'm not sure what you mean. Are you talking about `eth.DefaultConfig` or create something new in `node`?

**Comment by karalabe** [comment]
I think Felix meant https://github.com/ethereum/go-ethereum/blob/master/node/defaults.go#L37.

**Comment by karalabe** [comment]
@holiman Please fix if you'd like this merged for 1.8.2

**Comment by holiman** [comment]
Fixed, ptal

File: node/defaults.go [hunk 1]
```diff
@@ -45,6 +45,7 @@ var DefaultConfig = Config{
 		MaxPeers:   25,
 		NAT:        nat.Any(),
 	},
+	HTTPVirtualHosts: []string{"localhost"},
```
Comment (karalabe) [inline node/defaults.go]: Please move this below `HTTPModules` so the HTTP stuff is together.

**Comment by holiman** [comment]
done
