### PR TITLE
signer/core: don't mismatch reject and no accounts

### LINKED ISSUE #21674: Clef returns `request denied` instead of an empty list when there are no accounts to list
When we perform an `account_list` request to clef and there is no hardware wallet plugged-in or keystore files in the keystore directory, Clef errors with a `request_denied`. Seems like a better approach would be to respond with an empty list.

#### System information

Geth version: 1.9.15-stable
OS & Version: OSX

#### Expected behaviour
Return an empty list.

#### Actual behaviour
Errors with `request_denied`.

#### Steps to reproduce the behaviour
* Run clef with no HW wallet and using a keystore directory with no keystore files
* Make an `account_list` request

#### Backtrace

On Clef side: 
```
WARN [10-08|01:35:34.789] Served account_list                      reqid=0 t=6.788424ms               err="request denied"
```

On the requesting application side (using web3py):
```
  
File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/signers/software.py", line 167, in accounts
    normalized_addresses = self.__ipc_request(endpoint="account_list")
  File "/Users/david/NuCypher/dev/nucypher/nucypher/blockchain/eth/signers/software.py", line 136, in __ipc_request
    response = self.w3.manager.request_blocking(endpoint, request_args)
  File "/Users/david/.local/share/virtualenvs/nucypher-cjt3uwkK/lib/python3.8/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'request denied'}
```

### PR DESCRIPTION
**Pull request by holiman**
Now using empty lists instead of `nil` solves #21674

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

File: signer/core/api.go [hunk 1]
```diff
@@ -383,7 +383,7 @@ func (api *SignerAPI) startUSBListener() {
 // List returns the set of wallet this signer manages. Each wallet can contain
 // multiple accounts.
 func (api *SignerAPI) List(ctx context.Context) ([]common.Address, error) {
-	var accs []accounts.Account
+	var accs = make([]accounts.Account, 0)
```
Comment (karalabe) [inline signer/core/api.go:386]: Pls add a comment after so there won't be a future PR reverting this.

**Review by renaynay — APPROVED** [review]

**Comment by ekawibisono** [comment]
Hello, I have a same a problem, Please Help #27056
