### PR TITLE
miner: commit state which is relative with sealing result

### LINKED ISSUE #17441: Failed to reset txpool state
image

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #17441

### CODE REVIEW

File: mobile/types.go [hunk 1]
```diff
@@ -184,8 +184,7 @@ func (b *Block) GetExtra() []byte       { return b.block.Extra() }
 func (b *Block) GetMixDigest() *Hash    { return &Hash{b.block.MixDigest()} }
 func (b *Block) GetNonce() int64        { return int64(b.block.Nonce()) }
 
-func (b *Block) GetHash() *Hash        { return &Hash{b.block.Hash()} }
-func (b *Block) GetHashNoNonce() *Hash { return &Hash{b.block.HashNoNonce()} }
+func (b *Block) GetHash() *Hash { return &Hash{b.block.Hash()} }
```
Comment (karalabe) [inline mobile/types.go]: You can delete these two empty lines imho.
