### PR TITLE
Fix #2710 Filter race: concurrent map read and map write

### LINKED ISSUE #2710: Filter race:  concurrent map read and map write
#### System information

Geth version: `1.3.0` - `1.4.7`, `develop`
OS & Version: Linux & OSX

#### Expected behaviour

No crash, no RPC timeouts

#### Actual behaviour

geth crashes

#### Steps to reproduce the behaviour

Adding and deleting filters in fast succession.

#### Backtrace

This is a `1.4.6` backtrace. The race was recreated for the same results in `1.3.6`, `1.4.4` and `1.4.7` and code compared with all `1.3.x`, `1.4.x` and `develop`.

````
fatal error: concurrent map read and map write

goroutine 17456 [running]:
runtime.throw(0x1131ba0, 0x21)
        /tmp/go/src/runtime/panic.go:547 +0x90 fp=0xc838a00f80 sp=0xc838a00f68
runtime.mapaccess2_faststr(0xcedae0, 0xc820430390, 0xc83a9ee060, 0x22, 0x0, 0x428fd7)
        /tmp/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc838a00fe0 sp=0xc838a00f80
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc821af0000, 0xc83a9ee060, 0x22, 0x0, 0x0, 0x0)
        /tmp/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/api.go:528 +0x6d fp=0xc838a01048 sp=0xc838a00fe0
runtime.call64(0xc8221a3000, 0xfab5c8, 0xc83a9ee0c0, 0x1800000030)
        /tmp/go/src/runtime/asm_amd64.s:473 +0x3e fp=0xc838a01090 sp=0xc838a01048
reflect.Value.call(0xdc3520, 0xfab5c8, 0x13, 0xffb310, 0x4, 0xc83a9ee090, 0x2, 0x2, 0x0, 0x0, ...)
        /tmp/go/src/reflect/value.go:435 +0x120d fp=0xc838a013e0 sp=0xc838a01090
reflect.Value.Call(0xdc3520, 0xfab5c8, 0x13, 0xc83a9ee090, 0x2, 0x2, 0x0, 0x0, 0x0)
        /tmp/go/src/reflect/value.go:303 +0xb1 fp=0xc838a01440 sp=0xc838a013e0
````

### PR DESCRIPTION
**Pull request by hdiedrich**
Filter problems mostly revealed themselves successively after fixing each preceding one. This patch addresses all of them as each fix leads to crashes into the next bug.

This patch started from and addresses the issue #2710 **Filter race: concurrent map read and map write**

Our tests add and delete filters in fast succession, on weak hardware, which looks like a realistic use case in the light of the lack of relative block range parameters for filters.

I am trying to make our tests available. The existing test suits catch none of them.

1. UninstallFilter() missed logMu, blockMu and transactionMu locks before the filter id existence checks in respective queues.

2. GetFilterLogs() is missing a filterMapMu read lock. GetFilterChanges() could use read locks instead of write locks given it's a RWMutex.

3. NewBlockFilter() leaves blockMu lock hanging on failing filterManager.Add(). This should virtually never happen except for out of memory in exactly that place but there is a return handling it.

4. Filters are deadlocking through the call backs called by filterLoop() deadlocking FilterUninstall(), NewBlockFilter() etc:  

    * the former, filterLoop(), first acquires sf.filterMu, then the callbacks try for s.logMu, blockMu or transactionMu. 
    * The latter first acquire s.logMu, blockMu or transactionMu and then by calling filterManager.Add() or Remove() try for sf.filterMu. The solution of this patch is not the prettiest but least invasive.

5. wrong lock set, logMu instead if transactionMu, in transactionFilterChanged().

6. transactMu (sic) is not used.

Adding comments for implicit deadlock risk seemed appropriate to help future refactoring.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jun 17 08:57:01 UTC 2016_

File: eth/filters/api.go [hunk 1]
```diff
@@ -445,33 +442,37 @@ func (s *PublicFilterAPI) GetLogs(args NewFilterArgs) []vmlog {
...
-
 	id, ok := s.filterMapping[filterId]
 	if !ok {
 		return false
 	}
-
-	defer s.filterManager.Remove(id)
 	delete(s.filterMapping, filterId)
 
+	s.filterManager.Remove(id) // call inside logMu, blockMu, transactionMu deadlocks filterLoop()
```
Comment (hdiedrich) [inline eth/filters/api.go]: thoughts on this one appreciated

File: eth/filters/api.go [hunk 2]
```diff
@@ -203,15 +201,14 @@ func (s *PublicFilterAPI) NewPendingTransactionFilter() (string, error) {
 
 // newLogFilter creates a new log filter.
 func (s *PublicFilterAPI) newLogFilter(earliest, latest int64, addresses []common.Address, topics [][]common.Hash, callback func(log *vm.Log, removed bool)) (int, error) {
-	s.logMu.Lock()
-	defer s.logMu.Unlock()
-
 	filter := New(s.chainDb)
-	id, err := s.filterManager.Add(filter, LogFilter)
+	id, err := s.filterManager.Add(filter, LogFilter) // use inside logMu deadlocks filterLoop()
```
Comment (bas-vk) [inline eth/filters/api.go]: Could you explain?
> use inside logMu deadlocks filterLoop()

Locking after the Add could lead to missing logs when logs are raised and the new filter is not added to the logQueue. Afaik a deadlock is not feasible but it could stall the filterloop for a brief time when the function has not returned and new logs are generated that match the filter criteria.

File: eth/filters/api.go [hunk 3]
```diff
@@ -100,10 +98,11 @@ done:
 	for {
 		select {
 		case <-timer.C:
+			s.filterManager.Lock()
 			s.logMu.Lock()
 			for id, filter := range s.logQueue {
 				if time.Since(filter.timeout) > filterTickerTime {
-					s.filterManager.Remove(id)
+					s.filterManager.RemoveWhileLocked(id)
```
Comment (bas-vk) [inline eth/filters/api.go]: Why use external locking for the filter manager, performance?

**Comment by bas-vk** [comment]
Thx for this PR, highly appreciated.

File: eth/filters/api.go (hunk 3 above)
Comment (hdiedrich) [inline eth/filters/api.go]: Because of 4. in the original PR description. In the lines you quote, without the PR, logMu is acquired first, then Remove() tries to get sf.filterMu. While filterLoop() can concurrently first acquire sf.filterMu then through a callback (1) try to get logMu (2).

(1) https://github.com/ethereum/go-ethereum/blob/develop/eth/filters/filter_system.go#L158
(2) https://github.com/ethereum/go-ethereum/blob/develop/eth/filters/api.go#L225

File: eth/filters/api.go (hunk 2 above)
Comment (hdiedrich) [inline eth/filters/api.go]: Thanks a lot, you mean this could result into a read/write race here:
https://github.com/ethereum/go-ethereum/blob/develop/eth/filters/filter_system.go#L166 ?

That should be changed the same way that Remove works then, I guess. The comment holds, if Add() is called while logMu is held, then because Add() tries for sf.filterMu, it can deadlock filterLoop which can through the callbacks try the same locks in reverse order.

File: eth/filters/api.go (hunk 1 above)
Comment (hdiedrich) [inline eth/filters/api.go]: Your thoughts on this are appreciated.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3b68f9c645f872ca27857cbaef2f6dfec63db2db
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by hdiedrich** [comment]
Included Add() into the lock range. Commits will be squashed. It is more obvious now that all locks except filterMu could be thrown out. The potentially concurrent use of the same iterators, once for the outer, in other places for the inner loop results into there really just being complete mutual exclusion as approach. There is only one place where logMu might speed things up.

Regardless, we also tested this patch intensively, on 1.4.6, and it works for us, as did the original PR. The problems we ran into as listed above did not resurface.

We don't have a good way to make the tests available because they are deeply embedded in our system. We're happy to share the scripts but it might be hard to make sense of them with a lot of context missing. In essence, we just let them run very long on a local test net, keeping at the same stuff.

I know I am talking to myself, happy DAO hunting, who cares about some races in Ethereum core code :D

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3b68f9c645f872ca27857cbaef2f6dfec63db2db
  * Commits must be prefixed with the package(s) they modify

 * Commit: e69ebc6601ac31362b7c7e54c4ff26dd2cd70088
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Exposing locks across a package boundary (by adding FilterSystem.Lock) is not a good idea.
We can live with it temporarily if there is a better solution on the horizon, but it looks like a kludge
to me. The better solution would be to rework eth/filters so that less locking is required.

**Comment by hdiedrich** [comment]
This is the minimal invasive patch that works after intensive testing. Compared to what is published now, a breaking client, the counter argument sounds academic. Agree that it should best be rewritten, as proposed above, resulting into a single lock, or better yet as you showed me last week. As asked earlier, please consider to apply this patch in the mean time, allowing us to come back to a lesser patched geth asap. Thanks a lot!

**Comment by bas-vk** [comment]
We can include this for now since it fixes a bug. But its very complicated and dangerous with external and internal locking of the filter system. For instance `FilterSystem.Get` locks internally the filter system, if used within a function that has locked the filter system from the outside this will deadlock.

I have a new implementation of the filter package but it needs a bit more testing. When the whole DAO situation is handled we can focus on that. Until that moment has come this looks good enough to be included 👍.

**Comment by karalabe** [comment]
@hdiedrich Could you please squash the commits? We'd like to do a release today including this fix :)

**Comment by hdiedrich** [comment]
@karalabe squashed, thx

**Comment by obscuren** [comment]
Thanks @hdiedrich

**Comment by karalabe** [comment]
@fjl Could you please double check this and merge if it's fine? As you already read through it once I think it's better if you checked it.
