### PR TITLE
cmd/evm, core/vm, internal/ethapi: don't disable call gas metering

### LINKED ISSUE #16193: Regression in 1.8.x: call to contract with ecrecover/sha256 always returns `0x`
This bug manifests itself by RPC decoding errors such as the one returned by web3:

```
Error: Couldn't decode address from ABI: 0x
```

#### System information

Geth version: `Geth/v1.8.1-stable-1e67410e/darwin-amd64/go1.9.4`
OS & Version: OSX 10.13.3 (17D47)

#### Expected behaviour
`eth.call` (`eth_call`) should return the result of the operation.

#### Actual behaviour
The string `0x` is returned.

#### Steps to reproduce the behaviour
 * Get the repro code from https://gist.github.com/lionello/522e6a583e373ac745ee55f265380908
 * Run a Geth node on localhost with RPC on port 8545
```
geth --dev --rpc --rpcapi personal,eth
```
 * Run `./repro181.js` (nodeJS)

#### Backtrace
The Geth console shows only the following message with `--verbosity`:
```
DEBUG[02-26|16:29:52] Executing EVM call finished              runtime=183.253µs
DEBUG[02-26|16:29:52] Executing EVM call finished              runtime=209.303µs
DEBUG[02-26|16:29:52] VM returned with error                   err="evm: execution reverted"
DEBUG[02-26|16:29:52] Executing EVM call finished              runtime=209.662µs
```

### PR DESCRIPTION
**Pull request by karalabe**
Fixes #16193 

Our VM currently supports disabling gas metering, which was forcefully enabled for `eth_call`. Unfortunately, not all code paths check properly this debug property. This issue didn't surface until https://github.com/ethereum/go-ethereum/pull/15563 was merged, which started tracking some gas dynamics off the stack. These calculations didn't happen any more with `DisableGasMetering == true`, resulting in CALLs to precompiles to be done with gas 0. Apparently, some code didn't get the memo that gas metering was disabled and failed the call with OOG.

This PR gets rid of `DisableGasMetering` altogether. **This might not be the best approach**, since then gas calculation will be incurred with any `eth_call`. The reasons I did it like this is because 1) eth_call will behave exactly as eth_sendTransaction, which is arguably good; and 2) it seems dangerous to me especially long term that we'll have similar breakages.

Open to feedback or alternative proposals.

### CODE REVIEW

File: internal/ethapi/api.go [hunk 1]
```diff
@@ -642,11 +642,8 @@ func (s *PublicBlockChainAPI) doCall(ctx context.Context, args CallArgs, blockNr
 	// Setup context so it may be cancelled the call has completed
 	// or, in case of unmetered gas, setup a context with a timeout.
 	var cancel context.CancelFunc
-	if vmCfg.DisableGasMetering {
-		ctx, cancel = context.WithTimeout(ctx, time.Second*5)
-	} else {
-		ctx, cancel = context.WithCancel(ctx)
-	}
+	ctx, cancel = context.WithCancel(ctx)
+
```
Comment (fjl) [inline internal/ethapi/api.go]: Please keep the time limit and set gas to `^uint64(0)`.

Comment (karalabe) [reply internal/ethapi/api.go]: The default gas price is 50M if the user didn't provide any. We can increase that to maybe max uint64/2. https://github.com/ethereum/go-ethereum/issues/16160 reports issues originating from refunds, which I assume originate from specifying max uint64 as ga limit

**Comment by karalabe** [comment]
@fjl PTAL

File: internal/ethapi/api.go [hunk 2]
```diff
@@ -642,14 +642,11 @@ func (s *PublicBlockChainAPI) doCall(ctx context.Context, args CallArgs, blockNr
 	// Setup context so it may be cancelled the call has completed
 	// or, in case of unmetered gas, setup a context with a timeout.
 	var cancel context.CancelFunc
-	if vmCfg.DisableGasMetering {
-		ctx, cancel = context.WithTimeout(ctx, time.Second*5)
-	} else {
-		ctx, cancel = context.WithCancel(ctx)
-	}
+	ctx, cancel = context.WithTimeout(ctx, time.Second*5)
```
Comment (fjl) [inline internal/ethapi/api.go]: I hope you're aware that doCall is used for gas estimation, too. I'm unsure if the timeout and increased default gas can be an issue there.

**Comment by lionello** [comment]
Dare I say "missing test case"?

File: internal/ethapi/api.go (hunk 2 above)
Comment (karalabe) [reply internal/ethapi/api.go]: I hate these hard coded crap.

Gas estimation is based on binary search. I.e. it always needs an upper limit, which is set to either what the user supplies, or the current block limit. Both cases should be fine from a runtime perspective. But yes, this does tag on an extra timeout, which might be undersirable (heck, why do even do a non configurable hard coded timeout in the first place).

**Comment by karalabe** [comment]
@lionello EVM behavior needs to be covered by consensus tests, RPC by RPC tests. The former are integrated into hive whilst the latter was being worked on to be part of hive, but got neglected at a certain point. Yes, tests are definitely needed, but it's better to pick up the hive suite and make it work than to hack in a very specific test for this case only.

**Comment by raindecastro** [comment]
Hey @karalabe i'm not really that experienced when it comes to this and wondering if you could help me out too. I also have a function in my smart contract that returns a hash by using SHA256 and have deployed it to the private blockchain that i've created. Now when I call this function it only returns '0x' 

I have tried to do this inside the testrpc and it seems to be working and returns the correct digest but I want to be able to make it work in my own private blockchain.

How will I be able to apply the solution you have suggested in order for it to work. Please, I need it for some testing in my school project.

**Comment by lionello** [comment]
@raindecastro Make sure there's a contract at the address you expect by calling `eth.getCode("0x...")` first. The same behavior happens when the contract deployment fails, for whatever reason.

**Comment by raindecastro** [comment]
@lionello hey there! thank you so much! Now it works! looks like my deployment did fail when I was trying it. Maybe it was because I didn't have enough gas? Is it correct that I have to put gas in the precompiled contracts or just sufficient amount of gas inside my contract itself? I'm trying to understand the cause of the problem more, i'm sorry for the beginner questions, i've been searching for information about precompiled contracts and it gets confusing for me.
