### PR TITLE
rpc: to in eth_call no longer required. Fixed eth_estimateGas

### LINKED ISSUE #1040: eth_estimateGas requires {to: ..} ?
RPC logs: 

```
PAYLOAD { jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: 
   [ { data: '0x5b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055505b6102af8061003b6000396000f3006000357c0100000000000000000000000000000000000000000000000000000000900480633284fd791461004557806370a0823114610062578063ccb767ae1461007d57005b61005c60048035906020018035906020015061009a565b60006000f35b610073600480359060200150610150565b8060005260206000f35b6100946004803590602001803590602001506101a1565b60006000f35b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561014b5780600060005060008473ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282829054906101000a900463ffffffff160192506101000a81548163ffffffff021916908302179055505b5b5050565b6000600060005060008373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900463ffffffff1663ffffffff16905061019c565b919050565b8063ffffffff16600060005060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900463ffffffff1663ffffffff1610156101f6576102ab565b80600060005060003373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282829054906101000a900463ffffffff160392506101000a81548163ffffffff0219169083021790555080600060005060008473ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282829054906101000a900463ffffffff160192506101000a81548163ffffffff021916908302179055505b505056',
       from: undefined } ],
  id: 3 }
RESULT { id: 3,
  jsonrpc: '2.0',
  error: { code: -32602, message: 'to not valid, is required' } }
```

`to:` is unknown in case you're creating a contract. Would it be possible to make this optional?

### PR DESCRIPTION
**Pull request by obscuren**
Fixes #1040

### CODE REVIEW

File: rpc/api/args_test.go [hunk 1]
```diff
@@ -932,15 +932,6 @@ func TestCallArgsNotStrings(t *testing.T) {
 	}
 }
 
-func TestCallArgsToEmpty(t *testing.T) {
```
Comment (tgerring) [inline rpc/api/args_test.go]: This test could be left in by changing the check that `from` is populated correctly and `to` is nil

Comment (obscuren) [inline rpc/api/args_test.go]: Agreed. Will adjust

File: rpc/api/args_test.go [hunk 2]
```diff
@@ -935,9 +935,9 @@ func TestCallArgsNotStrings(t *testing.T) {
 func TestCallArgsToEmpty(t *testing.T) {
 	input := `[{"from": "0xb60e8dd61c5d32be8058bb8eb970870f07233155"}]`
 	args := new(CallArgs)
-	str := ExpectValidationError(json.Unmarshal([]byte(input), &args))
-	if len(str) > 0 {
-		t.Error(str)
+	err := json.Unmarshal([]byte(input), &args)
+	if err != nil {
```
Comment (tgerring) [inline rpc/api/args_test.go]: Not as precise as validating the field content, but in the case that we're only checking the requirement of "To" or not, this will suffice

**Comment by zelig** [comment]
:+1:

**Comment by bas-vk** [comment]
:+1:
