### PR TITLE
les: wait all task routines before drop the peer

### LINKED ISSUE #20008: LES `panic` due to nil balance tracker
Happens on latest master,  `v1.9.2` is not affected.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7c3b6]
goroutine 8918 [running]:
github.com/ethereum/go-ethereum/les.(*balanceTracker).requestCost(0x0, 0x91fa8)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/balance.go:258 +0x26
  github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func2(0xf4711b098e35afa1, 0xc0, 0xc098b47540, 0x5f42c0)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:246 +0x246
  github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg.func3(0xc04ada5240, 0xc077a50148, 0xc0b5ad84e0, 0xc048569220, 0xc045965680, 0xc0b383ed80)
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:362 +0xc96
  created by github.com/ethereum/go-ethereum/les.(*serverHandler).handleMsg
      /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/les/server_handler.go:276 +0xd9c
```

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #20008

### CODE REVIEW

File: les/peer.go [hunk 1]
```diff
@@ -94,6 +94,8 @@ type peer struct {
 	sendQueue *execQueue
 
 	errCh chan error
+	wg    sync.WaitGroup // Wait group used to track all in-flight task routines.
```
Comment (zsfelfoldi) [inline les/peer.go]: Actually this does not need to be a part of the peer struct because it is only used in the handler.

File: les/server_handler.go [hunk 2]
```diff
@@ -273,7 +276,9 @@ func (h *serverHandler) handleMsg(p *peer) error {
 		}
 		query := req.Query
 		if accept(req.ReqID, query.Amount, MaxHeaderFetch) {
+			p.wg.Add(1)
```
Comment (zsfelfoldi) [inline les/server_handler.go]: This could be a part of the `accept` function. You can leave it like this though if you think it improves readability.

File: les/clientpool.go [hunk 3]
```diff
@@ -378,6 +374,18 @@ func (f *clientPool) setLimits(count int, totalCap uint64) {
 	})
 }
 
+// requestCost feeds request cost after serving a request from the given peer.
+func (f *clientPool) requestCost(p *peer, cost uint64) {
```
Comment (zsfelfoldi) [inline les/clientpool.go]: Why did you remove the `balanceTracker` link from `peer` and use this function instead? We can do this if there is a good reason, I'm just curious why you needed this extra function and extra map lookup every time the stats are updated.

Comment (rjl493456442) [reply les/clientpool.go]: I think balanceTracker is just to collect stat for clientpool, so other components other than clientpool should not know and maintain these things.

Although we introduce another map lookup, it's really trivial. I think it's easier to maintain.

**Comment by rjl493456442** [comment]
Updated, please take another look

**Comment by karalabe** [comment]
Seems to spit out many many "already registered" errors.

```

Aug 27 10:35:33 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:33.499] Light Ethereum peer registration failed  id=8a3a52908ed4b8c1 conn=inbound err="peer is already registered"
Aug 27 10:35:33 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:33.684] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
Aug 27 10:35:33 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:33.846] Light Ethereum peer registration failed  id=f5ecaa5082047add conn=inbound err="peer is already registered"
Aug 27 10:35:35 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:35.907] Light Ethereum peer registration failed  id=146d2848d1696700 conn=inbound err="peer is already registered"
Aug 27 10:35:42 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:42.437] Light Ethereum peer registration failed  id=f99c61e51dd60300 conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:42.940] Light Ethereum peer registration failed  id=c5ea0b523c03334b conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:42.970] Light Ethereum peer registration failed  id=c7e62a8a8604bd70 conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.026] Light Ethereum peer registration failed  id=cd69a5af62072fa1 conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.222] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.228] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.358] Light Ethereum peer registration failed  id=584cc8d94b362df1 conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.360] Light Ethereum peer registration failed  id=df0efadee2c53c7b conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.812] Light Ethereum peer registration failed  id=e30d75bcb8e119fb conn=inbound err="peer is already registered"
Aug 27 10:35:43 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:43.875] Light Ethereum peer registration failed  id=370d1b0b8770956e conn=inbound err="peer is already registered"
Aug 27 10:35:44 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:44.089] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
Aug 27 10:35:44 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:44.195] Light Ethereum peer registration failed  id=d42e33416f35cdc4 conn=inbound err="peer is already registered"
Aug 27 10:35:44 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:44.280] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
Aug 27 10:35:44 bootnode-azure-australiaeast-001 geth: ERROR[08-27|07:35:44.315] Light Ethereum peer registration failed  id=f7a7ab4b5038bf5e conn=inbound err="peer is already registered"
```
