### PR TITLE
node: fix websocket connection header check

### LINKED ISSUE #21525: 404 not found for WS connection on windows server
Hi, I can't do any RPC request to my node via WS. On an attempt to connect to it I got an error 404 not found. This issue occurs with the latest geth v1.9.20  on dedicated Server. At home, I have version 1.9.18 and it works fine with my code. I tried to connect to it locally and from home- the same issue. Node works fine via HTTP connection. I tried to change the port to other value, it didn't help.

My file of configuration:

```
[Node]
DataDir = "C:\\Eth Nodes\\Geth"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8081
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["web3", "eth", "net", "db", "txpool", "admin"]
WSHost = "0.0.0.0"
WSOrigins = ["*"]
WSPort = 10000
WSModules = ["web3", "eth", "net", "db", "txpool", "admin"]
GraphQLVirtualHosts = ["localhost"]

```

#### System information

Geth version: v1.9.20
OS & Version: Windows Server 2019 Standart

#### Expected behaviour
ws connection should work

#### Actual behaviour
ws connection crashed with 404 error

UPD1:
I use c# library Nethereum, version 3.8.0 to communicate with geth

UPD2:
I think the issue is Connection header

Nethereum request looks like:

```
GET http://127.0.0.1:8888/ HTTP/1.1
Connection: Upgrade,Keep-Alive
Upgrade: websocket
Sec-WebSocket-Key: K+ysZX+D3PT+zeo6zzE4ig==
Sec-WebSocket-Version: 13
Host: 127.0.0.1:8888
```

https://github.com/ethereum/go-ethereum/blob/c0c01612e95dd20f125154646b38283ab780f357/node/rpcstack.go#L316
here code expects only one value

Nethereum can't modify the Connection header.

### PR DESCRIPTION
**Pull request by fjl**
Fixes #21525

### CODE REVIEW

**Review by renaynay — APPROVED** [review]

File: node/rpcstack_test.go [hunk 1]
```diff
@@ -73,6 +73,20 @@ func TestWebsocketOrigins(t *testing.T) {
 	assert.Error(t, err)
 }
```
Comment (renaynay) [inline node/rpcstack_test.go:75]:
```suggestion
// TestIsWebsocket tests if an incoming websocket upgrade request is handled properly.
```

**Review by renaynay — APPROVED** [review]

**Review by holiman — APPROVED** [review]

**Comment by BisonAl** [comment]
FYI, I pulled this branch down to test out https://github.com/ethereum/go-ethereum/issues/21668 and it solved my issue.

My whole team is rooting for this PR, @fjl you'll be our hero if you fix the linter

**Comment by fjl** [comment]
The lint, it was unbroken.
