### PR TITLE
cmd/geth: fix import / export issues related to DB unavailability

### LINKED ISSUE #21412: geth import: Fatal: Could not open database: resource temporarily unavailable
#### System information

Geth version:
```
> ./build/bin/geth version
Geth
Version: 1.9.19-unstable
Git Commit: 90dedea40fc174c914ef038b8b480c2c0ff031b9
Git Commit Date: 20200803
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.3
Operating System: linux
GOPATH=/home/ia/go
GOROOT=/home/ia/go1.14.3.linux-amd64
```
https://github.com/ethereum/go-ethereum/commit/90dedea40fc174c914ef038b8b480c2c0ff031b9

The issue is not present on tag [v1.9.18](https://github.com/ethereum/go-ethereum/commit/f5382591874220287de253bfc08b10afd5244927).

#### Expected behaviour

`geth import` imports an exported `.rlp.gz` file successfully.

#### Actual behaviour

`geth import` throws `Fatal: Could not open database: resource temporarily unavailable`.

#### Steps to reproduce the behaviour

These steps use an `export`ed `.rlp.gz` file `./tests/regression/simulated/foundation-condense-state/export.rlp.gz` and a corresponding config file `./tests/regression/simulated/foundation-condense-state/foundation.conf.json`, which are available [here](https://github.com/etclabscore/core-geth/tree/master/tests/regression/simulated/foundation-condense-state) if you want to reproduce exactly. Otherwise, any correct config/export pair should be sufficient.

```
> rm -rf dd

> ./build/bin/geth --debug --datadir ./dd init ./tests/regression/simulated/foundation-condense-state/foundation.conf.json
INFO [08-04|10:31:37.468|cmd/utils/flags.go:1164] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-04|10:31:37.468|cmd/utils/flags.go:1238] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-04|10:31:37.469|cmd/utils/flags.go:1566] Set global gas cap                       cap=25000000
INFO [08-04|10:31:37.469|ethdb/leveldb/leveldb.go:95] Allocated cache and file handles         database=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/chaindata cache=16.00MiB handles=16
INFO [08-04|10:31:37.488|core/genesis.go:165]         Writing custom genesis block
INFO [08-04|10:31:37.488|trie/database.go:768]        Persisted trie from memory database      nodes=1 size=150.00B time="27.352µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-04|10:31:37.488|geth/chaincmd.go:257]        Successfully wrote genesis state         database=chaindata hash="529b11…c00a48"
INFO [08-04|10:31:37.488|ethdb/leveldb/leveldb.go:95] Allocated cache and file handles         database=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/lightchaindata cache=16.00MiB handles=16
INFO [08-04|10:31:37.498|core/genesis.go:165]         Writing custom genesis block
INFO [08-04|10:31:37.498|trie/database.go:768]        Persisted trie from memory database      nodes=1 size=150.00B time="24.732µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-04|10:31:37.499|geth/chaincmd.go:257]        Successfully wrote genesis state         database=lightchaindata hash="529b11…c00a48"

> ./build/bin/geth --debug --datadir ./dd import ./tests/regression/simulated/foundation-condense-state/export.rlp.gz
INFO [08-04|10:31:45.123|cmd/utils/flags.go:1164] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-04|10:31:45.123|cmd/utils/flags.go:1238] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-04|10:31:45.125|cmd/utils/flags.go:1566] Set global gas cap                       cap=25000000
INFO [08-04|10:31:45.125|eth/backend.go:114]      Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [08-04|10:31:45.125|ethdb/leveldb/leveldb.go:95] Allocated cache and file handles         database=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/chaindata cache=512.00MiB handles=524288
INFO [08-04|10:31:45.170|core/rawdb/freezer.go:127]   Opened ancient database                  database=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/chaindata/ancient
INFO [08-04|10:31:45.171|eth/backend.go:125]          Initialised chain configuration          config="{ChainID: 1 Homestead: 50 DAO: 69 DAOSupport: true EIP150: 100 EIP155: 180 EIP158: 180 Byzantium: 437 Constantinople: 728 Petersburg: 728 Istanbul: 906, Muir Glacier: 920, YOLO v1: <nil>, Engine: ethash}"
INFO [08-04|10:31:45.171|consensus/ethash/ethash.go:453] Disk storage enabled for ethash caches   dir=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/ethash count=3
INFO [08-04|10:31:45.171|consensus/ethash/ethash.go:456] Disk storage enabled for ethash DAGs     dir=/home/ia/.ethash count=2
INFO [08-04|10:31:45.171|eth/backend.go:147]             Initialising Ethereum protocol           versions="[65 64 63]" network=1 dbversion=<nil>
WARN [08-04|10:31:45.171|eth/backend.go:153]             Upgrade blockchain database version      from=<nil> to=7
INFO [08-04|10:31:45.172|core/blockchain.go:424]         Loaded most recent local header          number=0 hash="529b11…c00a48" td=16384 age=51y3mo4w
INFO [08-04|10:31:45.172|core/blockchain.go:425]         Loaded most recent local full block      number=0 hash="529b11…c00a48" td=16384 age=51y3mo4w
INFO [08-04|10:31:45.172|core/blockchain.go:426]         Loaded most recent local fast block      number=0 hash="529b11…c00a48" td=16384 age=51y3mo4w
INFO [08-04|10:31:45.173|core/tx_journal.go:166]         Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-04|10:31:45.191|trie/sync_bloom.go:75]          Allocated fast sync bloom                size=512.00MiB
INFO [08-04|10:31:45.193|trie/sync_bloom.go:128]         Initialized fast sync bloom              items=1 errorrate=0.000 elapsed=1.268ms
INFO [08-04|10:31:45.194|ethdb/leveldb/leveldb.go:95]    Allocated cache and file handles         database=/home/ia/go/src/github.com/ethereum/go-ethereum/dd/geth/chaindata cache=512.00MiB handles=524288
Fatal: Could not open database: resource temporarily unavailable
```

### PR DESCRIPTION
**Pull request by renaynay**
Fixes #21412

### CODE REVIEW

**Comment by holiman** [comment]
Can confirm it fixes the bug that was reported  (haven't looked at the code yet)

**Comment by holiman** [comment]
Some more locations to apply the same fix for: 
- `build/bin/geth dump 0`

**Comment by holiman** [comment]
Looking at the code and fix, it's not quite clear to me why this fails -- since `makeFullNode` does actually call `makeConfigNode` under the hood. Perhaps it would be good to document these methods a bit, or at least add a description of which to use when (and when not to). 
What was the issue really?

**Comment by renaynay** [comment]
Yes I noticed that too, made a separate PR for those here: #21415

The explanation for this issue is that, when `makeFullNode` is called, an eth service is created as well, which attempts to open db on the node while the chaincmd (whether it's import, dump, export, so forth) also try to open the node's db simultaneously. I mentioned this in the comment of the above linked PR.

**Comment by renaynay** [comment]
Documenting this in the methods is a good idea.

File: cmd/geth/chaincmd.go [hunk 1]
```diff
@@ -278,7 +278,8 @@ func importChain(ctx *cli.Context) error {
 	utils.SetupMetrics(ctx)
 	// Start system runtime metrics collection
 	go metrics.CollectProcessMetrics(3 * time.Second)
-	stack, _ := makeFullNode(ctx)
+	// Make the bare-minimum node to avoid unnecessary service start-up
```
Comment (fjl) [inline cmd/geth/chaincmd.go:281]: Would be better to put a documentation comment on the actual function definition instead of documenting the behavior of makeConfigNode at individual call sites.

```
makeConfigNode loads geth configuration and creates a blank node instance.
```

```
makeFullNode loads geth configuration and creates the Ethereum backend.
```
