### PR TITLE
node: warn when using deprecated config/resource files

### LINKED ISSUE #16346: dumpconfig ignores StaticNodes
#### System information

Geth version: 1.8.3-unstable (built from master)
OS & Version: Linux,
Commit hash : fe6cf00f480aa6347b8d55079cbe6c473482ea27

#### Expected behaviour

After adding some nodes to `geth/static-nodes.json`, I would expect `geth dumpconfig` to include those nodes.

I have confirmed that the static nodes _are_ being respected (ie. the node does connect to said nodes with --nodiscover). It's just that dumpconfig seems to ignore them.

#### Actual behaviour

```console
$ geth dumpconfig
[Node.P2P]
...
StaticNodes = []
TrustedNodes = []
...
```

#### Steps to reproduce the behaviour

1. Write some geth/static-nodes.json
2. Run `geth dumpconfig | grep StaticNodes`
3. :cry:

### PR DESCRIPTION
**Pull request by fjl**
This solves an old TODO comment and fixes #16346. We now print a warning
when static-nodes.json, trusted-nodes.json or any of the 'old geth resources' are found.

### CODE REVIEW

File: node/config.go [hunk 1]
```diff
@@ -152,6 +153,10 @@ type Config struct {
 
 	// Logger is a custom logger to use with the p2p.Server.
 	Logger log.Logger `toml:",omitempty"`
+
+	staticNodesWarning     bool
+	trustedNodesWarning    bool
+	oldGethResourceWarning bool
```
Comment (karalabe) [inline node/config.go]: Why not use `sync.Once` for these? Would be cleaner imho and would get rid of the global lock.

Comment (fjl) [reply node/config.go]: I tried this, but it's not a good idea because some code shallow-copies Config structs. That doesn't work with sync.Once, it contains sync.Mutex.
