### PR TITLE
accounts/abi: Abi binding support for nested arrays, fixes #15648, including nested array unpack fix

### LINKED ISSUE #15648: Multi-dimensional fixed-size array return is converted to an incomplete (?) binding
Title says it all; the solidity code (and its conversion to abi) state that a `uint32[2][3]` is returned, but the generated go-binding only returns the inner array: `[2]uint32`.

#### System information

```
$ geth version
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
```

#### Expected behaviour
`GetTarget` binding should return `([3][2]uint32, error)`, i.e. a nested array, like the ABI and the solidity code declare.

#### Actual behaviour
It generates the go-bindings, but with this snippet, which seems incorrect to me:
```go
// GetTarget is a free data retrieval call binding the contract method 0x89d6d989.
//
// Solidity: function GetTarget() constant returns(uint32[2][3])
func (_BugTest *BugTestCaller) GetTarget(opts *bind.CallOpts) ([2]uint32, error) {
	var (
		ret0 = new([2]uint32)
	)
	out := ret0
	err := _BugTest.contract.Call(opts, out, "GetTarget")
	return *ret0, err
}
```

#### Steps to reproduce the behaviour

1) Create file `BugTest.sol`:
```soldity
pragma solidity ^0.4.19;
pragma experimental ABIEncoderV2;

contract BugTest {

    uint constant InnerSize = 2;
    uint constant OuterSize = 3;

    function GetTarget() public pure returns (uint32[InnerSize][OuterSize]) {
        uint32[InnerSize][OuterSize] memory result;
        // Imagine more advanced usage of the nested array ...
        result[0][0] = 1;
        result[0][1] = 2;
        result[1][0] = 3;
        result[1][1] = 4;
        result[2][0] = 5;
        result[2][1] = 6;
        return result;
    }
}
```
2.1) Create abi: run `solc -o build --abi --overwrite BugTest.sol`
2.2) Or use the abi it generated for me:
```json
[{"constant":true,"inputs":[],"name":"GetTarget","outputs":[{"name":"","type":"uint32[2][3]"}],"payable":false,"stateMutability":"pure","type":"function"}]
```

3) Create the go-binding, using the generated abi: `abigen --abi build/BugTest.abi --pkg abi --type BugTest --out "bug_test_binding.go"`
4) Check generated go bindings.

### PR DESCRIPTION
**Pull request by protolambda**
The binding generator only matched one level of the multi-dimensional array types that were parsed by the other binding code.

Fix:
- Method that reads the unmatched characters
- Looks for a valid array declaration
- Returns array-sizes of each level (empty if no array)
- Each language wraps their old (but cleaner) type-translator with the array reader.
- Each language has a method that translates the combination of inner-type and array-sizes into a typed array declaration.
- Minor fix: Java used "bool" while this should have been a "boolean". Not that anyone would pick Java bindings over Go 😄 
- Another minor fix: Java used int, also for non-32 bit numbers. I changed this to byte/short/int/long (8/16/32/64 bits) but I'm not sure about the implications. However, it should be better than previously in any case, as a Java int doesn't have sufficient space for the (u)int64.
- Edit: another bugfix: argument unpacking shifts to the correct index after nested arrays now.

*Before merging*: This is my first PR here, suggestions & reviews are very much appreciated 👍

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b5c402824e901a57a904477727dbf65ea3e33bf6
  * Commit subjects should be kept under 100 characters

 * Commit: aa5257580233c9dab10e5b2de7b770caeb9c50ae
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b5c402824e901a57a904477727dbf65ea3e33bf6
  * Commit subjects should be kept under 100 characters

 * Commit: ac6ff7e6a278a3f3211125c80b6a3c9728c258c4
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by protolambda** [comment]
@GitCop Added an ":" and split that one commit message, quality suggestions bot 👍

**Comment by protolambda** [comment]
For no particular good reason, the OSX Go 1.9 travis CI jobs fails:
```
--- FAIL: TestDeposit (0.24s)

	cheque_test.go:323: expected balance 40, got 42

FAIL

coverage: 77.0% of statements

FAIL	github.com/ethereum/go-ethereum/contracts/chequebook	1.261s
```

This happens in a package that wasn't touched in this PR, nor uses the accounts/abi/bind package. I suspect this is because of the test being prone to a race condition (Execution literally depends on `time.Sleep(...)`). @mexskican You worked on this test most recently, do you know what's up?

**Comment by holiman** [comment]
Thanks for the PR! 
Since this adds some new capabilties, could you please provide some testcases that utilise the new features, and verifies the correctness? 

I assume you already have examples that you based the implementation on, which you perhaps can place in the `bind_test.go` file?

**Comment by protolambda** [comment]
@holiman Sure, I'll make some tests. But that'll probably be next week. 🎅

File: accounts/abi/bind/bind.go [hunk 1]
```diff
@@ -139,118 +139,161 @@ var bindType = map[Lang]func(kind abi.Type) string{
...
-				return fmt.Sprintf("int%s[]", parts[2])
-			}
+		case "8":
+			return len(parts[0]), "byte"
+		case "16":
+			return len(parts[0]), "short"
+		case "32":
+			return len(parts[0]), "int"
+		case "64":
+			return len(parts[0]), "long"
```
[the remark this answers is not in the document]
Comment (protolambda) [reply accounts/abi/bind/bind.go]: 1) The `switch` isn't pretty, a map lookup may work better yes. It's not that this code is performance-critical anyway. On the other hand though, the mapping to go keywords is constant, and shouldn't change. And Go doesn't offer a constant `map` (afaik). So we either have a pseudo-constant map, or a (slightly less verbose) switch case.

2) No. From the solidity docs: "`uint` and `int` are aliases for `uint256` and `int256`, respectively.". And these are mapped to a `BigInt`. So it's 0 or more digits to parse, and I don't see a reason to limit it with a maximum. (Soldity has a *theoretical* limit of 2^256, but I don't see why this should be enforced in this regex)

I'll see if I can improve the clearity when I write the tests. 👍 

For now, happy holidays 🎄

**Comment by protolambda** [comment]
@gballet When preparing the tests, I found another more serious problem related to nested-arrays.

So I was writing the tests for the nested arrays, but discovered that the unpacking of nested arrays happened incorrectly. Packing of nested arrays works correctly, but unpacking only works for non-nested arrays/slices. The problem is that the unpacker assumes that each element of an array is 32 bytes (because of padding), but elements of a (nested) array-type can be different sizes.

Note that the current code still unpacks nested arrays, but the data is read wrongly; it only reads the first entry correctly, and starts incrementing with too small increments from there, misaligning & duplicating the read data.

I fixed it, but I'm not fond of my solution. Unpacking an individual element doesn't tell us the size of the consumed bytes, so I had to find another solution... For now, it calculates the size of the element by packing it, and it works correctly now, but the solution could be way nicer if we let `accounts/abi/unpack.go#toGoType` return the amount of consumed bytes.

You can find my debugging code here: https://github.com/protolambda/go-eth-nested-array-debug
(I'll move some of it to `bind_test.go` once the unpacking bug is fixed, and a nested-array test case in `unpack_test.go` is probably a good idea too).

File: accounts/abi/unpack.go [hunk 2]
```diff
@@ -113,17 +112,25 @@ func forEachUnpack(t Type, output []byte, start, size int) (interface{}, error)
...
+		reflectedInter := reflect.ValueOf(inter)
+
+		//Although we just did the reverse, pack it, to get the length of the actual element.
+		//Getting the length directly from the "toGoType" would be way better,
+		// but it requires some refactoring to get it return the *consumed* length.
+		interPacked, err  := t.Elem.pack(reflectedInter)
+		if err != nil {
+			return nil, err
+		}
+		i += len(interPacked)
```
Comment (protolambda) [inline accounts/abi/unpack.go]: By packing it, and using the length as the increment, it guarantees correct element alignment (given that packing works correctly). However, getting a "consumed" size from the `toGoType` call would be *much* more efficient. I decided to go with this inefficient solution first, since changing `toGoType` affects other code.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e08174f87ecb6d2342cae5c9175c6b77598664b8
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by protolambda** [comment]
Fixed unpacking of multi-dimensional arrays, without the packing step I took previously, and more efficient. 👍

Added a test for the bindings generated for the *deeply* nested (more than one level of nesting) arrays, as well as a test for both the unpacking and packing of the arrays.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 5d42cf60fa1db42bf537983c25946a85fba19422
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by protolambda** [comment]
@GitCop Great. :I

**Comment by protolambda** [comment]
Rebased to resolve merge conflicts, and rebased again to resolve GitCop.

PR should be good to go now.

@gballet Can you take a look?

**Comment by protolambda** [comment]
Well, one test, in **non-related** code, fails in one of the CI jobs because of a race condition... :(

```
--- FAIL: TestDeposit (0.26s)
	cheque_test.go:323: expected balance 40, got 42
FAIL
coverage: 77.0% of statements
```

File: accounts/abi/bind/bind.go [hunk 3]
```diff
@@ -139,118 +139,166 @@ var bindType = map[Lang]func(kind abi.Type) string{
...
 
+// Helper function for the binding generators.
+// It reads the unmatched characters after the inner type-match,
+//  (since the inner type is a prefix of the total type declaration),
+//  looks for valid arrays (possibly a dynamic one) wrapping the inner type,
+//  and returns the sizes of these arrays.
+//
+// Returned array sizes are in the same order as solidity signatures; inner array size first.
+// Array sizes may also be "", indicating a dynamic array.
+func wrapArray(stringKind string, innerLen int, innerMapping string) (string, []string) {
```
Comment (gballet) [inline accounts/abi/bind/bind.go]: It would be simpler, more readable and arguably more efficient to use the following regular expression `\[(\d*)\]` along with `FindAllStringSubmatch`.

File: accounts/abi/bind/bind.go [hunk 4]
```diff
@@ -139,118 +139,166 @@ var bindType = map[Lang]func(kind abi.Type) string{
...
 }
 
+// Translates the array sizes to a Java declaration of a (nested) array of the inner type.
+// Simply returns the inner type if arraySizes is empty.
+func arrayBindingJava(inner string, arraySizes []string) string {
+	out := inner
+	//append a "[]" for each array size.
+	// (Full arraySizes is used in signature for consistency with the go-lang version)
+	for i := 0; i < len(arraySizes); i++ {
+		//normally, like with Go, you could declare an array size. Not in Java.
```
Comment (gballet) [inline accounts/abi/bind/bind.go]: Please update this comment to make it more factual like "java array type declarations do not include the length".

We are not interested in starting yet another religious war on the theme of whose language is better. Also, your comment is inaccurate: Java has arrays while Go has slices, and the typing in Java is more dynamic than what Go offers, so not enforcing the array size in the type declaration makes sense (and is therefore 'normal'). You don't like Java? That makes two of us. Still, this is not the place to vent out.

File: accounts/abi/bind/bind.go [hunk 5]
```diff
@@ -139,118 +139,166 @@ var bindType = map[Lang]func(kind abi.Type) string{
...
 	}
 }
 
+// Translates the array sizes to a Java declaration of a (nested) array of the inner type.
+// Simply returns the inner type if arraySizes is empty.
+func arrayBindingJava(inner string, arraySizes []string) string {
+	out := inner
+	//append a "[]" for each array size.
+	// (Full arraySizes is used in signature for consistency with the go-lang version)
+	for i := 0; i < len(arraySizes); i++ {
```
Comment (gballet) [inline accounts/abi/bind/bind.go]: This loop can be rewritten: `inner + strings.Repeat("[]", len(arraySizes)`

File: accounts/abi/unpack.go [hunk 6]
```diff
@@ -93,6 +93,17 @@ func readFixedBytes(t Type, word []byte) (interface{}, error) {
 
 }
 
+func getDeepSizeForType(t *Type) int {
```
Comment (gballet) [inline accounts/abi/unpack.go]: Nitpicking here: I would prefer getTotalArraySize rather than "deep" size.

File: accounts/abi/unpack.go [hunk 7]
```diff
@@ -113,15 +123,18 @@ func forEachUnpack(t Type, output []byte, start, size int) (interface{}, error)
...
 
-	for i, j := start, 0; j*32 < len(slice); i, j = i+32, j+1 {
-		// this corrects the arrangement so that we get all the underlying array values
-		if t.Elem.T == ArrayTy && j != 0 {
-			i = start + t.Elem.Size*32*j
-		}
+	elemSize := 32
+	if t.T == ArrayTy {
+		elemSize = getDeepSizeForType(t.Elem)
+	}
```
Comment (gballet) [inline accounts/abi/unpack.go]: I would just write those 4 lines: `elemSize := getDeepSizeForType(t.Elem)` since `getDeppSizeForType` will return `32` if this is not an array.

File: accounts/abi/unpack_test.go [hunk 8]
```diff
@@ -189,6 +189,11 @@ var unpackTests = []unpackTest{
...
+		want: [4][3][2]uint32{{{1, 2}, {3, 4}, {5, 6}}, {{7, 8}, {9, 10}, {11, 12}}, {{13, 14}, {15, 16}, {17, 18}}, {{19, 20}, {21, 22}, {23, 24}}},
```
Comment (gballet) [inline accounts/abi/unpack_test.go]: you should also check that errors get caught if e.g. the string is shorter or longer than the total size, as well as if the type specification is wrong.

File: accounts/abi/bind/bind.go (hunk 4 above)
Comment (protolambda) [reply accounts/abi/bind/bind.go]: You're right, I'll change it. And I wasn't meaning to start a "religious war", it was written jokingly (i.e., you can in Java, but not in the same compact way).

File: accounts/abi/bind/bind.go (hunk 5 above)
Comment (protolambda) [reply accounts/abi/bind/bind.go]: Good spot, I started of with the Go implementation, which has changing additions, instead of repeating "[]".

File: accounts/abi/bind/bind.go (hunk 3 above)
Comment (protolambda) [reply accounts/abi/bind/bind.go]: Yup, probably a good idea. I'll simplify the implementation 👍

File: accounts/abi/unpack.go (hunk 6 above)
Comment (protolambda) [reply accounts/abi/unpack.go]: It's like a deep copy; it repeats the same operation up to the deepest array level. Total array size would work too, but it misses the aspect of nesting imho.

File: accounts/abi/unpack.go (hunk 7 above)
Comment (protolambda) [reply accounts/abi/unpack.go]: No, it doesn't. It is the element type that is being passed. So it returns 32 when *the element* is not array. Say you call `getDeepSizeForType(t.Elem)` with `t` being a slice, then we need the elemSize to be 32 bytes, since it's only the pointer to the contents of a slice-slot being counted, but `t.Elem` may be `ArrayTy`, resulting in something different than the 32 bytes.

File: accounts/abi/unpack_test.go (hunk 8 above)
Comment (protolambda) [reply accounts/abi/unpack_test.go]: I only fixed the iteration step being incorrect, not anything about the unpacking of types themselves. When the input length doesn't match up by accident, `toGoType` will handle it.

**Comment by protolambda** [comment]
> there is a lot of code repeats in your bindUnnestedTypes* / arrayBind*

Well, there is, but they're not mine. I dislike the switch cases too (and yes, a mapping for each conversion language would be nicer) but the switch-structure works as the previous author intended, without problems, and I'm fine with that. No need to refactor it even more.

File: accounts/abi/unpack_test.go (hunk 8 above)
Comment (gballet) [reply accounts/abi/unpack_test.go]: Alright

**Comment by gballet** [comment]
> Well, there is, but they're not mine.

I'm aware, I only meant that you gave it a thought. Just because it's been done by someone else doesn't mean they're better at it than you are ^^ This being said, I heard that there is a refactoring on the way so I'll just fix it at this moment. Thank you for your work so far, let me know when you're done with the regexp part and I'll review again.

**Comment by protolambda** [comment]
@gballet I'm not refactoring this *for now*. I prefer to keep PRs short, and also like to see these features being merged. Refactoring the old structure to the proposed regex+mapping structure is something for a future PR. You can make a short issue for it and I'll see when I've time to tackle it.

**Comment by protolambda** [comment]
@gballet Is this PR going to be merged? It has been approved and ready to merge for over 2 weeks now.

**Comment by gballet** [comment]
@protolambda our ranks have been decimated by the flu, it seems, but I'm sure @fjl will merge it soon. I'll make sure to remind him.

**Comment by protolambda** [comment]
@gballet I rebased all commits onto master, this should give you some extra time (to prevent merge conflicts). Get well soon everyone 👍

**Comment by protolambda** [comment]
Well, I found another bug related to nested arrays. When unpacking arguments, it only considered the outer-size of arrays. This resulted in binary contents of nested arrays "overflowing" (effectively) into the contents of the arguments following after the array.

Also see the explanation in the commit message.

@gballet Would you be so kind to re-review again, to include this small bugfix?

**Comment by protolambda** [comment]
@karalabe @gballet Is this PR still being looked at?

**Comment by holiman** [comment]
Now that 1.8.0 is out the door, we're lifting the "pr-embargo" and will start merging a bit more. I'm hoping to merge https://github.com/ethereum/go-ethereum/pull/15770 soon, and then some other abi-related PRs.

File: accounts/abi/argument.go [hunk 9]
```diff
@@ -80,6 +80,21 @@ func (arguments Arguments) Unpack(v interface{}, data []byte) error {
 	return arguments.unpackAtomic(v, data)
 }
 
+// Computes the full size of an array;
+// i.e. counting nested arrays, which count towards size for unpacking.
+func getArraySize(arr *Type) int {
```
Comment (holiman) [inline accounts/abi/argument.go]: I've done a rebase on master, and find that if don't even use this method, but leave it as is, I get no test failures. I'll push my rebased branch, with the method still present (but unused), and you can take a look and check if 

* The method is not needed, or, 
* An additional testcase is needed.

Comment (holiman) [reply accounts/abi/argument.go]: Check out my my branch: https://github.com/ethereum/go-ethereum/compare/master...holiman:pr_15676?expand=1 . It's rebased on master. PTAL that I didn't miss something, and why it's still working without using `getArraySize` (I guess the corresponding place in the master-code is here: https://github.com/ethereum/go-ethereum/compare/master...holiman:pr_15676?expand=1#diff-04b076f4fee5b5afe22e6efa614e4aceR200 )

Comment (protolambda) [reply accounts/abi/argument.go]: We probably need tests for the argument unpacking then, it may be very uncommon, but there was definitely a bug.

How to reproduce it (will test later with your rebase, this is what needed to be fixed in the original PR starting point):
1) Some argument value needs to be a nested array. The abi format packs the array pointers in-place, hence no standard 32 byte argument length, but a variable length based on the array.
2) There needs to be another argument value, *after the nested array*, that will be offset because of the miscalculated length of the previous argument (the nested array). If there isn't any, then there is (effectively) nothing wrong. But when there is, the argument is read from the wrong position, causing array data from the array argument to be read into content of following argument(s).

So it shows up very rarely, doesn't cause a panic, and only affects multi-valued arguments.

Also consider that there can be multiple levels of nested arrays, all packed together. Hence the for-loop that multiplies them. For completeness: multiplying in the size calculation works because of the array-size symmetry, no need to recursively sum all sizes. Other collections such as slices are just pointers, same size as any other argument, so nothing wrong there.

Comment (protolambda) [reply accounts/abi/argument.go]: https://github.com/ethereum/go-ethereum/compare/master...holiman:pr_15676?expand=1#diff-04b076f4fee5b5afe22e6efa614e4aceR200
Is indeed the relevant part, but it doesn't cover arrays with multiple levels of nesting, only the surface. I'll rebase it with the multi-level size calculation, and add a test for it :+1:

**Comment by holiman** [comment]
I missed that you had done this -- and I won't be available to review for a week. Maybe @gballet can review/merge?

**Comment by protolambda** [comment]
@gballet The name may be a bit confusing yes, but I didn't introduce it. The `virtualArgs` name was introduced here, by @holiman: https://github.com/protolambda/go-ethereum/commit/1ede68355db6adbf468d198a8d1ecb0ad1a3ea31#diff-04b076f4fee5b5afe22e6efa614e4aceR212

And if you read closer, it sort of makes sense, it counts things hidden from the surface argument count. Hence the "virtual". I do think they're not quite "arguments" however, more like partial arguments that just so happen to be exactly as long.

Also, I added some extra comments just above the first usage to explain what is happening, but kept the old naming (constantly renaming things is something I try to avoid).

@holiman Do you think it's a good idea to change it?

**Comment by holiman** [comment]
Yup, that was my 'bad'. I also think it sort of makes sense, but I'm not opposed to changing it to something better. Thanks for the hard work, @protolambda , and sorry that it took so long to get it in!
