### PR TITLE
ethdb: fix dead loop

### LINKED ISSUE #16790: Unable to perform graceful shutdown with new node
Hi,

I am using geth as a library (version: `1.8.8`) and instantiating a new node on a (private) Clique network.

The node sets-up the Genesis block in the DB just fine. 
When trying to shut down the node however, the node locks when trying to close the DB

The problem is that it is indefinitely waiting for  `quitChan`  in `ethdb/database.go#Close()`:

	if db.quitChan != nil {
		errc := make(chan error)
		db.quitChan <- errc    // <= This line
		if err := <-errc; err != nil {
			db.log.Error("Metrics collection failed", "err", err)
		}
	}

The reason is that nothing is ever sent to `quitChan` because the function `func (db *LDBDatabase) meter(refresh time.Duration)` returns before ever using the channel.

Since the DB is new, the following test makes it return too early because `leveldb.iostats` does not exist

		ioStats, err := db.db.GetProperty("leveldb.iostats")
		if err != nil {
			db.log.Error("Failed to read database iostats", "err", err)
			return
		}

I believe, inside the `if` test, the statement `db.quitChan = nil` should be inserted to skip over the test in `Close()`.

I guess the same reasoning applies to the test on `leveldb.stats`

(alternatively, why should missing `levelddb.iostats` cause the `meter` function to return, rather than the inner loop to `continue`?)

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #16790

### CODE REVIEW

**Comment by karalabe** [comment]
Although your fix does indeed fix the issue, it's not the best design wise. The goal of these termination channels is to provide an easily understandable termination flow. If we start skipping deliveries on channels, everything will blow up as we're all of a sudden susceptible to data races too (e.g. in your case, if the metrics gathering function is running, the channel will not deliver, and hence **not** shut down).

The correct way to solve this is to ensure that  `LDBDatabase.meter` does **not** return out of bound, rather if an error is encountered, the loop finishes and waits until termination is actually requested. The usual cleanup pattern with `chan chan error` is the following:

```go
func mygoroutine() {
	var (
		errc chan error
		err  error
	)
	for errc == nil && err == nil {
		// Do whatever
		if my_operation_failed {
			err = errors.New("failed")
			continue
		}

		select {
		case errc := <-quitCh:
		case <-time.After(refresh):
		}
	}
	if errc == nil {
		errc <- quitCh
	}
	errc <- err
}
```

**Comment by rjl493456442** [comment]
@karalabe Thanks! Really learn a lot from your patient suggestion!
Would you mind take a look again :)

File: ethdb/database.go [hunk 1]
```diff
@@ -210,13 +211,20 @@ func (db *LDBDatabase) meter(refresh time.Duration) {
...
 
+	var (
+		errc chan error
+		merr error
+		i    int = 1
+	)
+
 	// Iterate ad infinitum and collect the stats
-	for i := 1; ; i++ {
+	for errc == nil && merr == nil {
```
Comment (karalabe) [inline ethdb/database.go]: You can keep it `for i:=1; errc == nil && merr == nil; i++ {`
