### PR TITLE
core, core/types, miner: fix transaction nonce-price combo sort

### LINKED ISSUE #2139: TxByPriceAndNonce comparison is logically incorrect
TxByPriceAndNonce : core/types/transaction.go

Say, I have three transactions in the queue with the same price:
A: from account x, nonce=1
B: from account x, nonce=2
C: from account y, nonce=3

according to the comparison function:
A<B = true (comparing by nonce)
B<C = false (comparing by price)
A<C = false (comparing by price)

If the purpose if to "order by price, nonce", then the code should be changed accordingly. Otherwise the result of sort is unpredictable.

```
func (s TxByPriceAndNonce) Less(i, j int) bool {
	comparedByPrice := s.Transactions[i].data.Price.Cmp(s.Transactions[j].data.Price)
	
	if comparedByPrice == 0 {
		return s.Transactions[i].data.AccountNonce < s.Transactions[j].data.AccountNonce
	}
	
	return comparedByPrice > 0
}
```

### PR DESCRIPTION
**Pull request by karalabe**
This PR closes #2139 

Content wise it mainly discards the types.TxByPriceAndNonce, as that algo wasn't defining a total order over the elements, which messed up the ordering. The new algo fist sorts by nonces per account, and then uses a heap to merge in the best paying transactions, but only always considering the top available ones, not all.

Testing the nonce ordering is obvious, but the gas price is not so much. For every transaction in the sorted list the test finds the position of the previous- and next-nonce transaction from the same account (in between which two the selected transaction can move freely), and ensures that in that specific interval, the selected transaction is priced correctly.

---

A minor polish that this PR also includes is changing `types.TxByPrice` and `types.TxByNonce` from **containing** a struct to **aliasing** a struct. This needs us to manually implement the `sort.Len` and `sort.Swap` methods for these, but using an embedded struct really messes up the heap interface implementation, so this way is far cleaner (also it's the recommended way).

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jan 22 10:12:43 UTC 2016_

**Comment by obscuren** [comment]
:+1:

**Comment by karalabe** [comment]
@robotally Do your thing :D

**Comment by obscuren** [comment]
@robotally :heart:

File: core/types/transaction.go [hunk 1]
```diff
@@ -302,27 +304,78 @@ func TxDifference(a, b Transactions) (keep Transactions) {
...
-		return s.Transactions[i].data.AccountNonce < s.Transactions[j].data.AccountNonce
+// SortByPriceAndNonce sorts the transactions by price in such a way that the
+// nonce orderings within a single account are maintained.
+//
+// Note, this is not as trivial as it seems from the first look as there are three
+// different criteria that need to be taken into account (price, nonce, account
+// match), which cannot be done with any plain sorting method, as certain items
+// cannot be compared without context.
+//
+// This method first sorts the separates the list of transactions into individual
```
Comment (Gustav-Simonsson) [inline core/types/transaction.go]: "first sorts the separates the list of transactions" ?
