### PR TITLE
cmd/clef: fix incorrect file permissions for secrets.dat

### LINKED ISSUE #17634: Clef: Incorrect File Permissions For secrets.dat
Ref NCC-EF-Clef-001

The file permissions for secrets.dat should be set to `400` (instead of `700` ) in initializeSecrets() . The file permissions for secrets.dat should be ‘ANDed’ with `377` (instead of `077` )in checkFile() to maintain consistency.

### PR DESCRIPTION
**Pull request by YaoZengzeng**
fixes #17634

### CODE REVIEW

File: cmd/clef/main.go [hunk 1]
```diff
@@ -547,7 +547,7 @@ func checkFile(filename string) error {
 		return fmt.Errorf("failed stat on %s: %v", filename, err)
 	}
 	// Check the unix permission bits
-	if info.Mode().Perm()&077 != 0 {
+	if info.Mode().Perm()&377 != 0 {
```
Comment (holiman) [inline cmd/clef/main.go]: Please update method docs aswell

**Comment by YaoZengzeng** [comment]
@holiman Updated.
