### PR TITLE
p2p: add low port check in dialer 

### LINKED ISSUE #20937: Connection attempts to TCP Port 0
#### System information

Geth version:
```
Geth
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-MOW1yG/.go
```
OS & Version: `Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)`

#### Expected behaviour
Geth should reject and/or ignore nodes advertised as reachable on TCP Port 0 and not try to connect to them. It should not advertise on port 0 either (I don't know if it does? Might be other clients?)

#### Actual behaviour
Geth seems to have no issues trying to connect to remote IP addresses on TCP Port 0

#### Steps to reproduce the behaviour
I see these connection attempts at my firewall all the time, I assume just waiting for your node to try to connect to one would be enough.

### PR DESCRIPTION
**Pull request by fjl**
We already have a check like this for UDP ports, add a similar one in
the dialer. This prevents dials to port zero and it's also an extra
layer of protection against spamming HTTP servers.

Fixes #20937

### CODE REVIEW

**Comment by fjl** [comment]
Tests are failing in `p2p/simulations` because it seems to use low ports.

File: p2p/dial.go [hunk 1]
```diff
@@ -388,6 +389,9 @@ func (d *dialScheduler) checkDial(n *enode.Node) error {
 	if n.ID() == d.self {
 		return errSelf
 	}
+	if n.IP() != nil && n.TCP() < 1024 {
```
Comment (holiman) [inline p2p/dial.go:392]: Can `.IP()` be nil here? And if so, shouldn't that return some (other) error?

Comment (fjl) [reply p2p/dial.go:392]: Nodes can have no IP if the user just adds the ID as a static node. Nodes from discovery will always have an IP though.

**Comment by karalabe** [comment]
I tend to agree with Martin on the low ports. I honestly don't see a reason to forbid < 1024. 0 is special and should not be allowed, but the rest is imho fair game.

File: p2p/dial.go [hunk 2]
```diff
@@ -388,6 +389,9 @@ func (d *dialScheduler) checkDial(n *enode.Node) error {
 	if n.ID() == d.self {
 		return errSelf
 	}
+	if n.IP() != nil && n.TCP() == 0 {
```
Comment (karalabe) [inline p2p/dial.go:392]: Why do you need to check IP nil-ness?

Comment (fjl) [reply p2p/dial.go:392]: I already explained this in the earlier GH comment, but will add a code comment.

Comment (karalabe) [reply p2p/dial.go:392]: Oh, sorry, RTFM

**Comment by karalabe** [comment]
Hmm, all tests timed out. I think something broke

**Comment by fjl** [comment]
@karalabe tests work now, PTAL
