### PR TITLE
puppeth: handle encrypted ssh keys (closes #15442)

### LINKED ISSUE #15442: Puppeth should handle encrypted ssh keys
#### Expected behaviour

If my ssh keys are encrypted with a passphrase, I should still be able to use them with puppeth

#### Actual behaviour

1. puppeth calls `ssh.ParsePrivateKey(buf)` [at puppeth/ssh.go:79](https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/ssh.go#L79)

2.  `ssh.ParsePrivateKey` says "I only know how to parse unencrypted keys" [at crypto/ssh/keys.go:776](https://github.com/ethereum/go-ethereum/blob/master/vendor/golang.org/x/crypto/ssh/keys.go#L776)

3. puppeth says "Well then I guess this ssh key won't work" [at puppeth/ssh.go:79](https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/ssh.go#L81)

Errors look something like:

```
DEBUG[11-08|16:10:12] Attempting to establish SSH connection   server=bohendo.com
WARN [11-08|16:10:12] Bad SSH key, falling back to passwords   path=/home/bohendo/.ssh/id_rsa err="ssh: cannot decode encrypted private keys"
ERROR[11-08|16:10:12] Previous server unreachable              server=bohendo.com err="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain"
```

#### Steps to reproduce the behaviour

Use an ssh key with a head that looks like:

```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,4C513E8D138A8946654C15E8E35AB2C8
```

### PR DESCRIPTION
**Pull request by bohendo**
It looks like the ssh functionality of puppeth depends on a local version of `golang.org/x/crypto/ssh` which has a couple methods removed compared to the [original](https://github.com/golang/crypto/blob/master/ssh/keys.go). I'm not sure why they were removed but I copy/pasted two of the missing methods back in:

 - [`ParsePrivateKeyWithPassphrase`](https://github.com/golang/crypto/blob/master/ssh/keys.go#L787)
 - [`ParseRawPrivateKeyWithPassphrase`](https://github.com/golang/crypto/blob/master/ssh/keys.go#L833)

Then, I added a check into the dial function defined in [puppeth/ssh.go:80](https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/ssh.go#L80) to detect encrypted keys. If any are spotted, we'll ask for the password and then call the methods above to decrypt & parse them.

Now, puppeth is just a tiny bit smarter. Booyea!

### CODE REVIEW

**Comment by holiman** [comment]
LGTM, but I think it may be better to update the entire upstream file instead of copying individual methods.

**Comment by karalabe** [comment]
Thank for this!

Martin is right btw, these methods weren't deleted compared to the upstream crypto library, rather they didn't exist when we last updated the dependency (they were added this June https://github.com/golang/crypto/commit/fea6c2c83557701d46ea1cc0ea4c8272632fa3bd#diff-aab72d98d6b840106cb1ffed0390f951).

The "proper" way to pull in these changes is to update the dependency with the current upstream version. You can do that by installing `govendor`, and then asking it to update the dependency:

```
$ go get -u github.com/kardianos/govendor
$ govendor fetch golang.org/x/crypto/...
```

File: cmd/puppeth/ssh.go [hunk 1]
```diff
@@ -77,7 +77,23 @@ func dial(server string, pubkey []byte) (*sshClient, error) {
 		log.Warn("No SSH key, falling back to passwords", "path", path, "err", err)
 	} else {
 		key, err := ssh.ParsePrivateKey(buf)
-		if err != nil {
+		if string(err.Error()) == "ssh: cannot decode encrypted private keys" {
```
Comment (karalabe) [inline cmd/puppeth/ssh.go]: You don't need the string case here, `Error()` already returns a string.

Also this is a very brittle way to check for the error as it could change at any moment, however I do notice that the crypto package does not have an expose error constant for this. I'd suggest leaving this check as you implemented for now, but opening a PR against the upstream repo to make the error a constant.

File: cmd/puppeth/ssh.go [hunk 2]
```diff
@@ -77,7 +77,23 @@ func dial(server string, pubkey []byte) (*sshClient, error) {
...
+
```
Comment (karalabe) [inline cmd/puppeth/ssh.go]: Please no empty lines here :)

File: cmd/puppeth/ssh.go [hunk 3]
```diff
@@ -77,7 +77,23 @@ func dial(server string, pubkey []byte) (*sshClient, error) {
...
+			fmt.Printf("Enter the passphrase to decrypt your ssh key (no echo):\n>")
```
Comment (karalabe) [inline cmd/puppeth/ssh.go]: `no echo` -> `won't be echoed` to keep it consistent with all other password read instances.

Comment (karalabe) [reply cmd/puppeth/ssh.go]: Also Puppeth's "labels" generally take the form of questions, not statements, so I'd rather formulate this as:

`fmt.Printf("What's the decryption password for the SSH key? (won't be echoed)\n> ")`

File: cmd/puppeth/ssh.go [hunk 4]
```diff
@@ -77,7 +77,23 @@ func dial(server string, pubkey []byte) (*sshClient, error) {
...
+			blob, err := terminal.ReadPassword(int(syscall.Stdin))
+			fmt.Println()
+			if err != nil {
+				log.Warn("Couldn't read password to decrypt ssh key")
+			}
+
+			key, err := ssh.ParsePrivateKeyWithPassphrase(buf, []byte(blob))
+			if err != nil {
+				log.Warn("Bad SSH key, falling back to passwords", "path", path, "err", err)
```
Comment (karalabe) [inline cmd/puppeth/ssh.go]: Perhaps instead of `Bad SSH key`, output `Failed to decrypt SSH key` here, since it better highlights the issue.

File: cmd/puppeth/ssh.go (hunk 2 above)
Comment (bohendo) [reply cmd/puppeth/ssh.go]: So in general, no empty lines padding the beginning or end of blocks?

**Comment by bohendo** [comment]
Thank you for the feedback!

Proposal: decrypting ssh keys is a common enough situation that we can use it as the default next-action rather than specifically making that silly, fragile `if err == "specific string"` check. Simpler & avoids upstream error handling issues.

Running `govendor fetch golang.org/x/crypto/...` means we also need to upgrade a unix dependency (`golang.org/x/sys/unix`). All in all, these two fetches made some really heavy (& for now, unnecessary) dependency additions. Instead, I ran `govendor fetch golang.org/x/crypto/ssh`. No extra fetches required & it gives us exactly what we need.

Is it best practice for me to squash my commits or leave that up to you?

**Comment by bohendo** [comment]
Awesome, `golang.org/s/crypto` is fully upgraded and my commits have been squashed. I think we're good to go.

A recent commit removed the `syscall` import from `cmd/puppeth/ssh.go` so I followed suit and changed my `int(syscall.Stdin)` into `int(os.Stdin.Fd())` like was done later in that same file.
