### PR TITLE
core, eth: add lock protection in snap sync

### LINKED ISSUE #33396: Chain rollback fault injection caused node crash
We are conducting a security test on the Ethereum network using fuzzing and fault injection. The following findings were made while constructing fault injection experiments specific to the blockchain (using set_head for rollback or fork).

**Key Findings:**

1. We also conducted the same tests on Besu (which also supports `set_head`). Besu's block rollback speed was very fast, and no anomalies or bugs occurred.  ——**Part 1**
2. Rollback on geth was very slow, and there was a high probability that the node would get crash midway through execution.  **——Part 2**

### Part 1. The Besu client worked flawlessly and synced quickly. Screenshots and logs of the Besu client experiment are shown below:
```
fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1"],"id":1}' http://127.0.0.1:32888 | jq

{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "Success"
}
fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32888 12                
1) RPC reachable & client version
RPC reachable. clientVersion: besu/v25.10.0/linux-x86_64/openjdk-java-21
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 1 (hex:0x1)
Waiting 12s to check progress...
Block progressed: 1 -> 6461 (+6460)
4) recent block transactions check
Transactions in latest block: 0
Latest block has no transactions.
5) txpool status (if supported)
txpool_status:
null
6) peer count
Peer count: 4
````

### Part 2. Geth client experimental logs (in case of node crash):
```
fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12
1) RPC reachable & client version
RPC reachable. clientVersion: Geth/v1.16.7-unstable-5b77af39-20251103/linux-amd64/go1.24.9
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 6471 (hex:0x1947)
Waiting 12s to check progress...
Block progressed: 6471 -> 6472 (+1)

fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1900"],"id":1}' http://127.0.0.1:32883 | jq
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}

fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12                
1) RPC reachable & client version
RPC reachable. clientVersion: Geth/v1.16.7-unstable-5b77af39-20251103/linux-amd64/go1.24.9
2) eth_syncing
Node reports: synced (eth_syncing = false)
3) block number and progress check
Current block: 6400 (hex:0x1900)
Waiting 12s to check progress...
Block progressed: 6400 -> 6474 (+74)
4) recent block transactions check
Transactions in latest block: 0
Latest block has no transactions.
5) txpool status (if supported)
txpool_status:
{
  "pending": "0x0",
  "queued": "0x0"
}
6) peer count
Peer count: 4
fjl @ sg ➜  tx_storage  curl -s -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1"],"id":1}' http://127.0.0.1:32883 | jq 


fjl @ sg ➜  tx_storage  bash node_check.sh 127.0.0.1:32883 12                
1) RPC reachable & client version
[FAIL] Cannot reach RPC at 127.0.0.1:32883
```

#### Client error message logs:
```
[el-1-geth-lighthouse] INFO [11-05|09:45:27.990] Truncating from head                     type=state ohead=5303 tail=0 nhead=5302
[el-1-geth-lighthouse] INFO [11-05|09:45:28.014] Rewound to block with state              number=5301 hash=9bcb68..2b10b8
[el-1-geth-lighthouse] INFO [11-05|09:45:28.015] Truncating from head                     type=state ohead=5302 tail=0 nhead=5301
[el-1-geth-lighthouse] INFO [11-05|09:45:28.045] Rewound to block with state              number=5300 hash=e579e0..ec7ad8
[el-1-geth-lighthouse] INFO [11-05|09:45:28.046] Truncating from head                     type=state ohead=5301 tail=0 nhead=5300
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.047] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] WARN [11-05|09:45:28.047] Ignoring payload while snap syncing      number=6479 hash=4e0d9b..32bf65 reason="chain gapped, head: 6474, newHead: 6479"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Forkchoice requested sync to new head    number=6479 hash=4e0d9b..32bf65 finalized=unknown
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Reenabled snap sync as chain is stateless
[el-1-geth-lighthouse] INFO [11-05|09:45:28.054] Restarting sync cycle                    reason="chain gapped, head: 6474, newHead: 6479"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.069] Syncing beacon headers                   downloaded=74 left=0 eta=0s
[el-1-geth-lighthouse] ERROR[11-05|09:45:28.070] Failed to clean stale beacon headers     err="filled header below beacon header tail: 6474 < 6478"
[el-1-geth-lighthouse] INFO [11-05|09:45:28.075] Rewound to block with state              number=5299 hash=6fcc2f..52f458
[el-1-geth-lighthouse] CRIT [11-05|09:45:28.075] Chain is stateless at a non-genesis block
```

### Env
We use kurtosis's ethereum-package for testing, and the relevant configuration is as follows:
````
// The ethereum-package network-para.yaml
participants:
  - el_type: geth V1.16.2
    cl_type: lighthouse V7.0.1
  - el_type: nethermind V1.33.0
    cl_type: lighthouse V7.0.1
  - el_type: reth V1.6.0
    cl_type: lighthouse V7.0.1
  - el_type: besu V25.8.0
    cl_type: lighthouse V7.0.1
  - el_type: erigon V3.0.15
    cl_type: lighthouse V7.0.1
additional_services:
  - dora
```

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #33396, #33397, #33398

### CODE REVIEW

File: eth/catalyst/metrics.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
+// Copyright 20222 The go-ethereum Authors
```
Comment (MariusVanDerWijden) [inline eth/catalyst/metrics.go]: Wow you're living in the future 😋

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM, I have not tested it though

**Comment by rjl493456442** [comment]
@MariusVanDerWijden Can I get another approval?
