### PR TITLE
graphql: return correct logs for tx

### LINKED ISSUE #25583: GraphQL/JSON-RPC logs regression between 1.10.21 & 1.10.22
#### System information

Geth
Version: 1.10.22-stable
Git Commit: 2de49b04e56cf07f011d6d91f9d5c08847aabe8e
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

Archive node

#### Expected behaviour

Doing a complex GraphQL query returns correct data from a block, like in 1.10.21

#### Actual behaviour

Too much data (logs unrelated to current block)

#### Steps to reproduce the behaviour

Going to GraphQL UI : http://xxxxx:8545/graphql/ui

Type the following query :

```
{
  block(number: 15401505) {
    number
    transactions {
      logs {
        account {
          address
        }
      }
    }
  }
}

```

#### More details

That block on etherscan : https://etherscan.io/block/15401505

On a 1.10.22 node, this query returns 257386 lines, which is a bit too much (could depend on when you run the request)
On a 1.10.21 node, this query returns 2209 lines, which seems more in the norm

### PR DESCRIPTION
**Pull request by s1na**
As part of #25459 I made a change so that graphql's tx log query goes through the usual filter system so it benefits from the newly added cache. However the filter system only handles logs on the block level, not tx level and I didn't select logs based on txindex which caused a regression.

Fixes #25583

### CODE REVIEW

**Comment by s1na** [comment]
Did you see https://github.com/ethereum/go-ethereum/pull/24477? you can already pass in `--fdlimit` to guide geth how many file descriptors to use when possible. I think this PR and the link issue can be closed. Please re-open otherwise.

File: graphql/graphql.go [hunk 1]
```diff
@@ -478,8 +478,11 @@ func (t *Transaction) getLogs(ctx context.Context) (*[]*Log, error) {
 	if err != nil {
 		return nil, err
 	}
-	ret := make([]*Log, 0, len(logs))
+	ret := make([]*Log, 0)
 	for _, log := range logs {
+		if uint64(log.TxIndex) != t.index {
+			continue
```
Comment (fjl) [inline graphql/graphql.go:484]: `logs` is sorted by TxIndex, so this could be improved to skip most iteration:

```
ix := sort.Search(len(logs), func (i int) bool { return logs[i].TxIndex == t.index })
for ix < len(logs) && logs[ix].TxIndex == t.index {
    ret = append(ret, logs[i])
}
```

Comment (fjl) [reply graphql/graphql.go:484]: Also, it's kind of weird to use a filter here. We could just call `t.r.backend.GetLogs` here.

Comment (fjl) [reply graphql/graphql.go:484]: Hmm, just realized that the filter is used here exactly because `GetLogs` doesn't have access to the cache.

Comment (s1na) [reply graphql/graphql.go:484]: I kind of like the simplicity even tho it's slightly less fast, if you don't have a strong feeling about it.

Comment (SLoeuillet) [reply graphql/graphql.go:484]: Fix tested working on my personal node.
Would deploy 1.10.23 + your_fix on prod if no 1.10.24 official version before the merge (currently using 1.10.21 + TTD set in CLI params)

**Review by SLoeuillet — APPROVED** [review]

File: graphql/graphql.go (hunk 1 above)
Comment (holiman) [reply graphql/graphql.go:484]: I'm slightly in favor of @fjl's suggestion.

**Review by holiman — APPROVED** [review]
LGTM

File: graphql/graphql.go [hunk 2]
```diff
@@ -478,8 +478,11 @@ func (t *Transaction) getLogs(ctx context.Context) (*[]*Log, error) {
 	if err != nil {
 		return nil, err
 	}
-	ret := make([]*Log, 0, len(logs))
+	ret := make([]*Log, 0)
```
Comment (holiman) [inline graphql/graphql.go:481]:
```suggestion
	var ret []*Log
```

**Review by holiman — APPROVED** [review]
LGTM

**Review by gballet — APPROVED** [review]
LGTM
