### PR TITLE
eth/downloader: fix missing receipts for empty block

### LINKED ISSUE #31938: "Block receipts missing, can't freeze block" after pruned sync
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

I synced a mainnet node with the `--history.chain postmerge` flag. Immediately after sync finished it started emitting logs such as this when importing every block:

```
WARN [05-30|13:36:59.543] Truncating freezer table                 database=/home/ubuntu/datadir-el/geth/chaindata/ancient/chain table=bodies items=22,505,926 limit=22,505,794
WARN [05-30|13:36:59.570] Truncating freezer table                 database=/home/ubuntu/datadir-el/geth/chaindata/ancient/chain table=receipts items=22,505,899 limit=22,505,794
ERROR[05-30|13:36:59.596] Error in block freeze operation          err="block receipts missing, can't freeze block 22505975"
```

All of the errors are about the same block. This is the second time I am having this exact issue. First time around it was about a different receipt.

This also knocks out the log indexer:

```
INFO [05-30|13:36:32.086] Log index head rendering in progress     firstblock=22,276,737 lastblock=22,278,073 processed=1337 remaining=317,810 elapsed=41.100s
ERROR[05-30|13:36:33.146] Log index head rendering failed, reverting to unindexed mode error="failed to advance log iterator at 18055928015 while rendering map 275511: receipts not found for block 22279214"
```

Interestingly log indexer failed because it couldn't fetch another receipt: 22279214. I can confirm that the node doesn't have this receipt either.

#### Steps to reproduce the behaviour

Sync mainnet with `--history.chain postmerge`. Haven't been able to narrow it further down.

#### Logs

[geth_2025-05-30_10-49-1748602199.log](https://github.com/user-attachments/files/20521967/geth_2025-05-30_10-49-1748602199.log)

### PR DESCRIPTION
**Pull request by s1na**
Fixes #31938

### CODE REVIEW

File: eth/downloader/downloader.go [hunk 1]
```diff
@@ -1039,6 +1039,9 @@ func (d *Downloader) commitSnapSyncData(results []*fetchResult, stateSync *state
 	for i, result := range results {
 		blocks[i] = types.NewBlockWithHeader(result.Header).WithBody(result.body())
 		receipts[i] = result.Receipts
+		if len(result.Receipts) == 0 {
+			receipts[i] = rlp.EmptyList
```
Comment (fjl) [inline eth/downloader/downloader.go]: Maybe add a comment?

File: eth/downloader/downloader.go [hunk 2]
```diff
@@ -1039,6 +1039,13 @@ func (d *Downloader) commitSnapSyncData(results []*fetchResult, stateSync *state
 	for i, result := range results {
 		blocks[i] = types.NewBlockWithHeader(result.Header).WithBody(result.body())
 		receipts[i] = result.Receipts
+		// Blockchain expects the receipts to be properly encoded
```
Comment (rjl493456442) [inline eth/downloader/downloader.go]: Is it really possible?

In the handler, the received receipts is always encoded as `Storage Format` before
propagating to the downloader.

```go
func handleReceipts[L ReceiptsList](backend Backend, msg Decoder, peer *Peer) error {
	// A batch of receipts arrived to one of our previous requests
	res := new(ReceiptsPacket[L])
	if err := msg.Decode(res); err != nil {
		return err
	}
	// Assign temporary hashing buffer to each list item, the same buffer is shared
	// between all receipt list instances.
	buffers := new(receiptListBuffers)
	for i := range res.List {
		res.List[i].setBuffers(buffers)
	}

	metadata := func() interface{} {
		hasher := trie.NewStackTrie(nil)
		hashes := make([]common.Hash, len(res.List))
		for i := range res.List {
			hashes[i] = types.DeriveSha(res.List[i], hasher)
		}
		return hashes
	}
	var enc ReceiptsRLPResponse
	for i := range res.List {
		enc = append(enc, res.List[i].EncodeForStorage())
	}
	return peer.dispatchResponse(&Response{
		id:   res.RequestId,
		code: ReceiptsMsg,
		Res:  &enc,
	}, metadata)
}
```

```go
// encodeForStorage encodes a list of receipts for the database.
func (buf *receiptListBuffers) encodeForStorage(rs []Receipt) rlp.RawValue {
	var out bytes.Buffer
	w := &buf.enc
	w.Reset(&out)
	outer := w.List()
	for _, receipts := range rs {
		receipts.encodeForStorage(w)
	}
	w.ListEnd(outer)
	w.Flush()
	return out.Bytes()
}
```

In the `StorageFormat` encoding, the output will be an empty list (`0xc0`) rather than nil.
