### PR TITLE
core/vm: make gas cost reporting to tracers correct

### LINKED ISSUE #22649: Incorrect gas cost passed to tracer for EIP-2929 calls with cold account accesses
#### System information
Commit hash : anything past https://github.com/ethereum/go-ethereum/commit/6487c002f6b47e08cb9814f16712c6789b313a97 that introduced EIP-2929 support

#### Expected behaviour
With [EIP-2929](https://github.com/ethereum/EIPs/blob/d679d09f7aa4c8aac78830bdee2436eea7d561ad/EIPS/eip-2929.md) enabled, the dynamic cost of all call types includes an optional `COLD_ACCOUNT_ACCESS_COST`. This cost, if charged, should also be part of the total opcode gas cost passed to the tracer and exposed e.g. via `debug_traceTransaction`.

#### Actual behaviour
While properly charged, the `COLD_ACCOUNT_ACCESS_COST` is never part of the gas cost reported to the tracer.

#### Explanation
https://github.com/ethereum/go-ethereum/commit/6487c002f6b47e08cb9814f16712c6789b313a97 added the new `core/vm/operations_acl.go` file for EIP-2929 gas logic. Dynamic gas cost calculation for all call types is wrapped in [operations_acl.go#L176](https://github.com/ethereum/go-ethereum/blob/9c653ff6625df1ff0f6c6612958b2a1da0021e40/core/vm/operations_acl.go#L176):
```
func makeCallVariantGasCallEIP2929(oldCalculator gasFunc) gasFunc {
	return func(evm *EVM, contract *Contract, stack *Stack, mem *Memory, memorySize uint64) (uint64, error) {
		addr := common.Address(stack.Back(1).Bytes20())
		if !evm.StateDB.AddressInAccessList(addr) {
			evm.StateDB.AddAddressToAccessList(addr)
			if !contract.UseGas(ColdAccountAccessCostEIP2929 - WarmStorageReadCostEIP2929) {
				return 0, ErrOutOfGas
			}
		}
		return oldCalculator(evm, contract, stack, mem, memorySize)
	}
}
```
The issue is that the `ColdAccountAccessCostEIP2929` is charged directly, instead of being passed to the outside together with the rest of the dynamic gas, to be charged there and passed to the tracer. While this is necessary to properly calculate the available call gas in the inner `gasFunc`, it causes the incorrect gas reporting to the tracer at [interpreter.go#L278](https://github.com/ethereum/go-ethereum/blob/9c653ff6625df1ff0f6c6612958b2a1da0021e40/core/vm/interpreter.go#L278).

### PR DESCRIPTION
**Pull request by holiman**
Supersedes #22680 

Original description below:

---

Possible way to close #22649.
Previously, the `makeCallVariantGasCallEIP2929` charged the cold account access cost directly, leading to an incorrect gas cost passed to the tracer from the main execution loop.
This change still temporarily charges the cost (to allow for an accurate calculation of the available gas for the call), but then afterwards refunds it and instead returns the correct total gas cost to be then properly charged in the main loop.

This is the best fix I could come up with that keeps the general wrapper structure intact. Alternatives would be deeper changes to the way EIP-2929 gas cost calculation is conducted.

### CODE REVIEW

File: core/vm/operations_acl.go [hunk 1]
```diff
@@ -177,10 +177,15 @@ func makeCallVariantGasCallEIP2929(oldCalculator gasFunc) gasFunc {
...
+		// The WarmStorageReadCostEIP2929 (100) is already deducted in the form of a constant cost, so
+		// the cost to charge for cold access, if any, is Cold - Warm
+		coldCost := ColdAccountAccessCostEIP2929 - WarmStorageReadCostEIP2929
+		if !warmAccess {
 			evm.StateDB.AddAddressToAccessList(addr)
-			// The WarmStorageReadCostEIP2929 (100) is already deducted in the form of a constant cost
-			if !contract.UseGas(ColdAccountAccessCostEIP2929 - WarmStorageReadCostEIP2929) {
+			// Charge the remaining difference here already, to correctly calculate available
+			// gas for call
+			if !contract.UseGas(coldCost) {
```
Comment (rjl493456442) [inline core/vm/operations_acl.go:188]: Can we define another function which only does the check instead of charging directly? So that we don't need the "add it back" operation later.

**Review by rjl493456442 — APPROVED** [review]
One nitpick, otherwise lgtm.

File: core/vm/operations_acl.go (hunk 1 above)
Comment (holiman) [reply core/vm/operations_acl.go:188]: That would be neat, however, it doesn't quite work. We need to actually remove the gas, so that when the `oldCalculator` calculates the `63/64ths`, it does so from the lower amount, not the higher amount.

Comment (rjl493456442) [reply core/vm/operations_acl.go:188]: Gotcha, it makes sense.
