### PR TITLE
core, eth: fix database version

### LINKED ISSUE #18233: rawdb: Database Version must be unsigned integer
`rawdb` write database version as `int`. It is wrong because of `rlp` can only handle unsigned integer.
line 40 in accessors_metadata.go actually produced an error, but it ignored. This bug makes database version checking not work.

https://github.com/ethereum/go-ethereum/blob/f850123ec7500af732b73c2501f1ef36d80ee01d/core/rawdb/accessors_metadata.go#L40

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #18233

### CODE REVIEW

File: eth/backend.go [hunk 1]
```diff
@@ -143,8 +143,10 @@ func New(ctx *node.ServiceContext, config *Config) (*Ethereum, error) {
 
 	if !config.SkipBcVersionCheck {
 		bcVersion := rawdb.ReadDatabaseVersion(chainDb)
-		if bcVersion != core.BlockChainVersion && bcVersion != 0 {
-			return nil, fmt.Errorf("Blockchain DB version mismatch (%d / %d).\n", bcVersion, core.BlockChainVersion)
+		if bcVersion != nil && *bcVersion > core.BlockChainVersion {
+			return nil, fmt.Errorf("Blockchain DB version mismatch (%d / %d).\n", *bcVersion, core.BlockChainVersion)
```
Comment (karalabe) [inline eth/backend.go]: Since this is an error, the string should be lowercase. Also I'd expand the `/` form a bit, otherwise it's hard to interpret. Eg. `fmt.Errorf("database version is v%d, Geth %s only supports v%d", *bcVersion, params.VersionWithMeta(), core.BlockChainVersion)`

File: eth/backend.go [hunk 2]
```diff
@@ -143,8 +143,10 @@ func New(ctx *node.ServiceContext, config *Config) (*Ethereum, error) {
...
+		} else if bcVersion != nil && *bcVersion < core.BlockChainVersion {
+			log.Warn("Upgrade blockchain DB version", "from", *bcVersion, "to", core.BlockChainVersion)
```
Comment (karalabe) [inline eth/backend.go]: Lets expand `DB` to database. There's no point to have this abbreviation (I know it was in this code forever, let's fix it now).
