### PR TITLE
accounts: cache key addresses

### LINKED ISSUE #1785: accounts: unlock multiple accounts fails
When trying to use ``--unlock="0 1"`` geth fails with the message: `Fatal: Unlock account failed 'Decryption failed: MAC mismatch'`. The first account is unlocked and the message `Account '0' unlocked` is printed. 

It's important to note that `unlock="0"` AND `unlock="1"` both works! Also, if you invert the order ("1 0" instead of "0 1"), it prints `Account '1' unlocked` and then fails to unlock second account with same message. So, the problem is clearly related to unlock multiple accounts and problem always happens on second account.

### LINKED ISSUE #2100: The filename of keys makes a difference as to whether or not they can be unlocked
I found today by playing around with geth that the filename format of the keys makes a difference as to whether or not they can be unlocked.

Expected behaviour: I can place any file with a valid encrypted in key in /keystore and it will be possible to unlock the account with the correct password.

Actual behaviour (OSX, latest master, build from source): if i rename a key file to 'blah_blah' then obviously it's not recognised by ./geth account list and therefore using it is out of the question, which is expected.

However, if i rename the key file to say, '367670f9a85e63377c9cc43a2ff6fe78b33b01c4', then the account will appear in the account list, but even with the correct password, i cannot unlock it. 

Renaming it to the proper format, irrespective of timestamp used, fixes it. (modifying the timestamp does however move it up and down in the array of accounts, which I believe is expected).

Why this is a problem: I think a lot of people are securing their keys by:
- printing out the content of the keyfile
- deleting the file
... in order to put their funds in 'cold storage;

So these people are gong to be rather unhappy when they try to recover their keys later down the line and can't get geth to unlock the account even though the keys are valid and so are the passwords.

Temporary workaround:  create a brand new account, then copy the format of the file, change the date slightly, and then suffic with the proper public key. It allows you to unlock the file again (thankfully).

### PR DESCRIPTION
**Pull request by fjl**
In this PR:

* keystore and all related code moves to package accounts
* key addresses are cached, `Accounts` and `HasAccount` do not hit disk
* keys can have any file name

A few minor issues remain before this can be considered ready:

- [x] ~~On kqueue platforms (OS X, FreeBSD...), the fsnotify package polls every 100ms. I submitted a fix upstream (https://github.com/fsnotify/fsnotify/pull/124)~~.
- [x] ~~On kqueue platforms, fsnotify uses lots of file descriptors (3 + one for each key) to provide per-file events. We don't need this granularity, but there is no way to prevent it.~~
- [X] Use https://github.com/rjeczalik/notify instead because it has less problems.
- [x] The filesystem watcher is not shut down properly.
- [x] We need a fallback for platforms where fsnotify doesn't work.
- [x] Improve handling of duplicate addresses

Fixes #2100
Fixes #1785

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Mar 3 00:16:42 UTC 2016_

**Comment by Gustav-Simonsson** [comment]
This solution seems unnecessary complex. How about simply tracking a map of addresses to key files in a metadata file? Then getting all addresses is a single file read, which will be cached automatically by the OS if called often.

This would also resolve the privacy issue of having addresses in key file (names), though it would require a user to import a key using a specific command, which would need to decrypt the file in order to get the address to update the map. IMO that would be a good thing though, as it prevents import of files the user has forgotten the password to, and also avoids users from having to manually place files into a internal directory.

File: accounts/account_manager.go [hunk 1]
```diff
@@ -36,53 +36,86 @@ import (
...
+	if err != nil {
+		return err
+	}
+	key, err := am.keyStore.GetKey(addr, a.File, auth)
+	if key != nil {
+		zeroKey(key.PrivateKey)
+	}
+	if err != nil {
+		return err
+	}
```
Comment (karalabe) [inline accounts/account_manager.go]: Wouldn't it be better to check the error first and then zero the key? If not, could you add a comment as to why not?

File: accounts/account_manager.go [hunk 2]
```diff
@@ -36,53 +36,86 @@ import (
...
+	return os.Remove(a.File)
```
Comment (karalabe) [inline accounts/account_manager.go]: If I delete a key, shouldn't it also be dropped from the unlocked map? Otherwise it will still be available for signing, even though it doesn't actually exist any more.

File: accounts/addrcache.go [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+	a, err := ac.find(addr)
+	if err != nil {
+		return a, err
+	}
+	newcache := ac.all[:0]
+	for _, a := range ac.all {
+		if a.Address != addr {
+			newcache = append(newcache, a)
+		}
+	}
```
Comment (karalabe) [inline accounts/addrcache.go]: Just a heads up, if you don't set the tail elements of the address slice to nil, they will keep live references and prevent the GC from cleaning them up.

File: accounts/account_manager.go (hunk 1 above)
Comment (fjl) [inline accounts/account_manager.go]: The call to GetKey verifies that the password is correct. We don't actually need the key, so it should be zeroed always even if loading it produces an unrelated error.

File: accounts/watch.go [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+//
+// The go-ethereum library is distributed in the hope that it will be useful,
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU Lesser General Public License for more details.
+//
+// You should have received a copy of the GNU Lesser General Public License
+// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.
+
+// +build darwin freebsd linux netbsd solaris windows
```
Comment (karalabe) [inline accounts/watch.go]: Shouldn't android also be added to this list? Is it not supported by `fsnotify`?

File: accounts/account_manager.go (hunk 2 above)
Comment (fjl) [inline accounts/account_manager.go]: This is actually by design. I think it is unintuitive to erase the key in this case. It needs docs though.

File: accounts/account_manager.go (hunk 1 above)
Comment (karalabe) [inline accounts/account_manager.go]: Shouldn't `GetKey` ensure that if a password is wrong, it does not give you back the key?

File: accounts/account_manager.go (hunk 2 above)
Comment (karalabe) [inline accounts/account_manager.go]: Dunno. It's a bit surprising logic tbh. When I delete a key, I assume that the node is "safe" with regard to that key, whereas in reality it not only is still available, but can actually sign transactions. So if I unlock a key permanently, then there's no way to delete it without restarting the node (or calling lock beforehand), but that's non obvious imho.

File: accounts/addrcache.go (hunk 3 above)
Comment (fjl) [inline accounts/addrcache.go]: ac.all is []Account and doesn't contain pointers.

File: accounts/watch.go (hunk 4 above)
Comment (fjl) [inline accounts/watch.go]: I don't know whether inotify is reliable on android. It is safer to leave it disabled and the fallback isn't that bad, I think.

File: accounts/account_manager.go (hunk 2 above)
Comment (fjl) [inline accounts/account_manager.go]: Consider the case that we discussed on Gitter. If Unlock gives you a signer, should it cease to work if the account is deleted?

File: accounts/account_manager.go (hunk 1 above)
Comment (fjl) [inline accounts/account_manager.go]: yes, but I think it is good style not to assume anything about the relationship between key and err if the intention is to zero it in all possible cases.

**Comment by fjl** [comment]
I have thought about, and don't understand, the privacy concern about having the address recorded in the key file. As of this PR, keys can have any file name but the address must be present in the JSON.
Before this PR, the address had to be in the file name.

In order for {sign,unlock}-by-address to work, the addresses need to be tracked somehow.

File: accounts/account_manager.go (hunk 2 above)
Comment (fjl) [inline accounts/account_manager.go]: The previous implementation also behaved in this way. I have thought about this for a bit and agree with you now, it should be dropped.

**Comment by fjl** [comment]
This can be reviewed for real now.

**Comment by fjl** [comment]
...or not, looks like there is a new issue on Travis.

**Comment by Gustav-Simonsson** [comment]
@fjl The privacy concern is that if someone encounters an encrypted key file, they can, without knowing the password, check how much Ether (or other digital tokens) the key controls. This is useful information for an adversary.

Of course, this was the case when the address was in the file name, so not arguing that is better. Rather, now would be a good time to support both arbitrary file names for keys (as users have requested this) and also avoid storing the address in the key file.

The tracking of the address could be done in a separate file containing a map of all addresses to key files. This allows users flexibility as they can choose whether their encrypted keys expose an address or not (e.g. expose it when key is imported into geth keystore for use with an online node, and not expose it in other types of storage (cold-storage, or simply an offline backup of a online key).

Tracking addresses as a simple map in a file also allows for improved performance as `Accounts()` only requires one file read, and if read often will be cached by the OS. It would remove need for custom caching code, reducing size of the code base, it's complexity and number of dependencies.

**Comment by fjl** [comment]
> now would be a good time to support both arbitrary file names for keys (as users have requested this) 

This is now implemented as of this PR.

> The tracking of the address could be done in a separate file containing a map of all addresses to key files. This allows users flexibility as they can choose whether their encrypted keys expose an address or not (e.g. expose it when key is imported into geth keystore for use with an online node, and not expose it in other types of storage (cold-storage, or simply an offline backup of a online key).

This is possible by removing the address from the key file. The key will not be listed in `Accounts()` in this case. In order to get it back into the list, we'd need a new command to import an existing encrypted JSON key file. This command would then decrypt the key, derive the address and write the file into the store.

**Comment by obscuren** [comment]
@fjl and I had a code walk today; the code looks very good and I really like the approach Felix took. I'll do another code review on my own tomorrow. General observation during the code walk was the lack of godoc comments.

**Comment by fjl** [comment]
rebased

File: accounts/abi/bind/auth.go [hunk 5]
```diff
@@ -33,23 +35,24 @@ func NewTransactor(keyin io.Reader, passphrase string) (*TransactOpts, error) {
...
+	key, err := accounts.DecryptKey(json, passphrase)
 	if err != nil {
 		return nil, err
 	}
-	return NewKeyedTransactor(key), nil
+	return NewKeyedTransactor(key.PrivateKey), nil
 }
 
 // NewKeyedTransactor is a utility method to easily create a transaction signer
 // from a plain go-ethereum crypto key.
```
Comment (karalabe) [inline accounts/abi/bind/auth.go]: `plain go-ethereum crypto key` -> `plain ecdsa private key`

File: accounts/account_manager.go [hunk 6]
```diff
@@ -36,93 +37,147 @@ import (
...
+
+	// File contains the key file name.
+	// When Acccount is used as an argument to select a key, File can be left blank to
+	// select just by address or set to the basename or absolute path of a file in the key
+	// directory. Accounts returned by Manager will always contain an absolute path.
+	File string
 }
 
 func (acc *Account) MarshalJSON() ([]byte, error) {
 	return []byte(`"` + acc.Address.Hex() + `"`), nil
```
Comment (karalabe) [inline accounts/account_manager.go]: Wouldn't this make more sense with `return json.Marshal(acc.Address)`?

File: accounts/account_manager.go [hunk 7]
```diff
@@ -36,93 +37,147 @@ import (
...
+	*Key
 	abort chan struct{}
 }
 
-func NewManager(keyStore crypto.KeyStore) *Manager {
-	return &Manager{
-		keyStore: keyStore,
-		unlocked: make(map[common.Address]*unlocked),
-	}
+func NewManager(keydir string, scryptN, scryptP int) *Manager {
```
Comment (karalabe) [inline accounts/account_manager.go]: Please add a method doc if we're rewriting anyway.

File: accounts/account_manager.go [hunk 8]
```diff
@@ -36,93 +37,147 @@ import (
...
 
-func (am *Manager) HasAccount(addr common.Address) bool {
-	accounts, _ := am.Accounts()
-	for _, acct := range accounts {
-		if acct.Address == addr {
-			return true
-		}
-	}
-	return false
+func NewPlaintextManager(keydir string) *Manager {
```
Comment (karalabe) [inline accounts/account_manager.go]: Please add a method doc if we're rewriting anyway.

File: accounts/account_manager.go [hunk 9]
```diff
@@ -36,93 +37,147 @@ import (
...
 }
 
-func (am *Manager) DeleteAccount(address common.Address, auth string) error {
-	return am.keyStore.DeleteKey(address, auth)
+func (am *Manager) init(keydir string) {
+	am.unlocked = make(map[common.Address]*unlocked)
+	am.cache = newAddrCache(keydir)
+	// TODO: In order for this finalizer to work, there must be no references
+	// to am. addrCache doesn't keep a reference but unlocked keys do,
+	// so the finalizer will not trigger until all timed unlocks have expired.
```
Comment (karalabe) [inline accounts/account_manager.go]: What happens with non-timed unlocks? I.e. if I permanently unlock a key?

File: accounts/account_manager.go [hunk 10]
```diff
@@ -36,93 +37,147 @@ import (
...
+	runtime.SetFinalizer(am, func(m *Manager) {
+		m.cache.close()
+	})
+}
+
+// HasAdddress reports whether a key with the given address is present.
+func (am *Manager) HasAddress(addr common.Address) bool {
```
Comment (karalabe) [inline accounts/account_manager.go]: Nitpick, but if we have `Accounts` and `DeleteAccount`, wouldn't it make sense to rename this to `HasAccount`? Seems much cleaner to me.

File: accounts/account_manager.go (hunk 1 above)
Comment (karalabe) [inline accounts/account_manager.go]: Fair point!

File: accounts/account_manager.go [hunk 11]
```diff
@@ -36,93 +37,147 @@ import (
...
+	}
+	return err
 }
 
-func (am *Manager) Sign(a Account, toSign []byte) (signature []byte, err error) {
-	am.mutex.RLock()
-	defer am.mutex.RUnlock()
+// Sign signs hash with the private key of the given account.
+// The account must be unlocked.
+func (am *Manager) Sign(a Account, hash []byte) (signature []byte, err error) {
```
Comment (karalabe) [inline accounts/account_manager.go]: Can't we force `hash` to be `common.Hash`? I'm aware that in theory we could sign arbitrary hashes, not just 32 bytes ones, but in practice will we ever use other types of hashes? If not, doesn't it make sense to make it more type obvious and safe and prevent people from accidentally signing big blobs of data?

File: accounts/account_manager.go [hunk 12]
```diff
@@ -36,93 +37,147 @@ import (
...
 		am.expire(addr, unl, time.Duration(0)*time.Nanosecond)
 	} else {
-		am.mutex.Unlock()
+		am.mu.Unlock()
 	}
 	return nil
 }
 
-// TimedUnlock unlocks the account with the given address. The account
+// TimedUnlock unlocks the given account with. The account
```
Comment (karalabe) [inline accounts/account_manager.go]: > with // sentende end missing

File: accounts/account_manager.go [hunk 13]
```diff
@@ -36,93 +37,147 @@ import (
...
 // stays unlocked for the duration of timeout. A timeout of 0 unlocks the account
-// until the program exits.
+// until the program exits. The account must match a unique key.
 //
 // If the accout is already unlocked, TimedUnlock extends or shortens
 // the active unlock timeout.
```
Comment (karalabe) [inline accounts/account_manager.go]: Maybe it would be worth specifically mentioning that it will even convert a permanently unlocked account to a temporary one. Or maybe it would be worth to not support such operation.

Rationale: I had someone report that they unlock an account from the CLI, then do stuff with Mist and all of a sudden the account is unlocked. Given that they explicitly unlocked if for the session, it was surprising that it's locked back up. Maybe we shouldn't allow converting permanent unlocks to temporary ones to avoid these unexpected scenarios?

File: accounts/account_manager.go [hunk 14]
```diff
@@ -155,96 +222,84 @@ func (am *Manager) expire(addr common.Address, u *unlocked, timeout time.Duratio
...
-	}
-}
-
-// USE WITH CAUTION = this will save an unencrypted private key on disk
-// no cli or js interface
-func (am *Manager) Export(path string, addr common.Address, keyAuth string) error {
-	key, err := am.keyStore.GetKey(addr, keyAuth)
+// Export writes the unencrypted raw bytes of the given accounts private key to the
+// given file.
+func (am *Manager) Export(path string, a Account, passphrase string) error {
```
Comment (karalabe) [inline accounts/account_manager.go]: Please add an `ExportECDSA` counterpart.If people start using this account manager in external client code I can imagine a lot of valid use cases where you'd like to retrieve the private key and not just dump it to disk. And it would play nicely with `Import` and `ImportECDSA` API wise.

File: accounts/account_manager.go [hunk 15]
```diff
@@ -155,96 +222,84 @@ func (am *Manager) expire(addr common.Address, u *unlocked, timeout time.Duratio
...
+	priv, err := crypto.LoadECDSA(path)
 	if err != nil {
 		return Account{}, err
 	}
-	key := crypto.NewKeyFromECDSA(privateKeyECDSA)
-	if err = am.keyStore.StoreKey(key, keyAuth); err != nil {
+	return am.ImportECDSA(priv, passphrase)
+}
+
+func (am *Manager) ImportECDSA(priv *ecdsa.PrivateKey, passphrase string) (Account, error) {
```
Comment (karalabe) [inline accounts/account_manager.go]: Please add a method doc.

File: accounts/account_manager.go (hunk 10 above)
Comment (fjl) [inline accounts/account_manager.go]: In contrast to most methods, this one takes an address.

File: accounts/account_manager.go (hunk 14 above)
Comment (fjl) [inline accounts/account_manager.go]: I don't want to add additional API surface in this PR.

File: accounts/account_manager.go (hunk 10 above)
Comment (karalabe) [inline accounts/account_manager.go]: Yeah, but it still checks whether an associated Account exists.

File: accounts/account_manager.go (hunk 9 above)
Comment (fjl) [inline accounts/account_manager.go]: Permanently unlocked keys don't spawn a goroutine.

File: accounts/account_manager.go (hunk 13 above)
Comment (fjl) [inline accounts/account_manager.go]: Like I said earlier, I don't want to change the semantics of account operations in this PR.
I agree that some of the operations might not have the most clear semantics, but there is enough
change already.

File: accounts/account_manager.go (hunk 14 above)
Comment (karalabe) [inline accounts/account_manager.go]: It's something you removed: If I understand the PR correctly, by making the `keyStore` package private, you denied access to interacting with it directly. Previously it was possible to invoke `GetKey` to retrieve the associated private key into memory for processing however we wished. I don't see how it's possible with this PR.

Comment (karalabe) [inline accounts/account_manager.go]: My specific use case is:

```go
// ExportAccount retrieves an account from the key store and exports it using
// a different password.
func (eapis *EtherAPIs) ExportAccount(account common.Address, password string) ([]byte, error) {
	key, err := eapis.client.Keystore().GetKey(account, eapis.password)
	if err != nil {
		return nil, err
	}
	return crypto.EncryptKey(key, password, crypto.StandardScryptN, crypto.StandardScryptP)
}
```

If you can propose a valid solution to implement this same functionality, I'm happy to reconsider.

**Comment by Gustav-Simonsson** [comment]
> This is possible by removing the address from the key file. The key will not be listed in Accounts(). In order to get it back into the list, we'd need a new command to import an existing encrypted JSON key file. This command would then decrypt the key, derive the address and write the file into the store. No such command exists right now, but implementing it is trivial. If you care about anonymous cold wallets, maybe you could give it a try.

That's what I had in mind: instead of exposing the keystore directory to users and having them add/remove files, expose `ExportKey` and `ImportKey` on cmd line, so users would import/export key using a cmd rather than moving files.

I (and others) do care about anonymous key files (whether in cold storage or not) so if team decides to go ahead with this PR's approach I'd be happy to make a PR adding support for importing/exporting key files without (or empty) address field.

> I tried to find alternative approaches but filesystem events beat all in terms of convenience: You can simply drop a key file into the directory and it becomes available immediately. Multiple processes can access and modify the keystore concurrently without synchronisation. Tracking addresses in a separate file makes these things more complicated.

Have to disagree here - using import/export cmds is as easy as moving files around and a common practice in key management software. The only case I see where it would be easier is if the user is not familiar with using the command line, but then I'd rather recommend we guide users to import/export through UIs such as the Mist wallet.

Synchronisation would not be complicated - import/export could simply lock the keystore.

I disagree that tracking addresses in a separate file would be more complicated. How is reading/writing to a list in a file more complicated than ~250 lines of custom caching code + ~100 lines of watch code?

**Comment by fjl** [comment]
>> This is possible by removing the address from the key file.
> That's what I had in mind.

What I meant is that this is possible right now with this PR.

> Instead of exposing the keystore directory to users and having them add/remove files, expose ExportKey and ImportKey on cmd line, so users would import/export key using a cmd rather than moving files.

You can also write an external tool that does the file operation and address stripping/deriving on the keystore directory. With keys being just files, anon export is as simple as this (you need [jq](https://stedolan.github.io/jq/))

```text
$ cat anon-export.sh
#!/bin/bash
jq 'del(.address)' $1 > $2
rm $1
$ ./anon-export.sh .ethereum/keystore/coldwallet.key anonwallet.key
```

**Comment by bas-vk** [comment]
I played a bit with moving files in and out the keystore directory and it looks like the watcher is really unreliable. Sometimes it would fire and the accounts list is updated but just as often it would not fire. There where cases when the account was not imported/reloaded and after another key was copied it suddenly would trigger and botch accounts where successful imported.

I have seen this behavior on Linux and Windows.

**Comment by fjl** [comment]
@bas-vk that's bad news.

**Comment by fjl** [comment]
@bas-vk do you have more info, or time to debug the issue?

**Comment by bas-vk** [comment]
I'm pretty sure this is an issue in the notify package and not in your code. Did some really basic debugging. I will make some time today to see if I can found a bit more what is causing this.

**Comment by fjl** [comment]
We can switch back to https://github.com/fsnotify/fsnotify, but as noted in the PR description it consumes lots of file descriptors on OS X.

**Comment by bas-vk** [comment]
In some rare cases `notify.InDelete` or `notify.InCreate` (platform specific) are raised instead of `notify.Remove` or `notify.Create` and therefore ignored.

For linux the solution is to add these to the watch list.
```
err := notify.Watch(w.ac.keydir, w.ev, notify.Create, notify.Remove, notify.Rename, notify.InCreate, notify.InDelete)
```

File: accounts/account_manager.go (hunk 6 above)
Comment (fjl) [inline accounts/account_manager.go]: Maybe, but I won't touch it now.

File: accounts/account_manager.go (hunk 14 above)
Comment (fjl) [inline accounts/account_manager.go]: Export is now

```go
func (am *Manager) Export(a Account, passphrase, newPassphrase string) (keyJSON []byte, err error)
```

File: accounts/account_manager.go (hunk 13 above)
Comment (fjl) [inline accounts/account_manager.go]: It's now fixed.

**Comment by fjl** [comment]
@karalabe PTAL

**Comment by fjl** [comment]
@bas-vk PTAL

**Comment by fjl** [comment]
I'm looking into the test failure and it looks like the issue is as follows:

```text
=== RUN   TestWatchNewFile
I0407 18:21:02.422136 accounts/addrcache.go:215] reloaded keys, cache has 0 accounts
I0407 18:21:02.422267 accounts/addrcache.go:215] reloaded keys, cache has 0 accounts
I0407 18:21:02.422276 accounts/watch.go:83] now watching /tmp/eth-keystore-test042119476
[D] dispatching notify.Create on "/tmp/eth-keystore-test042119476/UTC--2016-03-22T12-57-55.920751759Z--7ef5a6135f1fd6a02593eedc869c6d41d934aef8"

[D] dispatching notify.Create on "/tmp/eth-keystore-test042119476/aaa"

I0407 18:21:02.523691 accounts/addrcache.go:248] can't decode key /tmp/eth-keystore-test042119476/zzz: EOF
I0407 18:21:02.523704 accounts/addrcache.go:215] reloaded keys, cache has 2 accounts
```

The watch fires immediately when the file is opened and is still empty.
Reloading cannot parse the key because it is still empty (it's being copied into).
I'll try to add a bit of delay into the watch.

**Comment by fjl** [comment]
@bas-vk Please try your test again.

File: accounts/watch.go [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+
+func (w *watcher) loop() {
+	defer func() {
+		w.ac.mu.Lock()
+		w.running = false
+		w.starting = false
+		w.ac.mu.Unlock()
+	}()
+
+	err := notify.Watch(w.ac.keydir, w.ev, notify.All)
```
Comment (bas-vk) [inline accounts/watch.go]: `notify.All` has only platform [independent](https://github.com/rjeczalik/notify/blob/master/event.go#L31) events. `InDelete` and `InCreate` are platform dependent and wont be fired with `All`. I have seen this issue also pop up under Windows and assume there are some custom events raised there as well.

Since `notify.Event` is just a typedef for uint32 can't we just use `0xffffffff` and match all signals on any platform? Not sure if reading a file triggers an event and causes an infinite loop.

Comment (fjl) [inline accounts/watch.go]: I tried adding them at first and tried it out a bit. It always fired both platform-independent and platform-specific ones.

**Comment by bas-vk** [comment]
Played a couple of minutes with it and the issue seems to be fixed :+1:.

**Comment by karalabe** [comment]
LGTM :+1: 

Humongous PR, but I like.

**Comment by fjl** [comment]
I'll rebase.

**Comment by obscuren** [comment]
@fjl status? Would like to merge.

**Comment by fjl** [comment]
OK, I squashed some of the commits.

**Comment by karalabe** [comment]
@fjl Merge conflict

**Comment by fjl** [comment]
fixed

**Comment by karalabe** [comment]
@fjl Test compile error :P

**Comment by fjl** [comment]
fixed again

File: accounts/key.go [hunk 17]
```diff
@@ -142,27 +160,70 @@ func NewKey(rand io.Reader) *Key {
...
+		f.Close()
+		os.Remove(f.Name())
+		return err
 	}
-	return key
+	f.Close()
+	return os.Rename(f.Name(), file)
+}
+
+// keyFileName implements the naming convention for keyfiles:
```
Comment (svolobuev) [inline accounts/key.go]: @fjl hello! Where can I'm read this convention?
