### PR TITLE
p2p/discover: fix crash when revalidated node is removed

### LINKED ISSUE #29860: ethereum node panic.
hi. sir. i got a panic in my ethereum node. i wonder what's happen?  the ethereum docker version : ethereum/client-go:latest . image id : 651587b0bf93

### PR DESCRIPTION
**Pull request by fjl**
Fixes #29860

### CODE REVIEW

File: p2p/discover/table_reval.go [hunk 1]
```diff
@@ -43,6 +43,14 @@ type revalidationResponse struct {
...
 }
 
+type revalStatus byte
+
+const (
+	revalStatusGone revalStatus = iota
+	revalStatusFailed
+	revalStatusOK
+)
+
```
Comment (lightclient) [inline p2p/discover/table_reval.go:53]: Was curious if this is strictly needed? I see it is only used by the test?

**Comment by HemirAli** [comment]
hi
