### PR TITLE
core, eth, internal: extend structLog tracer

### LINKED ISSUE #21198: Storage field in debug_traceTransaction traces does not include storage read from, only written to
#### System information

Geth version: 1.9.15-stable
OS & Version: Release Linux Mint 19.1 Tessa 64-bit

#### Expected behaviour

The trace output from `debug_traceTransaction`, in its `storage` field for each step, should include both all storage written to so far during the current call, and all storage read from so far during the current call.

By way of comparison, Ganache does this; now I know Geth invented `debug_traceTransaction`, and so gets to define what it does, but this seems like a distinct omission of relevant information, as storage read from is definitely relevant to the transaction.

#### Actual behaviour

Only storage written to is included; storage read from is omitted.  This causes problems for debuggers based on `debug_traceTransaction`.  For instance, storage variables will erroneously display as zero even after they've been read from, which is confusing when debugging.

(Reason I'm filing this bug: I'm the maintainer of the Truffle Debugger, and there, in addition to the above, it could possibly cause the wrong mapping keys to be kept track of.  If you want to see the discussion of this over on our GitHub, it's on [this issue](https://github.com/trufflesuite/truffle/issues/2066).)

#### Steps to reproduce the behaviour

Start geth with `geth --dev --http --http.api eth,net,debug`.  Deploy the following contract:

```solidity
pragma solidity ^0.5.16;

contract DebugTest {
  uint zr;
  uint nzr = 1;
  uint zwz;
  uint zwnz;
  uint nzwz = 2;
  uint nzwnz = 3;
  uint zwr;
  uint nzwr;

  function run() public {
    uint x;
    x = zr; //read zero
    x = nzr; //read nonzero
    zwz = 0; //write zero to zero
    zwnz = 4; //write nonzero to zero
    nzwz = 0; //write zero to nonzero
    nzwnz = 5; //write nonzero to nonzero
  }
}
```

Send a transaction for the `run()` function.  Use `debug_traceTransaction` on the result; since everything's within the same call, we can just look at the final trace step.  Observe that its `storage` field contains entries for storage slots 2 through 5, but not 0, 1, 6, or 7.

Thank you!

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR extends the structLog tracer to include storage read for each evm step.

Fixes #21198

### CODE REVIEW

File: core/vm/logger.go [hunk 1]
```diff
@@ -142,27 +141,32 @@ func (l *StructLogger) CaptureStart(from common.Address, to common.Address, crea
...
+	}
+	// capture SSTORE opcodes and record the written entry in the local storage.
 	if op == SSTORE && stack.len() >= 2 {
 		var (
 			value   = common.Hash(stack.data[stack.len()-2].Bytes32())
 			address = common.Hash(stack.data[stack.len()-1].Bytes32())
 		)
-		l.changedValues[contract.Address()][address] = value
+		l.storage[contract.Address()][address] = value
 	}
```
Comment (holiman) [inline core/vm/logger.go:170]: Any reason not to put this entire clause behind a `if !l.cfg.DisableStorage` ?

File: core/vm/logger.go [hunk 2]
```diff
@@ -142,27 +141,32 @@ func (l *StructLogger) CaptureStart(from common.Address, to common.Address, crea
 
 // CaptureState logs a new structured log message and pushes it out to the environment
 //
-// CaptureState also tracks SSTORE ops to track dirty values.
+// CaptureState also tracks SLOAD/SSTORE ops to track storage change.
 func (l *StructLogger) CaptureState(env *EVM, pc uint64, op OpCode, gas, cost uint64, memory *Memory, stack *Stack, rStack *ReturnStack, contract *Contract, depth int, err error) error {
```
Comment (holiman) [inline core/vm/logger.go:145]: At some point, we should also update the method signature to mimic the opcodes, using a CallContext instead of passing all these parameters...

File: core/vm/logger.go (hunk 1 above)
Comment (rjl493456442) [reply core/vm/logger.go:170]: right, fixed

File: core/vm/logger.go (hunk 2 above)
Comment (rjl493456442) [reply core/vm/logger.go:145]: Yes, but `callCtx` is an inner structure. Is it ok to uppercase it?

Comment (holiman) [reply core/vm/logger.go:145]: I didn't mean you have to do it in this PR, really. 
(but _I_ think we can uppercase it  if needed)
