### PR TITLE
core: initialize current block/fastblock atomics to nil, fix #19286

### LINKED ISSUE #19286: panic: interface conversion: interface {} is nil, not *types.Block
#### System information

Geth version: `1.8.23`
OS & Version: Ubuntu 18.04.2

#### Expected behaviour

After weeks of being in sync, if the full node is offline for a few days due to a power outage, it should be able to catch up and become in sync again.

#### Actual behaviour

```bash
INFO [03-18|07:31:09.725] Disk storage enabled for ethash caches   dir=/home/ethereum/.ethereum/geth/ethash count=3
INFO [03-18|07:31:09.725] Disk storage enabled for ethash DAGs     dir=/home/ethereum/.ethash               count=2
INFO [03-18|07:31:09.787] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [03-18|07:31:10.802] Head block missing, resetting chain      hash=5414aa…aaf1f5
WARN [03-18|07:31:10.802] Rewinding blockchain                     target=0
panic: interface conversion: interface {} is nil, not *types.Block

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.(*BlockChain).CurrentBlock(...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:359
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0x40195d4000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:302 +0x8a0
```

#### Steps to reproduce the behaviour

- Full sync a mainnet node
- Pull the plug
- Wait a few days
- Reset the node

#### Other info

This is part of my [Ethereum on ARM experiment](https://www.reddit.com/r/ethereum/comments/alnmxn/ethereum_on_arm_geth_and_parity_clients_update/). It took a week to fully sync, so starting from 0 is obviously not an acceptable solution, not when there's a chance of this so easily happening again.

I have the full 171GB in chaindata, so all my data is still there from the full sync from before.

This issue has also been posted in [StackExchange](https://ethereum.stackexchange.com/q/68453/31497).

### PR DESCRIPTION
**Pull request by holiman**
This initialises the two atomics use for tracking the current block and fast block to `nil`. the accessors `CurrentBlock` have pointer return type, so callers are already prepared that it might be nil, however, if the _atomic_ itself is nil it causes a `panic`.

@fjl I know you wanted a different fix, but I couldn't really figure out how you would rather have it, and this seems like a pretty clean fix to me.

### CODE REVIEW

**Comment by Matthalp** [comment]
Type: "This initialises **thw**" (the).

File: core/blockchain.go [hunk 1]
```diff
@@ -201,6 +201,10 @@ func NewBlockChain(db ethdb.Database, cacheConfig *CacheConfig, chainConfig *par
 	if bc.genesisBlock == nil {
 		return nil, ErrNoGenesis
 	}
+	var nilBlock *types.Block
+	bc.currentBlock.Store(nilBlock)
```
Comment (Matthalp) [inline core/blockchain.go]: Would it be better to put `bc.genesisBlock` here?

Comment (holiman) [reply core/blockchain.go]: I am not convinced that would be correct. That would change the semantics, and make it appear as if the current block is genesis -- which has a different meaning than `nil`. The latter indicates it is simply not set (yet), the former indicates that all is in order, we should start importing from genesis.

Comment (Matthalp) [reply core/blockchain.go]: This is actually what is already done in [`HeaderChain`](https://github.com/ethereum/go-ethereum/blob/master/core/headerchain.go#L100) for `HeaderChain.currentHeader`, so I don't think this changes semantics.

My understanding is that `BlockChain.loadLastState()` will overwrite this value because it reads directly from the database as well. IMHO there should be an invariant where `BlockChain.currentBlock` is always set.

Also note that the code in #19286 is attempting to set the head to genesis block anyways.

Comment (Matthalp) [reply core/blockchain.go]: It is also worth wondering how it got into this state. The chain configuration and genesis block were already present or `SetupGenesisBlockWithOverride` would have handled this, so maybe the "pull the plug" was when the head block hash key in the database got corrupted in #19286?
