### PR TITLE
p2p/discover: prevent bonding self

### LINKED ISSUE #2401: p2p/discover: vicious loop with local node inserted into kademlia table
#### System information

Geth version: 
Version: 1.3.5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: windows
GOPATH=
GOROOT=c:\go
OS & Version: Windows 7

#### Expected behaviour
Geth starts with empty blockchain and syncs up to the last best block.

#### Actual behaviour
Geth starts, syncs up to block 82656 and then looses connection to all peers. 
I watched geth syncing using the console and command admin.peers.
At the beginning, I have 5-9 active peers. After about 20minutes, the number of peers decreases, then only one peer is left, then 0 peers. Geth never recovers or finds new nodes afterwards.

If I install a file "static-nodes.json" (see below) in the datadir with some node addresses, geth succeeds in a full sync of the blockchain. 

#### Steps to reproduce the behaviour
Install Mist 0.5.2.
cd Ethereum-Wallet-win64-0-5-2\resources\node\geth
geth -verbosity "6" console 2>>log.txt

(a shortened log is attached, the original log is about 80MB).

#### Backtrace
n/a

[static-nodes.json.txt](https://github.com/ethereum/go-ethereum/files/198343/static-nodes.json.txt)
[log_short.txt](https://github.com/ethereum/go-ethereum/files/198331/log_short.txt)

### PR DESCRIPTION
**Pull request by fjl**
The first commit is somewhat unrelated and addresses #2507.
The behaviour is unchanged, but it should be easier to see that there is no bug
in the new version.

The second commit fixes #2401.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon May 2 16:00:39 UTC 2016_

**Comment by fjl** [comment]
Please review: @karalabe, @zsfelfoldi

**Comment by karalabe** [comment]
LGTM :+1:

File: p2p/discover/table.go [hunk 1]
```diff
@@ -457,6 +458,9 @@ func (tab *Table) bondall(nodes []*Node) (result []*Node) {
 // If pinged is true, the remote node has just pinged us and one half
 // of the process can be skipped.
 func (tab *Table) bond(pinged bool, id NodeID, addr *net.UDPAddr, tcpPort uint16) (*Node, error) {
+	if id == tab.self.ID {
+		return nil, errors.New("is self")
```
Comment (obscuren) [inline p2p/discover/table.go]: I do suggest to make these type of errors globally available such that comparison is easier and doesn't require one to check for the `.Error()`.

**Comment by obscuren** [comment]
👍
