### PR TITLE
swarm: better name resolver handling 

### LINKED ISSUE #3608: Swarm: Panic when swarm is started with invalid ethapi
#### System information

Geth version: 
Version: 1.5.8-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3

OS & Version: Linux

Commit hash : (if `develop`)

#### Expected behaviour
should not panic when swarm is started and peers are not reachable

#### Actual behaviour
Looks like ens calls a contract even if there is not ethapi 
http://pastebin.com/XmN92Rxg

#### Steps to reproduce the behaviour
start swam with  -- ethapi "" (double quotes with no space in between)

#### Backtrace
I0126 12:35:17.118746 swarm/api/http/server.go:88] Swarm HTTP proxy started on localhost::8500
I0126 12:35:17.118921 node/node.go:341] IPC endpoint opened: /home/zahoor/BZZ/testnet/bzzd.ipc
I0126 12:35:20.118824 swarm/network/hive.go:165] no peer
I0126 12:35:23.118793 swarm/network/hive.go:165] no peer
I0126 12:35:26.118780 swarm/network/hive.go:165] no peer
I0126 12:35:26.824851 server.go:2317] http: panic serving 127.0.0.1:55932: runtime error: invalid memory address or nil pointer dereference
goroutine 611 [running]:
net/http.(*conn).serve.func1(0xc421345080)
    /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xb0d140, 0xc420010130)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/ethereum/go-ethereum/ethclient.(*Client).CallContract(0x0, 0x7f9c05f16088, 0xc420010c68, 0x0, 0x0, 0x0, 0xc42000c480, 0x0, 0x0, 0x0, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/ethclient/ethclient.go:370 +0x2a9
github.com/ethereum/go-ethereum/accounts/abi/bind.(*BoundContract).Call(0xc42000c480, 0xc4203d0a18, 0xb84c80, 0xc42136de40, 0xbdd0ed, 0x8, 0xc4215490a0, 0x1, 0x1, 0x20, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go:131 +0x4cb
github.com/ethereum/go-ethereum/contracts/ens/contract.(*ENSCaller).Resolver(0xc4202559f0, 0xc4203d0a18, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0x0, 0x0, 0x0, 0xc421549188, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/contract/ens.go:195 +0x14d
github.com/ethereum/go-ethereum/contracts/ens/contract.(*ENSSession).Resolver(0xc4203d0a10, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0x0, 0x0, 0xc400000000, 0xc42136dca0, 0xc42136dc80)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/contract/ens.go:203 +0x84
github.com/ethereum/go-ethereum/contracts/ens.(*ENS).getResolver(0xc42025d5e0, 0xc4179ee6870e681f, 0x861bce7c700ae86b, 0x40b571a616a726d7, 0xc2172c5657eb13cb, 0xc2172c5657eb13cb, 0x10, 0xc421348d20)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/ens.go:100 +0x58
github.com/ethereum/go-ethereum/contracts/ens.(*ENS).Resolve(0xc42025d5e0, 0xc4204e5bd0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x7f9c05dd1bc0, 0x0)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/contracts/ens/ens.go:137 +0xde
github.com/ethereum/go-ethereum/swarm/api.(*Api).Resolve(0xc42025d600, 0xc4204e5bd0, 0xc, 0x1, 0x0, 0x0, 0x10, 0x8, 0x8)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:81 +0x21c
github.com/ethereum/go-ethereum/swarm/api.(*Api).parseAndResolve(0xc42025d600, 0xc4204e5bd0, 0xc, 0xc421549501, 0x70405d, 0xc42025f160, 0x0, 0x0, 0x0, 0x1, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:116 +0xa6
github.com/ethereum/go-ethereum/swarm/api.(*Api).Get(0xc42025d600, 0xc4204e5bd0, 0xc, 0xc421549901, 0x1, 0x1, 0xc, 0xc420dab040, 0x2, 0xc4207616c0, ...)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/api.go:143 +0x69
github.com/ethereum/go-ethereum/swarm/api/http.handler(0x1224e20, 0xc42158e0d0, 0xc4212d8780, 0xc42025d600)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/http/server.go:237 +0x10a1
github.com/ethereum/go-ethereum/swarm/api/http.StartHttpServer.func1(0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/swarm/api/http/server.go:74 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420494090, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201dc8a0, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /home/zahoor/go/src/github.com/ethereum/go-ethereum/vendor/github.com/rs/cors/cors.go:190 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc4200a60e0, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420294580, 0x1224e20, 0xc42158e0d0, 0xc4212d8780)
    /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421345080, 0x1225ce0, 0xc42133bc80)
    /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2293 +0x44d
I0126 12:35:29.118745 swarm/network/hive.go:165] no peer
I0126 12:35:32.118731 swarm/network/hive.go:165] no peer
I0126 12:35:35.118781 swarm/network/hive.go:165] no peer
I0126 12:35:38.118769 swarm/network/hive.go:165] no peer

### PR DESCRIPTION
**Pull request by holisticode**
fixes #3608

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 10ac5d2e81a125768df7ebfcb64610e335522c66
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 10ac5d2e81a125768df7ebfcb64610e335522c66
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9ce8965a66846908da02c06156499df930aa5ee8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

File: swarm/api/mocks/resolver.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+package mocks
+
+import (
+	"github.com/ethereum/go-ethereum/common"
+)
+
+type DummyResolver struct{}
+
+func (dummy *DummyResolver) Resolve(name string) (common.Hash, error) {
```
Comment (zelig) [inline swarm/api/mocks/resolver.go]: still not sure if we need a dummy resolver and why
but in any case the dummy resolver should return an error no?

Comment (holisticode) [inline swarm/api/mocks/resolver.go]: DummyResolver is only for tests. Tests currently initialize api like this:

`api := NewApi(dpa, nil)`

nil here corresponding to the dns object.
Now because of this new check we have in if swarm/api/api.go

`self.dns == nil {
￼	return nil, fmt.Errorf("Your node is not connected to the blockchain")
}`

swarm/api/api_test.go and swarm/api/http/server_test.go fail.
In other words, tests were supposed to succeed even if the dns part of the api object was nil.

Maybe there is another way to fix this, but that is what I figured out to be the quickest.

File: swarm/api/api_test.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ import (
 	"testing"
 
 	"github.com/ethereum/go-ethereum/log"
+	//	"github.com/ethereum/go-ethereum/swarm/api/mocks"
```
Comment (zelig) [inline swarm/api/api_test.go]: please remove line

File: swarm/api/http/server_test.go [hunk 3]
```diff
@@ -26,12 +26,14 @@ import (
...
 	"github.com/ethereum/go-ethereum/common"
 	"github.com/ethereum/go-ethereum/swarm/api"
+	"github.com/ethereum/go-ethereum/swarm/api/mocks"
 	"github.com/ethereum/go-ethereum/swarm/storage"
 )
 
 func TestBzzrGetPath(t *testing.T) {
 
 	var err error
+	var dummyDns = &mocks.DummyResolver{}
```
Comment (zelig) [inline swarm/api/http/server_test.go]: why do we need dummy  resolver here? 
Only if we use the bzz scheme

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 5fec71692077fa0d85ba3e2658641c7f3a4d5b4d
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

File: swarm/api/api.go [hunk 4]
```diff
@@ -72,21 +72,46 @@ type ErrResolve error
...
 	log.Trace(fmt.Sprintf("Resolving : %v", hostPort))
-	if hashMatcher.MatchString(hostPort) || self.dns == nil {
-		log.Trace(fmt.Sprintf("host is a contentHash: '%v'", hostPort))
-		return storage.Key(common.Hex2Bytes(hostPort)), nil
-	}
-	if !nameresolver {
-		return nil, fmt.Errorf("'%s' is not a content hash value.", hostPort)
+
+	//if self.dns is nil, don't resolve, but first try fall back to hash
+	if self.dns == nil {
```
Comment (zelig) [inline swarm/api/api.go]:
```golang
var contentHash Key
var err error 
if nameresolver { 
  if self.dns != nil { 
    contentHash, err = self.dns.Resolve(hostPort) 
    if err == nil { 
       return contentHash, nil 
    } 
  } else { 
    err = fmt.Errorf("no DNS to resolve name") 
  } 
} 
if hashMatcher.MatchString(hostPort) { 
   return storage.Key(common.Hex2Bytes(hostPort)), nil 
} 
if err != nil { 
   return nil, fmt.Errorf("'%s' does not resolve: %v but is not a content hash", hostPort, err) 
} 
return nil, fmt.Errorf("'%s' is not a content hash")
```

Comment (zelig) [inline swarm/api/api.go]: I think this is all you need for the resolve/fallback logic, then keep the functions as is and keep raw as nameresolve=true. All the tests that call with a proper hash now go through. 
We need to add tests to test these error responses and then we are done :)s

**Comment by fjl** [comment]
Please rebase
